### PR TITLE
Wallet API: added setRecoveringFromSeed();

### PR DESCRIPTION
**Pull request by Jaqueeee**

### CODE REVIEW

**Comment by mbg033** [comment]
@Jaqueeee, do we need this because of wallet can be closed after restore from the seed and next "init" will pull the hashes instead of blocks?

**Comment by Jaqueeee** [comment]
@mbg033 
There was an issue when a user killed the app before the sync was finished. Upon next run only the hashed were pulled. So i added the recover-state to the settings object for restoration to be able to continue on next start. https://github.com/monero-project/monero-core/pull/43

**Comment by mbg033** [comment]
aha, ok

**Comment by Jaqueeee** [comment]
@mbg033 i think the same thing would happen if sync never was started and user quit the gui. Like when the daemon isn't running.

**Pull request merged**
