### PR TITLE
Version

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by stoffu** [comment]
How about adding it to the daemon/wallet RPC?

**Comment by moneromooo-monero** [comment]
The daemon RPC has a version call. It would be good to add one to the wallet RPC indeed.

**Comment by moneromooo-monero** [comment]
It is get_version. It returns CORE_RPC_VERSION_*.

**Comment by stoffu** [comment]
This PR intends to return MONERO_RELEASE_NAME and MONERO_VERSION_FULL which are different from CORE_RPC_VERSION_*.

**Comment by moneromooo-monero** [comment]
Yes, different things.

I added a wallet rpc version in #3635.

**Comment by stoffu** [comment]
OK, there are a few different things that are called "version" (fork version, RPC version, software version etc), and this PR adds the ability to print the software version (release name & commit hash). I thought it'd be useful to have the ability to query the software version with the daemon/wallet RPC, because I believe the RPC is supposed to offer mostly the same set of functionality as the CLI.

**Comment by moneromooo-monero** [comment]
The RPC version makes more sense for the RPC since it can be compared.
The human string version makes more sense for the cli since it allows a user to tell me what git hash it's using.
I don't think I want a human version in RPC because it adds a good number of bits for fingerprinting. If you want to add it though, I won't NAK, but I don't think it's very useful.

**Comment by stoffu** [comment]
OK, I'm persuaded.

**Pull request merged**
