### PR TITLE
Add snap packaging.

### PR DESCRIPTION
**Pull request by cmars**
This adds [snap](https://snapcraft.io) packaging to the project. See the
link for more information on snaps, but basically, snap packages install on all Linux
distributions. On Ubuntu, snap confinement with apparmor and seccomp
provide an additional layer of security.

This snap sets up monerod as a systemd service, which should start
immediately on install. To access the wallet CLI, simply run `monero`
(/snap/bin/monero). I think it's a really quick & easy way to get
started with monero.

I've made some opinionated decisions in the packaging just to kick this
off, but I'm happy to iterate on this stuff.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I have no clue about snap, but I left a few minor comments.

**Comment by cmars** [comment]
@moneromooo-monero I didn't see any comments above. Let me know if there's anything else to address in a followup.

**Comment by elopio** [comment]
@moneromooo-monero @fluffypony I've opened #1532 to push the snap to the store. I'd love to give you a hand there, if you are interested.

**Comment by danrmiller** [comment]
I would guess this would require someone to commit to maintaining the package as well, particularly with communication and updates and testing for forks and security issues.

**Comment by elopio** [comment]
@danrmiller yes. But most of it should be automated. With the snapcraft.yaml you have in master, you could configure travis, launchpad or any other CI system to make automatic pushes to the edge channel every time that something lands into the repository:
http://snapcraft.io/docs/build-snaps/ci-integration

Then your community of testers can easily give you early feedback by just running: sudo snap install monero --edge. Their monero will be autoupdated every time a new version is pushed to the store.

We are working hard to make it as light-weight as possible, so we would love to get feedback every time you find something that could be easier. And in exchange, you will get many more users by exposing the application in the Ubuntu store, and hopefully many more contributors too.

**Comment by danrmiller** [comment]
I'll look into this, but I'm not yet familiar with the concept of "snaps" or why they would be used in place of .deb

**Comment by vdo** [comment]
Did some changes to simplify the snapcraft 
Works ok so far:
https://github.com/monero-project/monero/pull/1601

**Comment by danrmiller** [comment]
How does one build this snap locally?

**Comment by elopio** [comment]
@danrmiller in Ubuntu 16.04, you can do:

    $ sudo apt install snapcraft git
    $ git clone https://github.com/monero-project/monero
    $ cd monero
    $ snapcraft
    $ sudo snap install *.snap --dangerous

**Comment by anonimal** [comment]
@elopio would you be willing to help [kovri](https://github.com/monero-project/kovri/) get started with snapcraft? I'd like to learn more about snapcraft as it relates to kovri by getting my hands on a working yaml. If snapcraft works out well as a linux packaging solution, then great (even better if snapcraft could somehow implement osx/windows functionality).

Any help would be greatly appreciated.

**Comment by elopio** [comment]
@anonimal it would be my pleasure. Mi amas la nomojn de viaj projektoj :D

Why don't we jump into a chat or hangout or something? I will help you getting started, and answer any question as we go.
We usually hang in https://rocket.ubuntu.com/channel/snapcraft, which is cool because it's also a snap.

**Comment by anonimal** [comment]
>We usually hang in https://rocket.ubuntu.com/channel/snapcraft, which is cool because it's also a snap.

lol, nice

>Why don't we jump into a chat or hangout or something?

Do you use IRC on [Freenode](http://webchat.freenode.net/?randomnick=1&channels=%23monero-dev&prompt=1&uio=d4) (that's the quickest medium for me to use right now)? If not, then it may be a while before I'm able to create an account on ubuntu and get situated on rocket chat (I can only indulge in snap testing once other pressing kovri issues are resolved).

**Comment by elopio** [comment]
IRC is good. I've just joined your channel.

**Comment by vdo** [comment]
I'm testing integration with launchpad with my own repo:
https://code.launchpad.net/~vdo.greyfaze/+snap/monero

It's cool because it builds on x64,i386, arm and arm64 :)

I used the 'monero' name on store and I think it's unique, so I'm changing it to something like 'monero-unofficial'


Also a snap of daemon and GUI in progress here:

https://github.com/vdo/monero-snap/tree/dev

**Comment by milkowski** [comment]
Great idea, I'm testing it on RaspberryPI. There is one issue though, the data dir should be $SNAP_DATA_COMMON not $SNAP_DATA. The former is not touched during snap update/rollback, the latter is versioned in case of rollback and we want to avoid versioning 10GB of blockchain database during upgrade I suppose. :-O

**Comment by abelboldu** [comment]
@milkowski Yes you're right! But according to the [ref. doc](http://snapcraft.io/docs/reference/env) [1] it should be SNAP_COMMON, not SNAP_DATA_COMMON.

Thanks

**Comment by vdo** [comment]
@milkowski Yes you're right! But according to the [ref. doc](http://snapcraft.io/docs/reference/env) it should be SNAP_COMMON, not SNAP_DATA_COMMON.

Thanks

**Comment by milkowski** [comment]
@vdo Is there a chance to update you launchpad integration according to that? I suggest also to add explicit config file for moderod launch wrapper "--config-file=$SNAP_DATA/monerod.conf"

**Comment by elopio** [comment]
Hello again!
@vdo is there something I can do to help you there? 
What are you missing to make an official release? I can help you moving the ubuntu community to test it before making a stable release. Let me know if there's something I can do for you. Now that snaps also run in Ubuntu trusty (our previous long-term release), pushing it to the store will give you exposition to even more users.

**Comment by vdo** [comment]
Hi @elopio 
I did the changes suggested but I only need to figure out the best way to provide the monerod.conf plus some other minor changes.
About the "oficial release", I would be more than happy to maintain the snap packages both for daemon and gui
@fluffypony is it ok?

**Comment by elopio** [comment]
@vdo I'm not sure how's the config installed in monero, but maybe you can get some ideas from what we did in kovri: https://github.com/monero-project/kovri/pull/548/files
If you don't like my idea, well, I have others :) Feel free to ping me on IRC and I can give you a hand with the remaining details.

**Pull request merged**
