### PR TITLE
crypto: move null_pkey/null_skey to the cpp file

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by vtnerd** [comment]
Drop the `#include <boost/utility/value_init.hpp>` in the header, and update the initialization to:

```c++
null_pkey = crypto::public_key{};
null_skey = crypto::secret_key{};
```

After C++11, the compiler must perform zero-initialization, which happens before all other initialization (i.e. before global constructor calls, etc.).

**Comment by stoffu** [comment]
Doesn't the same reasoning apply to `crypto::{null_hash, null_hash8}` and `rct::{Z, I, L, G, H, H2}` as well?

**Comment by moneromooo-monero** [comment]
Those don't mlock memory, which was why I did this.

**Comment by stoffu** [comment]
Ah, makes sense. Thanks.

**Comment by moneromooo-monero** [comment]
Technically, null_pkey doesn't either, but as they're declared together I moved both.

**Pull request merged**
