### PR TITLE
Rename 'set_log' in wallet to 'log-level' for consistency with daemon

### PR DESCRIPTION
**Pull request by NanoAkron**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Isn't it set_log in both ?

**Comment by NanoAkron** [comment]
I start monerod with the RPC command `monerod --log-level=0` but you are correct - this was something that was raised in #1695.

Maybe I should be more comprehensive in my consistency changes, favouring RPC calls over the CLI ones

**Comment by moneromooo-monero** [comment]
--log-level is the command line option, set_log is the console command.

**Comment by hyc** [comment]
Looks like this patch is not needed.

**Comment by NanoAkron** [comment]
This patch is not needed. But should I attempt to make all the console and RPC commands more consistent as per #1695?

**Comment by NanoAkron** [comment]
Closing as this isn't quite the problem I imagined

**Pull request closed without merging**
