### PR TITLE
blockchain_db: add "raw" blobdata getters for block and transaction

### PR DESCRIPTION
**Pull request by moneromooo-monero**
This speeds up operations such as serving blocks to syncing peers

### CODE REVIEW

**Comment by NanoAkron** [comment]
For my edification, may I ask how it worked before and why this method will be faster? Thanks!

**Comment by moneromooo-monero** [comment]
A blob representation is stored in the db. Adding these functions mean there's no unneeded conversion to block/transaction. The original Cryptonote code kept all in memory (so as C++ objects) so never had the problem to begin with.

**Comment by NanoAkron** [comment]
Oh excellent. Why didn't we transfer blocks as blobs before now?

**Comment by moneromooo-monero** [comment]
We did. There was an additional transformation to blobdata.

**Pull request merged**
