### PR TITLE
crypto: remove unused OAES code

### PR DESCRIPTION
**Pull request by jeffro256**
@SyntheticBird45 reported that the OpenBSD compiler gives warnings about string functions used in `oaes_sprintf`, as well as use of `rand()` in `oaes_key_gen`. Neither of these functions are used in the codebase. Removing the unused OAES functions silences these warnings.

openbsd_oaes_warnings

### CODE REVIEW

**Review by tobtoht — APPROVED** [review]
Was about to PR the same thing.

**Review by 0xFFFC0000 — APPROVED** [review]
LGTM

**Comment by SyntheticBird45** [comment]
stillwarning

Still 1 warning left (if we forget easylogging++).
Build profile: 
```
$ cmake -DBUILD_TESTS=off -DCMAKE_BUILD_TYPE=release-static
$ gmake
```

**Comment by jeffro256** [comment]
Oops, I pushed an extra commit. Reverted. @SyntheticBird45 can you test now?

**Review by SyntheticBird45 — APPROVED** [review]
Error disappeared. Good job.

**Review by 0xFFFC0000 — APPROVED** [review]
LGTM

**Review by sneurlax — APPROVED** [review]

**Pull request merged**
