### PR TITLE
wallet2: fix wrong version status on daemon shutdown/startup

### PR DESCRIPTION
**Pull request by Jaqueeee**
fixes https://github.com/monero-project/monero-core/issues/386 and #1527

### CODE REVIEW

**Comment by NanoAkron** [comment]
Which version do you mean by 'old' daemons?

**Comment by Jaqueeee** [comment]
@moneromooo-monero no status at all. Updated to only return false if rpc call fails.

**Comment by moneromooo-monero** [comment]
"the old daemons, without that RPC available"

**Comment by moneromooo-monero** [comment]
I have just tried calling the getinfo RPC call while the daemon is syncing from scratch, and it works (without your patch).

**Comment by moneromooo-monero** [comment]
Same for the get_version RPC. While the daemon is starting, I get connection refused, until it binds/listens.

**Comment by Jaqueeee** [comment]
@moneromooo-monero This patch is not related to the busy daemon issue. 

If the wallet is connected to the daemon and the daemon is shut down check_connection will return true and version=0 for a while. Because of this line https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L2287 (i think is_connected() is cached for a while).

**Comment by NanoAkron** [comment]
@moneromooo-monero If you're referring to daemons prior to 0.10.1.0...why do we care?

**Comment by Jaqueeee** [comment]
@NanoAkron we care about letting them know that they need to update. Otherwise they won't know what the problem is.

**Comment by NanoAkron** [comment]
Hmmm...

So a version check at startup with a response `Daemon out of date, please update` would be a more generic catch-all.

**Comment by moneromooo-monero** [comment]
Also, https://github.com/monero-project/monero/pull/1780 for the status command.

**Comment by moneromooo-monero** [comment]
Nanoakron, so the wallet can know if it's connected to an old daemon.

**Comment by moneromooo-monero** [comment]
I read that line as, if it's not connected, it will connect, then run RPC. However, if connected, it will still run the RPC. I'd like to understand what's going on before this gets merged (or not).

**Comment by Jaqueeee** [comment]
(i think) is_connected() will return true until a rpc call actually fails. So after daemon shutdown check_connection() will return true on first run.

**Comment by moneromooo-monero** [comment]
It will do that if you're not asking for a version, and if the HTTP client doesn't realize the other side closed (if it doesn't that would be worth fixing).

Also, see https://github.com/monero-project/monero/pull/1786

**Comment by moneromooo-monero** [comment]
Can you try without this patch, and with the RPC fix ones (at least 178) ?

**Pull request merged**
