### PR TITLE
Fix connection leaks and only use more up to date peers for syncing

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by hyc** [comment]
Agreed, it seems it would interfere with tx broadcasting, if nothing else.

**Comment by moneromooo-monero** [comment]
What circumstances can you think of ? The one I could see is that if somehow everyone is syncing, then new nodes can't sync themselves. That's a temporary state of affairs though. Anything else ?

About tx broadcasting, if you mean your own txes, you shouldn't create them while your node is syncing (if nothing else, it'd wreck your fake out distribution). I think the daemon will prevent you anyway.

**Comment by xiphon** [comment]
> What circumstances can you think of ? The one I could see is that if somehow everyone is syncing, then new nodes can't sync themselves. That's a temporary state of affairs though. Anything else ?

Unfortunately, can't provide a concrete example. Just the change seems a bit risky to me.

**Comment by moneromooo-monero** [comment]
Would making it optional make it safe enough in your opinion ?

**Comment by xiphon** [comment]
> Would making it optional make it safe enough in your opinion ?

Yes, to some degree.

Could you shed some light on the problem you want to address? Is this an existing issue or just an optimization?

**Pull request merged**
