### PR TITLE
cryptonote_protocol_handler: fix race condition

### PR DESCRIPTION
**Pull request by perfect-daemon**

### CODE REVIEW

**Comment by mj-xmr** [comment]
Maybe I'm not the right reviewer for this, but what I can already complain is, that there's no description and not a single line of comment for all the new code.

**Comment by selsta** [comment]
@vtnerd would ideally review this, it's the race condition he previously pointed out in the deadlock patch PR.

**Review by vtnerd — COMMENTED** [review]
Is the primary purpose to move the two writes on `context.m_state` inside the strand? There are still naked (non-atomic) reads, but this is certainly an improvement.

**Comment by mj-xmr** [comment]
Please rebase, in order to grab the latest fixes of the tests. Otherwise you might introduce regressions, shadowed by the test failures.

**Review by selsta — APPROVED** [review]

**Pull request merged**
