### PR TITLE
Bump Gitian build instructions to v0.18.1.0 [Release Branch]

### PR DESCRIPTION
**Pull request by sethforprivacy**
Master version of this PR: https://github.com/monero-project/monero/pull/8442

### CODE REVIEW

**Review by tobtoht — APPROVED** [review]

**Comment by selsta** [comment]
Please rebase.

**Comment by sethforprivacy** [comment]
> Please rebase.

Rebased and squashed.

**Review by selsta — APPROVED** [review]

**Review by tobtoht — APPROVED** [review]

**Comment by hyc** [comment]
A bit late now since v0.18.1 has already been tagged.

**Comment by sethforprivacy** [comment]
> A bit late now since v0.18.1 has already been tagged.

It's just docs, so doesn't really matter when it gets added, right? Isn't in binaries etc.

**Review by jeffro256 — APPROVED** [review]

**Pull request merged**
