### PR TITLE
fixes #1660 depency on libepee.a for debug-test build

### LINKED ISSUE #1660: make debug-test failed to build: easylogging++
I sync'd with master this morning.  On Ubuntu 16.04, make debug-test

[ 60%] Linking CXX executable hash-target-tests
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::utils::s_currentHost[abi:cxx11]'
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::elStorage'
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::utils::s_currentUser[abi:cxx11]'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/hash-target-tests.dir/build.make:109: recipe for target 'tests/hash-target-tests' failed
make[3]: *** [tests/hash-target-tests] Error 1

### PR DESCRIPTION
**Pull request by tdprime**
Before change, make debug-test does,
```
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::utils::s_currentHost[abi:cxx11]'
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::utils::s_currentUser[abi:cxx11]'
../src/cryptonote_core/libcryptonote_core.so: undefined reference to `el::base::elStorage'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/hash-target-tests.dir/build.make:110: recipe for target 'tests/hash-target-tests' failed
```

Tried to add "epee" dependency to PUBLIC part of
src/cryptonote_core/CMakeLists.txt.  But, that adds libepee.a to
libcryptonote_core.so and to libwallet.so -- not necessary.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok

**Comment by tdprime** [comment]
There is something funny going on with the debug build that I am still trying to track down.

make clean; make debug-test -- this fails to link (as above)
make debug-test -- succeeds; but, rebuilds most things as if previous make was not run

**Comment by tdprime** [comment]
I found the difference between a clean build and subsequent builds,
```
< -- Building internal libraries with position independent code
---
> -- Building internal libraries as static
```

That implies the first commit is insufficient.  I will also have to open a new issue to report this new problem.

**Comment by moneromooo-monero** [comment]
epee should be before the boost libraries, as epee uses boost

**Comment by fluffypony** [comment]
@tdprime FYI, see @moneromooo-monero's comment above :)

**Comment by moneromooo-monero** [comment]
Also, do not introduce bad commits if you're just undoing them with a subsequent commit.

**Pull request closed without merging**
