### PR TITLE
daemon: remove redundant check

### PR DESCRIPTION
**Pull request by serhack**

### CODE REVIEW

**Comment by jeffro256** [comment]
Why is this check redundant? If `start_block_index > 0`, then `(uint64_t) -start_block_index` is undefined.

**Review by vtnerd — APPROVED** [review]

**Comment by vtnerd** [comment]
@jeffro256 expand the code section, this `if` statement is inside an `if` with a similar check. It doesn't hurt anything though; the compiler might be able to omit this check during optimzation phases.

**Review by jeffro256 — APPROVED** [review]
Ah, okay I see it now @vtnerd

**Comment by serhack** [comment]
Exactly @vtnerd . By the way, I did not know if I should open an PR for that trivial issue. Please close if anyone thinks it's more clear to have the redundant check.

**Pull request merged**
