### PR TITLE
cryptonote_basic: drop unused verification_context::m_not_rct field

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
There are other remaining references in wallet and tests

**Comment by xiphon** [comment]
> There are other remaining references in wallet and tests

Can't find any, could you please point to some?

**Comment by moneromooo-monero** [comment]
$ git grep not_rct
src/cryptonote_basic/verification_context.h:    bool m_not_rct;
src/rpc/core_rpc_server.cpp:      if ((res.not_rct = tvc.m_not_rct))
src/rpc/core_rpc_server_commands_defs.h:      bool not_rct;
src/rpc/core_rpc_server_commands_defs.h:        KV_SERIALIZE(not_rct)
src/rpc/daemon_handler.cpp:      if (tvc.m_not_rct)
src/wallet/wallet2.cpp:      if (res.not_rct)
tests/functional_tests/transfer.py:        assert res.not_rct == False
tests/functional_tests/transfer.py:        assert res.not_rct == False
tests/functional_tests/transfer.py:        assert res.not_rct == False

**Comment by dEBRUYNE-1** [comment]
@xiphon - Could you rebase?

**Comment by dEBRUYNE-1** [comment]
Ping @xiphon.

**Comment by xiphon** [comment]
@dEBRUYNE-1 

Done.

**Comment by dEBRUYNE-1** [comment]
Thanks!

**Pull request merged**
