### PR TITLE
[DO NOT MERGE] add (and use where appropriate) a file wipe function

### PR DESCRIPTION
**Pull request by moneromooo-monero**
This zeroes the file contents before unlinking it

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Do those supply a "secure erase" ioctl ?

**Comment by hyc** [comment]
Not really. The actual ATA `SECURE ERASE` command erases an entire drive, which is not what you want. It's possible to trigger a `TRIM` on a range of blocks, using an ioctl, but that's not quite "secure" - the blocks will typically be zeroed by the drive in the background, and if the drive implements TRIM asynchronously you won't know when it's done. In the meantime, reading those blocks thru the command interface will return zeroes, but if someone were to directly read the chips the data might still be present.

**Comment by moneromooo-monero** [comment]
Guess I could write pseudo random garbage instead. That takes care of dedup and RLE at least.

**Comment by moneromooo-monero** [comment]
Though that's in fact pointless since it gets written elsewhere anyway. Still good for HDD ?

**Comment by moneromooo-monero** [comment]
Mostly pointless, so let's close this.

**Pull request closed without merging**
