### PR TITLE
Add FreeBSD to "Signing assert files" section of gitian readme

### PR DESCRIPTION
**Pull request by MoneroArbo**
Adds FreeBSD to "Signing assert files" section of gitian readme

### CODE REVIEW

**Review by TheCharlatan — APPROVED** [review]
thank you :+1:

**Comment by moneromooo-monero** [comment]
Any chance you can add a sensible commit message ?

**Comment by MoneroArbo** [comment]
Sorry is this what you meant? This is my first set of PRs on literally anything

**Comment by moneromooo-monero** [comment]
No, that's the PR title on github. The commit message that will go in the repo says "Update README.md". I think you might have to use git rather than the github UI, not sure whether it's hard to find or not there in the UI.

**Pull request closed without merging**
