### PR TITLE
Clean removal of empty statements

### PR DESCRIPTION
**Pull request by shopglobal**
Cleaning up a little around code base, and I found empty statements on our fork. It is human error, and they are safely removed.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Can you squash those please.

**Comment by xiphon** [comment]
Don't you mind to fix all the other places?

**Comment by moneromooo-monero** [comment]
If there are many, maybe it's not worth the diffs. Those are completely harmless.

**Comment by xiphon** [comment]
> If there are many, maybe it's not worth the diffs

Yup, think so.

```
contrib/epee/demo/iface/transport_defs.h
  221,80:     s.m_storage_entry_int = epee::serialization::storage_entry(uint64_t(22222));;

contrib/epee/include/net/http_protocol_handler.h
  205,53: 				return m_config.m_phandler->init_server_thread();;

contrib/epee/include/net/munin_connection_handler.h
  240,91: 				return send_hook("Unknown command. Try list, nodes, config, fetch, version or quit\n");;

src/blockchain_db/lmdb/db_lmdb.cpp
  1956,57:   pruning_seed = tools::get_pruning_stripe(pruning_seed);;
  3200,60:     memcpy(&ret, &okp->data, sizeof(pre_rct_output_data_t));;

src/cryptonote_core/blockchain.cpp
  5155,34:   return m_db->for_all_outputs(f);;
  5160,42:   return m_db->for_all_outputs(amount, f);;

src/cryptonote_core/cryptonote_tx_utils.cpp
  145,68:       crypto::key_derivation derivation = AUTO_VAL_INIT(derivation);;

src/daemon/main.cpp
  72,66:     rpc_port_str = command_line::get_arg(vm, restricted_rpc_port);;

src/ringct/bulletproofs.cc
  175,76:     sc_mul(multiexp_data[i*2].scalar.bytes, a[ao+i].bytes, INV_EIGHT.bytes);;

src/simplewallet/simplewallet.cpp
  111,73:     m_suspend_rpc_payment_mining.store(false, std::memory_order_relaxed);; \
  1975,164:       message_writer() << tr("Difficulty: ") << diff << ", " << credits_per_hash_found << " " << tr("credits per hash found, ") << cph << " " << tr("credits/hash");;

tests/unit_tests/mul_div.cpp
  85,38:     ASSERT_EQ(hi, 0x0123456789abcdf0);;

tests/unit_tests/test_tx_utils.cpp
  47,29:   std::vector<uint8_t> extra;;
```

**Comment by shopglobal** [comment]
I'll take the time and get the others, and squash my commits. I found the
first empty statement with my eyes, thanks for the additional input fellas.

**Pull request merged**
