### PR TITLE
Update Raspberry Pi build instructions

### PR DESCRIPTION
**Pull request by bigreddmachine**
We don't have to compile boost by ourselves anymore!

### CODE REVIEW

**Comment by NanoAkron** [comment]
Would you maybe add this as a separate section for the Pi Zero rather than deleting the section on the Pi 2?

**Comment by bigreddmachine** [comment]
@NanoAkron - The Pi Zero bit is just to say that it's been tested on that. Later tonight I can test it on the 3 B (which is the same hardware as the 2 B but with bluetooth & wifi), but the way Raspberry Pi has engineered their Raspbian distribution, if it works on one it should work on all. The PR here isn't that this works on the Zero as opposed to the 2 B, but rather that it works on Raspbian Stretch out of the box, whereas with Raspbian Jessie we used to have to compile boost separately. Now just the regular `sudo apt-get libboost-all-dev` works as it should have all along.

Honestly, if anything the instructions shouldn't specify any particular hardware, which is why I changed the section header to say just "Raspberry Pi" instead of "Raspberry Pi 2". With the new Stretch OS, this should work on the OG Pi, the Zero, the 2, or the 3.

**Comment by bigreddmachine** [comment]
@NanoAkron - I suppose we could leave an old section for "Build on Raspbian Jessie" but separating by device type doesn't make sense right now because they all work the same regardless of hardware. If you'd like me to change the PR to reflect that I'd be happy to.

**Comment by NanoAkron** [comment]
Agree with your point - better to separate by OS rather than hardware

**Comment by NanoAkron** [comment]
By which I mean please leave in the stuff for Jessie :)

**Comment by bigreddmachine** [comment]
Sure, I can do that.

I wonder at what point it would be appropriate to remove that though. Any new installations *should* be using Stretch, and any old Jessie installations would have already done the boost compiling heavy lifting. I understand leaving it in for now, I suppose, but by 3-4 months from now it really wouldn't serve a purpose anymore... why would anyone be using Jessie at that point?

Anyway, I can modify the PR tonight after work to have a section for Raspbian Stretch and another for Raspbian Jessie.

**Comment by NanoAkron** [comment]
I agree. By the time of the next hard fork, we can probably deprecate the instructions

**Comment by bigreddmachine** [comment]
@NanoAkron, I've included another section for Raspbian Jessie explaining the extra steps needed to take. If reviewing without the commit diff is easier, one way you can get to the current state is here: https://github.com/bigreddmachine/monero/blob/master/README.md#on-the-raspberry-pi

Any thoughts?

**Comment by NanoAkron** [comment]
I like it :)

**Pull request merged**
