### PR TITLE
easylogging++: make this build on OpenBSD and musl

### PR DESCRIPTION
**Pull request by moneromooo-monero**
execinfo.h is not available there

### CODE REVIEW

**Comment by Dyrcona** [comment]
Following the build instructions for OpenBSD, the build still fails for me with this branch:

In file included from /home/jason/monero/external/easylogging++/easylogging++.cc:18:0:
/home/jason/monero/external/easylogging++/easylogging++.h:367:25: fatal error: execinfo.h: No such file or directory
 #   include <execinfo.h>

$ git branch
* execinfo.h

Is there something else I'm supposed to do?

**Comment by moneromooo-monero** [comment]
I don't have OpenBSD. I tried to fix without being able to build on it. Looks like there's a glibc without execinfo. __has_include is on GCC 5, but we support GCC 4.9, so this'd have to be checked so that __has_include is not used with GCC 4.9. If you can build on OpenBSD, please feel free to make a patch.

**Comment by Dyrcona** [comment]
Well, I'm using my patch from #2249 for now. I'm using GCC 4.9.

The way I would normally fix this, if the project used autotools, would be to check for execinfo.h in the configure script using autotools conventions. Maybe we should check for execinfo.h in cmake and have it define if it is present or not? I think cmake can do that. I've never used it, myself, so I'll have to learn how.

**Comment by danrmiller** [comment]
@moneromooo-monero I'll try this out and also get you access to an openbsd box. I'm using clang 3.8.0 on openbsd.

**Comment by moneromooo-monero** [comment]
Thanks, but looks like dyrcona is able to do and test this anyway, so we should be good. I'll close that since it doesn't actually work.

**Pull request closed without merging**
