### PR TITLE
Changed the use of boost:value_initialized for C++ list initializer

### PR DESCRIPTION
**Pull request by JesusRami**
I have replaced the boost:value_initialized method with the use of C++ initializer_list {}

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
What does it fix or improve ?

**Comment by JesusRami** [comment]
This replace the use of an initialization method from an external library with a feature already integrated in the language. This improve the portability of the code.

You can see more of this here:
https://akrzemi1.wordpress.com/2013/09/10/value-initialization-with-c/

**Comment by dEBRUYNE-1** [comment]
@JesusRami - Could you rebase this PR?

**Comment by moneromooo-monero** [comment]
whyiamroot rebased this, so closing

+duplicate

**Pull request closed without merging**
