### PR TITLE
fix: minor spelling issue

### PR DESCRIPTION
**Pull request by Justbeingjustin**
The word 'dont' is not spelled correctly.

### CODE REVIEW

**Comment by fluffypony** [comment]
@Justbeingjustin please rebase

**Comment by moneromooo-monero** [comment]
Please squash, you've got a merge commit in it.
Easiest is probably:
git rebase -i HEAD~2
replace the second "pick" with "f"
Save and exit

**Comment by fluffypony** [comment]
@Justbeingjustin FYI this just needs a squash and I can merge it :)

**Comment by fluffypony** [comment]
@Justbeingjustin please squash, when you get a moment

**Comment by fluffypony** [comment]
@Justbeingjustin giving this a final ping - will have to close and get someone else to do it and credit you if you don't have time to squash :)

**Comment by moneromooo-monero** [comment]
Recreated in https://github.com/monero-project/monero/pull/5411

+duplicate

**Pull request closed without merging**
