### PR TITLE
construct_tx_and_get_tx_key: return sorted sources for print_ring_memebrs to work properly

### PR DESCRIPTION
**Pull request by stoffu**
Fix for PR #2440

### CODE REVIEW

**Comment by stoffu** [comment]
Currently, the function `simple_wallet::print_ring_members` behaves incorrectly where `ptx_vector[n].construction_data.sources[i]` is referenced:

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/simplewallet/simplewallet.cpp#L2277

This is because the `sources` passed to `construct_tx_and_get_tx_key` is passed by value and doesn't change even though it gets sorted inside the function, and then it is assigned to ptx as

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/wallet/wallet2.cpp#L4114

This patch fixes this problem by making the `sources` argument passed by reference.

**Comment by moneromooo-monero** [comment]
Well, this doesn't explain anything, this just paraphrases the patch. What was behaving incorrectly ?

**Comment by stoffu** [comment]
Well, the `source` variable is used multiple times in the subsequent lines, e.g.,

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/simplewallet/simplewallet.cpp#L2278

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/simplewallet/simplewallet.cpp#L2308

And hence the printed text becomes wrong because the ordering of `ptx.construction_data.sources` and that of `tx.vin` are inconsistent due to sorting. Am I unclear?

**Comment by moneromooo-monero** [comment]
Do you just mean it displays the rings in a different order that they appear in the tx ?

**Comment by stoffu** [comment]
No, it displays the wrong amount due to this

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/simplewallet/simplewallet.cpp#L2278

and indicates the wrong mixin partner as the real spent output due to this

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/simplewallet/simplewallet.cpp#L2308

and this

https://github.com/monero-project/monero/blob/21c2c080416049a042b696ddae5a559176d2ccde/src/simplewallet/simplewallet.cpp#L2319

Anyway, the displayed information becomes completely wrong.

**Comment by moneromooo-monero** [comment]
Ah, that makes sense. Thank you :)

**Pull request merged**
