### PR TITLE
Show available types in db-type and remove db-auto-remove-logs

### PR DESCRIPTION
**Pull request by IPGlider**
Not needed anymore since the complete switch to LMDB.

Related to #1533.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
db-sync-mode is not actually removed.

I'd rather keep db-type, as more db types could be added later. Adding a help note mentioning the list (ie, only lmdb right now) would be better.

**Comment by IPGlider** [comment]
@moneromooo-monero The commit message should say db-auto-remove-logs instead of db-sync-mode options, my mistake.

I can modify the code to keep the db-type option as you say, but I think db-auto-remove-logs can be removed safely because is only used by the BerkeleyDB backend.

**Comment by moneromooo-monero** [comment]
The logs one is fine to remove, yes. I just want to avoid removing stuff that we'll when/if we add another db type. If  the commit message mentions the right option, it's all good. Thanks.

**Comment by moneromooo-monero** [comment]
The changes look good, thank you. Please squash the "remove db type" and "bring back db type" patches though. ok after that.

**Pull request merged**
