### PR TITLE
add another seed node

### PR DESCRIPTION
**Pull request by Gingeropolous**
node is funded by random people and managed by me. currently functioning as public node at uwillrunanodesoon.moneroworld.com

### CODE REVIEW

**Comment by selsta** [comment]
Please rebase.

**Comment by Gingeropolous** [comment]
ah shit the github gui makes this a proper pita. lemme try some buttons. if all else fails i can just make a new one. theres another IP i wanna add anyways.

**Comment by selsta** [comment]
Comment the other IP here you want to add here https://github.com/monero-project/monero/pull/6471

**Comment by Gingeropolous** [comment]
sounds good. Closing this one.

**Pull request closed without merging**
