### PR TITLE
TS files updated after changes to UI strings in the source code

### PR DESCRIPTION
**Pull request by ordtrogen**

### CODE REVIEW

**Comment by erciccione** [comment]
@ordtrogen, we got many important merges in the past days. Could you rebase and refresh again, so it's synced?

**Comment by ordtrogen** [comment]
Ohh, rebasing and refreshing, eh?  Everytime I've tried to do something fancy in git I've messed it up. What if I just pulled this PR, did the stuff and created a new PR?

**Comment by erciccione** [comment]
@ordtrogen I don't remember if you use git, in that case you can use `git pull upstream master --rebase`  the `--rebase` part will put your changes on top and will avoid the merge commit. Btw, in case just leave this as it is, we can refresh again later on

**Comment by ordtrogen** [comment]
Yeah sure. I use git on the command line. And I have learned to update my fork on github by pulling from upstream etc.  :-)

I'll give this a shot and see how it goes

**Comment by ordtrogen** [comment]
Crikey! Did this just work?  (can't believe it)

**Comment by erciccione** [comment]
Actually no. Looks like a lot of commits got in. The problem is with that merge commit

**Comment by erciccione** [comment]
Mooo has a point here actually, better update it when necessary

**Comment by ordtrogen** [comment]
How am I supposed to interpret this?

I have spent a ton of work translating both the CLI and the GUI. Now I wanted to continue translating the new strings, and maybe the guy who did a massive job on the French translation would like to continue, too. 

@erciccione, you being the localization coordinator and all, Please explain mooo's point cause I don't get it. Do we want to discourage people from contributing now?

**Comment by glv2** [comment]
@ordtrogen, I think @moneromooo-monero  meant that instead of making a PR that only adds the new strings to translate to the TS files, it would be better to make a PR that adds the new strings and their translations (in at least one language).

In fact, it might even be better if translators made PRs modifying only the TS file they worked on (running lupdate on it and translating) instead of also updating all the other TS files. It would reduce the probability of translation PR conflicts and allow translators not to have to wait for the global-TS-update PR to be merged before working on a TS file.

**Comment by ordtrogen** [comment]
Now, that makes sense!
Thanks, @glv2

**Comment by moneromooo-monero** [comment]
The "TS files updated" message is not very helpful. It sounds like you just ran the Qt tool. If you added/changes translations, then the commit mesage should say so and for which language.

**Comment by ordtrogen** [comment]
Well I did just run the Qt tool (the script update-translations.sh to be precise)

I see the instructions on
https://github.com/monero-project/monero/blob/master/README.i18n.md
do call for the translators themselves to extract the translatable files. Which I assume would require Linux.

OTOH having the TS files updated regularly would make it clearer what, if anything, needs to be translated and would lower the bar for anybody who'd like to contribute. My experience is that's how it has worked in the past. And now as a lot had changed, I wanted to help out. But it seems this PR is messed up anyway so I'll close it and just PR my own translation when it's finished.

**Comment by ordtrogen** [comment]
Apart from that, a big pile of respect to all you hard working contributors out there!  :-)

**Comment by moneromooo-monero** [comment]
I don't get it. If you just ran the updating tool, how does ignoring this PR impact the ton of work you've done (or will do) ? I think I'm missing something here.

**Pull request closed without merging**
