### PR TITLE
Simplify readline support

### PR DESCRIPTION
**Pull request by hyc**
And don't use std::mutex

Removes extraneous readline thread, avoids redundant copying/allocing buffers, etc...

### CODE REVIEW

**Comment by jtgrassie** [comment]
My fear with this PR is that a lot of old strange edge cases that were fixed may now have been lost.

**Comment by hyc** [comment]
@jtgrassie can you expand on that? What edge cases did you encounter before? It looks to me like the old code created more problems than it solved. In particular, using a dedicated thread for readline, which did a select() on stdin, while the existing reader thread also did the same thing, was a recipe for failure.

**Comment by jtgrassie** [comment]
There were quite a few that @moneromooo-monero found (like show_transfers, odd crashes etc). Also getting it working when in the interactive daemon correctly (e.g. start typing, other logs come though, you must hold the readline prompt). Don't get me wrong, I like the cleanup, just we went through a lot of testing to get it stable across the various IO in daemon and wallet. I'd rather just make sure we all do some testing before this gets merged so we don't lose anything.

**Comment by moneromooo-monero** [comment]
Some testing would be good, yes, but as this loses the extra thread, a lot of the racy stuff is just now gone by design. I tested a bit earlier and it looked good, but some more will be welcome.

**Comment by jtgrassie** [comment]
Quick question, what versions of readline have you both tested on thus far?

**Comment by moneromooo-monero** [comment]
hyc made the patch on 7.0, I'm on 6.3.

**Pull request merged**
