### PR TITLE
Remove Boost for macros

### PR DESCRIPTION
**Pull request by IPGlider**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Is it just preference, or does it change anything ?

**Comment by IPGlider** [comment]
Kind of preference, the behaviour is exactly the same.

BOOST_FOREACH and BOOST_REVERSE_FOREACH where useful pre C++11 because ranged for was not available, but is better to use the native syntax than a macro.

The codebase already has many ranged for. Also macros are not type safe.

**Comment by NanoAkron** [comment]
Squash as single concept change?

**Comment by moneromooo-monero** [comment]
OK. Surprising those macros aren't type safe, boost is usually a stickler for that.

**Pull request merged**
