### PR TITLE
updated CMakeLists.txt

### PR DESCRIPTION
**Pull request by SanyuktaSaha**
removed paranthesis

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Why ?

**Comment by mpenkov** [comment]
> Why ?

@moneromooo-monero https://hacktoberfest.digitalocean.com/faq#rules

**Comment by moneromooo-monero** [comment]
If you want to participate in the hacktoberfest, please feel free. We had a few bugs labelled last year as a posible guide. The GUI is in another repo, you might want to look at it too, it may be easier for a new coder to start with.

**Comment by moneromooo-monero** [comment]
+invalid

**Pull request closed without merging**
