### PR TITLE
DOCS: Add documentation for EPEE Portable Storage

### PR DESCRIPTION
**Pull request by jeffro256**
Ripped directly from @jtgrassie 's [monero-binary-rpc repo](https://github.com/jtgrassie/monero-binary-rpc/blob/master/reference/portable-storage.md). It's a very helpful little document and I think it deserves a place in the main repo.

### CODE REVIEW

**Comment by jtgrassie** [comment]
It would be nice if the changes _weren't_ squashed (to easily see the changes made to the upstream document).

**Comment by jeffro256** [comment]
@jtgrassie done! I'll post any changes to the document as a amendment to the second commit. Obviously feel free to discuss the changes.

**Comment by jeffro256** [comment]
Waiting to see if #8226 gets merged

**Review by tobtoht — APPROVED** [review]

**Comment by jeffro256** [comment]
@selsta @tobtoht ready for review

**Comment by selsta** [comment]
Minor but epee is spelled `epee`, not all caps: https://github.com/monero-project/monero/blob/master/contrib/epee/README.md

**Review by selsta — APPROVED** [review]

**Comment by jtgrassie** [comment]
The image just added is 1) wrong (it has mistakes) and 2) means it's difficult for anyone to fix (as there is no source for the image).

**Comment by jeffro256** [comment]
@jtgrassie Dang it you're right, I miscolored it in a couple spots and I really didn't like using an image, but Github doesn't support changing markdown styling. Maybe I could structure it like this:
 
```
01 11 01 01 01 01 02 01      01         // signature, version
14                                      // # of entries in section
0b                                      // length of section key "short_quote"
...

```

This makes the structure of a section, clearer and it's much easier to edit. I think it would be good to have a complete example, but I agree that my image is not a good medium for conveying that.

**Pull request merged**
