### PR TITLE
wallet: reroll fake outs selection on local tx_sanity_check failure

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Does this reuse the fake outs it requested on the first attempt (the wallet asks for more than it needs in the first place in case some are not usable) ?

**Comment by xiphon** [comment]
> Does this reuse the fake outs it requested on the first attempt (the wallet asks for more than it needs in the first place in case some are not usable) ?

Updated. Have to clear ringdb and outs cache on failed tx sanity check to force fetching new fake outs on the next attempt.

That said if generated tx passes sanity check, the following `transfer_selected_rct` call will reuse the outs.

Does this cover the case you mentioned? If not, could you please provide more details.

**Comment by moneromooo-monero** [comment]
It should not fetch new outputs, unless it really needs to. My point is that since it already requests more outputs than necessary from the daemon, it should not request other outputs if it can rearrange its pick from the outputs it already has. Failing that, it should ask additional outputs (rather than a full replacement) to avoid the daemon being able to tell which output is the real spend.

**Comment by xiphon** [comment]
Updated. Attempts to reroll fake outputs from the same outputs set it initially received from the daemon.

**Comment by moneromooo-monero** [comment]
Are you sure ? The top level loop calls get_outs repeatedly (if the sanity check fails) and the first thing get_outs does is clear the outs, and will call the daemon again to get outputs. What am I missing ?

**Comment by xiphon** [comment]
`get_outs` clears previously selected `outs` that were picked from `rct_offsets`, `rct_offsets` is outputs set the daemon returned on the first `get_outs` call and it doesn't get updated during all the attempts (see line 7809)

**Comment by moneromooo-monero** [comment]
Great. I thought rct_offets were the per block distribution on reading. All good then, thanks.

**Pull request merged**
