### PR TITLE
simplewallet.cpp: Add export_outputs help

### PR DESCRIPTION
**Pull request by SomaticFanatic**
#6547

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
If you're going to add this, might as well add the whole set of commands. Either the actual step needed, or the series, not just a couple ones in the series.

**Comment by SomaticFanatic** [comment]
You’re saying I need to outline the entire offline signing process?

**Comment by moneromooo-monero** [comment]
Maybe. I'm not sure what you mean by that. What I mean is that mentioning two commands out of the four is worse than mentioning either the four ones or just the one that is actually needed.

**Comment by SomaticFanatic** [comment]
Tied up at the moment but I will try to get around to this next month.

**Comment by SomaticFanatic** [comment]
How does this sound?

**Comment by moneromooo-monero** [comment]
Looks OK. Please squash.

**Comment by SomaticFanatic** [comment]
Done

**Comment by SomaticFanatic** [comment]
Wew screwed up this PR so I'll close it and open a new one

**Pull request closed without merging**
