### PR TITLE
set libatomic for cmake on armv7

### PR DESCRIPTION
**Pull request by danrmiller**
@MoroccanMalinois pointed out in IRC that this will fix building the "release-static-linux-armv7" target and I tested that it does. Here is an example of the error before the change:

https://build.getmonero.org/builders/monero-static-ubuntu-arm7/builds/1381/steps/compile/logs/stdio

### CODE REVIEW

**Comment by danrmiller** [comment]
Sorry, hold up on this, I'll look at the next error now.

https://build.getmonero.org/builders/monero-static-ubuntu-arm7/builds/1383/steps/compile/logs/stdio

[ 88%] Linking CXX executable ../../bin/monero-wallet-rpc
CMakeFiles/wallet_rpc_server.dir/wallet_rpc_server.cpp.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const':
/home/buildbot/slave/monero-static-ubuntu-arm7/build/src/wallet/wallet_rpc_server.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv]+0x18): undefined reference to `boost::program_options::arg'
/home/buildbot/slave/monero-static-ubuntu-arm7/build/src/wallet/wallet_rpc_server.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv]+0x20): undefined reference to `boost::program_options::arg'

**Comment by hyc** [comment]
Your libboost was not built with the same version of g++ as you're using now.

Also for the record, my ARMv7 compile runs to completion without any mention of libatomic.

**Comment by danrmiller** [comment]
> Your libboost was not built with the same version of g++ as you're using now.

Thanks, its the boost deb packages from the scaleway ubuntu port and clang++ from the scaleway ubuntu repo also. I'll try building with g++.

**Comment by danrmiller** [comment]
> Also for the record, my ARMv7 compile runs to completion without any mention of libatomic.

This is self-hosted, you mentioned you are cross-compiling. Do you recommend I make local configuration changes to find libatomic instead of adding this to CMake?

**Comment by hyc** [comment]
I suggest you don't mix compilers and pre-built libraries. Distros use g++ to build their libraries, not clang++. Also I suggest you build boost yourself instead of using a distro package. AFAICS there's no reason for libatomic to be a dependency here.

**Comment by danrmiller** [comment]
Thanks. Yes with the distro provided boost and g++ the other errors are gone and it builds, so long as the libatomic addition to CMakelists is there. I don't think that is related to libatomic.

My thought would be that most users will want to use the boost libs from their distribution, so if possible my opinion would be that using them should work and be tested. 

I'll try again with self-built boost libs, but I suspect it will still complain about libatomic. I'll try a different platform and see if it has similar issues about libatomic too.

**Comment by hyc** [comment]
Release binaries should be statically linked, so it doesn't matter what version of boost end-users have on their own systems.

**Comment by danrmiller** [comment]
> Release binaries should be statically linked, so it doesn't matter what version of boost end-users have on their own systems.

Yes, I just want to clarify I'm not talking about release binaries, I am talking about making sure users who download the source and try to build on their platform can do so.

**Comment by fluffypony** [comment]
@danrmiller please resolve conflict

**Comment by danrmiller** [comment]
I cleared the cmake cache, and it is building and locating atomic without the change. Closing.

**Pull request closed without merging**
