### PR TITLE
Limit incoming connections from the same IP

### PR DESCRIPTION
**Pull request by IPGlider**
Related to #1338.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
OK in general, just a comment to fix

**Comment by IPGlider** [comment]
Forgot the comment? :)

**Comment by anonimal** [comment]
Will this effect Tor users (more than 3 connections from 1 exit node)?

**Comment by IPGlider** [comment]
@anonimal With the current implementation Tor users would be affected. Maybe a check can be added to skip the limit or make it bigger in case of Tor exit nodes.

**Comment by anonimal** [comment]
Hmm.... does this also effect connections to the RPC server? If so, then this limit would be terrible for any nodes who run public onions which point to `127.0.0.1`.

**Comment by moneromooo-monero** [comment]
Yes, forgot the comment. It's so bloody annoying the way you have to remember to go find the commit button after the end...

**Comment by IPGlider** [comment]
@anonimal This change is only for the P2P, does not affect RPC connections.

**Comment by NanoAkron** [comment]
Should this maybe be a user option with a default value?

Or would it be so rarely changed that not exposing it to the user is the better choice here?

**Comment by IPGlider** [comment]
I can add an option if it is necessary. Should I do it?

**Comment by NanoAkron** [comment]
I'll defer to @moneromooo-monero or @fluffypony's opinion on that.

My thought is that it'll be useful whilst power users are using TOR, so they can increase the value as appropriate, but then once we switch to kovri (in a year maybe?) this will all have to be stripped out or modified again.

**Comment by moneromooo-monero** [comment]
I have no strong opinion, except that preventing proxies must not be done.

**Comment by NanoAkron** [comment]
Is there an easy way to recognise a TOR exit node or proxy and whitelist them?

**Comment by fluffypony** [comment]
@NanoAkron no there isn't, but I think that's largely unnecessary. You wouldn't WANT to accept multiple connections from the same proxy / exit node, as you're giving that proxy / exit node the ability to isolate your node. IMHO this is merge-able, barring any other issues?

**Comment by NanoAkron** [comment]
@fluffypony would you want this as a user option, or as a hard default value?

**Comment by anonimal** [comment]
>For a standard user, the lower default value would provide a safety belt.

I think this is a preemptive optimization. I think this entire PR is preemptive optimization unless there is a proven fault in the p2p system or a lingering issue that I don't know about (if so, can someone fill me in?).

>But then once we switch to kovri (in a year maybe?) this will all have to be stripped out or modified again.

I don't see why, but only if p2p sees in the incoming connection as `127.0.0.1` (or if kovri address is serving as a proxy for multiple nodes). If either are the case, then even now, this PR severely limits flexibility for advanced operators who have more involved network configurations and I would strongly advise against merging until all options are considered (more information needed, at least for me).

>You wouldn't WANT to accept multiple connections from the same proxy / exit node, as you're giving that proxy / exit node the ability to isolate your node

If someone wants to run 10 nodes behind a single IP address because they can't afford more IP space, why can't they? As for a Tor exit node isolating a monero node, is there a magic number to avoid? (exits can't (shouldn't be able to) determine originator)

>I have no strong opinion, except that preventing proxies must not be done.

I agree and I think - at a minimum - a user option is a must.

With that said, how can we anticipate what current site operators are doing internally? We can't, so unless I'm way-off here, I don't think we should blindly limit connections at this layer without a little more discussion. Is there MRL work or a spec somewhere that this PR is based from?

**Comment by fluffypony** [comment]
> I don't see why, but only if p2p sees in the incoming connection as 127.0.0.1 (or if kovri address is serving as a proxy for multiple nodes).

Not you're right, that's definitely incorrect, the p2p layer would see it as coming from ```blahblahhexstring.i2p```, not from an IP address.

> If someone wants to run 10 nodes behind a single IP address because they can't afford more IP space, why can't they?

Because it's a Sybil attack against the network, so they should be punished. We rely on limited IP space to make Sybil attacks expensive. This is a good, but dense, read on the subject: https://dsn.tm.kit.edu/publications/files/301/dissect2015_dsn.pdf

> As for a Tor exit node isolating a monero node, is there a magic number to avoid? (exits can't (shouldn't be able to) determine originator)

The magic number really should be "1 connection per IP address", which means you'd never allow more than 1 connection from an exit node. A good read on this is here: https://csdl.computer.org/csdl/proceedings/sp/2015/6949/00/6949a122.pdf

> I agree and I think - at a minimum - a user option is a must.

I disagree, this should be 1 connection per IP address, and 1 connection per C-class. Any weird use case that requires overriding it can be modified in the code. Given the immaturity of the network it's *ok* to have it at 3 right now, but that should be reduced to 1 over the next 24-36 months.

**Comment by anonimal** [comment]
This was discussed further in IRC. There are proven arguments both for and against merging this right now. It seems that partitioning is of greater concern right now, so if this PR does more good than harm then great. I still think there are more resilient solutions though I can't articulate them at the moment.

**Comment by IPGlider** [comment]
Reduced to one connection per IP. I see the pros and the cons, up to you guys to dice if goes in or not.

If anything change is needed just ask.

**Comment by moneromooo-monero** [comment]
Do we want to make it C class then ? Or maybe a limit of 2 for IPs in the same C class or something. Trivial to add.

**Comment by NanoAkron** [comment]
Sounds reasonable

**Comment by IPGlider** [comment]
IMHO it would be better to see how the network behaves with the one connection per address approach before going one connection per C class.

**Comment by NanoAkron** [comment]
Also reasonable

**Comment by iamsmooth** [comment]
I'm not convinced this is a good idea. I absolutely agree on one connection per address or even wider ranges such as /24 or /16 _for outgoing connections_ but I'm not convinced that adding this restriction on incoming is a good idea. Restricting incoming connections on all nodes makes an isolation attacker's job easier by reducing competing open ports available to a user who does find himself, even unknowingly, behind a shared IP (such an attacker would certainly disable the restriction on his own nodes).

Generally a node ought to be suspicious of relying entirely on incoming connections anyway, since they were all initiated by someone else (potentially all by the same attacker) whose motives are unknown. Perhaps a node that has not yet established _outgoing_ connections using addresses of its own choosing should be considered to be operating in a sort of degraded mode (with appropriate warning to the user). But I don't know that is a good reason to block these connections altogether.

**Pull request merged**
