### PR TITLE
cmake: Fix generation of version.cpp

### LINKED ISSUE #6012: Version string is only updated on clean build, not incremental
After a clean build, `monerod --version` shows the correct git commit hash it was built from. (This same version string is also logged during normal daemon startup.) However, after updating the source and rebuilding in the same directory, the new binary continues to report the old commit hash, from when the clean build was done.

```
% git status --ignored && git log -1
On branch master
Your branch is behind 'origin/master' by 36 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working tree clean
commit 441ed9f2fef6a43708c115191c51ca16930ce95b
Merge: 6c0572398 515e9316b
Author: luigi1111 <luigi1111w@gmail.com>
Date:   Wed Oct 16 13:54:06 2019 -0500

    Merge pull request #5990
    
    515e931 functional_tests: fix transfer test - long payment ids are gone (moneromooo-monero)
% time make -j8
...
make -j8  3529.69s user 139.56s system 600% cpu 10:10.84 total
% ls -l build/**/bin/monerod 
-rwxr-x--- 1 ndorf ndorf 13623808 Oct 23 11:18 build/Linux/master/release/bin/monerod
% ./build/Linux/master/release/bin/monerod --version
Monero 'Boron Butterfly' (v0.14.1.2-441ed9f2f)
```

The clean build above prints the correct hash, 441ed9f2f. The incremental build below still prints the same one, but it should print 4233d8834:

```
% git pull
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 4233d88341a074450c38064807ed348fe4691019.
% git submodule update --recursive
Submodule path 'external/randomx': checked out 'b53f0ed145c1a51df6ca0708a215089b76d0c056'
% git status --ignored && git log -1
On branch master
Your branch is up-to-date with 'origin/master'.
Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

	build/

nothing to commit, working tree clean
commit 4233d88341a074450c38064807ed348fe4691019
Merge: bb2bcf352 abd376313
Author: luigi1111 <luigi1111w@gmail.com>
Date:   Tue Oct 22 10:54:46 2019 -0500

    Merge pull request #5973
    
    abd3763 cryptonote: fill in tx weight when syncing from pruned blocks (moneromooo-monero)
% time make -j8
...
make -j8  3410.07s user 129.51s system 613% cpu 9:37.02 total
% ls -l build/**/bin/monerod        
-rwxr-x--- 1 ndorf ndorf 13654712 Oct 23 11:33 build/Linux/master/release/bin/monerod
% ./build/Linux/master/release/bin/monerod --version
Monero 'Boron Butterfly' (v0.14.1.2-441ed9f2f)
```

In this example, all or almost all of the sources were rebuilt (9:37 vs 10:10 time), but the new executable is still printing the old version. After another clean build, it finally shows the correct one:

```
% git clean -xdf
Removing build/
% time make -j8
make -j8  3520.28s user 135.10s system 618% cpu 9:51.12 total
% ls -l build/**/bin/monerod 
-rwxr-x--- 1 who who 13650616 Oct 23 11:48 build/Linux/master/release/bin/monerod
% ./build/Linux/master/release/bin/monerod --version
Monero 'Boron Butterfly' (v0.14.1.2-4233d8834)
```

### PR DESCRIPTION
**Pull request by ndorf**
This fixes #6012 and seems to work correctly in all cases. The file is regenerated if and only if the version tag changes (or the input file does). In particular:

1) Nothing is regenerated or rebuilt if nothing changes in the source tree
2) After `git commit --allow-empty -m 'whatever'`, the version file is regenerated and built, and the executables quickly relinked, with no unexpected other targets being built. The new executables report the correct new version hash.
3) Modifying the input file `src/version.cpp.in` or deleting the output file `build/.../version.cpp` causes the file to be regenerated with no unexpected errors.

Additionally, since 33e91e1a1e94c2957f59def9fe49f75956a9f699, I don't think the two cases not using GenVersion.cmake could have worked -- they don't set `VERSION_IS_RELEASE`, without which the generated version.cpp fails to compile (empty space after the bool assignment). That should also be fixed here.

### CODE REVIEW

**Comment by ndorf** [comment]
Just noticed that #1 isn't quite true: for some unknown reason, epee and randomx are unexpectedly rebuilt on the first incremental build only. Subsequent ones build nothing as expected. That's unrelated to this patch though, it happens with or without it.

(IOW: `rm -rf build; make; make; make` -- The first make builds everything and the third builds nothing, as expected. The second unexpectedly builds epee and randomx.)

**Comment by hyc** [comment]
@ndorf that double-build isn't happening here. Probably your system clock is wrong. Patch looks good to me.

**Comment by trasherdk** [comment]
This is breaking building outside source tree.
```
.
├── build-monero-release-v0.15 <== ( cmake bla bla ../monero-src-release-v0.15 )
├── monero-release-v0.15 <======== ( binaries to build package )
├── monero-src-release-v0.15 <==== ( git clone ... )
└── packages
```
When running cmake:
```
-- Found Git: /usr/bin/git
fatal: Not a git repository (or any parent up to mount point /home/user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Warning at cmake/GitVersion.cmake:42 (message):
  Cannot determine current commit.  Make sure that you are building either
  from a Git working tree or from a source archive.
Call Stack (most recent call first):
  cmake/Version.cmake:42 (get_version_tag_from_git)
```
Did I miss something?

```
$ ./monero-release-v0.15/monerod --version
Monero 'Boron Butterfly' (v0.14.1.2-unknown)
crypto@ghost-m1:~/local/build/build-monero$ cd monero-src-release-v0.15/
crypto@ghost-m1:~/local/build/build-monero/monero-src-release-v0.15$ git branch -a
  master
* release-v0.15
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/release-v0.11.0.0
  remotes/origin/release-v0.12
  remotes/origin/release-v0.13
  remotes/origin/release-v0.14
  remotes/origin/release-v0.15
```

**Comment by hyc** [comment]
@trasherdk try with this patch:
````
diff --git a/cmake/GitVersion.cmake b/cmake/GitVersion.cmake
index a367787f1..b35f17958 100644
--- a/cmake/GitVersion.cmake
+++ b/cmake/GitVersion.cmake
@@ -32,6 +32,7 @@
 
 function (get_version_tag_from_git GIT)
     execute_process(COMMAND "${GIT}" rev-parse --short=9 HEAD
+                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                     RESULT_VARIABLE RET
                     OUTPUT_VARIABLE COMMIT
                     OUTPUT_STRIP_TRAILING_WHITESPACE)
````

**Comment by trasherdk** [comment]
@hyc Thanks, but.. that's not it.

`CMAKE_SOURCE_DIR` is pointing to the right place, but no cigar.

```
./Makefile:51:CMAKE_SOURCE_DIR = /home/user/local/build/build-monero/monero-src-release-v0.15
```
The same goes for `CMAKE_BINARY_DIR`
```
./Makefile:54:CMAKE_BINARY_DIR = /home/user/local/build/build-monero/build-monero-release-v0.15
```

The cmake output:

```
$ cmake -D ARCH=x86-64 -D CMAKE_BUILD_TYPE=Release ../monero-src-release-v0.15/
-- CMake version 3.5.2
-- Building without build tag
-- Checking submodules
-- Submodule 'external/miniupnp' is up-to-date
-- Submodule 'external/unbound' is up-to-date
-- Submodule 'external/rapidjson' is up-to-date
-- Submodule 'external/trezor-common' is up-to-date
-- Submodule 'external/randomx' is up-to-date
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Using LMDB as default DB type
-- Stack trace on exception enabled (using easylogging++)
-- Using OpenSSL include dir at /usr/include
-- Could NOT find HIDAPI (missing:  HIDAPI_LIBRARY HIDAPI_INCLUDE_DIR) 
-- Found miniupnpc API version 16
-- Using in-tree miniupnpc
-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 64-bit LMDB from source tree
-- Backtrace_LIBRARY: 
-- Setting CXX flag -maes
-- Setting C flag -maes
-- Could not find HIDAPI
-- Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Could not find Protobuf
-- Building on x86_64 for x86-64
-- AES support enabled
-- Performing Test _fcf_protection=full_c
-- Performing Test _fcf_protection=full_c - Failed
-- Performing Test _fcf_protection=full_cxx
-- Performing Test _fcf_protection=full_cxx - Failed
-- Using C security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- Found Boost Version: 105900
-- Found readline library at: /usr
-- Found Git: /usr/bin/git
-- You are currently on commit 3b0a43a8d
fatal: Not a git repository (or any parent up to mount point /home/user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Warning at cmake/GitVersion.cmake:54 (message):
  Cannot determine most recent tag.  Make sure that you are building either
  from a Git working tree or from a source archive.
Call Stack (most recent call first):
  cmake/Version.cmake:42 (get_version_tag_from_git)
  src/CMakeLists.txt:103 (include)


-- Trezor support disabled
-- Not building tests
-- Not building debug utilities
Doxygen: graphviz not found - graphs disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/local/build/build-monero/build-monero-release-v0.15
```

**Comment by trasherdk** [comment]
Tried this one too:
```
    execute_process(COMMAND "${GIT}" -C ${CMAKE_SOURCE_DIR} rev-parse --short=9 HEAD
                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                    RESULT_VARIABLE RET
                    OUTPUT_VARIABLE COMMIT
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
```
Which works, when run as:
```
$ git -C ../monero-src-release-v0.15  rev-parse --short=9 HEAD
3b0a43a8d
```

**Comment by trasherdk** [comment]
Actually. Building in `souurce-dir/build` and `build-dir` gives the same result now:
```
build-monero-release-v0.15$ ./bin/monerod --version
Monero 'Boron Butterfly' (v0.14.1.2-3b0a43a8d)
```
```
monero-src-release-v0.15/build$ ./bin/monerod --version
Monero 'Boron Butterfly' (v0.14.1.2-3b0a43a8d)
```
Only the `fatal: Not a git repository` part differs.

**Comment by trasherdk** [comment]
This one seems to do the trick.
```
$ git diff
diff --git a/cmake/GitVersion.cmake b/cmake/GitVersion.cmake
index a367787f..13ab938a 100644
--- a/cmake/GitVersion.cmake
+++ b/cmake/GitVersion.cmake
@@ -31,7 +31,8 @@
 # Check what commit we're on
 
 function (get_version_tag_from_git GIT)
-    execute_process(COMMAND "${GIT}" rev-parse --short=9 HEAD
+    execute_process(COMMAND "${GIT}" -C ${CMAKE_SOURCE_DIR} rev-parse --short=9 HEAD
+                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                     RESULT_VARIABLE RET
                     OUTPUT_VARIABLE COMMIT
                     OUTPUT_STRIP_TRAILING_WHITESPACE)
@@ -47,7 +48,7 @@ function (get_version_tag_from_git GIT)
         message(STATUS "You are currently on commit ${COMMIT}")
 
         # Get all the tags
-        execute_process(COMMAND "${GIT}" rev-list --tags --max-count=1 --abbrev-commit RESULT_VARIABLE RET OUTPUT_VARIABLE TAGGEDCOMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)
+        execute_process(COMMAND "${GIT}" -C ${CMAKE_SOURCE_DIR} rev-list --tags --max-count=1 --abbrev-commit RESULT_VARIABLE RET OUTPUT_VARIABLE TAGGEDCOMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)
 
         if(NOT TAGGEDCOMMIT)
             message(WARNING "Cannot determine most recent tag. Make sure that you are building either from a Git working tree or from a source archive.")
```

**Comment by trasherdk** [comment]
This one seems to do the trick.
```
$ git diff
diff --git a/cmake/GitVersion.cmake b/cmake/GitVersion.cmake
index a367787f..13ab938a 100644
--- a/cmake/GitVersion.cmake
+++ b/cmake/GitVersion.cmake
@@ -31,7 +31,8 @@
 # Check what commit we're on
 
 function (get_version_tag_from_git GIT)
-    execute_process(COMMAND "${GIT}" rev-parse --short=9 HEAD
+    execute_process(COMMAND "${GIT}" -C ${CMAKE_SOURCE_DIR} rev-parse --short=9 HEAD
+                    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                     RESULT_VARIABLE RET
                     OUTPUT_VARIABLE COMMIT
                     OUTPUT_STRIP_TRAILING_WHITESPACE)
@@ -47,7 +48,7 @@ function (get_version_tag_from_git GIT)
         message(STATUS "You are currently on commit ${COMMIT}")
 
         # Get all the tags
-        execute_process(COMMAND "${GIT}" rev-list --tags --max-count=1 --abbrev-commit RESULT_VARIABLE RET OUTPUT_VARIABLE TAGGEDCOMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)
+        execute_process(COMMAND "${GIT}" -C ${CMAKE_SOURCE_DIR} rev-list --tags --max-count=1 --abbrev-commit RESULT_VARIABLE RET OUTPUT_VARIABLE TAGGEDCOMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)
 
         if(NOT TAGGEDCOMMIT)
             message(WARNING "Cannot determine most recent tag. Make sure that you are building either from a Git working tree or from a source archive.")
```

**Comment by ndorf** [comment]
Thanks for the fix @trasherdk , sorry I didn't think to test that case.

**Comment by trasherdk** [comment]
Well, @hyc supplied the nail and hammer, I just did the banging.

**Pull request merged**
