### PR TITLE
wallet: add sweep_single command

### PR DESCRIPTION
**Pull request by stoffu**
This patch adds a new command `sweep_single <key_image> <address>` which sweeps exactly one output specified by the given key image to the destination address with no change. This may be useful for a few purposes:

- Cold signing: After exporting the set of correct key images from the offline full wallet to the online watch-only wallet, this command can be used to spend each one of output in the cold wallet without generating a new change output, which simplifies the process of moving funds from a cold wallet to a hot wallet by making it unnecessary to export/import outputs/key-images every time moving funds.

- Manual churning

- Defense against potential privacy leak when spending many outputs from the same entity (e.g. an exchange)

```
[wallet A1PbM6]: incoming_transfers available verbose
               amount   spent    unlocked  ringct    global index                                                               tx id                                                              pubkey                                                           key image
       1.750732960000       F    unlocked  RingCT          289557  <1a49403c7c718d517edd7856060fce96d01d602242f67bb3081e9ed73ad20243>  <0ff2f2309ff0bd58150ded6b844edb195efe5a9ebbb1701ec6df4433b958efc3>    f2e713dc54a9b1ec9c4925793ee1f35636234c8b99b7dd168791677e51e704df
[wallet A1PbM6]: sweep_single unimportant 5 f2e713dc54a9b1ec9c4925793ee1f35636234c8b99b7dd168791677e51e704df 9vfmz4q7LGQYMisHnLZzUCW1kjG35394sK14D3EfRK9xabR2VouaNSDYdTE5EeSvTe5WV2e6tFUFrEbC8gaHk85oCM4uz8g

Transaction 1/1: txid=<bf29fb9516072b8674f6edf83ea29346248ac8959bf08a1104c809b95731b304>
Input 1/1: amount=1.750732960000
Originating block heights:  965548 *1012065 1014813 1015188 1015378
|___________________________________________________________________________o__*|

Sweeping 1.750732960000 for a total fee of 0.004783740000.  Is this okay?  (Y/Yes/N/No)
```

### CODE REVIEW

**Comment by iamsmooth** [comment]
This will create transactions with one output. Does the issue raised in #1375 apply?

https://github.com/monero-project/monero/issues/1375#issuecomment-264968191

**Comment by stoffu** [comment]
No, this command is identical to `sweep_all` except that there's always only one input. The tx will always have two outputs, one to the destination and the other to a random address (with zero amount).

**Comment by iamsmooth** [comment]
@stoffu Thanks for the explanation. 

Is it better to send to a random address rather than send it back to the same wallet as change (change of zero)? In the latter case we could choose to spend them at some point. That would incur some tx fee, but would avoid the (perhaps insignificant, I'm not sure) reduction of privacy from the fact that these outputs will statistically have one less spend on average than others. (Same applies to sweep_all)

**Comment by fluffypony** [comment]
@stoffu plz see feedback from smooth

**Comment by stoffu** [comment]
@iamsmooth @fluffypony 
Sorry, I forgot to reply.

> That would incur some tx fee, but would avoid the (perhaps insignificant, I'm not sure) reduction of privacy from the fact that these outputs will statistically have one less spend on average than others. (Same applies to sweep_all)

I don't know for sure, but I intuitively feel that the statistical difference is too small to be detected by blockchain analysis. Also, as stated, this point applies to the current `sweep_all` command, so I think it should be discussed separately from this PR (maybe open a new issue)?

CC: @moneromooo-monero @luigi1111

**Comment by moneromooo-monero** [comment]
I agree that discussion needs not delay that PR since it's already the case elsewhere.

**Comment by iamsmooth** [comment]
I agree it isn't specific to this feature (in particular, sweep_all is similar, though in that case the intent may often be to retire the wallet, so slightly different), so I agree it should not delay this PR at all. I was mostly raising the issue for awareness.

**Comment by stoffu** [comment]
@iamsmooth I appreciate if you could open an issue on this for later discussion.

**Pull request merged**
