### PR TITLE
libwallet_merged compilation on android armv7-eabi

### PR DESCRIPTION
**Pull request by naughtyfox**
Wallet client libs and dependencies made to compile on android.

Since mobile wallet libs don't need `readline`, `boost::locale` (it's used only on windows) and `zmq` libraries new build option `EMBEDDED_WALLET` was introduced (supposed to be used to compile static libs for mobile gui wallets) which excludes these libraries from client library building process. 

Example:
```
$ mkdir armv7-eabi && cd armv7-eabi
$ PATH=/opt/android/tool32/arm-linux-androideabi/bin:/opt/android/tool32/bin:$PATH CC=clang CXX=clang++ cmake -D BUILD_TESTS=OFF -D ARCH="armv7-a" -D STATIC=ON -D BUILD_64=OFF -D CMAKE_BUILD_TYPE=release -D ANDROID=true -D BUILD_TAG="android" -D BOOST_ROOT=/opt/android/boost_1_63_0 -D BOOST_LIBRARYDIR=/opt/android/boost_1_63_0/android32/lib -D OPENSSL_ROOT_DIR=/opt/android/openssl-1.0.2n -D OPENSSL_CRYPTO_LIBRARY=/opt/android/lib/armeabi-v7a/libcrypto.a -D OPENSSL_SSL_LIBRARY=/opt/android/lib/armeabi-v7a/libssl.a -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=true -D EMBEDDED_WALLET=ON ..
```

Tested on `armv7-eabi` arch

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
The boost thing seems useful. The embedded wallet not using zmq seems totally arbitrary. I'd rather you add an option to enable 0mq or not if there is none at the moment. The warning thing seems unrelated.

**Comment by naughtyfox** [comment]
> The warning thing seems unrelated
Actually it's necessary. Otherwise you can't compile monero with ndk (currently i'm using ndk 16b). This is the error:
```[ 61%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/tx_pool.cpp.o
In file included from /home/sergey/src/monero/src/cryptonote_core/cryptonote_core.cpp:33:
In file included from /home/sergey/src/monero/contrib/epee/include/include_base_utils.h:32:
In file included from /home/sergey/src/monero/contrib/epee/include/misc_log_ex.h:33:
In file included from /home/sergey/src/monero/external/easylogging++/easylogging++.h:383:
In file included from /opt/android/tool32/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/map:442:
/opt/android/tool32/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/__tree:1819:22: error: the specified comparator type does not provide a const call operator [-Werror,-Wuser-defined-warnings]
                     __trigger_diagnostics()), "");
                     ^
/opt/android/tool32/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/__tree:960:70: note: in instantiation of member function 'std::__ndk1::__tree<std::__ndk1::pair<std::__ndk1::pair<double, long>, crypto::hash>, cryptonote::txCompare,
      std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::pair<double, long>, crypto::hash> > >::~__tree' requested here
    template <class, class, class> friend class _LIBCPP_TEMPLATE_VIS set;
                                                                     ^
/opt/android/tool32/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/__tree:970:7: note: from 'diagnose_if' attribute on '__trigger_diagnostics':
      _LIBCPP_DIAGNOSE_WARNING(!__invokable<_Compare const&, _Tp const&, _Tp const&>::value,
      ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/android/tool32/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/__config:1095:20: note: expanded from macro '_LIBCPP_DIAGNOSE_WARNING'
    __attribute__((diagnose_if(__VA_ARGS__, "warning")))
                   ^           ~~~~~~~~~~~
1 error generated.
src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/build.make:86: recipe for target 'src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o' failed
make[3]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```
i can't hack android ndk and fix it so the only way i see is to suppress this warning.

> The embedded wallet not using zmq seems totally arbitrary. I'd rather you add an option to enable 0mq or not if there is none at the moment
What use cases for `zmq` do you see in mobile wallets' gui libs? I bet it's a big headache to build it manually for android. But if it's necessary i can add an option for it, no problem.

**Comment by moneromooo-monero** [comment]
About 0mq, the use of it is RPC to the daemon. The current JSON RPC is still around, but the idea is to migrate at some point.
I'll let other give their opinions.

**Comment by naughtyfox** [comment]
probably it worths do it when zmq interface for client wallets is ready?

**Comment by naughtyfox** [comment]
@moneromooo-monero check this out please. i added possibility to optionally build zmq for embedded devices

**Comment by stoffu** [comment]
I agree with @moneromooo-monero. Such a predefined set of flags seems to belong to the top level Makefile (or get_libwallet_api.sh for the GUI).

**Comment by jonathancross** [comment]
@naughtyfox This needs to be rebased.  Are you still working on it?

**Comment by naughtyfox** [comment]
I can rebase it if you plan to merge it

**Comment by jonathancross** [comment]
@naughtyfox : it seems @moneromooo-monero and @stoffu still have some unaddressed concerns.
PS: I don't have permission to merge anyways.  Was just trying to gauge if this was being worked on or not.

**Comment by moneromooo-monero** [comment]
Do you still want some version of this with better names or should this be closed ?

**Comment by naughtyfox** [comment]
I think you may close it

**Comment by moneromooo-monero** [comment]
+invalid

**Pull request closed without merging**
