### PR TITLE
command_parser_executor: limit miner threads based on max threads

### PR DESCRIPTION
**Pull request by cryptochangements34**
I shouldn't be able to start 10 miner threads when my cpu can only handle 4

### CODE REVIEW

**Comment by cryptochangements34** [comment]
@moneromooo-monero simlewallet already does this. Should the wallet have this functionality but not the daemon command line?

**Comment by moneromooo-monero** [comment]
Probably not. That seems to date back to the original CN code. Maybe we should remove that (or at least bump the limit a lot, rather than assume hardware concurrency is a hard limit). I'll wait for other opinions.

**Comment by cryptochangements34** [comment]
Ok

**Comment by jtgrassie** [comment]
A warning may be better IMHO.

TBH, even a warning can be deemed too much. Lot's of assumptions based on hardware checks, which won't always detect accurately. The docs are pretty clear so why not just leave to the user to set correctly based on what they know about their hardware?

**Pull request closed without merging**
