### PR TITLE
Keep readline optional

### PR DESCRIPTION
**Pull request by jtgrassie**
Reported by @xmr-eric on IRC. This PR allows build without a readline dependancy.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
How about this instead:

diff --git a/cmake/FindReadline.cmake b/cmake/FindReadline.cmake
index 7a11a27..9dd93d7 100644
--- a/cmake/FindReadline.cmake
+++ b/cmake/FindReadline.cmake
@@ -79,3 +79,6 @@ if(HAVE_COMPLETION_FUNCTION AND HAVE_COPY_TEXT)
   set(READLINE_FOUND TRUE)
 endif(HAVE_COMPLETION_FUNCTION AND HAVE_COPY_TEXT)
 
+if(Readline_LIBRARY STREQUAL "NOTFOUND")
+  set(Readline_LIBRARY "")
+endif()

**Comment by jtgrassie** [comment]
@moneromooo-monero yes I thought about that way too but wasn't sure if that's the most suitable way. Reason being, could there in the future be a case of some new code relying on any readline library, not specifically the GNU version. NOTFOUND is thus valid it that case, whereas in our current code, the explicit checks are there to ensure readline is GNU, as that's required by this current code. All that said, I like the set (to 
"") and forget simplicity of the other approach. Happy to change if you prefer.

**Comment by moneromooo-monero** [comment]
I just don't like having to add the tests in every makefile, where the variable could be set right in the first place. If this variable is not the right one, then it can be changed to the right one (I'm not familiar with how the distinction between GNU and non GNU readline is done in this detection).

**Comment by jtgrassie** [comment]
I understand that want to not have to perform the check in each cmake file, but the current ones actually depend on GNU readline. If we want to keep the FindReadline.cmake module portable to future code that may not require the GNU variant, the way it currently works, it is. That's because Readline_LIBRARY will be set to whatever variant of readline is detected but only GNU_READLINE_FOUND is set when the found readline is GNU. It's also only 4 files that have the test presently.

Hence:

> ...where the variable could be set right in the first place

I believe it is set right. Readline_LIBRARY is set to either not found, libedit or GNU readline. It's up to individual makefiles to decide if they depend on any found variant or the GNU variant.

If we don't care about future possible code that may not be dependent about which variant of readline, then we can indeed edit the FindReadline.cmake to only set Readline_LIBRARY to "" or a found GNU version. Personally I prefer stating explicitly what's required in the 4 makefiles.

**Comment by hyc** [comment]
At this point our usage of readline API is pretty basic - do we actually need GNU readline specifically? Does libedit's emulation actually work?

**Comment by jtgrassie** [comment]
@hyc yes GNU readline still required. Casual check shows at least functions rl_save_prompt and rl_restore_prompt not in libedit (at least on Mac). Also the variables such as rl_end, rl_done etc. So yes, definitely still requires GNU readline.

**Comment by moneromooo-monero** [comment]
Then why can it be set to "libedit" if it's pointless ? Either to something usable, or nothing. Done.

**Comment by jtgrassie** [comment]
> Then why can it be set to "libedit" if it's pointless ? Either to something usable, or nothing. Done.

Because we cannot anticipate that some some other future feature may support libedit. Or the current readline code may get refactored to support libedit. The FindReadline.cmake module is best kept flexible surely?

**Comment by moneromooo-monero** [comment]
Ceteris paribus, surely.

**Comment by xmr-eric** [comment]
Build still fails

**Comment by jtgrassie** [comment]
@xmr-eric current failing builds are unrelated to this PR

**Comment by jtgrassie** [comment]
Updated as-per conversation with @moneromooo-monero on IRC:

< moneromooo> - detect libreadline: if found, set GNU_READLINE_LIBRARY to it, and READLINE_LIBRARY to it.
< moneromooo> - detect libedit: if found, set LIBEDIT_LIBRARY to it, and READLINE_LIBRARY to it.
< moneromooo> Monero makefiles use GNU_READLINE_LIBRARY.

**Comment by laugh26** [comment]
where do i put that
 diff --git a/cmake/FindReadline.cmake b/cmake/FindReadline.cmake
index 7a11a27..9dd93d7 100644
--- a/cmake/FindReadline.cmake
+++ b/cmake/FindReadline.cmake
@@ -79,3 +79,6 @@ if(HAVE_COMPLETION_FUNCTION AND HAVE_COPY_TEXT)
   set(READLINE_FOUND TRUE)
 endif(HAVE_COMPLETION_FUNCTION AND HAVE_COPY_TEXT)
 
+if(Readline_LIBRARY STREQUAL "NOTFOUND")
+  set(Readline_LIBRARY "")
+endif()

**Pull request merged**
