### PR TITLE
Adding HTTP Digest Auth (but not yet enabled)

### PR DESCRIPTION
**Pull request by vtnerd**
@hyc has been against adding HTTP auth and instead suggests adding TLS two-certificate checking (making it identical to SSH except with the complication of a CA root for server). My argument is simply that it is better to strongly nudge people to only accept local connections for HTTP, and use stunnel or SSH if someone really needs to use a remote connection. And if ZeroMQ-JSON-RPC is _eventually_ going to be preferred option over HTTP-JSON-RPC, it already has a built-in encryption / authentication based on CurveCP. So then the recommendation would be to always use ZeroMQ-JSON-RPC for remote connections. This prevents a hard-dependency on a SSL library, and the ZeroMQ security would require a libsodium dependency.

Also:
- Note the addition of a epee static library. Thoughts?
- This does **not** contain code to enable HTTP auth for either RPC server. It adds the functionality and tests, but the default argument is not used yet. I would like to do that in a separate patch - the default behavior will be to randomly generate a password and store in a file only readable by the user that started the process. Two hidden options will also be added - one for selecting username/password, and another for completely disabling HTTP auth.

### CODE REVIEW

**Comment by anonimal** [comment]
@vtnerd I would strongly recommend you become more familiar/involved with kovri since monero's dependencies will eventually be the same (this includes openssl and cpp-netlib).  I think fighting the TLS option will also be more trouble than it's worth. See also https://github.com/monero-project/kovri/issues/54.

**Comment by vtnerd** [comment]
I think the builtin TLS support _might_ be useful for kovri's tunnel and proxy modes due to the likely frequency of their use by remote machines. I'm still not certain whether that means monero should implement TLS directly for HTTP-RPC. I was persuaded long ago (before Heartbleed) by a [Colin Perceival blog post](http://www.daemonology.net/blog/2009-09-28-securing-https.html) that using OpenSSL in a separate virtual memory space was preferable. Is it possible to move toward a shared TLS wrapper? The wrapper would perform the authentication and decryption and forward the data via pipe or domain socket to a parent process (`monero-wallet-rpc`, etc). Further directory reading, etc. (or [OpenBSD pledge](http://man.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/pledge.2)), can be used to restrict permissions on the TLS process too.

With TLS client-cerificates, HTTP auth support becomes murky. TLS supports a null cipher mode, so local only connections can perform authentication and skip encryption. Not sure how many people clients support that mode though. In some cases HTTP auth might still be useful because if someone tries to re-use a client certificate in firefox for kovri, the [CSRF issue to `monero-wallet-rpc`](https://labs.mwrinfosecurity.com/advisories/csrf-vulnerability-allows-for-remote-compromise-of-monero-wallets/) would still be left open. Not an easy case to "auto-detect".

Also, this is the first mention of cpp-netlib that I can recall. That library does not support HTTP auth directly. The amount of work needed to make this patch work with cpp-netlib should be low since it was implemented as a separate component. Only the code referencing the `request` / `response` representations should need updating.

**Comment by hyc** [comment]
Back up a step. What exactly is the motivation for this patch?

Are you planning to use the Digest authentication to also set up an encryption layer? Or only for authentication?

Is this a use case that could be easily satisfied by just using a unix domain socket for local RPC?

**Comment by vtnerd** [comment]
The primary motivation is the CSRF issue mentioned previously. An attacker can remotely ask a web-browser to make connections to local only TCP listeners, so even local-only HTTP servers have to be careful about the source of their connections. HTTP digest authentication is not intended to ever setup encryption. Its only intent is to make sure the process generating HTTP requests is the desired one.

I thought about unix domain sockets because the builtin process identification is desirable. The obvious negatives are cross platform issues, and potential integration problems (HTTP over domain socket is not a common use case for many libraries). A non-obvious negative is that it authenticates at a "lower-level" than the application layer, so if a user setup a SSH or SSL-stunnel - both of which can forward TCP to domain socket - there's still potentially an unauthenticated TCP server on the remote machine. In other words, `browser->local_tcp->remote_(ssl|ssh)_tunnel->unix_socket`. Admittedly this case is likely to be rare.

The HTTP authentication that I am proposing (this patch plus one more) randomly generates a 128-bit password at each process start. User selected passwords or auth disabling will be hidden options. In this setup, the user has to manually lookup and use a hidden option for the `monero-wallet-rpc` process OR copy the password from file each time the process starts OR use a process that can read the file on the local filesystem. Any TLS, SSH, CurveCP, whatever, TCP->socket tunnel the user creates will also be protected until the user explicitly signals their intent to the `monero-wallet-rpc` process. But honestly, people are still likely to trigger the `--disable-rpc-auth` option without reading any of the related source material. I give up at that point.

Am I being too pessimistic? This parses remote input which has risks and has to be taken into consideration. I used boost::spirit to do all parsing, which is the same library that the cpp-netlib backend uses.

**Comment by vtnerd** [comment]
Also, in case it wasn't clear above, this could be used in conjunction with TLS. TLS certs do the two-way remote authentication, and HTTP auth ensures it is not coming from the users web browser unintentionally.

**Comment by anonimal** [comment]
@vtnerd 

>So then the recommendation would be to always use ZeroMQ-JSON-RPC for remote connections. This prevents a hard-dependency on a SSL library, and the ZeroMQ security would require a libsodium dependency.

This was all I was arguing against while suggesting openssl or cpp-netlib as a potential SSL handler.

At the patch level (or even an extra feature), I don't see anything wrong with HTTP auth in and of itself.

**Comment by vtnerd** [comment]
I tracked down the source of the [windows build failure](https://build.getmonero.org/builders/monero-static-win32/builds/383/steps/test/logs/stdio). The build bots are using an older GTest header than the one included with the project.

Should I work around? Nudge the build-bot maintainer to update?

**Comment by danrmiller** [comment]
@vtnerd Let me know the details and I will update the buildbot system.

**Comment by danrmiller** [comment]
@vtnerd The included vendored gtest lib isn't working for 64-bit windows: https://github.com/monero-project/monero/issues/1087

**Pull request merged**
