### PR TITLE
REF: copyright years changed to 2021.

### PR DESCRIPTION
**Pull request by JaydenElliott**
Copyright years changed to 2021. This includes copyright text of the following format:
- Copyright (c) 2018-2020 
- Copyright (c) 2018

Process: Scanned through all file types searching for this pattern and replaced with appropriate year.

### CODE REVIEW

**Review by xmrnightknight — APPROVED** [review]

**Comment by JaydenElliott** [comment]
Not sure why that last test failed... I painstakingly skimmed through all 669 file changes twice on the Github Desktop to check all the changes were correct.

**Review by xmrnightknight — APPROVED** [review]

**Comment by xmrnightknight** [comment]
I went through all changes. Indeed there are only changes in comments with years, so failing test is broken...

**Comment by selsta** [comment]
Thanks for the PR. Problem is we have now 3 open PRs with copyright changes, not sure which one to merge.

**Comment by JaydenElliott** [comment]
> Thanks for the PR. Problem is we have now 3 open PRs with copyright changes, not sure which one to merge.

@selsta the two last PR's had 603 and 494 file changes. Mine has 669, so it looks like they missed quite a few files.

**Comment by xmrnightknight** [comment]
@JaydenElliott Right. I was that they skipped files with following copyright format:
`// Copyright (c) 2021, The Monero Project`

**Comment by xmrnightknight** [comment]
@JaydenElliott btw here is recipe to retrigger checks: 
`https://github.com/monero-project/monero/pull/7334#discussion_r581050088`

**Comment by selsta** [comment]
You can ignore CI in this case.

**Comment by JaydenElliott** [comment]
@selsta anything else needed before merge then?

**Comment by mj-xmr** [comment]
That test is known to break at that moment.

> @selsta anything else needed before merge then?

I guess only time time.

**Comment by selsta** [comment]
Seems like `Copyright (c) 2018` got changed to `Copyright (c) 2021`. Ideally we would do `Copyright (c) 2018-2021` to preserve the creation date.

**Comment by selsta** [comment]
2022

**Comment by mj-xmr** [comment]
I think I'll just write a script to handle it.

**Pull request closed without merging**
