### PR TITLE
Created monero-wallet-rpc, moving functionality from monero-wallet-cli

### PR DESCRIPTION
**Pull request by vtnerd**
I was asked to move the wallet rpc functionality into a new process, and  this is the result. Very little new code was added, most of it is moved around. I hope this isn't too aggressive, but I know the code well enough to move it around based on requests/suggestions.

- `wallet_args.h/cpp` now handles the log file and concurrency command line arguments + the various global initializations for the two wallet processes.
- Command line argument handling for p2p-daemon and passwords have been moved to `wallet2` so that both processes can use the same code.
- `password_container` was moved to `src/wallet`
- Various fixes for translations
- `monero-wallet-rpc` now asks for wallet password if its not provided, so it does _not_ have to read it from a file or from a command line argument.

Questions:
- Are there any translations to test with?
- Is the `translations/monero.ts` file maintained? Should I revert changes to that file?

### CODE REVIEW

**Comment by NanoAkron** [comment]
@vtnerd, How well does this play with @tewinget's work on 0MQ?

**Comment by vtnerd** [comment]
Forced pushed updates which I think _finally_ got all the versions to be green. Does anybody have a file for `--generate-from-json` testing? I verified that it loads and rejects non json files, but nothing else. Probably should @fluffypony too.

@NanoAkron I just looked at the pull request related to 0MQ. I scanned through the relevant files, and I do not anticipate there being any major problems. It might require some human merging, but hopefully not much more.

**Comment by moneromooo-monero** [comment]
{
  "version": 1,
  "filename": "exampleseed.bin",
  "scan_from_height": 70000,
  "password": "42",
  "viewkey": "view key here as hex",
  "spendkey": "spend key here as hex",
  "seed": "seed words here",
  "address": "standard address here"
}

The keys/seed/address are optional, you just need enough to be sure.

**Comment by fluffypony** [comment]
I'm happy with maintaining the translations for now, at some point someone will care about CLI translations:)

**Pull request merged**
