### PR TITLE
Improving daemon startup log message

### PR DESCRIPTION
**Pull request by NanoAkron**
Just making things a bit clearer for people reviewing the logs

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok, though it's not super obvious this function just happens to be called for the daemon case and not the general case, so ideally the "daemonized" message would be placed somewhere else.

**Comment by NanoAkron** [comment]
Why does the system write this to the logs from both main.cpp and executor.cpp?

Is there a resource that gives an outline sketch of what different parts of code does so that newcomers can get up to speed?

**Comment by moneromooo-monero** [comment]
I added the one in main to ensure the logs get the version number, as a help for debug. I'm not sure why the other is here, maybe it used to be printed always before the daemon code ? You'd have to check git logs to be sure. I don't know of such an outline sketch.

**Comment by NanoAkron** [comment]
Do you know the sequence of calls/functions from first running monerod to when it determines it can be forked into the background and started as a daemon? I could add the entry there instead.

**Comment by moneromooo-monero** [comment]
I do not know. I just read the code, or crash in the function I'm interested and use gdb on the core (or use gdb and use "break functionname" if you have all debug info).

**Comment by NanoAkron** [comment]
OK, well let me resubmit this as a minor cleanup instead until it becomes clearer where this should/could go in the code.

**Comment by moneromooo-monero** [comment]
I've not rejected it. When I start with ok, it means I agree to it being merged. Sometimes, there are comments, which the author may want to do something about, but that's optional. If there's an ok first, you're good :)
Besides, I did not say this is the wrong place to put it, just that it wasn't obvious until I chcked the code.

**Comment by NanoAkron** [comment]
Makes sense - thanks :)

**Pull request merged**
