### PR TITLE
Better log message for unusable anon networks

### PR DESCRIPTION
**Pull request by hyc**

### CODE REVIEW

**Review by vtnerd — APPROVED** [review]
It should be possible to cherry pick this onto the 0.17 branch too.

**Comment by hyc** [comment]
PR'd against release in #7011

**Comment by hyc** [comment]
There's something flaky going on here, the height is always logged as zero. How can that be?

**Comment by selsta** [comment]
Tests fails to compile

**Comment by hyc** [comment]
unit_tests fixed

**Review by selsta — APPROVED** [review]

**Pull request merged**
