### PR TITLE
switch to boost::thread for mingw build

### PR DESCRIPTION
**Pull request by vtnerd**
@danrmiller lets watch the win32 build.

### CODE REVIEW

**Comment by vtnerd** [comment]
Ok, so just realized the build-bot is not fetching `monero/master` then merging my branch against, its actually checking out my branch directly. So let me rebase this try the build bots again ...

**Comment by danrmiller** [comment]
> Ok, so just realized the build-bot is not fetching monero/master then merging my branch against, its actually checking out my branch directly.

I've noticed this behavior too recently, and in the next few days I'm going to look into changing it to the expected behavior of merging just the changes from the pull request.

**Comment by vtnerd** [comment]
Finally force pushed an update. @danrmiller be aware of https://github.com/monero-project/monero/issues/1739 , cross-compiling some of the tests is tricky. @moneromooo-monero I updated more files than you saw last time, previously I only did a `make unit_tests`.

**Comment by danrmiller** [comment]
Great, this works.

**Pull request merged**
