### PR TITLE
Removed fnv1a usage from ipv4_network_address + fixed serialization bug

### PR DESCRIPTION
**Pull request by vtnerd**
Need feedback from @moneromooo-monero before any merge.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
The padding needs initializing for the full check to work, and I don't really like having host/port in the base class, since it kinda defeats the point of having the "agnostic" base class, but the rest seems fine.

**Comment by vtnerd** [comment]
The padding is initialized via the default constructor in `network_address_base` which is called by the derived class constructor (the entire 64-bits are initialized to 0 in one shot).

And having ip/port in the base class is gross, but just a temporary solution. My full recommendation would look something like:

```c++
class ipv4_network_address {
public:
  ...
private:
  union {
    uint64_t full;
    struct {
      uint32_t ip;
      uint16_t port;
    } split;
  } m_data;
};

class ipv6_network_address {
public
  ...
private:
  uint64_t big_ip;
  uint64_t little_ip;
  uint16_t port;
}:

class i2p_network_address {
 ...
};

class network_address {
  struct internal; // defined in CPP file

  public:
  enum class type : std::uint8_t {
    kIPv4 = 0,
    kIPv6,
    kI2P
  };

  constexpr network_address() noexcept : m_data{}, m_type(type::kIPv4) {}

  // automagically ref-counted via "internal" struct

  bool equal(const network_address& rhs) const noexcept {
    if (m_type != rhs.m_type) return false;
    if (m_type == type::kIPv4) m_data.ipv4 == rhs.m_data.ipv4;
    return internal_equal(rhs);
  }
  ....

private:
  union {
    ipv4_network_address ipv4;
    internal* heap;
  } m_data;
  type m_type;
};
static_assert(16 == sizeof(network_address), "bad size");
```

The `sizeof(boost::shared_ptr<...>)` is `sizeof(void*) * 2` so the polymorphic type uses no additional space with 64-bit pointer systems. This does double the space for 32-bit pointer systems - packing everything further is possible but a less flexible design. The big advantage is that IPv4 requires no heap memory - two branches are now introduced for comparison functions but two pointer dereferences are removed. Also, the implicit vtable pointer is removed since all functions from the polymorphic class will do a cast instead of a virtual method call (runtime performance will be very similar in that case).

**Comment by moneromooo-monero** [comment]
I acknowledge you're a lot more fluent in C++ than I am, but this feels like more complexity and dodginess just for the sake of not having a hash function and gain a very small amount of space, no ?

**Comment by vtnerd** [comment]
64-bits is a small range for a unique fingerprint function (md5 is 128 bits!), and the fnv1a is not designed to have the properties desirable for this task. It _might_ be possible to prove that no collision occurs over the range of ipv4/port inputs but if the plan is to mix I2P addresses into the same 64-bit space why take the risk of a collision? It could alter the behavior of the program in unexpected ways, since no one expects `operator==` to occasionally return true on something that is not equivalent.

The techniques I am proposing are very C-like too. The proposed implementation could make everything a pointer, which would remove some of the "dodginess" while still requiring some additional branches.

**Comment by vtnerd** [comment]
I should note that if you prefer the hash implementation, some modern cryptographic hash seems desireable IMO ...

**Comment by moneromooo-monero** [comment]
Well, FNV is just a particular hash function. It could be, say, Keccak. Using Keccak would in no way require any of the changes you've made to move derived stuff into the base class though, so that can't be the reason for the patches.

**Comment by vtnerd** [comment]
I am proposing this PR right now (as opposed the above code snippet) because these changes are not as aggressive. The goal is simply to remove any surprises in the next release, while still allowing the base-hash implementation to be easily re-introduced with I2P addresses. I still hope my techniques above are considered - the resulting code will not be any more difficult than much of the code being maintained already.

I also have another PR after this one to smooth the edges of `network_address` that I hope can be merged into the next release branch. Its primarily adding `nullptr` checks and ensuring that modifications cannot be done to a shallow-copied base class.

**Pull request closed without merging**
