### PR TITLE
Valgrind

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I've no idea to be honest. I didn't find boost documentation that made me clearly know what this bit of code is doing. It may also be wrong, since it breaks on Mac in the wallet (similar code steps). If the semantics of joining twice are the same as just one, then it could be made unconditionally. The other APIs would need checking to see if they can be called multiple times though.

**Comment by vtnerd** [comment]
See my edit above - probably should have made that a new post. The relevant code is [here](https://github.com/boostorg/thread/blob/develop/include/boost/thread/detail/thread_group.hpp#L118) - which checks the `joinable()` flag before joining. Unfortunately the behavior is not listed in the documentation, so it could technically change. I wish some throw semantics were listed in the `thread_group` docs too.

**Comment by moneromooo-monero** [comment]
That looks like a good refactoring of the stuff in rctSigs, Blockchain, and Wallet, yes. Even better if you could also add the work object and use that in those three places.

**Comment by vtnerd** [comment]
Sounds like something best done in a separate pull request then.

**Comment by fluffypony** [comment]
@vtnerd @moneromooo-monero so should I merge this PR, and then @vtnerd could you make that change in a subsequent PR?

**Comment by vtnerd** [comment]
@fluffypony Yes.

**Pull request merged**
