### PR TITLE
epee: fix include for ofstream

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by vtnerd** [comment]
This might be a good time to move these functions to a cpp - only `#include <string>` and #include <ctime>` appear to be needed in that situation.

**Comment by moneromooo-monero** [comment]
Looks like moving the file to contrib/epee/src causes massive diffs, even with git mv :/

**Comment by vtnerd** [comment]
Its not that much code to verify if it were moved. Additional, `get_file_time`, `set_file_time`, and `append_string_to_file` are all unused and can be dropped in the move (making the code inspection even easier). Something to mark for changing in the near future if this particular patch is fixing a build and is of higher priority.

**Comment by luigi1111** [comment]
@vtnerd wanna make an issue for that?

**Pull request merged**
