### PR TITLE
Add my node to list of seed nodes.

### PR DESCRIPTION
**Pull request by guywillett**
I am running a mainnet node in the cloud and I would like to volunteer it as a seed node.

Of note:

1. It has a fixed IP address
2. I will be promptly updating it as required (currently running` v0.15.0.5`)
3. I intend to keep running it for the long term

Having followed the discussion at the last `monero-dev` meeting (29/03/20), I have added my node's IP address to the list in this PR.

I think that @binaryFate will be able to vouch for me in terms of trust.

If you need further details, let me know.

### CODE REVIEW

**Comment by binaryFate** [comment]
I can totally vouch for @guywillett indeed, I know him IRL.

What cloud provider would that node be, in case we need to spread around?

**Comment by guywillett** [comment]
The provider is `Hetzner` and the node is located in Helsinki, Finland.

**Comment by guywillett** [comment]
Apologies - the commit message was github generated and I did not check it ;-)

**Comment by selsta** [comment]
Please rebase.

**Comment by selsta** [comment]
I think a proper rebase is only possible with git client :/ Can you squash your commits?

**Comment by guywillett** [comment]
Rebasing and squashing commits keeps failing. I am going to close this PR and open another one.

**Pull request closed without merging**
