### PR TITLE
support freeze, thaw, and frozen in wallet rpc

### PR DESCRIPTION
**Pull request by woodser**

### CODE REVIEW

**Comment by woodser** [comment]
Fixes issue #7720

**Review by selsta — CHANGES_REQUESTED** [review]
bump WALLET_RPC_VERSION_MINOR

**Comment by woodser** [comment]
Done.

**Review by moneromooo-monero — APPROVED** [review]

**Review by vtnerd — COMMENTED** [review]
I missed this unfortunately - @woodser next time use `crypto::key_image` directly in the request object. The `struct_init` pattern ensures the object is always zero initialized, and unpacking into the struct is automatically done by `epee`. Hopefully in the near future will be more efficient too - I hope to change the epee DOM to use slices internally such that there is exactly two copies from kernel to C struct.

**Pull request merged**
