### PR TITLE
Removing some unused files.

### PR DESCRIPTION
**Pull request by moneroexamples**
https://github.com/monero-project/monero/issues/1588

The files removed seem to be totally unused. Probably their functionality was replaced with some other files, but they still remain in the source code.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
They were just never used in the first place, mostly. That's how libs are used. I guess I'm OK with this patch since we won't ever update epee, but please don't do that for other libs like unbound or lmdb, even if nothing is used from some files. It only makes updates more of a pain for no reason.

**Comment by moneroexamples** [comment]
Yes, no problem. I have no intention to keep removing files from monero. I only found them because in my projects I was using `get_set_log_detalisation_level`, but recently it was removed from monero, but not completely and still appeared to be used in monero codebase. This resulted in confusion leading to issue: https://github.com/monero-project/monero/issues/1588

**Comment by moneromooo-monero** [comment]
WTF, I didn't realize the patch was removing daemon tests too, leave those in. You can just remove the unused (and obviously won't-be-used) stuff in epee.

**Comment by moneroexamples** [comment]
OK. Thanks. So I will close this one, and later prepare new PR.

**Comment by NanoAkron** [comment]
In future just git push --force to update your branch after changes, no need to close a PR

**Comment by moneroexamples** [comment]
Thanks for info. Will remember that for next time.

**Pull request closed without merging**
