### PR TITLE
epee: fix ssl autodetect on reconnection

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by xiphon** [comment]
**Issue**

Given the same `blocked_mode_client` instance with `m_ssl_options.support` initially set to `e_ssl_support_autodetect`.

On first successful SSL connection attempt it will skip certificate check (due to `e_ssl_support_autodetect`) and change `m_ssl_options.support` to `e_ssl_support_enabled`.

Any following `connect` invocation will fail due to enforced certificate check by `e_ssl_support_enabled`.

**Comment by vtnerd** [comment]
The fix I was going to recommend was returning an `enum` from the `handshake` function that indicated whether SSL failed entirely, verification occurred or whether verification was skipped. The HTTP client could use that information to set SSL to disabled, enabled + verified or enabled + no verification. The middle path "upgrades" the security slightly on the next connection iff the server has a CA signed cert.

**Comment by vtnerd** [comment]
Also, this should obsolete the need for the `set_ssl` change in [PR 5581](https://www.github.com/monero-project/monero/pull/5581)

**Comment by moneromooo-monero** [comment]
Are you happy enough with this (ie, we don't need to wait for your better fix) ?

**Comment by vtnerd** [comment]
I guess? This should work, and is done in the fewest line changes. But it is possible to remove cruft while fixing too.

Removing the two `= enabled` lines entirely and changing the checks to `if (m_ssl)` or `if (m_ssl.mode != disabled)` does the same thing without adding fields or code.

**Comment by vtnerd** [comment]
I'm not trying to block this PR and hold things up in anyway btw - the file has some other "logic cruft" surrounding SSL anyway.

**Comment by xiphon** [comment]
Updated

**Pull request merged**
