### PR TITLE
rctsig: optimize by removing addition of zero points

### PR DESCRIPTION
**Pull request by UkoeHB**
There is no need to sum, for some point P, 0+P.

### CODE REVIEW

**Comment by NanoAkron** [comment]
What sort of speed-up are you seeing @UkoeHB?

**Comment by UkoeHB** [comment]
Not equipped to test speedups. This will help with verifying old blockchain data, probably ~1% over borromean blockspan. It also helps MLSAG verification a lot. Right now we have:

for m inputs, p outputs, and v mixin (v+1 ring size)

For RCTTypeFull we need ((v + 1) · (m + 1) + 1) · 32 bytes of storage, and verify with:
PA PointadditionforsomepointsA,B: A+B [m∗(v+1)]
PS Point subtraction for some points A,B : A−B [(v+1)∗(p+1)]
KBSM Known-base scalar multiplications for some integer a: aG [1]
DVBA Double-variable-base addition for some integers a, b, and point B: aG+bB [(m+1)∗(v+1)] 
VBA Variable-base additions for some integers a, b, and points A, B: aA + bB [m ∗ (v + 1)]

For RCTTypeSimple we need (2(v + 1) + 2) · m · 32 bytes of storage, and verify with:
PA Point addition for some points A,B: A+B [m+p+1]
PS Point subtraction for some points A,B : A−B [m∗(v+1)+1]
KBSM Known-base scalar multiplications for some integer a: aG [1]
DVBA Double-variable-base addition for some integers a, b, and point B: aG + bB [2 ∗ m ∗ (v + 1)]
VBA Variable-base additions for some integers a, b, and points A, B: aA + bB [m ∗ (v + 1)]

So imagine 2-in,2-out tx. One fewer PA is significant.

**Comment by NanoAkron** [comment]
I think you should squash commits before moneromooo gets back... :)

**Comment by UkoeHB** [comment]
I think I made it worse..

**Comment by stoffu** [comment]
I ran the performance tests and compared the timings between the current master 62f3f0480a87c0f9a805acb2f101e5bcfd71e90a and this PR 01c28f713b6d4b9a3fa07310906e8cd24da5d52d. Since the performance difference is expected to be small, I multiplied the loop count by 50 as follows:
```diff
diff --git a/tests/performance_tests/performance_tests.h b/tests/performance_tests/performance_tests.h
index 29d296571..0e3745bca 100644
--- a/tests/performance_tests/performance_tests.h
+++ b/tests/performance_tests/performance_tests.h
@@ -84,7 +84,7 @@ public:
     std::cout << "Warm up: " << timer.elapsed_ms() << " ms" << std::endl;
 
     timer.start();
-    for (size_t i = 0; i < T::loop_count; ++i)
+    for (size_t i = 0; i < T::loop_count * 50; ++i)
     {
       if (!test.test())
         return false;
@@ -99,7 +99,7 @@ public:
   int time_per_call(int scale = 1) const
   {
     static_assert(0 < T::loop_count, "T::loop_count must be greater than 0");
-    return m_elapsed * scale / T::loop_count;
+    return m_elapsed * scale / (T::loop_count * 50);
   }
 
 private:
@@ -133,7 +133,7 @@ void run_test(const std::string &filter, const char* test_name)
   if (runner.run())
   {
     std::cout << test_name << " - OK:\n";
-    std::cout << "  loop count:    " << T::loop_count << '\n';
+    std::cout << "  loop count:    " << (T::loop_count * 50) << '\n';
     std::cout << "  elapsed:       " << runner.elapsed_time() << " ms\n";
     const char *unit = "ms";
     int time_per_call = runner.time_per_call();
```
and performed two sets of test runs. Sadly the timing difference was almost negligible compared to the natural variance.

- Master: [1st run](https://paste.debian.net/hidden/e63c1e06/), [2nd run](https://paste.debian.net/hidden/0aac582a/)

- This PR: [1st run](https://paste.debian.net/hidden/aa8b77d2/), [2nd run](https://paste.debian.net/hidden/bd34bffe/)

**Comment by UkoeHB** [comment]
Thanks for the help stoffu :). It seems like this optimization doesn't take us anywhere, so I'll just close the PR.

**Pull request closed without merging**
