### PR TITLE
comon: fix link error on at least one platform (no clue which one)

### PR DESCRIPTION
**Pull request by moneromooo-monero**
Bug and fix reported by tdprime

### CODE REVIEW

**Comment by vtnerd** [comment]
Yup, I am seeing linker errors for `boost::regex` too. Ubuntu 16.04 with gcc 5.4 FWIW

**Comment by moneroexamples** [comment]
Arch same.

**Comment by schnerchi** [comment]
fixes the link errors on mac osx sierra for me.

**Comment by NanoAkron** [comment]
Why did this only recently appear? Confirmed Ubuntu 16.04, GCC 5.4.1, ARMv8

**Comment by moneromooo-monero** [comment]
Because I factored some code from a couple places (wallet and GUI) into src/common/utils, and this code required boost libs that wallet and GUI were linking against, but not all tests.

**Pull request merged**
