### PR TITLE
Wallet API: always use approximate calc of blockchain height

### PR DESCRIPTION
**Pull request by Jaqueeee**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Does the wallet API do its own thing elsewhere ? The patch removes some overriding code, but the commit message hints there is some left elsewhere.

**Comment by Jaqueeee** [comment]
@moneromooo-monero No. After this is removed API relies on the approx calc in wallet2::generate(). In the future it would be good to rewrite the wallet creation code in the API and make it use the height from the daemon instead.

**Comment by sumonkoberaj** [comment]
DMpstWQbWfJrT5Nw4PEzdEeAqbdn2kSPad

**Comment by sumonkoberaj** [comment]
DMpstWQbWfJrT5Nw4PEzdEeAqbdn2kSPad

**Pull request merged**
