### PR TITLE
Txpool dspend

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by hyc** [comment]
This appears to include the commit from #2506 too, was that intentional?

**Comment by Gingeropolous** [comment]
This commit adds the ability to detect double spends in the transaction pool. 

comment made by gingeropolous bot, providing simple english explanations of commits that don't have explanations.

**Comment by moneromooo-monero** [comment]
No, I will rebase when that one's merged, as they conflict with each other.

**Comment by moneromooo-monero** [comment]
rebased after yesterday's  mergefest

**Comment by fluffypony** [comment]
Please rebase again, apologies

**Pull request merged**
