### PR TITLE
[RELEASE] mlog_get_default_log_path: use process name only when provided empty …

### PR DESCRIPTION
**Pull request by stoffu**
…filename

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I don't like that. It can be simplified, but also why do this ? Is this fixing something ? If so, what ?

**Comment by stoffu** [comment]
The motivation comes from a conversation in the GUI repo (https://github.com/monero-project/monero-gui/pull/1358#discussion_r184905431) where I didn't like the proposed change:

```diff
-    Monero::Wallet::init(argv[0], "monero-wallet-gui");
+    const QString logFile = getLogFile(parser.value(logFileOption));
+    Monero::Wallet::init(logFile.toStdString().c_str(), "");
```
because the first argument of `Wallet::init(argv0, default_log_base_name)` is apparently supposed to really be `argv[0]`. The above patch was made so because otherwise the `logFile` value will not take any effect, which seems like a wrong behavior, hence this patch. Actually I'm not confident about how logging should be treated, so I'd highly appreciate if you could weigh in that thread.

That said, I still find the function `mlog_get_default_log_path(filename)` as it is now quite strange, because the argument `filename` I think is always ignored. That is, if I read it correctly, `process_name` is never empty and so is `default_log_file`, and therefore the last `else` is never executed. This doesn't cause any problem because the default log file name is the same as the process name, but this code means that the code like `mlog_get_default_log_path("monero-blockchain-usage.log")` is no different from something like `mlog_get_default_log_path("blahblah")`, which feels odd to me.

**Comment by moneromooo-monero** [comment]
The default log filename is here in case the process name cannot be found. It's a default, not an override, and your patch changes it to an override. If you want a specific filename, then you don't need to call mlog_get_default_log_path in the first place.

**Comment by stoffu** [comment]
Ah, then it’s my misunderstanding. I suppose the GUI patch should also be corrected accordingly. Please look over the patch and provide your feedback.

**Comment by pazos** [comment]
>If you want a specific filename, then you don't need to call mlog_get_default_log_path in the first place.

It is called as part of [Wallet::Init](https://github.com/monero-project/monero/blob/master/src/wallet/api/wallet.cpp#L308-L316). Is this used somewhere besides the GUI?

**Pull request closed without merging**
