### PR TITLE
wallet2: fix infinite loop in fake out selection unit test

### PR DESCRIPTION
**Pull request by jeffro256**
#8794

### CODE REVIEW

**Comment by jeffro256** [comment]
@UkoeHB @j-berman @moneromooo-monero

**Comment by selsta** [comment]
```
[  FAILED  ] select_outputs.exact_unlock_block
[  FAILED  ] select_outputs.exact_unlock_block_tiny
```

**Comment by jeffro256** [comment]
Depends on https://github.com/monero-project/monero/pull/8794

**Comment by jeffro256** [comment]
Rebased

**Pull request merged**
