### PR TITLE
St all

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by stoffu** [comment]
Confirmed to work on Mac, but still can't get the stack trace on Windows:

```
2018-04-15 13:06:27.667	8168	INFO 	msgwriter	src/common/scoped_message_writer.h:102	Height: 15701/1551754 (1.0%) on mainnet, not mining, net hash 9.32 kH/s, v1, up to date, 3(out)+0(in) connections, uptime 0d 0h 0m 24s
2018-04-15 13:06:27.678	8168	INFO 	stacktrace	src/common/stack_trace.cpp:129	crashing
2018-04-15 13:06:27.678	8168	INFO 	stacktrace	src/common/stack_trace.cpp:130	Unwound call stack:
```

**Comment by moneromooo-monero** [comment]
Did cmake claim it was enabled ?
Do you have libbactrace installed ?
What boost version are you using ?

**Comment by moneromooo-monero** [comment]
The only way for libunwind to be used and no trace to be shown seems to be that libunwind reported a succesful empty trace. I guess you can add a log in src/common/stack_trace.cpp here:
    if (ret == 0)
      break;
It probably breaks on the first loop.

**Comment by stoffu** [comment]
I tried compiling it again, and now I see this error which is also in the buildbot log https://build.getmonero.org/builders/monero-static-osx-10.12/builds/4084/steps/compile/logs/stdio:

    ld: unknown option: --wrap=__cxa_throw

I forgot how I was able to run it on Mac (https://github.com/monero-project/monero/pull/3642#issuecomment-381405302).

**Comment by stoffu** [comment]
Also I tried it again on Windows 10, but now I'm getting completely empty stack trace, both for exception crashing and general crashing:

```
2018-06-22 06:06:04.658	1368	INFO 	stacktrace	src/common/stack_trace.cpp:129	Exception: char const*
2018-06-22 06:06:04.658	1368	INFO 	stacktrace	src/common/stack_trace.cpp:130	Unwound call stack:
2018-06-22 06:06:04.660	1368	INFO 	stacktrace	src/common/stack_trace.cpp:170	
2018-06-22 06:06:04.665	1368	INFO 	stacktrace	src/common/stack_trace.cpp:129	crashing
2018-06-22 06:06:04.665	1368	INFO 	stacktrace	src/common/stack_trace.cpp:130	Unwound call stack:
2018-06-22 06:06:04.665	1368	INFO 	stacktrace	src/common/stack_trace.cpp:170	


2018-06-22 06:11:03.119	8636	INFO 	stacktrace	src/common/stack_trace.cpp:129	crashing
2018-06-22 06:11:03.119	8636	INFO 	stacktrace	src/common/stack_trace.cpp:130	Unwound call stack:
2018-06-22 06:11:03.119	8636	INFO 	stacktrace	src/common/stack_trace.cpp:170	
```

CMake log says the Boost stack trace is enabled:
```
-- Found Boost Version: 106501
-- Looking for backtrace_full in backtrace
-- Looking for backtrace_full in backtrace - found
-- Stack traces enabled (using boost/backtrace)
-- Stack trace on exception enabled
```

**Comment by moneromooo-monero** [comment]
Hmm.  That linker must not have the --wrap option I guess.
Since it's not working on Mac either, let's just close this until Mac and Windows people want to hack on it.

**Pull request closed without merging**
