### PR TITLE
Build: fix debug build on FreeBSD

### PR DESCRIPTION
**Pull request by coneiric**
Fixes linker error:

```
CMakeFiles/obj_wallet.dir/wallet2.cpp.o: file not recognized: File format not recognized
```

Not clear why a compiler option fixes a linker error, but it does.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
-O2 makes is hard to debug though.

**Comment by coneiric** [comment]
> -O2 makes is hard to debug though.

Right, I tried with -O0, -O1, and -Og, which all fail in the same way. Not sure what the underlying reason is in `wallet2.cpp`, but -O2 was the only thing that made debug builds work.

**Comment by ndorf** [comment]
There's a different error if one tires to build `debug-static`:

```
[100%] Linking CXX executable ../../bin/monerod
/usr/bin/ld: /usr/local/lib/libboost_chrono.a(chrono.o): relocation R_X86_64_32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libboost_chrono.a: could not read symbols: Bad value
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [src/daemon/CMakeFiles/daemon.dir/build.make:222: bin/monerod] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:2991: src/daemon/CMakeFiles/daemon.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:3003: src/daemon/CMakeFiles/daemon.dir/rule] Error 2
gmake: *** [Makefile:864: daemon] Error 2
```

For the monero-blockchain-* tools, the error is the same except coming from libboost_filesystem.a.

The release binaries, on the other hand, all seem to be statically linked by default (presumably, against the same Boost static libs), and they link and run without errors.

**Comment by ndorf** [comment]
Looks like someone actually noticed this a while back in #4119

**Comment by moneromooo-monero** [comment]
It tells you what to do: build boost with -fPIC.

**Comment by ndorf** [comment]
@moneromooo-monero sorry about that, I mistakenly assumed that error was a canard.

Meanwhile, using the non-static debug build, I finally managed to get a [stack trace](https://github.com/monero-project/monero/files/2469502/monerod_crash_log.txt) of the crash on SIGTERM. (For anyone else having trouble with that, you just need to install the newer version of gdb from packages or ports.)

Note: there are two backtraces in that log, the second is the relevant one. There's also this on stderr: `Fatal error 'thread 0x807816000 was already on queue.' at line 271 in file /usr/src/lib/libthr/thread/thr_cond.c (errno = 19)`, for what that's worth.

Also worth noting is that using the /stop_daemon RPC call does exit cleanly, this problem only occurs with the signal.

**Comment by moneromooo-monero** [comment]
Open a new bug to report that or it'll be mostly missed/ignored/forgotten.

**Comment by ndorf** [comment]
Done, #4563. I might have found the cause.

**Comment by monerorus** [comment]
- i'm install gcc8 on FreeBSD.
- Add `-DCMAKE_C_COMPILER=/usr/local/bin/gcc8 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++8` to monero's Makefile in `cmake-debug` section.
- Add memory up to 8Gb.

and wallet2.cpp.o error gone. (but here is another, see below)
When i use 4Gb RAM and gcc8 i get `swap space error` when wallet2.cpp.o compile. I don't know why it happens, cause when i monitor memory usage it just once take 4+Gb RAM on compile proccess (i have 4Gb RAM + 0.9Gb swap at this time and get swap error. usualy compile use 2.2Gb RAM)
Back to clang and error comeback (even with 8Gb RAM)
Any ideas?

The error with using gcc8:
gcc8_error
Sory for error screenshot instead text.

**Comment by moneromooo-monero** [comment]
Do you have more than one boost lib installed ?

**Comment by ndorf** [comment]
I get the same error with gcc8. Only one boost installed, from the FreeBSD package repository.

Maybe it's because those boost libs are built with Clang, and the C++ symbol manging is incompatible with gcc8? In that case @monerorus would need to build boost with gcc8, also.

**Comment by monerorus** [comment]
no. just 1.68.0

**Comment by ndorf** [comment]
I got the same error with gcc7.

**Comment by monerorus** [comment]
> 
> 
> I get the same error with gcc8. Only one boost installed, from the FreeBSD package repository.
> 
> Maybe it's because those boost libs are built with Clang, and the C++ symbol manging is incompatible with gcc8? In that case @monerorus would need to build boost with gcc8, also.

rebuild boost with gcc8, fix problem.
Fix is:
RAM 5+Gb
gcc8 instead clang for build (boost-libs and monero)

**Comment by moneromooo-monero** [comment]
Cleaning up. The patch is a bodge that doesn't seem worth it.

+invalid

**Pull request closed without merging**
