### PR TITLE
build: prepare v0.18.1.1

### PR DESCRIPTION
**Pull request by selsta**
I would like to put out a point release somewhat soon with output export fixes, unicode path fixes and other smaller bug fixes.

### CODE REVIEW

**Comment by BeholdersEye** [comment]
🍑
🔥

**Comment by BeholdersEye** [comment]
> 10 days ago 

...

> somewhat soon

Clarification requested. Still awaiting a valid archive before updating from v0.17.

> All checks have passed

> This branch has no conflicts with the base branch

What is the impediment?

**Comment by selsta** [comment]
Code is all ready. We need final review, merges and then a release.

**Comment by BeholdersEye** [comment]
> You can also use v0.18.0.0 in the meantime

I was hoping to use the auto-updater and avoid having to manually verify the archive since I understood that was the purpose of having an auto-updater. But thanks for the suggestion.

**Review by j-berman — APPROVED** [review]

**Comment by selsta** [comment]
@BeholdersEye everything is approved now, only thing missing is merges -> tag -> release. Don't have an exact date since it involves multiple people but likely in the next days, plus another day to activate auto updater.

**Comment by BeholdersEye** [comment]
I am optimistic that Ubuntu's default archive manager will not crash when attempting to open the archive containing the release. Recommend checking the time stamps before making a release public just in case.

**Pull request merged**
