### PR TITLE
not found that miniupnpc

### PR DESCRIPTION
**Pull request by FndNur1Labs**
fixed miniupnpcc only

### CODE REVIEW

**Comment by FndNur1Labs** [comment]
sorry miniupnp

**Comment by iDunk5400** [comment]
Invalid.

Please read [this](https://github.com/monero-project/monero#cloning-the-repository) on how to clone or add miniupnp (and unbound) submodule.

**Comment by FndNur1Labs** [comment]
https://github.com/FndNur1Labs/catav7/commit/1e93bfeac66818849024aefe4e82ebaef9924b66

fixed miniupnpc

**Comment by FndNur1Labs** [comment]
no wait even miniupnp is add submodule. they wrong dir see external/cmakelist.txt and same with p2p/net_node.inl

you guys put 2 folder inside....miniupnp/miniupnpc lol

**Comment by anonimal** [comment]
@FndNur1Labs actually, miniupnp did. Look at their repo.

**Pull request closed without merging**
