### PR TITLE
Disguise password length in prompt

### LINKED ISSUE #2748: Disguise password length in 'Wallet password:' prompt
```sh
./monero-wallet-cli
Monero 'Helium Hydra' (v0.11.1.0-release)
Logging to /path/to/monero-wallet-cli.log
Wallet password: **** # <-- Leaks password length
```

Better use a suitable readline prompt instead.

### PR DESCRIPTION
**Pull request by leonklingele**
Fixes #2748

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
I have a feeling this might cause confusion for Windows users.

**Comment by leonklingele** [comment]
@dEBRUYNE-1 how do password inputs normally behave on Windows?

**Comment by dEBRUYNE-1** [comment]
@leonklingele The password length isn't disguised. Perhaps we should only disguise password length for UNIX like systems?

**Comment by leonklingele** [comment]
Even if this doesn't adhere to Windows style guidelines (if there is such a thing) I'd still prefer to mask the password on both (= all) systems.

**Comment by NanoAkron** [comment]
Agreed. There's no reason to downgrade security just because someone chooses to uses Windows.

**Comment by fluffypony** [comment]
@leonklingele congrats on your first merged pull request!

wine drinking

**Pull request merged**
