### PR TITLE
Edits for grammar

### PR DESCRIPTION
**Pull request by BitcoinErrorLog**
http://notaverb.com/backup

"compatibility" spelled incorrectly

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I'd say either "backup the wallet" or "back the wallet up".
OK for the other change.

**Comment by BitcoinErrorLog** [comment]
Fair enough, I updated with your suggestion.

**Comment by moneromooo-monero** [comment]
Thanks, seems to have been left with two commits, one adding the wrong one (IMHO), and one fixing, though.

**Comment by fluffypony** [comment]
Plz squash commits

**Comment by NanoAkron** [comment]
Any way you could change your avatar from a big red cross? It's quite distracting.

**Comment by NanoAkron** [comment]
@BitcoinErrorLog ping

**Comment by NanoAkron** [comment]
Because @BitcoinErrorLog has ignored his PR after submission, I've just gone ahead and fixed it up as requested. We shouldn't let these tiny things clog the list of submitted PRs.

**Comment by fluffypony** [comment]
Closing in lieu of replacement PR

**Pull request closed without merging**
