### PR TITLE
Fix static builds for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by LocalMonero**
Link libbsd, libmd, libprotokit in CMakeLists.txt for ZMQ to fix static builds for Ubuntu 22.04

### CODE REVIEW

**Review by selsta — APPROVED** [review]

**Comment by jeffro256** [comment]
How were you linking before so that it didn't work? I'm using Ubuntu 22.04 and it works fine for me on `master`.

**Comment by LocalMonero** [comment]
@jeffro256 You were running `make release-static` and it worked on your clean Ubuntu 22.04 install?

**Comment by jeffro256** [comment]
Hi @LocalMonero, sorry it took so long to get back to you. I was trying out a bunch of Ubuntu installations trying to reproduce the linking errors that you were getting but I was not able to. From a clean installation of Ubuntu Server 22.04 on a VM, I 1) did `sudo apt update && sudo apt upgrade && sudo apt install <all monero dependencies>` 2) cloned the MiniUPNP repo and built and installed from source 3) cloned the monero repo and ran `make release-static`. I was able to build `release-static` without any errors. Is there anything else you can think of that you might have done to your install of Ubuntu 22 that would cause this error?

**Comment by LocalMonero** [comment]
@jeffro256 we didn't clone and build MiniUPnP, only libzmq3.

**Comment by jeffro256** [comment]
Sorry, that's what I meant to say: I built and installed libunbound from source. Do you have the package `libunbound-dev` installed? If you do, what happens when you `sudo apt remove` that package, then do a `make clean` and rebuild monero?

**Comment by selsta** [comment]
I needed this patch to compile release-static on a fresh Ubuntu 22.04 machine.

**Comment by jeffro256** [comment]
Does this work without removing the `libunbound-dev` package?

**Comment by selsta** [comment]
I assume it depends where you install the custom compiled unbound and which path you tell CMake.

**Review by jeffro256 — APPROVED** [review]
This fixes when `libunbound`'s dependencies are linked statically through the `--enable-static --disable-shared` flags when `./configure`ing.

**Comment by jtgrassie** [comment]
Shouldn't all these checks be wrapped in `if(STATIC)` so they only apply to static builds?

**Comment by LocalMonero** [comment]
@jeffro256 building with `sudo apt install libunbound-dev` doesn't work, static or not. Only self-compiled libunbound works,

**Comment by jeffro256** [comment]
@LocalMonero Right. I was saying that when the `libunbound-dev` package is installed, our CMake rules for finding `libunbound` might have linked against the wrong library (I don't know if they did or not). For those who are linking Monero statically, it is probably best to remove that package, as long as you don't have other packages which depend on it.

**Comment by LocalMonero** [comment]
@jeffro256 libunbound has been an undocumented issue (the README.md still recommends using the package manager `libunbound-dev`) issue on Ubuntu builds ever since it stopped being vendored (#8439). On Ubuntu 22.04, assuming self-compiled libunbound is installed, this patch fixes the static build. Without this patch the static build fails. With the package manager libunbound the static build also fails, with or without this patch.

**Comment by jeffro256** [comment]
> Shouldn't all these checks be wrapped in `if(STATIC)` so they only apply to static builds?

Probably? It *probably* shouldn't negatively affect non-static builds, but it would be likely be the better option, at least so the code is self-documenting in that this is a patch for static builds.

**Comment by busyboredom** [comment]
This fixes builds for me too (also ubuntu 22.04). Would be nice if we could get this merged so master would build out-of-the-box again.

**Comment by selsta** [comment]
@busyboredom it's in the merge queue already

**Comment by jeffro256** [comment]
@selsta what do you think of @jtgrassie 's comment?

**Comment by jtgrassie** [comment]
@jeffro256 
> Probably? It probably shouldn't negatively affect non-static builds, but it would be likely be the better option, at least so the code is self-documenting in that this is a patch for static builds.

My general stance is this: If it's not needed (based on make options), don't link it.

**Comment by selsta** [comment]
We already link to libraries that are only needed for static, so it's fine to change it but I would do it in a separate commit later.

**Pull request merged**
