### PR TITLE
Uri

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Plus unit tests and a couple fixes on corner cases

**Comment by NanoAkron** [comment]
This is really cool. 

Do you think in the future we can access blocks and transactions or navigate merkel trees using a URI scheme?

**Comment by moneromooo-monero** [comment]
No idea. This scheme only does addresses (and associated data). Maybe future changes could include tx/block hashes too. That would likely require changing monero:$ADDRESS to be, maybe monero:/address/$ADDRESS, so other top level things could be added too.

**Comment by moneromooo-monero** [comment]
fluffypony reckons other uses would use a separate scheme anyway.

**Comment by fluffypony** [comment]
@NanoAkron to elaborate - it's a payment URI, so it's always going to be address + metadata. It's not a general purpose URI.

**Comment by NanoAkron** [comment]
Ah. OK cool. I just remember old conversations in bitcoin (couple of years back) about creating a portable universal blockchain navigation scheme using the root (i.e. the hash of the genesis block) and then the offset (location on the merkel tree of your UTXO).

**Comment by anonimal** [comment]
cpp-netlib has a great URI implementation; robust and well-tested. After conferring with http://monero.wikia.com/wiki/URI_formatting, I think cpp-netlib should be considered (lessens dev time, amount of code needed, and possibly more secure). 

I would want to spend a few more moments with both cpp-netlib and monero before pushing anything but, since the only reason monero is asking for boost 1.58 is *because* of cpp-netlib, was there a reason to not start using cpp-netlib now?

Note: kovri's `http.{cc,h}` is just one implementation example which shows how simple it can be to do URI parsing. As for custom monero handling, that would require just a little bit more code (afaict).

**Comment by moneromooo-monero** [comment]
I think the reason for 1.58 was because kovri needed it, and it was thought good to also require it for monero. Since some of vtnerd's code, 1.55 doesn't work anymore, 1.59 does, but I'm not sure whether 1.58 does.

**Comment by anonimal** [comment]
Yes, 1.58 was needed because of kovri (but only because of cpp-netlib). Btw, monero works with 1.58 (running an instance now against current master).

**Comment by moneromooo-monero** [comment]
Anyway, I wouldn't be opposed to using this instead. The %XX encoding tests might fail, but need to be changed, as I did not see a canonical way to handle error states for this in the RFC. Other than that, if the other tests pass, go for it.

**Comment by anonimal** [comment]
>before pushing anything

Sorry, my bad choice of wording (I meant pushing agenda, not code).

I'm too busy with what seems like never-ending kovri work. I'll keep this in mind though, it would be fun to get more involved - but I don't want to break anything in the process.

**Comment by moneromooo-monero** [comment]
Pushing agenda ? There's no scam in here... it's just implementing the preexisting spec...

**Pull request merged**
