### PR TITLE
Fix for biased signature nonce

### PR DESCRIPTION
**Pull request by SarangNoether**

### CODE REVIEW

**Comment by vtnerd** [comment]
This check was added by @moneromooo-monero supposedly from a [recommendation by Quarkslab](https://github.com/monero-project/monero/commit/a4317e61b5f48c05bb094f8bfe1a8cc890885a6f). Perhaps their recommendation was not a great one ... ?

**Comment by SarangNoether** [comment]
Small nonces were not mentioned in the QuarksLab report. The nonce should be unbiased, so small values must be equally considered.

**Comment by fuwa0529** [comment]
This will not introduce another small key attack right? just wondering ...

**Comment by SarangNoether** [comment]
> This will not introduce another small key attack right? just wondering ...

How so? This is only for the nonce. It is assumed that the key was also generated uniformly.

**Comment by fuwa0529** [comment]
> > This will not introduce another small key attack right? just wondering ...
> 
> How so? This is only for the nonce. It is assumed that the key was also generated uniformly.

Right, that was nonsense. This seems to be an unusual check, I wonder why it was there in the first place though.

**Comment by MaxXor** [comment]
Maybe contact QuarksLab to clarify?

**Comment by moneromooo-monero** [comment]
This was not from QL. IIRC it was just me thinking that picking small scalars make it easier to brute force, but on second thought it was a dumb idea.

**Pull request merged**
