### PR TITLE
Improve 'show_transfers' date formatting

### PR DESCRIPTION
**Pull request by ryan-ronnander**
Change the wallet's 'show_transfers' command to always output the transaction date with timestamp (24 hour UTC).

### CODE REVIEW

**Comment by ryan-ronnander** [comment]
Screenshots illustrating date changes (from SUMO patch, but same date formatting):

Change transaction format from (recent transactions missing date, show 12 hour time format):

image

To (all transactions display consistent date and timestamps):

sumokoin_show_transfers_format_new

**Comment by moneromooo-monero** [comment]
Whether this improves is subjective. This had been done on purpose.

**Comment by jtgrassie** [comment]
I tend to agree with @moneromooo-monero

**Comment by ryan-ronnander** [comment]
@moneromooo-monero Let me describe my use case:

Use case: Export transactions from cli wallet to text based csv or similar format with full date and timestamps. With this data you can ultimately determine relative USD and BTC values for each transaction. I'd like to believe I'm not the only one attempting to export my monero transaction data for trade analysis, tax preparation, or any other use case. **Forgive me If there's a better way to export wallet data in a consistent useful format with full date and timestamps.** If there is, I'd love to know.

My current process for procuring this data is as follows:

1. Export wallet transaction data using _show_transfers_ command.
2. Use available tools such as grep and sed to massage the export into csv format. [I use a similar process to this stack exchange answer](https://monero.stackexchange.com/questions/6068/how-do-i-export-my-transaction-history-from-wallet-cli-in-a-usable-format-txt/6072#6072).
```bash
./monero-wallet-cli --command 'show_transfers' --wallet-file=monerowallet --password 'password' | egrep '^ '| sed 's/^ //g'| sed 's/ PM/PM/g' | sed 's/ AM/AM/g' | sed 's/ \+/,/g' | sed 's/,-,/,,/g' | sed 's/PM/ PM/g' | sed 's/AM/ AM/g' > my_txns_formatted.csv
```

3. Use a custom script to scrape and insert actual date and timestamps from the blockchain explorer based on TX hash. 

At the end of step 2 I was initially frustrated. I now had a table of data with two different data types in the same column. Some transactions were merely dates. Some transactions were timestamps. At this point my data export was fairly useless and needed further processing. Enter step 3 - a needlessly complex web scraper just to get a consistent SQL-like 'datetime' format for all exported wallet transactions.

This eventually pushed me to take a look at the code and eliminate step 3 from my current process, hence the pull request.

This pull request is a minimal improvement, even trivial, yes. However I'd argue this change is more than just "I don't like current formatting A, so here's my preferred formatting B" (again, see use case above). 

Maybe this would be better served in a new feature instead of changing the output of an existing command? Say a new wallet command such as 'export_transactions_to_csv'?

**Comment by jtgrassie** [comment]
@ryan-ronnander 
> Maybe this would be better served in a new feature instead of changing the output of an existing command? Say a new wallet command such as 'export_transactions_to_csv'?

It would. You have a specific use case that I'd say `show_transfers` is not the right fit for. However, have you checked the RPC call? That will give you JSON with more processing friendly timestamps.

**Comment by moneromooo-monero** [comment]
If you want full data on batch, you use RPC, really.
I originally did this since it needed less width (and that's what ls does for example) but if people prefer full precision for old stuff I'm fine with it.

**Pull request merged**
