### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sheffladreece**
Changed the linux guide to go to "cd monero-master" as opposed to "cd monero"

### CODE REVIEW

**Comment by NanoAkron** [comment]
But git clones into ~/monero by default...

**Comment by sheffladreece** [comment]
Ahh i see... I am new to coding and downloaded the repo as zip, as opposed to cloning it and didnt realise it would be different. Appologies.

**Comment by NanoAkron** [comment]
Make sure you have git installed, then on your command line try:

`git clone https://github.com/monero-project/monero.git` and go from there :)

**Comment by sheffladreece** [comment]
Yes, thanks just started that now!

**Pull request closed without merging**
