### PR TITLE
Fix typos in readable messages across various files

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
The commit message is odd (git commit --amend)

**Comment by fluffypony** [comment]
@rex4539 please rebase

**Comment by rex4539** [comment]
I think I did it now. Did it work?

Sorry but I'm not very familiar with git.

**Comment by moneromooo-monero** [comment]
Looks good

**Comment by fluffypony** [comment]
@rex4539 so sorry, looks like it needs another rebase, my apologies!

**Comment by rex4539** [comment]
@fluffypony Should be ok now :)

**Comment by fluffypony** [comment]
@rex4539 did you push the rebase? This is another rebase after the last time I asked for a rebase, we must've merged something that created a new conflict - apologies!

**Comment by rex4539** [comment]
After getting some help from monero-dev, and still not being sure I have actually done it correctly, I ended up with 2 separate commits due to an erroneous conflict resolution. I hope that is acceptable.

**Comment by moneromooo-monero** [comment]
git rebase -i HEAD~2
replace the pick with f on the SECOND line (not the first)
save and exit

**Comment by rex4539** [comment]
@fluffypony All done and ready for merge :)

**Comment by fluffypony** [comment]
There we go - thank you so much for all your effort, @rex4539 - and congrats again on your first merged pull request!!!

**Pull request merged**
