### PR TITLE
Add ARMv8-A AES support

### PR DESCRIPTION
**Pull request by hyc**
More than twice as fast as plain C code. Note that both ARMv7 and
ARMv8 can be further improved with better use of NEON.

Also tweak ARMv7 multiplier

Someone please test ARMv7 with asm before merging this, thanks.

### CODE REVIEW

**Comment by NanoAkron** [comment]
Woo hoo!

**Comment by NanoAkron** [comment]
@hyc Can I ask how your code knows where ARM or aarch64 has been defined?

**Comment by hyc** [comment]
@NanoAkron those are platform defines, hardcoded into the C preprocessor. But to get __ARM_FEATURE_CRYPTO defined you must compile with "-march=armv8-a+crypto"

**Comment by NanoAkron** [comment]
I'll update CMakeLists.txt and make a PR

**Comment by hyc** [comment]
IMO the CMakeLists.txt shouldn't be changed. As we've recently found out, there are plenty of ARMv8 chips out there without crypto support. (Like the Raspberry Pi 3's Broadcom BCM2837.)

We'd need to add runtime AES detection before making +crypto the default build arch.

**Comment by radfish** [comment]
Btw, do we know for sure that `-march=native` does not enable +crypto?
(The `native` option seems to address exactly this problem.)

If it does, then the feature will be enabled at least for native builds
with `make release` (which passes `-march=native` already). It's a
reasonable level of support before the runtime detection is implemented
to make the same binary portable across arch's with/without the feature.

If is doesn't, then does anyone know why would they not follow the
logical convention of having `native` enable all available features
instead of this `+feature` suffix? Can one at least do
`-march=native+feature`?

**Comment by hyc** [comment]
-march=native is invalid on my box:
> gcc -c -march=native foo.c
> foo.c:1:0: error: unknown value ‘native’ for -march

**Comment by radfish** [comment]
On Sat, Sep 17, 2016 at 10:21:21AM -0700, hyc wrote:
> -march=native is invalid on my box:
> > gcc -c -march=native foo.c
> > foo.c:1:0: error: unknown value ‘native’ for -march

Odd. What platform is that on? Is this stock gcc? which version?
Then, `make release` is broken on that box? so needs fixing (?)

From man gcc on my armv7 with stock gcc 6.1.1 from Arch Linxu ARM repo:

       -march=name

       ...
       -march=native causes the compiler to auto-detect the architecture
       of the build computer.  At present, this feature is only
       supported on GNU/Linux, and not all architectures are recognized.
       If the auto-detect is unsuccessful the option has no effect.  

Hm.. that note suggests that perhaps `-march=native` is not reliable.

**Comment by hyc** [comment]
This is a geekbox running 64bit Debian Jessie. Compiler is gcc 4.9.2.

I haven't used "make release". I started this build tree several months ago and have not used any of the recent CMakeLists changes.

**Comment by radfish** [comment]
Ok.

Just to answer one of my questions above: at least gcc 6.1.1 should
accept `-march=native+feature`, based on the section on AArch64:

          Specify the name of the target architecture and, optionally,
          one or more feature modifiers.  This option has the form
          -march=arch{+[no]feature}*.

          The permissible values for arch are armv8-a,
          armv8.1-a or native

**Comment by smokerholic** [comment]
Thank you for ARMv8-A AES support.
Is there a way to mine cryptonight/xmr with ARMv8-A AES support on a pool?

**Comment by hyc** [comment]
I'm not aware of anyone releasing any code for that yet. You can just take the existing code for a CPU miner and add the same ARMv8 changes as I've written here into that.

**Pull request merged**
