### PR TITLE
README.md: fix portable binaries build targets

### PR DESCRIPTION
**Pull request by lancillotto**
Corrections on Building Portable Statically Linked  Binaries section

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
The commit message seems to be unchanged. You changed the name on github only :P

**Comment by lancillotto** [comment]
Not too easy to do but meantime I learned a lot, thank you.

**Comment by moneromooo-monero** [comment]
Thanks :)

**Comment by fluffypony** [comment]
@lancillotto congrats on your first PR! Can I ask you a favour: can you close this and open it against Master instead? The release branch is for very important bug fixes only, which this doesn't count as:)

**Pull request closed without merging**
