### PR TITLE
Easylogging: remove unused config def

### PR DESCRIPTION
**Pull request by MoroccanMalinois**
ELPP_STACKTRACE_ON_CRASH doesn't look used anymore

### CODE REVIEW

**Comment by MoroccanMalinois** [comment]
That's ELPP_STACKTRACE, not ELPP_STACKTRACE_ON_CRASH ?

**Comment by moneromooo-monero** [comment]
Ah, sorry, I was on a branch before the patch. Yes, it's now unused, but really renamed to ELPP_FEATURE_CRASH_LOG, so I think the ifdef should stay, but define ELPP_FEATURE_CRASH_LOG instead of ELPP_STACKTRACE_ON_CRASH

**Comment by moneromooo-monero** [comment]
In fact, it looks like this patch and your previous one might get just replaced by this renaming ?

**Comment by MoroccanMalinois** [comment]
Still the static issue. Changed the previous patch to account for this renaming

**Pull request merged**
