### PR TITLE
device: fix ledger requesting secret keys export twice

### PR DESCRIPTION
**Pull request by xiphon**
Fixes https://github.com/monero-project/monero-gui/issues/2354

### CODE REVIEW

**Comment by xiphon** [comment]
@cslashm

**Comment by cslashm** [comment]
Seems ok, thanks.

**Comment by cslashm** [comment]
In fact doing that  disables the export key view except for device creation .
My next PR will revert that

**Comment by selsta** [comment]
@cslashm #5923

**Pull request merged**
