### PR TITLE
Updating gitian yml files for v0.15

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by hyc** [comment]
Is there any way to pull this version number from some existing stamp in the source tree, so this doesn't need to be manually updated on every release?

**Comment by jonathancross** [comment]
I agree, that would be nice to automate, but I also see that Bitcoin Core is doing it manually like us:
https://github.com/bitcoin/bitcoin/commit/fa1ad8f06eba5e120c30f07263250bc382891179

They keep master at the 'next release' which we might also want to adopt.

**Comment by dEBRUYNE-1** [comment]
Can you also open this against master?

**Comment by jonathancross** [comment]
> Can you also open this against master?

I'll see what I can do.  Might need to create a new PR.

**Comment by dEBRUYNE-1** [comment]
Can you revert this PR back to the old state? It currently cannot be merged.

**Comment by dEBRUYNE-1** [comment]
Thanks.

**Pull request merged**
