### PR TITLE
SimpleWallet: Change restore from electrum command

### PR DESCRIPTION
**Pull request by HarrisonHesslink**
Change command line --restore-deterministic-wallet to a more friendly --restore-from-seed.

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
This will break a lot of existing documentation. I personally think the benefit is not worth the trade-off in this case.

**Comment by HarrisonHesslink** [comment]
Yea I thought of that. It just a weird command name imo. I don't think people would need to look up documentation to restore from seed. If the command is restore-from-seed.

**Comment by moneromooo-monero** [comment]
If you want to add an alias though, that'd be OK (assuming boost can do this).

**Comment by moneromooo-monero** [comment]
I did it since this was left off: https://github.com/monero-project/monero/pull/5983
I think that does what you wanted.

**Pull request closed without merging**
