### PR TITLE
move txpool to database

### PR DESCRIPTION
**Pull request by moneromooo-monero**
I'll be using that on my mainnet node for a while to see if anything breaks, but looks fine on testnet + passes tests.

### CODE REVIEW

**Comment by iamsmooth** [comment]
This PR should be closed until and unless the code is open source. People working on the open source project should not even be reviewing the code, as doing so creates potential legal claims should similar work be done independently by others later. I see from the comments that some reviews have already been done, but that should stop immediately.

I personally will not look at or review the code (other than having looked to see what the mentioned license issue was about) and therefore object to merging code into the repo that I am not able to review.

There is no place for submissions to an open source project (and that's what this repo is, entirely) that are not themselves open source (nor I would suggest, without extensive community discussion, submissions that modify license terms or use any license other than the modified BSD that applies to the entire repo). 

If the contributor has some dispute on payment terms with those paying or promising to pay him, that needs to be worked out out-of-band and not in the repo.

Please resubmit under the license in LICENSE.

**Comment by moneromooo-monero** [comment]
Locking fix.

**Comment by NanoAkron** [comment]
How large are we predicting the Tx pool will grow that it needs to be out of memory? Or is this a further extension to the fluffy-blocks concept where the system pre-assigns certain transactions into blocks and waits for the header and TxID list to come in?

**Comment by hyc** [comment]
@NanoAkron the point is that we don't know how large it will get, and any limit we might choose to impose would be entirely arbitrary.

Also, while that wasn't the original purpose of this PR, I view it as a necessary step. I've found that when running two daemons on the same DB, each with their own separate txpool, the txpools get out of sync with reality. I.e., normally when a block arrives, its txs are removed from the pool. But with multiple daemons, only one daemon knows that the block was added and clears its pool. The other daemons never see the block arrive, it just appears in the blockchain DB spontaneously. So they never remove the block's txs from their own pools. Moving the txpool into the DB is an obvious first step to avoiding that issue.

**Comment by NanoAkron** [comment]
Interesting. And there's no noticeable speed trade-off? Will fresh incoming transactions remain in memory for a time before being written to disk, in case they need to be relayed onwards?

**Comment by iamsmooth** [comment]
@NanoAkron LMDB is a **memory mapped** database. Any fresh data this is being accessed is kept in RAM, assuming there is available RAM. If there isn't, then the current mempool would swap with much worse performance (in memory collections are not optimized for disk I/O). 

There is probably a small amount of overhead in terms of using DB apis to access the data, but LMDB is pretty efficient all around.

**Comment by moneromooo-monero** [comment]
Deadlocks should now be fixed.

**Pull request merged**
