### PR TITLE
p2p: tone down "no incoming connections" warning to info if in peers …

### PR DESCRIPTION
**Pull request by moneromooo-monero**
…is 0

Also add an info if not offline, since it weakens the network

### CODE REVIEW

**Comment by hyc** [comment]
The current warning shows up on my node every 15 minutes. It looks like this patch doesn't change the message frequency, just its severity. Is that right?

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by scoobybejesus** [comment]
Is it reasonable to request that the frequency gets toned down as well?  If so, that'd be my request.

**Comment by moneromooo-monero** [comment]
Every hour now.

**Comment by BigslimVdub** [comment]
Thanks

**Pull request merged**
