### PR TITLE
Separate data from code

### PR DESCRIPTION
**Pull request by calidion**
Put data together.
Separate data from code.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I don't really like moving stuff around for the sake of it.
I assume it's just moving around and reformatting, right ?

**Comment by moneromooo-monero** [comment]
Updating the .gitignore could be good though.

**Comment by calidion** [comment]
@moneromooo-monero 

it would be much easier to locate the data when you are not working with blockchain.cpp or node_api.h.

Since they are not code, they are just configurable data, separate them will help code to be much cleaner.

**Comment by calidion** [comment]
Close for another pull request is created.

**Pull request closed without merging**
