### PR TITLE
[release-v0.16]: Update gitian yml files

### PR DESCRIPTION
**Pull request by iDunk5400**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
> I also updated #6514 to include these changes.

Would you mind not doing so ? It is really annoying when what purports to be the same patch on two different branches are actually not the same ones, and makes it hard to spot stuff that's been forgot on one branch.

**Comment by selsta** [comment]
Would you prefer if I revert it or for the future?

**Comment by moneromooo-monero** [comment]
If it's not too much hassle, I'd rather have the same patches on both sides.

**Comment by selsta** [comment]
Updated but wasn’t able to get the same commit hash. Not sure if that is possible.

**Comment by moneromooo-monero** [comment]
That's expected, the commit hash also depends on the commit's ancestry.

**Pull request merged**
