### PR TITLE
Daemon: print msg upon success for commands that are completely silent

### PR DESCRIPTION
**Pull request by binaryFate**
Find it bad that you don't know if flushing is complete or if you have to wait because something hanging

### CODE REVIEW

**Comment by stoffu** [comment]
I agree. Maybe the same thing could also be done for `relay_tx` while you're at it?

**Comment by MaxXor** [comment]
Success messages are not written for some other commands too. For example just above, the `unban` command. I think it should get added to to all commands to have consistent feedback of successful operations.

**Comment by binaryFate** [comment]
Thanks for the suggestion, will add to other relevant commands

**Comment by binaryFate** [comment]
Updated, I added the same thing to all commands that were silent in terms of success message, but some of them were printing something further inside the code, for instance now with this patch we get:
```
unban 85.XXX.XXX.XXX
2017-11-09 09:34:47.535     7fda9d419700        INFO    global  src/p2p/net_node.inl:270        Host 85.XXX.XXX.XXX unblocked.
IP 85.XXX.XXX.XXX is now unbanned
```
I think it's clogging up and redundant, so maybe we should do it only for commands that were absolutely completely silent.
Thoughts?

**Comment by moneromooo-monero** [comment]
What is bad isn't that commands don't print spurious "done" messages, but that the readline stuff is printing the prompt even when it should not (in the wallet anyway). In the daemon, the absence of prompt does this.

**Comment by binaryFate** [comment]
> In the daemon, the absence of prompt does this

I don't understand what you mean as there is no prompt in the daemon. When executing flush_txpool I see zero indication that it completed and that it's not hanging somewhere

**Comment by moneromooo-monero** [comment]
I mean that, due to the daemon not displaying a prompt, you don't see when the program is waiting for a new command. This is contrasting with the wallet, which does (albeit buggily since the readline patch went in).

**Comment by binaryFate** [comment]
Ok; I was only talking about patching the daemon here. 
Not sure what is your suggestion then... dropping the "success" strings and solve this by adding a prompt instead?

**Comment by moneromooo-monero** [comment]
Doing that seems better, but I'm not sure I'm suggesting it just yet. Still fuzzy in my head.

**Comment by moneromooo-monero** [comment]
Meh, I think this is shed painting because I just dislike random useless messages on success, so let's just add this if people in general think it's good. Some of the indentation on new lines seem off though.

**Comment by stoffu** [comment]
FWIF, my opinion isn’t strong, and I’m not qualified to judge the merit of this patch wrt @momeromooo’s concern regarding readline etc.

**Comment by binaryFate** [comment]
I'm not UX expert, just me personally I like to see a "success!" reporting *even* if a new prompt would show it at least completed. Putting myself in the shoes of somebody new to the software and that is not familar with code base conventions, "new prompt == everything ok, request executed" is far from obvious.

**Comment by moneromooo-monero** [comment]
It's the canonical way commands go. Do you get a "Success" message with rm, chmod, cat, and pretty much every other command ? The exception is when you have something to actually report, rather than a simple "marker" message. But then the shell doesn't print the prompt again before they're done :)

**Comment by binaryFate** [comment]
It's the canonical way bash and unix in general commands go. Does not mean that the majority of the users will come to expect this.

If you find it useless to spit a static string, I'd posit that a "successfully flushed *X* transactions" would be handy ;)

**Comment by moneromooo-monero** [comment]
Totally :)

I OK'd the patch a few comments ago fwiw.

**Comment by binaryFate** [comment]
@moneromooo-monero indention looks messed up because that file is a mix of spaces and tabs.

What should we do in this case? Reformat whole file? Or stick to spaces or tabs for new changes?

**Comment by stoffu** [comment]
@binaryFate 
I think we should refrain from reformatting in order to keep the history clean. You can find in wallet2.cpp some even worse mess of spaces and tabs mixed up _one line after another_; it looks really ugly, but we have to bear with it :)

**Comment by moneromooo-monero** [comment]
No mass reformat please. When I edit such files, I try to use the same formatting as surrounding lines. If the surrounding lines themselves are inconsistent, then I'd consider fixing them, unless doing so makes them inconsistent with their own surrounding lines.

**Comment by binaryFate** [comment]
Allrighty, will do that, thanks

**Comment by binaryFate** [comment]
Updated: 

* use space or tabs according to lines around
* only added success message to calls that were entirely silent (in log level 0). These are: `start_save_graph`, `stop_save_graph`, `flush_txpool`, `relay_tx`.

**Pull request merged**
