### PR TITLE
[DO NOT MERGE] add get_tx_proof_support

### PR DESCRIPTION
**Pull request by cslashm**
Edit: Only  required if sanity check is add to this branch

- Add support for get_tx_proof and check_tx_proof, needed for pending sanity check PR
- Enhance log
- Minor cleanup

### CODE REVIEW

**Comment by stoffu** [comment]
This seems to be adding a new feature to the release branch which seems unsuitable; the branch is supposed to be updated only with critical bug fixes that should go into the next point release. Do you have a specific reason why this should go into the release branch instead of master?

**Comment by cslashm** [comment]
When I discussed with @moneromooo-monero  it told me the new sanity check we may be added to 0.13 branch for 0.14.0.3+. So this patch is only needed in that case. 
The same is done on master in #5332

**Comment by moneromooo-monero** [comment]
If we release a 0.14.0.3 (which is unlikely now I think) we might merge this. But the sanity check code is only on master currently.

**Comment by cslashm** [comment]
OK so do not merge it.

**Comment by moneromooo-monero** [comment]
+duplicate

**Pull request closed without merging**
