### PR TITLE
rx-slow-hash: decrease log spam for per hash warnings/messages

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by hyc** [comment]
This is spamming the logs? How? Each of those allocations only occurs once.

**Comment by moneromooo-monero** [comment]
Then it is a bug. I get one of these this once a hash (at least every block since I use --fixed-difficulty 1). Maybe I got overeager for the others though.

**Comment by hyc** [comment]
Just one specific message? Which one?

**Comment by moneromooo-monero** [comment]
A sample from running monerod earlier today:

```
2019-12-07 00:18:06.758	W Couldn't allocate RandomX dataset for miner
2019-12-07 00:18:06.798	I Found block <b72aa808c1abee8ca11e4fcfe6b2a2837aefeb475b0903ab67263bdea0a2ce3c> at height 93 for difficulty: 1
2019-12-07 00:18:06.845	W Couldn't allocate RandomX dataset for miner
2019-12-07 00:18:06.883	I Found block <357710f1282d317069ab17424ff4861f1be3155eeeaba91ddce4f9cbfa5e6b26> at height 94 for difficulty: 1
2019-12-07 00:18:06.937	W Couldn't allocate RandomX dataset for miner
```

**Comment by hyc** [comment]
OK, so every time it fails it just uses the 256MB cache and mines in slow mode. I guess I could set a flag saying "we've already tried to allocate a dataset and failed, don't try any more."

**Comment by hyc** [comment]
````
diff --git a/src/crypto/rx-slow-hash.c b/src/crypto/rx-slow-hash.c
index a7a459ad3..9f848b158 100644
--- a/src/crypto/rx-slow-hash.c
+++ b/src/crypto/rx-slow-hash.c
@@ -62,6 +62,7 @@ static CTHR_MUTEX_TYPE rx_dataset_mutex = CTHR_MUTEX_INIT;
 static rx_state rx_s[2] = {{CTHR_MUTEX_INIT,{0},0,0},{CTHR_MUTEX_INIT,{0},0,0}};
 
 static randomx_dataset *rx_dataset;
+static int rx_dataset_nomem;
 static uint64_t rx_dataset_height;
 static THREADV randomx_vm *rx_vm = NULL;
 
@@ -246,20 +247,25 @@ void rx_slow_hash(const uint64_t mainheight, const uint64_t seedheight, const ch
     }
     if (miners) {
       CTHR_MUTEX_LOCK(rx_dataset_mutex);
-      if (rx_dataset == NULL) {
-        rx_dataset = randomx_alloc_dataset(RANDOMX_FLAG_LARGE_PAGES);
+      if (!rx_dataset_nomem) {
         if (rx_dataset == NULL) {
-          mdebug(RX_LOGCAT, "Couldn't use largePages for RandomX dataset");
-          rx_dataset = randomx_alloc_dataset(RANDOMX_FLAG_DEFAULT);
+          rx_dataset = randomx_alloc_dataset(RANDOMX_FLAG_LARGE_PAGES);
+          if (rx_dataset == NULL) {
+            mdebug(RX_LOGCAT, "Couldn't use largePages for RandomX dataset");
+            rx_dataset = randomx_alloc_dataset(RANDOMX_FLAG_DEFAULT);
+          }
+          if (rx_dataset != NULL)
+            rx_initdata(rx_sp->rs_cache, miners, seedheight);
         }
-        if (rx_dataset != NULL)
-          rx_initdata(rx_sp->rs_cache, miners, seedheight);
       }
       if (rx_dataset != NULL)
         flags |= RANDOMX_FLAG_FULL_MEM;
       else {
         miners = 0;
-        mwarning(RX_LOGCAT, "Couldn't allocate RandomX dataset for miner");
+        if (!rx_dataset_nomem) {
+          rx_dataset_nomem = 1;
+          mwarning(RX_LOGCAT, "Couldn't allocate RandomX dataset for miner");
+        }
       }
       CTHR_MUTEX_UNLOCK(rx_dataset_mutex);
     }
````

**Comment by moneromooo-monero** [comment]
Works for me.

**Pull request closed without merging**
