### PR TITLE
disable AES on s390x architecture

### PR DESCRIPTION
**Pull request by tmh1999**
AES is only on available on x86*

### CODE REVIEW

**Comment by NanoAkron** [comment]
AES is also available on ARMv8

**Comment by NanoAkron** [comment]
I believe cmake should have a mechanism to test if that flag works or not on the local architecture. Don't quote me on it though.

**Comment by vtnerd** [comment]
Did a comment get deleted? My email is showing one that isn't coming up ... Anyway cmake has [CheckCXXCompilerFlag](https://cmake.org/cmake/help/v3.0/module/CheckCXXCompilerFlag.html), [CheckCXXSourceCompiles](https://cmake.org/cmake/help/v3.0/module/CheckCXXSourceCompiles.html), and [CheckCXXSourceRuns](https://cmake.org/cmake/help/v3.0/module/CheckCXXSourceRuns.html). They are going to be tricky to use properly (false positives), so I am not sure if anyone wants to put that much effort into this. But it should be possible.

**Comment by tmh1999** [comment]
Would you mind merge this PR for now and wait for https://github.com/monero-project/monero/issues/3740 later ?

**Comment by moneromooo-monero** [comment]
It will be merged once we get to it after we start merging to master again. We will not be waiting for #3740.

**Comment by baryluk** [comment]
You should test for positive archs, not negative archs. I.e. if you go this route you might need to exclude dozen other archs. Better to list just supported archs. Or just ask compiler if it understands the flag.

@NanoAkron -maes is about AES-NI, it is only on x86 and amd64 archs. and maybe ia64. Many ARM subarchs, and even modern PPC, Power, MIPS and s390x does in fact have AES acceleration one way or another, but it is different thing.

**Comment by iamsmooth** [comment]
Maybe references to 'AES support' in the CMake should be changed to something better descriptive of what it actually does?

**Comment by luigi1111** [comment]
@tmh1999 please rebase.

**Comment by moneromooo-monero** [comment]
ping

**Comment by moneromooo-monero** [comment]
I rebased this to current master, see https://github.com/monero-project/monero/pull/4401.

**Comment by fluffypony** [comment]
Closed; cherry-picked, rebased and merged via #4401

**Pull request closed without merging**
