### PR TITLE
blockchain: fix total_height in getblocks.bin response

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by ksemaev** [comment]
@selsta this fix didn't get into 0.16.0.1?

**Comment by moneromooo-monero** [comment]
Wrong.

**Comment by vbonini** [comment]
Do you have an ETA as to when this fix might get implemented?

**Comment by moneromooo-monero** [comment]
It is fixed (unless you tested it and it's not).

**Comment by vbonini** [comment]
Thank you for the clarification. We will test and confirm.

**Comment by vbonini** [comment]
[I found your commit](https://github.com/monero-project/monero/commit/b7812d1674b9a2c5df4bd4c98f18de340098a3c4), so your previous comment now makes sense. 

We tested and confirmed fixed in 0.16.0.1. cc @ksemaev @gutenye

**Comment by moneromooo-monero** [comment]
Cool, thanks.

**Pull request merged**
