### PR TITLE
build: prepare v0.18.3.4

### PR DESCRIPTION
**Pull request by selsta**

### CODE REVIEW

**Review by vtnerd — APPROVED** [review]

**Comment by plowsof** [comment]
```
monero-blockchain-export --data-dir /var/lib/monero/.bitmonero --blocksdat --output-file blockchain.dat --block-stop 3159500
sha256sum blockchain.dat 
b57e82f2aad8b08a5cece78b9839b8184e2959fdb0f44be6571fa8e45ce66de2  blockchain.dat
```
```sh
height="3159500"
difficulty="0x4ee8653b54b8d40"
hash="985a58096a03b7369a8b56cec6e77ffa6cc98f94d8b57dc9affd61c8477a852e"
node=127.0.0.1:18081
REQ=$(curl http://${node}/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_block_header_by_height","params":{"height":'${height}'}}' -H 'Content-Type: application/json')
DATA=$(echo $REQ | jq '.result.block_header')
actual_difficulty=$(echo $DATA | jq -r '.wide_cumulative_difficulty' )
actual_hash=$(echo $DATA | jq -r '.hash')
if [ "$actual_hash" != "$hash" ]; then 
        echo "hashes don't match"; exit
fi
if [ "$difficulty" != "$actual_difficulty" ]; then
        echo "difficulty not equal"; exit
fi
echo "OK"

```

**Review by plowsof — APPROVED** [review]

**Comment by selsta** [comment]
Updated with newer checkpoints.

**Comment by plowsof** [comment]
```bash
$ monero-blockchain-export --data-dir /var/lib/monero/.bitmonero --blocksdat --output-file blockchain.dat --block-stop 3198000
$ sha256sum blockchain.dat 
8ada865350270fd008397684d978dac75ea4029a8a1ffcaa9975c43be119ec19  blockchain.dat
```
```
height="3198000"
difficulty="0x517d415fee3a816"
hash="1d685b39be51e4e84e0af69fa78e023c7cb21de7d33acd012d0371d5f78712d5"
node=127.0.0.1:18081
REQ=$(curl http://${node}/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_block_header_by_height","params":{"height":'${height}'}}' >
DATA=$(echo $REQ | jq '.result.block_header')
actual_difficulty=$(echo $DATA | jq -r '.wide_cumulative_difficulty' )
actual_hash=$(echo $DATA | jq -r '.hash')
if [ "$actual_hash" != "$hash" ]; then 
        echo "hashes don't match"; exit
fi
if [ "$difficulty" != "$actual_difficulty" ]; then
        echo "difficulty not equal"; exit
fi
echo "OK"
```
:heavy_check_mark:

**Review by plowsof — APPROVED** [review]

**Review by sneurlax — APPROVED** [review]
These changes match many similar "build: prepare" PRs, LGTM

**Pull request merged**
