### PR TITLE
hardfork: fix crash in test

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by danrmiller** [comment]
Fixes the crash in the test that was happening on osx-10.10.

**Comment by moneromooo-monero** [comment]
yay! \o/

**Comment by moneromooo-monero** [comment]
In that case, maybe we want your patch (minus the extra reformatting) :)

**Comment by vtnerd** [comment]
Crap, already closed that one. I will remove formatting and do another pull request since I still have that branch open locally.

**Pull request closed without merging**
