### PR TITLE
wipeable_string: don't try to wipe an empty buffer

### PR DESCRIPTION
**Pull request by moneromooo-monero**
memset_s doesn't like it

### CODE REVIEW

**Comment by jtgrassie** [comment]
There's one check missed on line 79 (`wipeable_string::wipe`)...
```
* thread #1: tid = 0x567999, 0x00007fff96ab4f06 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff96ab4f06 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff91dcf4ec libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff90b9f6df libsystem_c.dylib`abort + 129
    frame #3: 0x00000001033c1781 libcommon.dylib`memwipe(ptr=0x0000000000000000, n=0) + 49 at memwipe.c:59
    frame #4: 0x00000001033c01e4 libcommon.dylib`epee::wipeable_string::wipe(this=0x00007fff5fbf3fb0) + 68 at wipeable_string.cpp:79
    frame #5: 0x00000001033c0168 libcommon.dylib`epee::wipeable_string::~wipeable_string(this=0x00007fff5fbf3fb0) + 24 at wipeable_string.cpp:74
    frame #6: 0x00000001033c0205 libcommon.dylib`epee::wipeable_string::~wipeable_string(this=0x00007fff5fbf3fb0) + 21 at wipeable_string.cpp:73
    frame #7: 0x0000000103361206 libcommon.dylib`tools::password_container::~password_container(this=0x00007fff5fbf3fb0) + 38 at password.cpp:228
```

**Comment by moneromooo-monero** [comment]
added

**Comment by hyc** [comment]
Or just change memwipe to return/no-op if length==0.

**Comment by moneromooo-monero** [comment]
Yes, but I thought it'd be nice to check whether those calls were bugs in the caller. I'm kind of undecided yet which one I prefer.

**Pull request merged**
