### PR TITLE
fix a tiny typo (I think)

### PR DESCRIPTION
**Pull request by Kuplynx**
It's more common for "be" to be after "just"

### CODE REVIEW

**Comment by selsta** [comment]
"could be just" shows more results on Google than "could just be".

See for example https://tatoeba.org/en/sentences/show/2953038

**Comment by hyc** [comment]
Fwiw the wording in this patch is what I'm most used to, but at the same time I don't think the distinction is important enough to warrant a patch. I personally would ignore all this.

**Comment by Kuplynx** [comment]
Yeah, it's what I'm used to and when I saw the message in the daemon I immediately said "oh, that looks wrong"

**Comment by hyc** [comment]
Except it isn't clearly wrong. What's clear is that a majority of people speak/write with that pattern. Should close this ticket.

**Comment by Kuplynx** [comment]
Alright

**Pull request closed without merging**
