### PR TITLE
[RELEASE] Unbound: bump to 1.7.0rc3 + remove in-tree source, use git submodule

### PR DESCRIPTION
**Pull request by anonimal**
As approved by @moneromooo-monero on IRC, still open for consideration: here is the concept of what we should consider doing for all our external dependencies.

To consider:
- I wish to immediately move https://github.com/anonimal/unbound into monero-project, thus stripping any of my write access to the repo
- I've kept things simple regarding svn to git: no trunk/branch/tag conversions, no prettying of git log. This has proven to make things easier when we `git svn rebase`; especially because we are working from a custom branch and we will need to rebase for every unbound release.

Referencing https://github.com/monero-project/monero/pull/2089#discussion_r124184672

### CODE REVIEW

**Comment by anonimal** [comment]
>github does not seem to show the patch setting the commit hash for the submodule, it shows some dodgy looking preparsed link

Yes, it's annoying, but it appears to be accurate. I'm guessing the only other way to verify with confidence (until github fixes, if ever) will be to fetch branch monero from my fork to confirm the commit. I'm thinking people will be doing this anyway, so that's good.

>I think it should be merged only after the URL target switches to monero-project

As soon as @fluffypony et al creates monero-project/unbound, I'll move my repo over a.s.a.p.

**Comment by fluffypony** [comment]
@anonimal created https://github.com/monero-project/unbound

**Comment by anonimal** [comment]
@fluffypony rebased. I don't have push access to monero-project/unbound (at least temporarily to get my repo moved) so the code will have to get there somehow before this PR is merged.

**Comment by fluffypony** [comment]
@anonimal can't you PR to that? or must I initialise with a readme for that to work?

**Comment by anonimal** [comment]
>can't you PR to that?

Nope. I tried. AFAICT the repo needs to be pushed directly. Ideally (in fact, we probably shouldn't) you don't initialize a README or any file because `master` will be the pure svn-to-git of unbound and having our own commit will make things a pain to deal with IMHO.

**Comment by anonimal** [comment]
Successfully pushed to https://github.com/monero-project/unbound.

**Comment by hyc** [comment]
We'll definitely need a pristine branch for syncing from upstream, but also a monero-specific branch for any point patches we need to apply.

**Comment by danrmiller** [comment]
This submodule already uses the "monero" branch from https://github.com/monero-project/unbound/tree/monero. 

We should verify that everything we need is in there and PR what's missing. It looks like many things, for example 45e9838bb1f697a7b7d35e7abc6eb236ca7b625c, are already included upstream.

For the "clean" branch, I'll check out upstream with subversion and verify, but it looks like we are tracking trunk. Should we pick a tag instead like either the latest 1.6.7 or the 1.6.3 we were previously using? Or do the differences between svn and git make that not practical?

**Comment by moneromooo-monero** [comment]
Is there anything I can help with here ?

**Comment by anonimal** [comment]
Oops, forgot that I opened this PR. When someone gives me the go-ahead, I'll rebase. I'm not sure if @danrmiller had a chance to verify.

>Or do the differences between svn and git make that not practical?

AFAICT, and IIRC, not practical (but maybe someone else has input on that).

**Comment by anonimal** [comment]
Ping @danrmiller

**Comment by danrmiller** [comment]
@anonimal What would you like me to do? I don't have anything to add since last time.

**Comment by anonimal** [comment]
@danrmiller ok, thanks for clarifying.

I've opened https://github.com/monero-project/unbound/pull/1 and https://github.com/monero-project/unbound/pull/2. After they are merged, this PR will resolve #3413 (@fluffypony I can't rebase this PR until those are merged).

**Comment by anonimal** [comment]
Note: this PR was marked for release because the in-tree unbound is outdated at 1.6.3. The current 1.7.0rc3 is the latest stable version and is the tag used in their March 15th, release.

**Pull request merged**
