### PR TITLE
Backport of Ryo fix for a wallet caching bug

### PR DESCRIPTION
**Pull request by fireice-uk**
xref https://github.com/ryo-currency/ryo-currency/pull/86

### CODE REVIEW

**Comment by fireice-uk** [comment]
Note, please see the other commits in the xref'ed pr. I didn't include them because our fork selection system works differently to yours.

**Comment by moneromooo-monero** [comment]
Looks ok, please use a sensible commit message though (eg, "node_rpc_proxy: fix fork earliest height caching" or so).

**Comment by fireice-uk** [comment]
Problem is that `get_earliest_ideal_height_for_version` will return `1546000` for any input >= 7 in your case. As long as that behaviour is expected then you can get away with just this patch.

In our case we have different features enabled on different heights for the testnet and mainnet so this is how it triggered a secondary bug (we assigned bulletproofs to a disabled v255).

**Comment by moneromooo-monero** [comment]
OK. It should currently return max uint64_t by my reading, and it changed a few months ago to support "jumps" in versions as aeon was doing that and this got backported. We'll do with just what you PRed, thanks.

**Pull request merged**
