### PR TITLE
add xiphon's GPG key

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by jonathancross** [comment]
Hi, I'm curious, how was this key verified?
Unfortunately I haven't found any signed commits using this key and it isn't in the PGP WOT / has no signatures.

**Comment by xiphon** [comment]
> Hi, I'm curious, how was this key verified?
> Unfortunately I haven't found any signed commits using this key and it isn't in the PGP WOT / has no signatures.

Using two different communication channels.

**Comment by jonathancross** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I am reasonably confident that the account @xiphon here on GitHub as of today is also the owner of this gpg key (8F77 964D BBA3 2419 8D78  A603 BD72 EC6C 3F18 7C67) as he/she/it was able to:
1. Receive email at the address listed in the key.
2. Decrypt a message encrypted to that key.
3. Sign a message of my choosing.
4. Confirm over IRC.
5. Post the signed message to this github account.*

* https://gist.githubusercontent.com/xiphon/e603ad026db2c524028f9710a07b06c7/raw/ac5f993d72ea95f96d0b222938912997a64e0c10/jonathancross
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCAAdFiEEMsk361Pa9SImG35c2FeN+Op8zxsFAl4F6GEACgkQ2FeN+Op8
zxufJQf/c0PzZcVhzWcL6qqFLkm7xYPxoydnG07vaqw14UUTm/iyG/BUeXoyEiDx
35EBcA6h4v1smOWPe9xh1S4wfi7XcnVOfHKxqOjjvoVKl+HR6rWQprLs9Xqsn4Rn
8GVUaNaruyBPR/L0dZyGerSeOx1z6GBWwSsUk8FFkGii5vMnPUS9Tzg/8MH7DDpS
XaoZdXmQ3Q3NOxx+l+HA/TrWK6psh0WLkwD1EJ/DEHOqYjBnVB9hcwZ1dayOymGC
FilN49LVJ+hWYy0oknrWbsM5JX31dtOhJ0iuw4dmeks3MZ6vjjCki1R3uAAbiEQe
Jr4vshSerrz9U0Eqss+ll3Vvee8+Kg==
=PvCJ
-----END PGP SIGNATURE-----
```

**Comment by moneromooo-monero** [comment]
I asked xiphon on Freenode for the fingerprint, and checked it matches the one here. So you'd need to have compromised xiphon at the source, or being able to both (one of break SSL or pwn one of the freenode servers I and xiphon connected through at the time, or pony's server I proxy through) and (break SSL/TLS ot pwn github.com). Or pwn my local machine to make me see different things that are actually posted.

**Pull request merged**
