### PR TITLE
wallet: feature: transfer amount with fee included [RELEASE]

### PR DESCRIPTION
**Pull request by jeffro256**
#8861

### CODE REVIEW

**Comment by vtnerd** [comment]
Does this feature really need to be ported to the stable release branch?

**Comment by jeffro256** [comment]
Why wouldn't it be? It's a useful feature. Are you saying it hasn't been reviewed enough? (True, it hasn't, but then we just don't approve it yet)

**Comment by vtnerd** [comment]
I many projects, new features are not ported to an existing release branch to keep it stable. So I'm asking whether its worth breaking the possible stability of the current release branch for this feature.

**Comment by jeffro256** [comment]
Putting this PR in draft mode b/c I don't want it to be merged yet

**Comment by jeffro256** [comment]
Needs the C++17 PR on release branch to move forwards

**Review by selsta — APPROVED** [review]

**Pull request merged**
