### PR TITLE
monerod: do not log to tmpdir in daemon mode

### PR DESCRIPTION
**Pull request by ston1th**
~~The logging to /tmp/bitmonero.daemon.stdout.stderr caused segfaults if the /tmp mount was full~~ (#2851).

Now the daemon is only logging to /tmp/bitmonero.daemon.stdout.stderr in the debug builds.

### CODE REVIEW

**Comment by leonklingele** [comment]
Can we get rid of `PrivateTmp=true` inside the [systemd unit file](https://github.com/monero-project/monero/blob/ed67e5c001d50a2eea5fa24dfc58eba0921d525b/utils/systemd/monerod.service#L18) then?

**Comment by moneromooo-monero** [comment]
I don't have anything against this, but a segfault on ENOSPC is a bug in the first place.

**Comment by ston1th** [comment]
Since I haven't found anything else writing to `/tmp`, I think we can remove the `PrivateTmp=true`.

**Comment by moneromooo-monero** [comment]
stdout is already closed. It seems pointless to reopen it just to go to /dev/null.

**Comment by ston1th** [comment]
You are right. Fixed it.

**Pull request merged**
