### PR TITLE
cmake: set xcode file type

### PR DESCRIPTION
**Pull request by selsta**

### CODE REVIEW

**Comment by mj-xmr** [comment]
Were there any symptoms/drawbacks on Mac before? Did the source need to get recompiled every time or sth?

**Comment by selsta** [comment]
It fails to compile unless you manually set the source type to assembler. This is for Xcode (IDE) only, not if compiling via command line

**Comment by mj-xmr** [comment]
> It fails to compile unless you manually set the source type to assembler. This is for Xcode (IDE) only, not if compiling via command line

OK, so it works now.

**Review by mj-xmr — APPROVED** [review]

**Comment by selsta** [comment]
> OK, so it works now.

It does not work yet but we are one step closer with this PR.

**Pull request merged**
