### PR TITLE
Blackball N N sized identical rings

### PR DESCRIPTION
**Pull request by moneromooo-monero**
Need 3428 to get merged first

### CODE REVIEW

**Comment by SamsungGalaxyPlayer** [comment]
Putting this here for reference:

"Monero Ring Attack: Recreating Zero Mixin Transaction Effect"
https://eprint.iacr.org/2018/348.pdf

**Comment by NanoAkron** [comment]
Can I ask what you mean by 'blackball'? Is it the same as 'blacklist'?

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by luigi1111** [comment]
@moneromooo-monero please rebase.

**Comment by moneromooo-monero** [comment]
You already merged that one a few days ago AFAICT.

**Comment by moneromooo-monero** [comment]
OK, I seem to have PRed that twice, so closing.

**Pull request closed without merging**
