### PR TITLE
unbound: make this build with openssl 1.1

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by erikd** [comment]
:+1: Now builds for me on Debian Testing.

**Comment by erikd** [comment]
It was building but failing `unit_tests`. With this patch:
```diff
diff --git a/external/unbound/validator/val_secalgo.c b/external/unbound/validator/val_secalgo.c
index 0f4cbe67..9b64974f 100644
--- a/external/unbound/validator/val_secalgo.c
+++ b/external/unbound/validator/val_secalgo.c
@@ -301,11 +301,7 @@ setup_ecdsa_sig(unsigned char** sig, unsigned int* len)
        }
 #else
         {
-               const BIGNUM *r, *s;
                BIGNUM *R = BN_new(), *S = BN_new();
-               ECDSA_SIG_get0(ecdsa_sig, &r, &s);
-               BN_copy(R, r);
-               BN_copy(S, s);
                R = BN_bin2bn(*sig, bnsize, R);
                S = BN_bin2bn(*sig+bnsize, bnsize, S);
                if(!R || !S) {
```
it builds and *passes* `unit_tests` but probably still leaks memory (`R` and `S`).

**Comment by hyc** [comment]
This is an issue for upstream, no?

**Comment by moneromooo-monero** [comment]
Thanks, can you PR that as a git patch ?

It's an upstream thing, yes. Upstream does have a patch to make it build with 1.1, but it's suspiciously different from this, so I think we'd need to update libunbound wholesale in order to be able to use their patch.

**Comment by erikd** [comment]
Just to clarify, you want my little diff as a PR against your branch?

And if the version of libunbound in monero is updated, is this even relevant?

**Comment by erikd** [comment]
Should probably drop this in favor of upgrading unbound, after they fix some bugs I found and reported.

**Comment by erikd** [comment]
PR #2089 upgrades unbound and builds on debian testing.

**Comment by moneromooo-monero** [comment]
If a new version of unbound is imported, and it builds fine with old and new openssl, this patch can be dropped.

**Pull request closed without merging**
