### PR TITLE
fix dependency: put HardFork back to cryptonote_basic, made some BlockchainDB functions virtual again

### PR DESCRIPTION
**Pull request by kenshi84**
Easy (but iffy) workaround for #1851

### CODE REVIEW

**Comment by hyc** [comment]
This patch is too invasive. I would prefer something like this instead:


[dif.txt](https://github.com/monero-project/monero/files/828018/dif.txt)

**Comment by kenshi84** [comment]
@hyc Thank you for the patch.
@moneromooo-monero 
Is this patch something you thought of?
[diff_lambda.txt](https://github.com/monero-project/monero/files/828087/diff_lambda.txt)
Wonder which one is better.

**Comment by moneromooo-monero** [comment]
hyc's patch is fine too. Not sure why the hard fork object/funcptr/methods can't be just in the base class though, but that's a separate thing.

**Comment by kenshi84** [comment]
Now I have better understanding of what have happened in the past:
- `hardfork.cpp` was separated from `cryptonote_core` to a new library `cryptonote_basic` in PR #1626 
- `BlockchainDB::get_block_from_height` was changed from pure-virtual to non-virtual in PR #1727
- Since `hardfork.cpp` uses `BlockchainDB::get_block_from_height` and `blockchain_db` depends on `cryptonote_basic`, shared libs build produces a link error, as reported in #1782 & #1792 
- To solve this, `hardfork.cpp` was moved back to `cryptonote_core` in PR #1804 
- But `BlockchainDB` uses `HardFork::add`, so the link error still persists.

So, another viable solution may be to keep those functions changed in PR #1727 to virtual and keep `hardfork.cpp` in `cryptonote_core` so it can use those functions without linkage symbols. Here's such a patch:
[diff_virtual.txt](https://github.com/monero-project/monero/files/829486/diff_virtual.txt)

What do you think?

**Comment by gubatron** [comment]
I like the `virtual` one better than the function parameter or lambda function parameter work around. However, the patch still might need some work, this happens to me when I try building:

```cmake
[ 66%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o
In file included from /Users/gubatron/workspace.frostwire/monero/src/blockchain_db/blockchain_db.cpp:31:
/Users/gubatron/workspace.frostwire/monero/src/blockchain_db/blockchain_db.h:40:10: fatal error: 
      'cryptonote_basic/hardfork.h' file not found
#include "cryptonote_basic/hardfork.h"
```

**Comment by kenshi84** [comment]
@gubatron Thanks for your feedback. Your compile error looks really bizarre to me, because the patch clearly moves `hardfork.h` from `src/cryptonote_core/` to `src/cryptonote_basic/`:
> rename from src/cryptonote_core/hardfork.h
> rename to src/cryptonote_basic/hardfork.h

And it compiles just fine on my computer. Are you sure that you've applied the patch properly by doing
```
git apply diff_virtual.txt
```
at the repository root?

**Comment by gubatron** [comment]
oh I did `patch -p < diff_virtual.txt`, will try again

**Comment by gubatron** [comment]
```
git clean -f
git checkout -- .
cp ~/Downloads/diff_virtual.txt .
git apply diff_virtual.txt
cmake .
make -j 8
...
```

screen shot 2017-03-09 at 4 21 52 pm

thanks-playa

should I submit a PR with that patch?

**Comment by gubatron** [comment]
Here's the PR in case you wanna merge right away
https://github.com/monero-project/monero/pull/1859

**Comment by kenshi84** [comment]
@gubatron You didn't need to create another PR, I'll just update this one. Also your PR is incomplete in that `hardfork.cpp` was just deleted instead of being moved.

**Comment by kenshi84** [comment]
update done

**Comment by gubatron** [comment]
Thank you guys!

**Pull request merged**
