### PR TITLE
Add hidapi to depends

### PR DESCRIPTION
**Pull request by TheCharlatan**
This pull request is based on #4420 , please merge that first.
The hidapi library is easily cross compiled to windows and mac, so this should fix the depends builds for mac and windows. I have not tested the produced binaries for Ledger Support, this should be probably be done at some point.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
The travis build results can be seen here: https://travis-ci.org/TheCharlatan/monero/builds/432681811?utm_source=github_status&utm_medium=notification

**Comment by fluffypony** [comment]
Please rebase, looks like 4420 was included in this PR

**Comment by TheCharlatan** [comment]
...as stated in the pr description. I'll pull over the changes from 4420 then. That should fix the apple build and leave 4420 with just the travis addition.

**Comment by fluffypony** [comment]
@TheCharlatan I did merge 4420 first, per the description, but it's conflicting despite that

**Comment by TheCharlatan** [comment]
Weird, I first got the notification of your message, then only the merge notice of 4420. Sorry for the confusion.
Rebased.

**Pull request merged**
