### PR TITLE
Added Codefresh.yml pipeline

### PR DESCRIPTION
**Pull request by homdx**
Added Codefresh.yml pipeline

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
What is it, what does it do ?

**Comment by homdx** [comment]
https://codefresh.io/pricing/

This is service for build docker images.
I tested WORKFLOW with Inline YAML Use YAML from Repository

**Comment by moneromooo-monero** [comment]
Can you put it in some directory in contrib please ? This way it doesn't spam the root directory. Moving the docker file would also be nice, not sure why it got added in the root.

**Comment by moneromooo-monero** [comment]
Thanks. The other file can stay if it's causing trouble.

**Pull request merged**
