### PR TITLE
Silence miner debugmsg spam

### PR DESCRIPTION
**Pull request by hyc**
Don't try to allocate the dataset repeatedly if it has already failed.

### CODE REVIEW

**Comment by hyc** [comment]
Supersedes #6221

**Comment by moneromooo-monero** [comment]
One drawback I'm just thinking about is that if you don't have the RAM for it, freeing RAM isn't enough anymore, you've got to restart monerod too.

**Comment by hyc** [comment]
I guess we could change this so the flag only affects the debug msg, and it still tries to allocate every time. But that seems a bit wasteful since after the first failure, most of the time it will fail.

**Comment by moneromooo-monero** [comment]
Sounds like a fair middle ground to me.

**Comment by hyc** [comment]
OK, flag is reset on stop_mining

**Pull request merged**
