### PR TITLE
Account: fix wiping fake spend key

### PR DESCRIPTION
**Pull request by coneiric**
Use secret key member function to wipe the spend key in a watch-only account.
Fixes compiler error about using `memset` on a non-trivial type:
```
/monero/src/cryptonote_basic/account.cpp: In member function 'void cryptonote::account_base::create_from_viewkey(const cryptonote:
:account_public_address&, const secret_key&)':                                                                                              
/monero/src/cryptonote_basic/account.cpp:160:34: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 
'using secret_key = struct tools::scrubbed<crypto::ec_scalar>' {aka 'struct tools::scrubbed<crypto::ec_scalar>'}; use assignment or value-in
itialization instead [-Werror=class-memaccess]                                                                                              
     memset(&fake, 0, sizeof(fake));                                                                                                        
                                  ^                                                                                                         
```

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Didn't that get fixed a couple days ago ?

**Comment by moneromooo-monero** [comment]
Ah, https://github.com/monero-project/monero/pull/3851/files

Your method seems nicer though.

**Comment by coneiric** [comment]
> Didn't that get fixed a couple days ago ?

Oh, I wasn't aware of that. Just noticed when trying to build from v0.12.2.0 tag. If it's already fixed, I can close this PR. Just let me know what you prefer.

**Comment by moneromooo-monero** [comment]
On second thought, I now prefer my version, because we actually need zeroes here, and scrub isn't for zeroing, but for securely wiping the data, and it might as well fill with ff or randoms.
So this PR can be closed, but thanks for the patch :)

**Pull request closed without merging**
