### PR TITLE
Preparations for 0.10.2 tag and release, plus copyright year updates

### PR DESCRIPTION
**Pull request by fluffypony**

### CODE REVIEW

**Comment by NanoAkron** [comment]
Who runs the fallback nodes/where do the addresses come from?

**Comment by fluffypony** [comment]
@NanoAkron known contributors. I run some, the Core Team run some, pools run some, etc.

**Comment by moneromooo-monero** [comment]
The blanket copyright updates on all files is wrong.

**Comment by moneromooo-monero** [comment]
The rest is hard to validate, but ok enough I guess.

**Comment by fluffypony** [comment]
@moneromooo-monero we've done it every year:) If there's an alternative then I'm open to suggestions?

**Comment by moneromooo-monero** [comment]
I think the honest way is to do it for files changed in that year.

**Comment by moneromooo-monero** [comment]
I mean, you can't copyright *nothing*.If a file doens't change for a while, its contents slowly walk towards public domain (in a sane world anyway). Granularity isn't great, but it's better than nothing.
Copyright is loads of years anyway, so you don't risk microsoft legally screwing over that (they can legally screw you in many other ways already)

**Comment by NanoAkron** [comment]
Copyright is also an implicit right so it doesn't need to be declared/asserted in order to exist. So even just the year of creation would probably be ok.

**Comment by anonimal** [comment]
In this case, legally, I don't think updating the copyright date is "wrong" or "dishonest". In fact, a quick review of BSD3 shows that updating copyright date is legally legitimate because of copyright's implicit nature which, in itself, reflects the lifetime of the copyright (as @NanoAkron pointed out). If anything, updating the copyright date to reflect the current year on unaltered files or files *not* updated in current year is a verbose way of saying that the copyright still exists (as it does). So, ultimately, I don't think morality is the question.

Also, as I've pointed out earlier, editing the file in the current year to update the copyright date in order to reflect the current year, if one were to use the current year as an indicator to update the copyright date, would ultimately require updating the copyright year to reflect the new change made when updating the copyright date to the current year 🤣

Referencing https://github.com/monero-project/kovri/pull/539

**Comment by fluffypony** [comment]
Per the discussion on IRC, we can revisit this discussion (perhaps with legal advice from the Software Freedom Law Centre) towards the end of the year, and then decide if we want to do 2018's update differently.

**Pull request merged**
