### PR TITLE
epee: tcp server - set SO_LINGER instead of SO_REUSEADDR option

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Why ? Would this not prevent restarting a server (without waiting) ?

**Comment by xiphon** [comment]
> Why ? Would this not prevent restarting a server (without waiting) ?

Fixed, setting SO_LINGER instead of SO_REUSEADDR. Should fix the restart problem on the OSes that don't handle process shutdown correctly leaving the port in use.

Regarding SO_REUSEADDR issue:
1. Run monerod 
with p2p port 18080, rpc port 18081, zmq port 18082
2. Run another monerod instance 
with p2p port 18080, rpc port 18081, zmq port 18083
3. Expected behavior is the second monerod instance to fail binding p2p and rpc ports. But this won't happen due to SO_REUSEADDR.

**Comment by moneromooo-monero** [comment]
Weird. I'm pretty sure it used to work :|

**Comment by xiphon** [comment]
Updated, have to enable SO_LINGER with zero timeout

**Pull request merged**
