### PR TITLE
DO NOT MERGE - Mac smart mining

### PR DESCRIPTION
**Pull request by revler1082**
I'm just abusing the CI to see if this will compile since I don't have a mach, don't hate me =(

### CODE REVIEW

**Comment by revler1082** [comment]
whoo, something compiled, if someone wants to build the branch on their mac and let me know if it actually runs that'd be awesome.

**Comment by xmr-eric** [comment]
I can give it a shot later today

**Comment by xmr-eric** [comment]
Doesn't seem to work

https://paste.fedoraproject.org/paste/p9u0RCR3Kv858fUlknNM1V5M1UNdIGYhyRLivL9gydE=

**Comment by xmr-eric** [comment]
The fpaste shows me trying it with the last parameter set both to true and false. See line 11 and 20.

**Comment by fluffypony** [comment]
@revler1082 is this still WIP and must stay open?

**Comment by revler1082** [comment]
Yea, I think I know what I have to do, just gotta find some time, I'll try
to get it done by this week or close the PR

**Comment by fluffypony** [comment]
@revler1082 just giving this a little bump - no rush if you haven't gotten to it :)

**Comment by vtnerd** [comment]
I've been ignoring this for no good reason - @revler1082 do you need a tester? I have a Mac Mini here that I could test against and debug on.

**Comment by revler1082** [comment]
Yea I don't have a Mac so I kinda just guessed, I think I got it right, but
I might just need to multiply/divide by 100 somewhere

**Comment by fluffypony** [comment]
Ok waiting on feedback from @vtnerd before merging

**Comment by NanoAkron** [comment]
Should this be closed in favour of #2055?

**Comment by revler1082** [comment]
Yea if he made it work on Mac go for it

**Pull request closed without merging**
