### PR TITLE
simplewallet: do nothing in on_skip_transaction (wallet2 already logs warnings)

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Maybe a MERROR is better here ? It still won't display on the console.

**Comment by stoffu** [comment]
Thanks, updated.

**Comment by leonklingele** [comment]
How often does such an invalid transaction occur to warrant this change?

**Comment by stoffu** [comment]
@dEBRUYNE-1 
I'm also curious which txes cause that message. I've scanned the blockchain from scratch for a certain wallet, and didn't observe it.

**Comment by moneromooo-monero** [comment]
Transactions sent with an early subaddress patch which embedded a zero size extra pubkeys array, which the scanner doesn't like.

**Comment by stoffu** [comment]
@moneromooo-monero 
I also thought so too, but I didn't see the error message even using the release v.0.11.1.
Am I missing something?

**Comment by moneromooo-monero** [comment]
The messages :D 
Ahem.
Did you go over those txes ? If you create a new wallet, it might have skipped them by height.

**Comment by stoffu** [comment]
Grammar nazi :p

@moneromooo-monero 
> Did you go over those txes ? If you create a new wallet, it might have skipped them by height.

I've set the refresh height to 0 and scanned the whole chain from the genesis.

**Comment by dEBRUYNE-1** [comment]
@stoffu I saw a few on testnet, which resulted in me (erroneously) assuming that mainnet would have more (as there are significantly more transactions on mainnet). 

Also, a while ago I noticed a lot of similar looking messages in the log and I might have (again erroneously) assumed that those would now end up in the terminal. 

The root cause of my erroneous assumptions is probably that I have been conflating the "Transaction extra has unsupported format" message with the "transaction <>, unsupported transaction format" message.

**Comment by stoffu** [comment]
@dEBRUYNE-1 

Yeah, admittedly the messages are a bit confusing. The message "Transaction extra has unsupported format" occurs when for example a new field like additional tx keys (for multi-subaddress transfer) is introduced which the wallet can't recognize, while the message "transaction <>, unsupported transaction format" means that the tx has no tx pubkey attached to it, which probably means that the output can't be received and spent by anybody.

For the record, the following is the current list of all testnet txes without tx pubkey:

```
Height 855432, transaction <79c89de5700e796ea6dead9142741a8569ba0154841bf92b95a01064e4b946ad>, unsupported transaction format
Height 855433, transaction <1f921152a002fb1dd8c3aeddfc8a984833646f7282e913747678ccaad068b818>, unsupported transaction format
Height 855434, transaction <6245b9cabc214e4108c425de3a53a47663da2eb7ca09e9e71b74d3f627aa07b8>, unsupported transaction format
Height 855435, transaction <4a9561e2c3fd7af05bda953c3fa7681dc859ded7482ecc1b577413e5e6a04d78>, unsupported transaction format
Height 855437, transaction <6900ad86a1e352e1d0d234ef4e7e8722166f230cd9e2184d3242eb47219da6a6>, unsupported transaction format
Height 855438, transaction <7444886d832c68000f7642e60683321708f4c113500f5c9fc06a6aa6ac4b9899>, unsupported transaction format
Height 855439, transaction <4d49fd6c672dd18588312b5d94c2ddd131458265f8c5dc3fb674316113d519d6>, unsupported transaction format
Height 855442, transaction <339bdfa7aa9ca78a170206cd62c9f512964503953d0c499fe8770fdc6e4ddd75>, unsupported transaction format
Height 855443, transaction <cd9dcf9b14a1062e6580b025ce7a01cd815cb86e7f75b6b949a9af1b53396980>, unsupported transaction format
Height 855444, transaction <fc073a50ef1085fdb4dfb4839a5bc39a533edb415018b6729aa19de1b0f5eff6>, unsupported transaction format
Height 855448, transaction <b8bbb9795efe24213b43aa37f5cc04b19e93c7f46c7e59750af8310430cb9c2b>, unsupported transaction format
Height 855451, transaction <48a035153cd7ceb41f551ba540cc49e7f0be080a65717f0e44adb92854557a58>, unsupported transaction format
Height 855452, transaction <7031493c7256f89a62acf8036ed6982d6b5bc4eb6a4189e5f736d2585b3061bd>, unsupported transaction format
Height 855463, transaction <a152ee9480b78503aca64ae2ea65d035697b14cfd7560e072aa582822bb07f11>, unsupported transaction format
Height 855465, transaction <10771293ee5eee2545257e1d880baa8454959341d41c363054adc346d802d8b1>, unsupported transaction format
Height 855467, transaction <47d4235e9bafc33e4b5f80825b1a8013fc6e78b1662b20694543857be854a716>, unsupported transaction format
Height 855469, transaction <6bb4c933814d67f9e43ffb6cd6ed0338222df21044e69f93b6560df6ad32fef5>, unsupported transaction format
Height 855473, transaction <5200004300cb8dc93ffaa2bc494cf6a7c2d967c12b60171898e5b1d21d381c71>, unsupported transaction format
Height 855474, transaction <110acaa9ec066cd5c4a5718bd3af52a4907ccf3a2846d33585e8387760012fc2>, unsupported transaction format
Height 855477, transaction <02a7d02e23bcc4e7a40e578a60a8f268f39cd6a0a1a1a7f1dd0029dddd188c2c>, unsupported transaction format
Height 855483, transaction <6d0235fc661366bf571943e841d8f288fc14f80d797bf63d751a84194cf24de0>, unsupported transaction format
Height 855484, transaction <c443e17e40060b64b03d11191cbf5ea8e9d1b91b09932c5fa58e785ba663b492>, unsupported transaction format
Height 855491, transaction <46e0521142f26d32cbcf5773a2cdda554393f85d1aac7d0c16a1519072004a1c>, unsupported transaction format
Height 855492, transaction <5ad3fe81aaa53da4ce8e7eddcb3d74464217f7ead0e6bf2808b85156aaeb248c>, unsupported transaction format
Height 855493, transaction <d526f09bb9f674731d1ca63a55c8b11ecee0425f66ce0895a8b6102393224282>, unsupported transaction format
Height 855495, transaction <8adcf94ad58b9bffe31d17e7ab3b2478046ef23b0c713f174db59795bc51e123>, unsupported transaction format
Height 855500, transaction <77284e0581b4dd4aab3952d2fca221a8150b1a83cef939a68026d01d00450f6b>, unsupported transaction format
Height 855848, transaction <c6ac23a0545117903e0a07c33edc29280fede98c86cabc298fc8ca5575f60941>, unsupported transaction format
Height 855849, transaction <f1144c97a12b3f2ff92c584955f8d69a274370eb69913f013468d06dafc268cc>, unsupported transaction format
Height 855857, transaction <96b2de3adb1be3c0a07a31cfc32069b3901e80fea487e49d7362075e41deb197>, unsupported transaction format
Height 855864, transaction <d7def21ac273d861bfa0d1a1d030fac54d7f99197c2759a1d1bfa0680eb3457b>, unsupported transaction format
Height 855867, transaction <c57da920ea38efc8a73ff978e322638c9f3a1f937f15b7cd4a5fdcfa50ec1437>, unsupported transaction format
Height 855868, transaction <191a805b2a46c95f1652c78cf211b447da588b8023cea7ab972ea0a2ec259a4c>, unsupported transaction format
Height 855869, transaction <710bcad7c537d4d5b3856489535ec5ffd4033810d14590216ff67dc1794192d7>, unsupported transaction format
Height 855870, transaction <bc015db20d1fbd1db8bd2f17648ddfce0791017c2dcff37f2b37b69dc22701b3>, unsupported transaction format
Height 855872, transaction <879efd91af91686098a443b6d9898f6b29011d68c82cff3452d8eb295d75169a>, unsupported transaction format
Height 855873, transaction <06b09758860386919ae864c981e76091c9c7f660aa8bb6a722fc7184dcf1a761>, unsupported transaction format
Height 855878, transaction <528201d5a326f881a655dc86d4a609207d408f653d9e07d7ae7966a3c36d6d19>, unsupported transaction format
Height 855879, transaction <5055836f151e780a2fcd8093f3692866846e2bb3df13d24867018ec402c2f2aa>, unsupported transaction format
Height 855881, transaction <e55dd3db0b264cc10c36b38a0d03afd8a81dbce04751458836d5da714c7fb430>, unsupported transaction format
Height 855884, transaction <b2564734a5fd95e4b924ae1a2f808df7ae9d062d5584b2bc068c2c1efc3c2c4e>, unsupported transaction format
Height 855885, transaction <497ba29ce87e27192f52bb53aab2c2f0d9dffa6c276dc335e4d490ff2d8a22d8>, unsupported transaction format
Height 855888, transaction <2906aae5a07367360dbcbe57156b04b098bda45b0b08001ac1cfa373efe1ce83>, unsupported transaction format
Height 855889, transaction <9399b5e549295218f8e2fd58c8cc1aad0b0d981ce1c1c866ebb7f143976808ae>, unsupported transaction format
Height 855890, transaction <8f1399524c79ae57afce3b2b2b34682b2d52735af0f94951cc4dff1f7cf71b94>, unsupported transaction format
Height 855891, transaction <f8432eb9ebf86fefbc7a0ff4574bebf10c012aae687b07142c0cfd3ece32d358>, unsupported transaction format
Height 855892, transaction <32a2c3c37d2d32c5e9c5686bf3e4acbf0f9f8022ae2a9823cab117db99db707a>, unsupported transaction format
Height 855894, transaction <564a18e9f2fa04774d3d453f848bffc2bcb609168e976fba7d4ddb715740b0b4>, unsupported transaction format
Height 855896, transaction <ebc3bad957ef84b9b22e5f1446585f6e9ffbaa2fd0432b8f241b2a6e4329d6a4>, unsupported transaction format
Height 855897, transaction <55a3d7806cfc7c734f7143ecffecb0f175d4d955b6cea5739e4c3062992f67ce>, unsupported transaction format
Height 855899, transaction <8ff069694dca493794abad4dd55f059696487c40bbe3bda5295b4d1ae093b29a>, unsupported transaction format
Height 855901, transaction <90235649dfdc836b28e319d171b186861004564a86ff1e85027aa5c253c858fa>, unsupported transaction format
Height 855902, transaction <caeaf45142c16266affad0708c87be89e8b23b8e17f7da5589a5fa4957b3f204>, unsupported transaction format
Height 855903, transaction <4144a93e35e23c410bbe58d3117b91b1554ee6aa338746bcd236537117db6037>, unsupported transaction format
Height 855906, transaction <f1ad7e5e92402e44af4e0225aa3b23215f9309cf7dbc31ae548cba6b3ffdd9ed>, unsupported transaction format
Height 855907, transaction <3878660f5c72ef12bdccd77f8069a71420aded166a3bd362984ca7284c075a2d>, unsupported transaction format
Height 855908, transaction <5c1ebb4ad62b948b55fc1b861463d3cffcb3b26d6f6c6d8b4f39c4173a09f655>, unsupported transaction format
Height 855909, transaction <46c8bc3eccc4ff9a7e795fa205bcd3bf0bde9fe62388cf21febfd828020ac913>, unsupported transaction format
Height 855910, transaction <31227785c5cd729575fe6ce808ebb0a30856e64acecd53ca32d9040af9a94a86>, unsupported transaction format
Height 855912, transaction <afa72ae977f4e548f9371fe7697045ca0f1e3ef349a995b5b3ed01183774543e>, unsupported transaction format
Height 855913, transaction <3c8c50de752f5c8b9d562a9799d5e2d8870fabc0a1ba49a5bb807bad216df5c8>, unsupported transaction format
Height 855914, transaction <eb7a24be7216ffce7236b5d82de500aa85ed814d187696cb64681e8e147d4272>, unsupported transaction format
Height 855915, transaction <a228811e63d58489bada3a434da5f82e93cdc6d4d05a16e2239bb421eb32c604>, unsupported transaction format
Height 855916, transaction <7cb884b31357a9bdd3fe85a60a8d9b689f074831aac0390ca2578788bd4b302c>, unsupported transaction format
Height 855917, transaction <4d08c2c013d53c59b34abd5ac4a83ee52d098fb0c868d6a7a23ac878f74888b8>, unsupported transaction format
Height 855918, transaction <5c2967755d2c9d14aa8dff6277564a7f12fd74a580abb71a19a6a47cbbf48db9>, unsupported transaction format
Height 855920, transaction <a57cc68074dbd9bd0c3392bedbe53d2990001a4c18ba37d8a212395427a3b3d2>, unsupported transaction format
Height 855922, transaction <515f0179e13cfa80aff387b470d6a5459ffbffaba7b08dd0e08de0d4e1e1e7bc>, unsupported transaction format
Height 855923, transaction <d5ede4a7d8f35c0463ea359a74916ef379531d56a29181bb9346bd9b45060d5c>, unsupported transaction format
Height 855925, transaction <a768a65ae23b6b5083733636c0edcdd4eedb7216b6cc2ab5cfc5c146139b1a0f>, unsupported transaction format
Height 855926, transaction <c0e563752e8c68ebb5bcff372c539a8823b118e4df7a05ecb98f3823e690fe3a>, unsupported transaction format
Height 855927, transaction <e9f5b7176c820509463db191884e9debdf907d442b0c77f51fa639b0a762dee1>, unsupported transaction format
Height 855929, transaction <f4fc117edb83feacb4af4914f887dc4379fa8b7aafd9fcc194b4eb878ca862ed>, unsupported transaction format
Height 855930, transaction <b425e89eb6af4566d49ca89247a3d72c3cc0b084bcf0ba57ecde7dd8b9d4f669>, unsupported transaction format
Height 855931, transaction <6ad8614bd793246df562b19bcdc6d6d647418c0f4ea0298d390d6b35b2da3548>, unsupported transaction format
Height 855932, transaction <232e9741c8e0f231d0588c463a34d601e27d6929a711fc3606a1a63a5474d8ec>, unsupported transaction format
Height 855933, transaction <5f617debce035c77c34fe2021f93db015d73ba7ad464032272d882586ca5f52e>, unsupported transaction format
Height 856059, transaction <3dfbda7b288e727cbc88bab29f85a4e668d0fc4aeffb972994bd2e91a4ff53ef>, unsupported transaction format
Height 856062, transaction <4b1338b22b7e782b0183e3d9d1d324f639c6c934b627bfdc5ea69af948b48780>, unsupported transaction format
Height 856064, transaction <c57c383771091a1a80d7c6bdf3fbc71af590e40bac7fb60d34cb5a79df962f01>, unsupported transaction format
Height 856066, transaction <cb1363e5f2905983b0a96efca9fb253946d47952a82bc0475658b0438fb9f0c6>, unsupported transaction format
Height 856067, transaction <29bbbb539cf3db82cbb2e2eebcd64fbf750a3d01732c50272c61ef50cccf84e1>, unsupported transaction format
Height 856068, transaction <46719332af25a28f103c53872a43df5d44bdd74e0aea2aee4b1bfbcc7ec975ac>, unsupported transaction format
Height 856069, transaction <5caf35ed5835726720ee66a69fa6b3e0fa6c14f74c675acf00bb462bc223044a>, unsupported transaction format
Height 856071, transaction <3ed14e4854f472b01569973a91a6628f28e7230993364d01b77925b470adedaa>, unsupported transaction format
Height 856072, transaction <eb394a05722c15810f7d3b28f2aae1702a099e8565b3c81073a5a596697c8c7e>, unsupported transaction format
Height 856073, transaction <36dcb181ce11a1a50327c99ddf30b910f518a650ceffb296c5b044f7f0115332>, unsupported transaction format
Height 856074, transaction <dc6b7c4145707a846afcf71a8d0863d3695236e495914db0b19a1b6903b95dd6>, unsupported transaction format
Height 856075, transaction <c10d31e3780a3149036bc7b85bdf3e180f8ffb470dd327594726f201c1e16f58>, unsupported transaction format
Height 856076, transaction <d7045ec4d301b682ad45ffbfeef930889caad49fb37b2a59d46f4ed36c5136a1>, unsupported transaction format
Height 856078, transaction <c65df4a35ab9b40fed65c8bde488f703b886914d1adc95855f4cb0ae246229cb>, unsupported transaction format
Height 856079, transaction <4a425e914fd7a743152b8b05213fbea3f2264e2ed708ae1b0760f76f72b60fe3>, unsupported transaction format
Height 856083, transaction <0f27a02815c04167ff1b6c20a8ada96553cfc87317f402706e4dcefddd8eeb8b>, unsupported transaction format
Height 856084, transaction <6b07a6c71e79d1eb718aed10e8f355eb17fced83cdd81c388f06b1c9fc333adf>, unsupported transaction format
Height 856085, transaction <817f4e4e4eef6751b3305fb43cac37eb38611e1f3363118d58f19db7700354f0>, unsupported transaction format
Height 856086, transaction <a58aa0ab6f0367c7667be1e1d06c89afe3c9ba3f3c4be6455fb64046f668c95e>, unsupported transaction format
Height 856088, transaction <0acefa30619930d52a279df58a95c7f0a783e04b2e1cdc46c71a68403a853e9d>, unsupported transaction format
Height 856090, transaction <437950837302d5530d67172cad78b5f18f9dcaae85b64c985925c4a906c5045b>, unsupported transaction format
Height 856092, transaction <25afdf415f37090e3bc2880fcefda4bb39004e816acd5d67739c18ea8a37186e>, unsupported transaction format
Height 856093, transaction <6a19a22fd0d36c783c9afb450cb1f7375dd80cc1356d2e57e393844b15785a08>, unsupported transaction format
Height 856094, transaction <f2fe4077e6abee5ab91057d41b9bca92829c3f1b2c0590bf5e201392199ee77d>, unsupported transaction format
Height 856095, transaction <3b817026b876e0dbf1a3b18c0ed59324d189fb8fd82abdd2c30f6f3a9e2378ca>, unsupported transaction format
Height 856096, transaction <a59edf2ff6eaf96c806311311055d9bba0eab986bcc42a0b6c5819046c756026>, unsupported transaction format
Height 856097, transaction <2cef7ca24ae86e0faa9e4ec94b960d67e5a6f7479e492303c7b29d1f4ad9ecb5>, unsupported transaction format
Height 856098, transaction <c34c17ec126eb484cb8d70e2c953632555bf7a6caada0df2a81af2b78581a11c>, unsupported transaction format
Height 856099, transaction <773f7d3179f1877bc8a9308b1e8669441ed2fa56003f17a91ad90ac7d8e5129a>, unsupported transaction format
Height 856100, transaction <9e0a1dedd4ea35f1acd85ea178e6a01cdf6c5ce9c6997d98b55bb88328c1b2f1>, unsupported transaction format
Height 856101, transaction <024222da30118033f2512940602f7a13a1ea201ca5b1137a5b68bb1c8875f528>, unsupported transaction format
Height 856102, transaction <3a41817f44e64b37c6eec65b7b722d295183abdd790fe2ec150fb71ce727d220>, unsupported transaction format
Height 856103, transaction <82e847a25811fd6ed09258b84dc9e098bc1ab8cbe6d7572de2328bda25acdbbb>, unsupported transaction format
Height 856105, transaction <75a9d1dd7d944973e6a298430d1c532397245ced62b43682a1f05febad1928c1>, unsupported transaction format
Height 856107, transaction <3bd4d7d02e0a997e7e970df39dad3f4182de5c6bacc8f6b9a95384fc61ac8341>, unsupported transaction format
Height 856109, transaction <ec383a1b5bcd876364c72147aa2da45a6d8a1efba74805f3e621d9a5f448b62a>, unsupported transaction format
Height 856110, transaction <258dfc05b24bab767be9a330310c83c8964d476ce909b900a83c081186dda9f8>, unsupported transaction format
Height 856111, transaction <e8ad1dd7f9cf56153d0a754c2d132c9ff4401ad7cce86ac6ac1f5aeda6f69f7c>, unsupported transaction format
Height 995050, transaction <61c625f82c458f862cbd5e076443da7e9e371efa519f54fb3eab27ad99f3a86f>, unsupported transaction format
Height 995437, transaction <93278cde512ceeb6d2a8f102d3014c7253d9208de2c63362e37d4a92ee520a7e>, unsupported transaction format
```

**Comment by stoffu** [comment]
@moneromooo-monero 

I realized that wallet2.cpp also has this log message

```c++
      LOG_PRINT_L0("Public key wasn't found in the transaction extra. Skipping transaction " << txid);
```
just before the call to `on_skip_transaction`. As a result, the log will have messages like:
```
2018-02-14 22:54:51.423	  0x7fffbb9033c0	WARN 	wallet.wallet2	src/wallet/wallet2.cpp:1072	Public key wasn't found in the transaction extra. Skipping transaction <5f617debce035c77c34fe2021f93db015d73ba7ad464032272d882586ca5f52e>
2018-02-14 22:54:51.423	  0x7fffbb9033c0	ERROR	wallet.simplewallet	src/simplewallet/simplewallet.cpp:3193	Height 855933, transaction <5f617debce035c77c34fe2021f93db015d73ba7ad464032272d882586ca5f52e>, unsupported transaction format
```
which seem a little redundant/spammy to me. How about removing the message altogether from simplewallet?

**Comment by moneromooo-monero** [comment]
Sure.

**Comment by stoffu** [comment]
@moneromooo-monero 
OK, updated.

**Pull request merged**
