### PR TITLE
p2p: init hashes after deserializing a network address

### PR DESCRIPTION
**Pull request by moneromooo-monero**
Fixes multiple connections to the same address

### CODE REVIEW

**Comment by vtnerd** [comment]
I think this is a flaw of the class itself - the member variables should not be public (fragile interface). You can serialize two local variables on the stack, then do `na = epee::net_utils::ipv4_network_address{ip, port}` instead.

Alternatively, I would like to temporarily drop the `fnv1a` hashing code and store just ip/port in the base class. There is no other implementation currently so it saves CPU and memory while protecting against a fnv1a collision. I am not aware of any obvious collisions but ip+port is 48 bits so the probability is a bit higher than I would like.

I already have a patch + tests if you can accept it ... how to handle i2p addresses can be determined later. I think the space in the base class can be better utilized regardless.

**Comment by moneromooo-monero** [comment]
I2P addresses don't have a uint32_t ip, that's why this is not in the base class as there will be an I2P network address class at some point. Why would be the point of saving CPU cycles and space if it prevents the goal of why this was done ?

If you're concerned about a collision, then maybe the ipv4 class could just copy ip/port into the hash, with the other bits zeroed.

Not sure creating the class from data is easily doable, you could do a placement new I suppose, that might indeed be better...

**Comment by vtnerd** [comment]
>I2P addresses don't have a uint32_t ip, that's why this is not in the base class as there will be an I2P network address class at some point. Why would be the point of saving CPU cycles and space if it prevents the goal of why this was done ?

Currently there is no implementation for I2P addresses. I am not suggesting reverting this patch entirely, just changing the base class to only use 64-bits with the derived class using no additional space. Determining how to use the I2P class effectively can be determined later.

> If you're concerned about a collision, then maybe the ipv4 class could just copy ip/port into the hash, with the other bits zeroed.

This is closer to what I was thinking. The ipv4 derived class does not need any data members. We are probably better off dropping inheritance entirely in favor of an enumerated field + generic storage for a custom variant. Its fairly easy in C++11 to do this correctly.

> Not sure creating the class from data is easily doable, you could do a placement new I suppose, that might indeed be better...

Placement new is not needed. The class currently has a default copy-assignment constructor which does the equivalent of a `std::memmove`. The code snippet I provided previously will work directly. It is preferable because forgetting to call `init_ids` when changing public variables is going to be a common issue.

**Comment by moneromooo-monero** [comment]
I meant making the hash a bit copy of ip:port:0. But hey, maybe I'll like your code if I see it. Post the patch you said you have ?

**Comment by vtnerd** [comment]
See https://github.com/monero-project/monero/pull/2332

**Pull request merged**
