### PR TITLE
Remove 1.25x multiplier from tx_pool

### PR DESCRIPTION
**Pull request by NanoAkron**

### CODE REVIEW

**Comment by dternyak** [comment]
FYI: Wallet changes were merged here: https://github.com/monero-project/monero/pull/2022

**Comment by NanoAkron** [comment]
Maybe after enough of the network has updated to 0.11.0

**Comment by NanoAkron** [comment]
@moneromooo-monero good point. Will try to implement.

**Comment by moneromooo-monero** [comment]
Oh, that's right, it's bypassed for txes from blocks. Nevermind then, ignore my comment. The one in 2022 is already in ?

**Pull request merged**
