### PR TITLE
workflows: don't build PRs if only docs and READMEs are being changed

### PR DESCRIPTION
**Pull request by erciccione**

### CODE REVIEW

**Review by moneromooo-monero — APPROVED** [review]

**Review by mj-xmr — APPROVED** [review]
Great idea. The syntax change will allow for easier integration (coexistance) of build scheduling.

**Comment by mj-xmr** [comment]
While we're here, could you please also add this to `depends.yml`?

**Comment by selsta** [comment]
ping @erciccione

**Comment by erciccione** [comment]
Sorry, i forgot this PR. Done same for `depends.yml`.

**Review by selsta — APPROVED** [review]

**Review by mj-xmr — APPROVED** [review]

**Comment by mj-xmr** [comment]
@selsta @luigi1111 : Any chance of merging this? It's completely harmless for parallel developments.

**Pull request merged**
