### PR TITLE
Remove infinite loop in refresh code

### PR DESCRIPTION
**Pull request by Jaqueeee**
This reverts commit fd181b03bb58a8b0628d2af8637cf6bb968fc437.

https://github.com/monero-project/monero/pull/1197 can cause an infinite loop together with #1404

### CODE REVIEW

**Comment by NanoAkron** [comment]
Is there any way to accomplish the goal of #1197 without this risk?

**Comment by Jaqueeee** [comment]
@NanoAkron Yes, probably. But i don't have time to debug it right now. ping @revler1082

**Comment by revler1082** [comment]
My bad everyone, I'll try to get to it today after work =)

**Comment by moneromooo-monero** [comment]
ok

**Pull request merged**
