### PR TITLE
abstract_tcp_server2: fix crashy race on socket shutdown

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by vtnerd** [comment]
What happens with non-SSL connections? This should be trying to do a SSL shutdown sequence, even for non-SSL connections.

The description also indicates that some bug crashes the process. I don't see why an improper SSL shutdown would crash a crash. Are there more details about this?

**Comment by moneromooo-monero** [comment]
https://svn.boost.org/trac10/ticket/7611

The socket was closed too early, while other async ops were in progress.

If you don't like it, the close() call can just be removed, to be as it was before the SSL patch.

**Comment by vtnerd** [comment]
I fail to see how this fixes the issue you describe; the SSL and TCP objects are listed as thread un-safe. If the shutdown methods are accessing the object while other async operations are being queued/processed, then the behavior is different yet still undefined. If we are lucky this change masks the issue in most/all cases. Correctly fixing looks like it could be some fairly heavy work - acquiring the send lock before shutdown will at least improve things a bit (assuming all paths into shutdown never hold the lock currently).

BTW, this _might_ work with non-SSL connections because the current ASIO implementation filters out some calls to `SSL_shutdown` . The documentation doesn't list this behavior, so there isn't much to "rely" on here.

**Comment by moneromooo-monero** [comment]
If it does not want close to be called when there's any pending R/W, then is there a way to cancel those ? The docs don't mention one. They say the async op continues until buffers are full or an error occurs, which means we might get quite a long time if a connection is timing out.

**Comment by vtnerd** [comment]
I have never used `asio::ssl` so I didn't catch this issue during review unfortunately - `asio::ssl::stream` differs from `asio::tcp::stream` in that all async operations must be within a "strand" according to the documentation. So, with scant documentation, there is actual thread-safety of the asio object and thread-safety of the subsystem (OpenSSL, OS handle) object that asio is using. Since OpenSSL does not have a thread-safe handle, our external locking implementation here will not work.

I'm not sure what I would recommend here. Fixing the server code completely for SSL usage will be a decent overhaul. If a stranded implementation cannot be managed by next tagged/binary release, the best action is probably to disable SSL on the server side for that release branch. The client code should be acceptable since (I think) it is single threaded.

As for this PR here, I'm not sure if this is beneficial or not. If it fixes some use case you have, it might be worth merging, but another issue will have to be immediately opened either way. And I would recommend only calling `sock_.shutdown` if SSL is in use on that socket.

**Comment by vtnerd** [comment]
So I somehow missed that the server is _partially_ using an asio strand. Work needs to be done to ensure that all calls to the ssl stream are done within the strand. Its still a bit messy since there are callbacks from multiple locations.

**Comment by moneromooo-monero** [comment]
I have no idea what strands do. As so much in boost, it seems to be tell you roughly what it does, but the details are arcane. AFAICT it ensures all calls are made from the same thread, right ? There are two async read/write calls which have this disabled, I have no idea why (they were that way originally).  Are you saying these should get their strand-ishness enabled again ? Plus the close() calls ?
I'll change the shutdown on socket_ to be only if ssl is enabled for now then.

**Comment by vtnerd** [comment]
> I have no idea what strands do. As so much in boost, it seems to be tell you roughly what it does, but the details are arcane.

And there doesn't appear to be a ton information about strands. [Someone wrote](http://www.crazygaze.com/blog/2016/03/17/how-strands-work-and-why-you-should-use-them/) a blog post about their own strand implementation, and it sounds close to the ASIO implementation.

> AFAICT it ensures all calls are made from the same thread, right ?

ASIO only guarantees that the callbacks are **not** executed concurrently. So the callbacks may execute on different threads, just not at the same time. ASIO has a lock internally to handle the behavior. However, unlike having locks in our code, ASIO "knows" about strands and will "defer" a callback for later execution if it will block. ASIO also acquires the lock before doing its sys/OpenSSL call, which is important for the later case. ASIO also "knows" whether the current callstack is "in a strand", so calling `strand.dispatch(foo{})` will: (1) call `foo` immediately if execution is in a current strand callback, (2) acquire the lock and call `foo` immediately if the strand is not "blocked", and (3)  "queue" the call to `foo` if it will block. So its usage can help with throughput since nothing blocks a thread, with the downside that its typically more difficult to get correct than blocking code (the usual problem).

>  There are two async read/write calls which have this disabled, I have no idea why (they were that way originally). Are you saying these should get their strand-ishness enabled again ? Plus the close() calls ?

Yes, for SSL usage it appears this will be necessary. If I had to guess, they were disabled due to some deadlocking issues since our code has locks too. These locks within our code may also be unnecessary, but that analysis is a little more complex.

The calls to close/shutdown will not have to wait until the async read/writes completed, just until the strand is no longer blocking. `strand.wrap` does not require that the events happen in queued order, just that the callbacks are done in the same order as their completion. So if the call sequence is async_read->async_write->async_close but the OS marks their readiness in read->close->write order, the latter is the order that the callbacks are invoked.

**Comment by moneromooo-monero** [comment]
I'm now running a node with the first close() called only if SSL is on, and the two extra async calls in the strand. I'm going to chicken out of anything else unless some crash or other infelicity shows up, since I don't really know what I'm doing with ASIO.

**Comment by moneromooo-monero** [comment]
It's been running good here (though without incoming connections) so far. Pushed.

**Pull request merged**
