### PR TITLE
Fix test for 'ARM_ID' as caught by @radfish in #1088

### PR DESCRIPTION
**Pull request by NanoAkron**
This fixes the detection and assignment of ARMv6 and ARMv7 according to ```${ARCH}``` in CMakeLists.txt

Is there any way get Travis to test against ARM boards? Donating to get a room full of different systems set up somewhere would be cool.

### CODE REVIEW

**Comment by radfish** [comment]
Cool, thx for PRing this before it got forgotten. LGTM.

**Comment by NanoAkron** [comment]
You're welcome :)

**Comment by fluffypony** [comment]
@NanoAkron yes - @danrmiller is on it, that's why we're switching from Travis-CI to buildbot

**Comment by NanoAkron** [comment]
Nice :)

**Pull request merged**
