### PR TITLE
Fix broken build + refresh language files

### PR DESCRIPTION
**Pull request by erciccione**
Build error solved changing a couple of strings from `[<payment_id>]` to `[payment_id]`.

Refreshed using a tweaked `build-translations.sh` script

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
That doesn't seem right. Looks like something failed to convert < to &lt; etc.

**Comment by erciccione** [comment]
@moneromooo-monero I checked the file as best as my knowledge but couldn't find what the error was referred to. I remembered this happened in past so i changed directly the .ts file. Also, the troubleing strings seem to disappear after the refresh. Btw  when running the `build-translations.sh` script i get some `: tr() cannot be called without context`. Don't know if related

**Comment by moneromooo-monero** [comment]
The second < above was ampersand l r semicolon but github mangled it to <.

**Comment by ordtrogen** [comment]
Hold on a second, I'm writing a comment to this. Be ready in a minute ...

**Comment by ordtrogen** [comment]
Two comments:

1.  @erciccione you mention changing the .ts file directly but doesn't that go against the idea that the localizable strings are extracted from the source to create or update a .ts file by running some combination of the lupdate program with the generate_translations_header.c and CMakeLists.txt in monero/translations  ?

2.  I've posted this comment as an image as it's tricky to get angle brackets and other markup information to display correctly when entered into an field in a web page:


image

**Comment by erciccione** [comment]
@ordtrogen 

1. It does, but, as i said, the lines that were breaking the build get removed after the refresh (de397e3). So yes, it's very ugly to edit directly the .ts files, but in this case has no side effects. Btw, as i pointed above, there is certainly a problem when building the .ts file, but this can be fixed in another moment and it's not a priority for me right now.

2. You are correct, and this structure is consistent wit the rest of the file, but as for the reason in the point above, there's no need to edit. The two lines for `sweep_all` and `sweep_below` are correctly built at the line `1518` and `1528`

**Comment by moneromooo-monero** [comment]
If refreshing the files fixes the problem, why bodge them ?

**Comment by erciccione** [comment]
Because wasn't possible to refresh without removing those `<>`. I don't see the problem here, but i can squash those commits in just one if this makes this PR look cleaner @moneromooo-monero

**Pull request merged**
