### PR TITLE
Update License to exclude government use

### PR DESCRIPTION
**Pull request by pavoltravnik**
Government entities are considering ban of anonymous cryptocurrencies. It is possible by author to restrict use of the source code based on civil law. This should be seriously considered due to multiple legal reasons. We should not be prohibited to use anonymous cryptocurrencies. If governments are thinking about ban of anonymous cryptocurrencies, they should be legally deprived of option to use anonymous coins first. "Nevertheless, it would be worthwhile to consider introducing a ban. If authorities then bump into the prohibited activities, they have a legal basis for prosecution, insofar not yet available. Possibly, imposing a ban could also have a deterrent effect." Source: http://www.europarl.europa.eu/cmsdata/150761/TAX3%20Study%20on%20cryptocurrencies%20and%20blockchain.pdf

### CODE REVIEW

**Comment by LordMajestros** [comment]
What exactly does this achieve? How does that help adoption, promotion or decentralization? Is this just to prevent government snooping using nodes of banned currencies? I'm actually curious. Please explain.

**Comment by pavoltravnik** [comment]
Government will not be able to legally use blockchain analysis, use or spend forfeited coins or use monero ledger as evidence in criminal proceedings. This is actually legal hack, which is overcomplicating legal process when government is involved. I know, that many of us are fans of open source software, but for me personally, this could be great advantage to use monero, when I consider as lawyer consequences of such restriction of use.

**Comment by LordMajestros** [comment]
I'm not very knowledgeable legally. I'll need to gather some opinions to form one myself. However I don't think this stops governments from acting outside the law as they typically do. In any case this needs visibility @fluffypony , @SChernykh @moneromooo-monero  thoughts?

**Comment by LordMajestros** [comment]
And the question on authorities preventing criminal misuse of blockchains and cryptocurrencies is still valid. Does this not preclude them if it works (with monero and monero code at least) from legally doing so?

**Comment by pavoltravnik** [comment]
I understand, that this could be very political move and should be considered very carefully. However I consulted this in multiple occasions and I see it as right move to protect my privacy against unproportionally and well equipped party in legal proceedings.

**Comment by moneromooo-monero** [comment]
This software is free to use for everyone :)

Moreover, we cannot change copyright on existing code. All we could do it change copyright to *new* code. All someone would need to do to comply by such a new licence is rewrite that new code - admittedly that might be a fair amount, depending on what the party would want to rewrite.

**Comment by LordMajestros** [comment]
That settles it then. It's not feasible.

**Comment by moneromooo-monero** [comment]
I, for one, welcome governmental use of Monero. The more the merrier. Protecting pecuniary privacy for people, whether vaunted virtuous vanguard of the future, or venal vassals of vacuous vampiric vandals.

**Comment by fluffypony** [comment]
Is there something the EFF or similar have published indicating this “hack” is even remotely plausible? Sounds like the EOS constitution; entirely unenforceable.

**Comment by SChernykh** [comment]
This will have little or no effect at all. Most countries have a priority of their own laws over any licence agreement. Whatever we write here will be legally void to them if it contradicts their law.

**Comment by SChernykh** [comment]
@pavoltravnik "it will be a breach of law" Law is not a constant: if a government decides to ban private crypto, they'll for sure fix this little issue with the new law. You can't win on their field.

**Comment by SChernykh** [comment]
If the new law, for example, declares Monero source code "a malware/forbidden to use", will it need author consent to be used? Of course no.

**Comment by pavoltravnik** [comment]
@SChernykh You changed a topic. Topic was if author can legally exclude the government from the use of the source code. It is possible from my point of view and other lawyers as well. Ban of cryptocurrencies is impractical end will not be successful.

**Comment by SChernykh** [comment]
> Topic was if author can legally exclude the government from the use of the source code
Today - yes. In the future - no. If the government really wants something, laws will be changed. Monero shouldn't rely on legal texts as a layer of protection.

**Comment by pavoltravnik** [comment]
@SChernykh Monero definitely shouldn't rely on it, sure, but why it shouldn't benefit from it? For me it is very simple change with huge potential in future legal cases. Unfortunately, these legal proceeding exist in reality and if 3 lines of code could change the outcome of it ...

**Comment by fluffypony** [comment]
@pavoltravnik the language used doesn’t sound like a lawyer looked at it at all.

**Comment by thomasvaughan** [comment]
From the United Kingdom's [_Copyright, Designs and Patents Act 1988_ Part I Chapter III (Public Administration) Section 50](http://www.legislation.gov.uk/ukpga/1988/48/section/50):

> **50  Acts done under statutory authority.**
> 
> 1. Where the doing of a particular act is specifically authorised by an Act of Parliament, whenever passed, then, unless the Act provides otherwise, the doing of that act does not infringe copyright.
> 2. Subsection (1) applies in relation to an enactment contained in Northern Ireland legislation as it applies in relation to an Act of Parliament.
>  3. Nothing in this section shall be construed as excluding any defence of statutory authority otherwise available under or by virtue of any enactment.

**Comment by pavoltravnik** [comment]
@thomasvaughan - not section you provided but this one paragraph is crucial "Copyright is not infringed by anything done for the purposes of parliamentary or judicial proceedings."
https://www.legislation.gov.uk/ukpga/1988/48/section/45
So I am closing this pull request.

**Comment by pajasevi** [comment]
As much as I would like to agree, this does not comply with the open source software license rules https://opensource.org/faq#evil

**Pull request closed without merging**
