### PR TITLE
patched parameter type bug that was causing failure on 32 bit (#1207)

### PR DESCRIPTION
**Pull request by revler1082**

### CODE REVIEW

**Comment by NanoAkron** [comment]
Why only this one?

**Comment by revler1082** [comment]
I'm guessing on 32 the uint_64 isn't defined the same as size_t so the linker wasn't finding the get_blocks symbol which uses size_t? Also, because I suck ;)

**Comment by moneromooo-monero** [comment]
That's weird, I don't get why this'd break. That seems like a compiler bug, but maybe I'm missing the trick... But the patch is fine.
Also, I left a few comments on the original PR, which got merged before I had a chance to see it.

**Comment by NanoAkron** [comment]
Just thinking further, does declaring this as size_t fix the issue in the same way?

**Pull request merged**
