### PR TITLE
[DO NOT MERGE] blockchain.cpp make timestamp increase over time

### PR DESCRIPTION
**Pull request by Gingeropolous**
changes timestamp check from < to <=

### CODE REVIEW

**Comment by vtnerd** [comment]
This is a consensus rule change, so we'd have to be careful about when/how this gets merged. We have to first test against historical data, and possibly guard against data near a fork. As in the check _may_ need to differ depending on "fork side".

The variable claims this is the median, not average. I recall this being the case, but I'd have to rescan this logic to make sure. It should be possible split consensus before the next fork. Those that upgraded their clients (in preparation for the fork) would be one side, and everyone else on the other.

What prompted this patch? Was someone concerned about timestamps never progressing? Even with this patch timestamps can move only 1 second at a time.

**Comment by Gingeropolous** [comment]
@vtnerd 

> What prompted this patch? Was someone concerned about timestamps never progressing? Even with this patch timestamps can move only 1 second at a time.

There was (and may still be) an attacker on the randomx fork of testnet. Someone was mining with the same timestamp repeatedly. Last I checked, they had mined upwards of 500 blocks with the same timestamp. This caused the difficulty on this testnet to grow from ~20 kh/s (when I assume the attacker started) to over 841 kh/s in a matter of days, with blocks taking over 10 hours to be created by the attacker (so still probably mining with less than 20 kh/s). 

There are various viewpoints on the attack, namely questioning the reality of such an attack that requires >51% of the hashrate. 

However, my counterpoint is that 51% attacks remain a real possibility as long as our network is secured by PoW, and therefore we should make these attacks as costly as possible. This hack (mining with the same timestamp) effectively decreases the amount of time necessary to render the blockchain useless. 

That being said, my amazingly succinct commit of 1 character isn't a perfect fix, as you stated. Here, time can only advance by 1 second at a time. 

All this being said, Bitcoin has similar logic - they check that a new block timestamp is greater than the last one.

**Comment by Gingeropolous** [comment]
due to the consensus rule nature I edited the title to include DO NOT MERGE

**Comment by stoffu** [comment]
I think this change doesn't add any real benefit and only introduces extra unneeded complication to the consensus code. The gist of the suggested vulnerability is that the attacker would set his blocks' timestamps as low as possible allowed such that the denominator `<time_span>` in the difficulty calculation

    <next_diff> = 120 * <total_work_during_time_span> / <time_span>

is minimized, thus increasing the next difficulty as fast as possible. The minimal value for `<time_span>` is currently 1 thanks to the zero check (so there's no worry about divide-by-zero error). The proposed change intends to force the minimum possible value for `<time_span>` to increase so that the rise of the difficulty in the above attack is lessened. But in practice, requiring the block timestamp to be at least as late as the previous 60 blocks' timestamps median **plus one** doesn't really change things much. Here's a javascript demonstration of my point:

```javascript
function median(vec) {
  var tmp = vec.slice();
  tmp.sort();
  var n = Math.floor(tmp.length / 2);
  if (tmp.length % 2)
    return tmp[n];
  else
    return Math.floor((tmp[n-1] + tmp[n]) / 2);
}

var timestamps = [];
for (var i = 0; i < 60; ++i)
  timestamps.push(i*10 + Math.floor(Math.random() * 100));

console.log(timestamps.slice());

var num_iter = 60;

for (var i = 0; i < num_iter; ++i) {
  var m = median(timestamps);
  // timestamps.push(m);       // current
  timestamps.push(m + 1);   // proposed
  timestamps.shift();
}

console.log(timestamps);
console.log(Math.max.apply(null, timestamps) - Math.min.apply(null, timestamps));
```

As you increase the `num_iter` value, the `<time_span>` value becomes smaller and smaller; usually 1 or 2 when `num_iter=90`, depending on the initial state.

**Comment by Gingeropolous** [comment]
probably not a real problem, and this isn't a real solution to the probably not problem.

**Pull request closed without merging**
