### PR TITLE
Fix mempool key image meta bug

### PR DESCRIPTION
**Pull request by vtnerd**
@binaryFate 

I found this with further testing of the split mempool. I broke this into its own patch and tests because the changes in the split mempool make it harder to see the changes a bit.

I _think_ this is the intent based on the [original commit message](https://github.com/monero-project/monero/commit/10013e94342c0d9ca2f10c79779b08affc5209c1).

### CODE REVIEW

**Comment by vtnerd** [comment]
Sorry, this wasn't a privacy bug so I changed the title. The issue was that key images weren't showing up (in the core tests) - although it was likely fine when taken as a whole system. Also I changed the control because I thought it was slightly easier to read, let me know if I should revert.

The reason why I wanted to highlight this separately is because this will shortly become a check against anonymity, stempool, and do_not_relay transactions (assuming this behavior is correct).

**Comment by moneromooo-monero** [comment]
I don't see the bug. You just changed the logic to use do_not_relay rather than relayed, I assume that's what the bug is, but I'm not seeing why it is a bug. Can you expand on where the bug is exactly ?

Also, and this is totally bikeshedding, but you called some file mempool. It stores txes, not memory. Lots of people call this mempool and it seems totally misapplied...

**Comment by vtnerd** [comment]
When anonymity i2p/tor routing or stempool stuff is added this leaks data before that phase ends. The transaction has been relayed but has not yet left anonymity phase. The comments indicated that this was always intended to be `do_not_relay` but I wanted to make sure in a separate patch and that it didn't get lost in the noise.

> Also, and this is totally bikeshedding, but you called some file mempool. It stores txes, not memory. Lots of people call this mempool and it seems totally misapplied...

I'll change the name to txpool.

**Comment by vtnerd** [comment]
There is a new flag, in the upcoming patch. Its just that this was arguably wrong in the first place, so instead of blasting it over I was going to show the two-step process.

**Comment by vtnerd** [comment]
And by wrong, I mean slightly off the description (the effects are the same afaik).

**Comment by binaryFate** [comment]
@vtnerd 

I am not fresh enough with the code involved to be 100% sure what you should do. Rather I can explain what was the intent of the commit you mention, so you can judge better if your change is ok or not.

The [commit](https://github.com/monero-project/monero/commit/10013e94342c0d9ca2f10c79779b08affc5209c1) you are referring to was meant to avoid that an observer, by making repeated RPC requests to a public node, could pinpoint that this node was the original sender of particular transactions.

In particular, from that commit explanation, the relevant bit to your recent changes is:
```
* get_transaction_pool will not list transaction that have do_not_relay set to true, and will not list key images that are used only for such transactions
```

The idea is that transactions not yet relayed should not be publicly disclosed (via RPC calls) as being known by a node. Otherwise it reveals that this node is the source.
This is true for transactions that are created with "do_not_relay=true" until they are relayed obviously, but also for normal ones with "do_not_relay=false" when *relaying takes a long time* for whatever reason. Your mention of I2P/Tor routing is very relevant.

So it seems to me what really matters in the condition you changed is whether the transaction was actually relayed (hence known by other nodes on the network), and not whether the sender used do_not_relay which is just a subset of the potential cases.

If in the code `relayed` is always `!do_not_relay`, then your change is fine. If not, then I guess it should follow the intent I explained above and stick to use `relayed`?

I have no idea about the issue with the tests. But the tests should follow whatever logic is intended, which sometimes is for some key images not to show up in call answers.

**Comment by vtnerd** [comment]
> This is true for transactions that are created with "do_not_relay=true" until they are relayed obviously, but also for normal ones with "do_not_relay=false" when relaying takes a long time for whatever reason. Your mention of I2P/Tor routing is very relevant.

Currently transactions get marked as relayed [before any relaying is attempted](https://github.com/monero-project/monero/blob/master/src/cryptonote_protocol/cryptonote_protocol_handler.inl#L2226).

> So it seems to me what really matters in the condition you changed is whether the transaction was actually relayed (hence known by other nodes on the network), and not whether the sender used do_not_relay which is just a subset of the potential cases.

I don't see why that matters. The RPC call is attempting to retrieve transaction info, and the `relayed` flag is always returned with this information. The primary thing being filtered is private information; `do_not_relay` is the privacy flag, `relayed` flags is just current state information.

> I have no idea about the issue with the tests. But the tests should follow whatever logic is intended, which sometimes is for some key images not to show up in call answers.

I was/am adding new tests to cover tx pool behavior, because the metadata leakage is increasingly important.

**Comment by moneromooo-monero** [comment]
It's not a privacy flag. It's meant to mine your own txes to save fees. It became used as a proxy for privacy when combining RPC and P2P, but there is no attempt to otherwise use it for privacy. A privacy flag would be set for any tx received by RPC, regardless of do_not_relay.
The fact that setting the flag is done before or after the relay seems to be misdirection. Setting the flag afer the relay without waiting for an ack would be no different. What would be needed is adding P2P messages to ack receipt of a tx, and only setting the flag if acked.

**Comment by moneromooo-monero** [comment]
I think your change is wrong. If the tx was relayed (ignoring whether it was succesful since there is no support for this), then it's known to the network, and if it was not, then it is not (when a tx is received via P2P, relayed is set). So relayed is the right flag to use to decide whether to include it in the RPC response.

**Comment by vtnerd** [comment]
> I think your change is wrong. If the tx was relayed (ignoring whether it was succesful since there is no support for this), then it's known to the network, and if it was not, then it is not (when a tx is received via P2P, relayed is set). So relayed is the right flag to use to decide whether to include it in the RPC response.

But if `do_not_relay = true`, how does any other network participant know about the transaction? The `do_not_relay` flag would seem to be the more important one in this context. The `relayed` flag is useful if someone wanted to relay, had no network connection, then restarted their `monerod`. The `relayed` flags indicates that an immediate re-broadcast is needed.

The other way to look at it - if someone receives a transaction it could still be marked as `relayed = false` - should that tx be suppressed from RPC calls, etc?

**Comment by moneromooo-monero** [comment]
If do_not_relay is true, other network participants *should* not know about the transaction (unless relayed manually via relay_tx, but that's a corner case).

**Comment by vtnerd** [comment]
> If do_not_relay is true, other network participants should not know about the transaction (unless relayed manually via relay_tx, but that's a corner case).

Isn't that exactly what this change does? Maybe I'm missing something else ... ?

**Comment by moneromooo-monero** [comment]
I don't understand why your last sentence applies. AFAICT, the change is to equating "the world knows about it" to "is it meant to be sent", from equating "the world knows about it" to "it has been sent or received". The latter seems more correct. Do you agree with the characterisations above ? If not, what would be a better characterisation ?

**Comment by binaryFate** [comment]
> AFAICT,  the change is to equating "the world knows about it" to "is it meant to  be sent", from equating "the world knows about it" to "it has been sent  or received". The latter seems more correct. 

That seems correct to me. As I said the former is only a subset of the latter but can leave some transactions at risk. The latter is what my commit was doing, on purpose.

**Comment by vtnerd** [comment]
> I don't understand why your last sentence applies.

You said, "If do_not_relay is true, other network participants should not know about the transaction", which:

```c++
if (!meta.do_not_relay)
  // Do not include that transaction if in restricted mode and it's not relayed	            
  ki.txs_hashes.push_back(epee::string_tools::pod_to_hex(tx_id_hash));
```
does just that. The second case is when the function is called with `include_sensitive_data`.

-----------------------

>> AFAICT, the change is to equating "the world knows about it" to "is it meant to be sent", from equating "the world knows about it" to "it has been sent or received". The latter seems more correct.
>
> That seems correct to me. As I said the former is only a subset of the latter but can leave some transactions at risk. The latter is what my commit was doing, on purpose.

Once i2p/tor/dandelion++ is integrated, when it gets sent is irrelevant. The broadcasting state is far more relevant. Transactions in the stem phase must appear as invisible to the outside world through RPC and p2p calls.

When I "broke down" the components, I realized the `do_not_relay` flag is an existing broadcasting state. Instead of being in the i2p/tor or dandelion++ state, its in the `do_not_relay` state, and it will appear invisible until it gets mined locally into a block or until relaying is requested (which puts it into one of the other states).

The working state of the [split txpool is here](https://github.com/monero-project/monero/compare/master...vtnerd:fix/split_mempool) if that helps. Got the core tests I wanted completed, and wrapping up testing (hopefully).

**Comment by vtnerd** [comment]
BTW, the force push was adding a core test to the main list. It was being compiled but not included in the main file to be run.

**Comment by vtnerd** [comment]
Force pushed a rebase. The buildbots are failing because of an unrelated issue AFAIK.

**Comment by vtnerd** [comment]
Re-reading @binaryFate response, and the intent seems to be to hide the source of a tx being leaked via restricted RPC. Which makes some sense, except the `relayed` flag is always updated immediately, so it doesn't provide any protection. And I was all over the place in my responses. :/

The split mempool is ready and fixes this with a new state change (the tx has to be re-played backed before appearing in a RPC). So I will close this instead of pushing this further.

**Comment by binaryFate** [comment]
> Re-reading @binaryFate response, and the intent seems to be to hide the source of a tx being leaked via restricted RPC. 

Yes

> Which makes some sense, except the relayed flag is always updated immediately, so it doesn't provide any protection.

Was it true even when the transaction is submitted with `do_not_relay=true`?

> The split mempool is ready and fixes this with a new state change (the tx has to be re-played back to the daemon before appearing in a RPC). So I will close this instead of pushing this further.

Sounds good :)

**Comment by vtnerd** [comment]
>> Which makes some sense, except the relayed flag is always updated immediately, so it doesn't provide any protection.
>
> Was it the case even when the transaction is submitted with do_not_relay=true?

If `do_not_relay == true` then the tx remained `relayed == false`. This PR kept behavior consistent in that situation, but instead checked `do_not_relay`.

**Pull request closed without merging**
