### PR TITLE
adding win building details.

### PR DESCRIPTION
**Pull request by k1nghat**
cloning and extra build details included.

### CODE REVIEW

**Comment by k1nghat** [comment]
sure. if the goal is to increase the amount of people that build their own binaries, especially on windows, the instructions are incomplete and out of order. just an opinion from someone looking in from the outside. 😛 @dEBRUYNE-1 had to hand hodl me through it so i figured i would propose these changes so that someone can actually step by step build on win.

**Comment by moneromooo-monero** [comment]
If it's out of order, then it should be moved rather than duplicated,

**Comment by k1nghat** [comment]
you guys are correct. the vast majority of end users will not understand. especially if they have never built anything before.  im just giving my outside opinion.

if the global cloning documentation has to stay at the top and not be duplicated, then there should at least be a note in the correct spot under the windows build instructions to look at the top of the readme for the cloning instructions.

also, is it not true that you need to install the MSYS2 environment on windows before you can clone and build with it?

**Comment by cryptochangements34** [comment]
The only time I foresee this being helpful is if somebody is trying to build by blindly going through the README without even reading all the instructions

**Comment by k1nghat** [comment]
im just saying its not clear. youre assuming ppl who dont even know what cloning is, to know where that step should be in the win build process, and also to go back to the top of the readme to find it.

again, if the goal is to increase the number of people building themselves then these directions are inadequate. its a know your audience type of thing. there needs to be hand hodling, complete step by step instructions. if this is not the goal and want to keep answering questions then i guess the windows build guide should just stay the way it is.

**Comment by moneromooo-monero** [comment]
Maybe I'm missing something, but I see the same instructions (slightly different repo name but equivalent), before the build instructions, so it seems in order already. And if people don't know what cloning is, repeating the step isn't going to help. If the intent is "if they skipped a step, then let's add it again later in case they don't skip it twice", then :S :D If your point is different, then please explain.

**Comment by moneromooo-monero** [comment]
OK, I see the point. People will just grep for "windows" and shoot themselves in the foot. Fair enough. It seems silly to repeat the same steps for all platforms though (yes, you've duplicated just for one, but if it's done for one...). Anyway I get the point now, thanks :)

**Comment by k1nghat** [comment]
i was actually going to mention about putting it into the other platforms but i wasnt getting anywhere with the windows instructions. since there are more window users i think its a good idea to at least have it there. ill have to look over the GUI readme for windows as well.

**Pull request merged**
