### PR TITLE
Rename binaries, drop deprecated binaries

### LINKED ISSUE #80: Rename legacy bits to Monero
Per https://help.github.com/articles/renaming-a-repository - renaming a project will forward everything from the old name to the new with no major consequences. Forks would do well to change their upstream URL, or just re-clone their fork to a working copy, but it'll forward a 'git fetch upstream' to the new URL.

The binary should also be renamed 'monerod' from 'bitmonerod'.

### PR DESCRIPTION
**Pull request by fluffypony**
This closes #80, except for renaming CRYPTONOTE_NAME, which will be addressed in a new issue later on.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok

**Comment by tewinget** [comment]
Seems fine to me.

**Comment by radfish** [comment]
does blockchain_dump has a replacement?

**Comment by fluffypony** [comment]
@radfish no - but it was only used to compare LMDB / in-RAM dbs. Given where we are now, I'm confident that we'd be able to write another DB implementation without the need for blockchain_dump, or we'd reinstate it at that time.

**Comment by lethos3** [comment]
with ringct monero is finally graduating from its cryptonote base

**Pull request merged**
