### PR TITLE
added Swedish localization

### PR DESCRIPTION
**Pull request by ordtrogen**
I couldn't find any 'languages.xml' file like the one in monero-gui so I suppose all there is to do is add the localized file

### CODE REVIEW

**Comment by ordtrogen** [comment]
Oh, great catch. @erciccione! I hadn't noticed but will fix it prontissimo. :-)

**Comment by ordtrogen** [comment]
So, let's see. I updated the file in my forked repo, and it looks like it's reflected here in the PR. Is that all needs to be done?

**Comment by moneromooo-monero** [comment]
You need to squash the commits, they show up as two here.

**Comment by ordtrogen** [comment]
Thanks for making me read up on squashing ... :-)  I did learn enough for next time but messed up my local repo for now. Will make a new PR with the correct file and close this PR.

**Pull request closed without merging**
