### PR TITLE
Use `genesis_tx` parameter in `generate_genesis_block`.

### PR DESCRIPTION
**Pull request by jeandudey**
This might probably break testnet because it was using the mainnet genesis tx.

### CODE REVIEW

**Comment by stoffu** [comment]
I also found this function strange because it doesn't use the provided parameter `genesis_tx` and always uses `config::GENESIS_TX`. How come it can generate a valid genesis tx for testnet?

Also, I think these four lines can be safely removed because the result isn't used:

```c++
    account_public_address ac = boost::value_initialized<account_public_address>();
    std::vector<size_t> sz;
    construct_miner_tx(0, 0, 0, 0, 0, ac, bl.miner_tx); // zero fee in genesis
    blobdata txb = tx_to_blob(bl.miner_tx);
    std::string hex_tx_represent = string_tools::buff_to_hex_nodelimer(txb);
```

**Comment by jeandudey** [comment]
@moneromooo-monero in that case I think i can change the `testnet::GENESIS_TX` constant to be the same as the mainnet `GENESIS_TX`, in theory anything can't be broke because these constants are only used in `generate_genesis_tx`. Or we can remove the `genesis_tx` parameter and remove these branches at [`Blockchain::init`][1].

[1]: https://github.com/monero-project/monero/blob/master/src/cryptonote_core/blockchain.cpp#L370

**Comment by moneromooo-monero** [comment]
If you double check the actual genesis block is the same, then I'm fine wite replacing it in the define.

**Comment by stoffu** [comment]
+1 for updating cryptonote_config.h versus changing the function signature of `generate_genesis_tx`, because Aeon being rebased is starting a new testnet that has a unique genesis tx.

**Comment by jeandudey** [comment]
I've updated the PR and changed the `config::testnet::GENESIS_TX` to be the same as the mainnet's transaction.

**Comment by stoffu** [comment]
I think you can also safely remove the five lines above.

**Comment by jeandudey** [comment]
@stoffu but doesn't `construct_miner_tx` modifies `bl.miner_tx`? I mean the other lines aren't doing anything but i think it's the only one that modifies the block.

**Comment by jeandudey** [comment]
@stoffu you're right these lines did nothing and I've removed them.

**Pull request merged**
