### PR TITLE
README.md - add few FreeBSD instructions, fix v13.0 release tag

### PR DESCRIPTION
**Pull request by monerorus**
tested on current FreeBSD 11.2-p4 , used master and release-v0.13 branchs of monero (w\o any patches)
`gmake` - success
`gmake release-static` - fail (-fPIC error, i think i need build dependencies from ports static instead install from pkg)
`gmake debug` - fail (wallet2.cpp.o - file not recognized: file format no recognized) See #4548 
`gmake release-test` - success (100% passed)

### CODE REVIEW

**Comment by iDunk5400** [comment]
Instead of changing `v0.13.0.0` to `release-v0.13`, you should change it to `v0.13.0.2`.

**Comment by monerorus** [comment]
`gmake release-static` - success on release-v0.13

**Comment by monerorus** [comment]
> 
> 
> Instead of changing `v0.13.0.0` to `release-v0.13`, you should change it to `v0.13.0.2`.

ok i see. made mistake beetween tags and branches

**Comment by ndorf** [comment]
Same error here when trying to build debug: "file not recognized: File format not recognized" on wallet2.cpp.o and/or a couple of other objs. It fails when tried directly, too:

```
$ ld -o /dev/null debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o: file not recognized: File format not recognized
$ file debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o: ELF 64-bit LSB relocatable, x86-64, version 1 (FreeBSD), stripped
$ du -sh debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o 
 82M	debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
```

The release builds have been working well for me, except that monerod will raise SIGABRT and crash anytime it receives a SIGTERM. Do you see that as well?

Unfortunately, I can't even get a stack trace so far. Although the daemon isn't affected by that wallet linker error above, it just hangs after 'core RPC server started ok' -- if and only if it's both the debug binary, and running gdb.

**Comment by monerorus** [comment]
My monerod is in syncing now... will test SIGTERM when it completed
wallet works fine with remote node(0.13.0 version).

**Comment by moneromooo-monero** [comment]
The wallet2 error may be because it's too large for your compiler.

**Comment by moneromooo-monero** [comment]
I meant that I've seen a case where the amount of stuff in the object file goes past a certain limit in a file format. Kind of a shot in the dark though.

**Comment by ndorf** [comment]
@moneromooo-monero the debug version of the object is indeed bigger:
```
 82M	./build/FreeBSD/release-v0.13/debug/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
 11M	./build/FreeBSD/release-v0.13/release/src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
```

But, I don't think that alone explains it. At least, I'm able to link a dummy test object with a 250MB string on the same system. 

`objdump` also refuses to read the wallet2.cpp.o object, so I can't even see which section(s) account for the increased size, or anything. Any suggestions? Is it time to ask the FreeBSD people for help?

**Comment by moneromooo-monero** [comment]
ping, please rebase.

**Comment by moneromooo-monero** [comment]
Last ping before I close this as abandoned.

**Comment by dEBRUYNE-1** [comment]
Perhaps someone else could open this if the author is not responding anymore?

**Comment by dEBRUYNE-1** [comment]
Thanks.

**Comment by monerorus** [comment]
sory missed ping messages. 
My skills in git are weak, can you told me what exactly i must to do (for rebase), or do it yourself? if it is still relevant :)

**Comment by moneromooo-monero** [comment]
Alright, it's now in https://github.com/monero-project/monero/pull/5105

I'll close this as a dupe once the other is merged.

**Comment by monerorus** [comment]
> 
> 
> Alright, it's now in #5105
> 
> I'll close this as a dupe once the other is merged.

ok, thanx

**Comment by moneromooo-monero** [comment]
+duplicate

**Pull request closed without merging**
