### PR TITLE
Cl

### PR DESCRIPTION
**Pull request by moneromooo-monero**
<s>One moment - some scoped messge calls still in</s>

### CODE REVIEW

**Comment by hyc** [comment]
with `BUILD_GUI_DEPS=ON`, `make wallet_merged` fails.

````
-- Found Git: /usr/bin/git
CMake Error at contrib/epee/src/CMakeLists.txt:42 (install):
  install TARGETS given target "epee_readline" which does not exist in this
  directory.


CMake Error at contrib/epee/src/CMakeLists.txt:56 (target_link_libraries):
  Cannot specify link libraries for target "epee_readline" which is not built
  by this project.


-- Configuring incomplete, errors occurred!
See also "/home/software/bitmonero/build/waldep/CMakeFiles/CMakeOutput.log".
Makefile:1144: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
````

**Comment by moneromooo-monero** [comment]
Should be fixed now.

**Comment by hyc** [comment]
Spoke too soon. Regular build fails.
````
[ 62%] Built target wallet
[ 63%] Linking CXX executable ../../bin/monero-wallet-rpc
/usr/bin/ld: cannot find -lepee_readline
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:134: recipe for target 'bin/monero-wallet-rpc' failed
make[2]: *** [bin/monero-wallet-rpc] Error 1
CMakeFiles/Makefile2:1977: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make[1]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by hyc** [comment]
Fixed it with this
````
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a5b5039..907e650 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -684,6 +684,7 @@ if(USE_READLINE)
     add_definitions(-DHAVE_READLINE)
     include_directories(${Readline_INCLUDE_DIR})
     message(STATUS "Found readline library at: ${Readline_ROOT_DIR}")
+       set(EPEE_READLINE epee_readline)
   else()
     message(STATUS "Could not find GNU readline library so building without readline support")
   endif()
diff --git a/src/daemon/CMakeLists.txt b/src/daemon/CMakeLists.txt
index 5d9b6d3..2f9c2b2 100644
--- a/src/daemon/CMakeLists.txt
+++ b/src/daemon/CMakeLists.txt
@@ -95,7 +95,7 @@ target_link_libraries(daemon
     serialization
     daemon_rpc_server
     epee
-    epee_readline
+    ${EPEE_READLINE}
     version
     ${Boost_CHRONO_LIBRARY}
     ${Boost_FILESYSTEM_LIBRARY}
diff --git a/src/simplewallet/CMakeLists.txt b/src/simplewallet/CMakeLists.txt
index 78b3987..08dd4d1 100644
--- a/src/simplewallet/CMakeLists.txt
+++ b/src/simplewallet/CMakeLists.txt
@@ -50,7 +50,7 @@ target_link_libraries(simplewallet
     mnemonics
     p2p
     epee
-    epee_readline
+    ${EPEE_READLINE}
     version
     ${Boost_CHRONO_LIBRARY}
     ${Boost_PROGRAM_OPTIONS_LIBRARY}
diff --git a/src/wallet/CMakeLists.txt b/src/wallet/CMakeLists.txt
index 23bd505..5190bcf 100644
--- a/src/wallet/CMakeLists.txt
+++ b/src/wallet/CMakeLists.txt
@@ -109,7 +109,7 @@ if (NOT BUILD_GUI_DEPS)
     PRIVATE
       wallet
       epee
-      epee_readline
+      ${EPEE_READLINE}
       rpc
       cryptonote_core
       cncrypto
````

**Comment by moneromooo-monero** [comment]
Ah, makes sense. Thanks.

**Pull request merged**
