### PR TITLE
simplewallet: moan harder about untrusted nodes

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by Gingeropolous** [comment]
I would argue that the wording is ... not direct. "Connect to the monero network using your own daemon". Technically, the way we have things set up, a bootstrap daemon is still your own daemon, but you getting info from someone elses node. 

So it should be more direct. "Use your own copy of the blockchain. Do not trust someone elses blockchain"

**Comment by jtgrassie** [comment]
Seems a big assumption the user is using a 3rd party daemon just because it's not local and the user didn't supply the `--trusted-daemon` argument when starting the wallet. Understand wanting to add a loud waring, but would be nice if it didn't make assumptions in the wording. I assume we don't want users simply adding `--trusted-daemon` to silence (as this has other consequences)?

**Comment by moneromooo-monero** [comment]
Obviously not. Do you think someone could be that dumb as to do something dangerous just to not see a message warning about that dangerous thing ?

**Comment by jtgrassie** [comment]
Sadly I do.

The point is more about what can now be an inaccurate message. The 2nd and 3rd line state it's using a third party daemon that can be wrong.

**Comment by moneromooo-monero** [comment]
Oh I see. It doesn't :) It's just that it's very likely.

**Comment by moneromooo-monero** [comment]
I could add something like "if you or someone you trust run this daemon, you can use --trusted-daemon" if you like ?

**Comment by jtgrassie** [comment]
Maybe adjust "Using a third party daemon..." to "If this is a third party daemon, it can be...". 

Plus your extra line above.

**Comment by moneromooo-monero** [comment]
The current wording does not assume, though you seem to think it does.

**Comment by jtgrassie** [comment]
It's an implied assumption.

**Comment by trasherdk** [comment]
Maybe the wording is not `user friendly` enough.
The word `daemon` only has meaning to programmers, and the like. Maybe `node` would be a better choice.

And
```
"Using your own without SSL exposes your RPC traffic to monitoring"
```
should probably have been
```
"Using your own node/daemon without SSL exposes your RPC traffic to monitoring"
```

**Pull request merged**
