### PR TITLE
Copyright: Update to 2023

### PR DESCRIPTION
**Pull request by mj-xmr**
Disclaimer for selsta:

No hidden dev fee was added to this PR.

### CODE REVIEW

**Comment by plowsof** [comment]
during review i found 20 files that could be added to this PR. (ive made a PR to your branch here https://github.com/mj-xmr/monero-mj/pull/2) #8701 found them for me . otherwise lgtm

**Comment by mj-xmr** [comment]
Good job!

**Comment by iamamyth** [comment]
The following is not, and should not be construed as, legal advice, but I really do not understand the rationale for "change all copyright headers" PRs. At best, such bulk changes seem counterproductive, as the final year in the range of every header now reflects simply the current year (a fact totally divorced from the contents of the file), rather than the last year of significant modification (a fact related to the file itself, which, though possibly available via source code control, also reflects some author's judgment as to the materiality of a change). I also note that well-known open source projects, such as the Linux kernel (see, e.g., https://github.com/torvalds/linux/blob/master/kernel/cgroup/cgroup.c) do not follow this practice, and large companies, such as Google, also do not recommend this practice in their open source guidelines (https://opensource.google/documentation/reference/copyright). Surely polluting the repo history and spending time reviewing a change or tool for presumably legal reasons requires some affirmative legal justification, so, I ask: Has anyone received actual legal advice that such changes are productive? Or has this practice been proposed simply because others do it?

Notwithstanding the foregoing concerns, I suspect a "change all headers" tool could probably be repurposed to a "check for copyright year edits when editing a file, and warn if absent" tool, which seems maybe helpful to reviewers and contributors.

**Comment by mj-xmr** [comment]
@iamamyth I would tend to agree with you.

I do it because of this:

> (...) Or has this practice been proposed simply because others do it?

and because I saw various contributors doing the same thing at the same time, each having their own sets of updated files, undeniably increasing the review effort, so I thought to have at least just one set, while they can focus on other stuff.

**Review by selsta — APPROVED** [review]

**Pull request merged**
