### PR TITLE
Add readline support

### PR DESCRIPTION
**Pull request by jtgrassie**
This PR adds readline support to the daemon and monero-wallet-cli. Only
GNU readline is supported (e.g. not libedit) and there are cmake checks
to ensure this.

There is a cmake variable, Readline_ROOT_DIR that can specify a
directory to find readline, otherwise some default paths are searched.

There is also a cmake option, USE_READLINE, that defaults to ON. If set
to ON, if readline is not found, the build continues but without
readline support.

One negative side effect of using readline is that the color prompt in
the wallet-cli now has no color and just uses terminal default. I know
how to fix this but it's quite a big change so will tackle another time.

### CODE REVIEW

**Comment by jtgrassie** [comment]
This could do with some improvement on the cmake file(s) that check if readline is present. 
Main problem is cmake is sometimes picking up libedit as readline (because they are often symlinked and share the same header names). This addition only works with gnu readline, not libedit however. I just don't know cmake well enough to distinguish between libedit and readine.

**Comment by jtgrassie** [comment]
I've got my head round the gnu readline vs libedit for cmake so committed that fix into this too. Reason being is that OSX has libedit by default so cmake needs to do a compile check to ensure that a brew / macports gnu readline is used instead. 
For any system that has both gnu readline and libedit, the path to readline can be supplied by cmake option Readline_ROOT_DIR. If not supplied, and libedit is found, the compile check strips out this readline support so builds still succeed.
It is a shame that libedit doesnt have a couple of the needed calls for this "hack" but my intention was to keep all the exisitng code and interfaces to console output as-is rather than making wide-scale changes just to support readline.

**Comment by moneromooo-monero** [comment]
I haven't looked at the patch yet, but what are the plusses compared to just using rlwrap ?

**Comment by jtgrassie** [comment]
No external program required. 
No extra config required for the external program. 
No need to download, build and install this extra program.
Proper built-in readline support with its included full capabilities. 
The ability to add custom completions in the future if ever desired.

Essentially rlwrap is a fudge to fix programs that don’t use readline that should.

**Comment by moneromooo-monero** [comment]
This breaks creating a new wallet: https://github.com/monero-project/monero/issues/2100

**Comment by jtgrassie** [comment]
@moneromooo-monero can you send me details of crash as I cannot replicate.

**Pull request merged**
