### PR TITLE
[release-v0.16] MMS: New 'config_checksum' subcommand

### PR DESCRIPTION
**Pull request by rbrunner7**

### CODE REVIEW

**Comment by rbrunner7** [comment]
Updated in analogy to master PR #6549.

Depends on @moneromooo-monero 's branch PR #6551.

**Comment by rbrunner7** [comment]
Updated and tested again with the latest version of #6551 .

@vtnerd 's optimization suggestions for the same code over at the master PR #6549 will get worked into master code. This PR here can go ahead as-is, IMHO, in the interest of an early merging for the upcoming release.

**Comment by dEBRUYNE-1** [comment]
@rbrunner7 - Needs a rebase.

**Comment by rbrunner7** [comment]
Rebased.

**Pull request merged**
