### PR TITLE
For 0.12.3.0

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by anonimal** [comment]
@fluffypony I *really really really really* hope that https://github.com/monero-project/monero/issues/3990 is resolved before we bump to 0.12.3.0. I can't update dependencies until that happens.

**Comment by stoffu** [comment]
I got these compile errors:
```
src/wallet/api/wallet.cpp:600:9: error: use of undeclared identifier 'setStatusError'
        setStatusError(string(tr("failed to generate new wallet: ")) + e.what());

src/wallet/api/wallet_manager.cpp:128:29: error: no member named 'parse_subaddress_lookahead' in namespace 'tools'
    auto lookahead = tools::parse_subaddress_lookahead(subaddressLookahead);
                     ~~~~~~~^
```
due to #3489 and #3921 not being merged to the release-0.12 branch.

**Comment by moneromooo-monero** [comment]
Fixed.

**Comment by moneromooo-monero** [comment]
I wasn't planning to. I could certainly be convinced to.

**Comment by moneromooo-monero** [comment]
I've asked pony/luigi what they think.

**Pull request merged**
