### PR TITLE
wallet2: do not commit transactions more than once

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by hyc** [comment]
Shouldn't you have "fix #8793" in this commit msg?

**Comment by jeffro256** [comment]
Just to clarify: since the new checks in this PR occur after the RPC request to /sendrawtransaction, this will always attempt to relay the transaction regardless, but just won't commit the balance recovery information more than once, correct?

**Comment by moneromooo-monero** [comment]
Yes.

**Comment by plowsof** [comment]
repro'd #8793 , this PR fixes the issue (i will need to rtfm and get these python tests running)

**Review by jeffro256 — APPROVED** [review]

**Pull request merged**
