### PR TITLE
wallet_rpc_server: error out if wallet-file and wallet-dir are both used

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by jtgrassie** [comment]
Can it not be a valid case to supply both parameters though? I.e. subsequent opens can use just a filename and the pre-supplied wallet-dir?

**Comment by moneromooo-monero** [comment]
Sure, that'd be OK too.

**Comment by el00ruobuob** [comment]
@jtgrassie after further testing, when passing both `--wallet-dir` and `--wallet-file` parameter, it does not open the wallet.

**Comment by jtgrassie** [comment]
@el00ruobuob my point is this... when a user supplies `--wallet-dir`, that should be used as the _base_ for any _relative_ wallet file arguments to RPC calls or `--wallet-file`. Supplying both arguments should be valid. If both are supplied and the file argument is relative, it's base path should use the dir argument. If the file argument is absolute, the dir argument can be ignored but stored for future RPC calls which get passed a wallet filename (for which the same above logic can apply).

**Comment by el00ruobuob** [comment]
@jtgrassie i do agree with you, i'm just reporting the current behavior.

**Comment by hyc** [comment]
@jtgrassie no. If you start with --wallet-file that means you want the server to only work with that single file. If you start with --wallet-dir that means you want to support multiple files. I wrote it this way to preserve compatibility with previous --wallet-file behavior.

**Comment by jtgrassie** [comment]
@hyc Fair enough. That makes sense then.

**Comment by el00ruobuob** [comment]
And I do understand the behavior. Thanks @hyc

**Pull request merged**
