### PR TITLE
[RELEASE] wallet2: store rct_config in tx_construction_data

### PR DESCRIPTION
**Pull request by stoffu**
otherwise cold signing breaks due to calling use_fork_rules()

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Does adf6d773 not fix it enough, or were you testing prior to pulling it ?

**Comment by stoffu** [comment]
Oh, I was unaware of that patch which seems to fix the same issue. I ran into the issue because I used the release binary which doesn't include this patch. I think it needs to be pushed to the release branch as well.

**Comment by moneromooo-monero** [comment]
It will if there's another 0.14.0.x, but I think there won't.

**Comment by stoffu** [comment]
Ok, hopefully the release of the fixed version will be available soon, since currently release binary users can’t do cold signing which is a pretty important usage.

**Comment by moneromooo-monero** [comment]
Once the RPC tests go in, this won't break again as this is one of the tests, with a wallet with no daemon :)

**Pull request closed without merging**
