### PR TITLE
Cold signing: make sure short payment id isnt encrypted twice

### LINKED ISSUE #1539: integrated address doesnt work with cold signing
When using cold signing functions (`save_transfer, sign_transfer, submit_transfer`) the short payment id is first encrypted in view only wallet and then again in cold wallet but with different tx key. The recipient will therefore get wrong payment id.

### PR DESCRIPTION
**Pull request by Jaqueeee**
fixes #1539

### CODE REVIEW

**Comment by luigi1111** [comment]
Couldn't you just not encrypt it as [here](https://github.com/monero-project/monero/blob/master/src/cryptonote_core/cryptonote_format_utils.cpp#L624) ? (Though I'm unclear that that actually does anything...)

**Comment by Jaqueeee** [comment]
Assumed there could be scenarios where you wan't to use the save_tx() function even if you have the spend key. But if that's not the case we could just disable encryption of payment_id in cryptonote_core if spend key doesn't exist.

**Comment by moneromooo-monero** [comment]
The construction data has destination addresses with payment ids already stripped (ie, not integrated addresses, if those were used originally) ? I can't recall :) This extra code hints this is so, but I thought I'd ask just in case.

**Comment by luigi1111** [comment]
Right if the data was there in the destination, the signing wallet could just dump extra and recreate (it's kinda ridiculous how many functions extra gets passed though). :)

I can imagine using savetx() **with** a spendkey, but it'd be for "raw tx" purposes, and thus signatures and encrypted extra would be assumed included. Maybe there's some different reason it could be used though.

**Comment by moneromooo-monero** [comment]
Having extra passed around allows not having to change a lot of code every time you want to add a new chunk type, though. Except in this case I guess :)

**Comment by Jaqueeee** [comment]
@moneromooo-monero 
Yes. Integrated address is parsed in simplewallet::transfer_main and libwallet::createTransaction respectively . And gets encrypted in cryptonote::construct_tx_and_get_tx_key. And encrypted again when construct_tx_and_get_tx_key is called a second time in sign_tx.

**Comment by moneromooo-monero** [comment]
In that case, I think it's safer to nuke any encrypted payment id when doing cold signing, and then recreate it from the known good one from the integrated address. It prevents (1) errors like the one I've made there, and (2) a compromised hot wallet from sneaking the wrong payment id and the user not realizing it doesn't match the integrated address.

**Comment by moneromooo-monero** [comment]
Turns out the destination passed to the cold wallet is only the standard address, not the integrated address, so we can't do that. I'm ok with the way the patch works then.

**Pull request merged**
