### PR TITLE
copyright update to 2017

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

I read some of your code and adjusted the copyright information according to when the files where changed last. No functional changes.

Cheers,
tpltnt

### CODE REVIEW

**Comment by NanoAkron** [comment]
My personal feeling is that we just need to copyright the original year of creation. I'm not an IP lawyer but I believe the derivative works (i.e. updates) are covered under the appropriate licenses, and so don't need to include an indication of the present year to still be protected.

**Comment by fluffypony** [comment]
@nanoakron probably not entirely necessary to update them, but we've done it every year, and it means that if someone takes a single file for re-use elsewhere they automatically have a current copyright:)

**Comment by fluffypony** [comment]
@tpltnt can I ask you to squash your commits, please? they all have the same description, so no major value in having them all separate anyway;)

**Comment by moneromooo-monero** [comment]
Copyright should include all the years (possibly as a range) for which the file changed (other than the copyright change itself, and maybe trivial things).

OK once squashed.

**Comment by tpltnt** [comment]
squashed and synced with master

**Comment by NanoAkron** [comment]
Hrm...could you remove `f56b69f` and `eab72cd` from the commit and then squash `resovled merge conflicts` (sic) into `2016 -> 2017`?

**Comment by tpltnt** [comment]
@NanoAkron thank you for the hints, but my git repo seems to be messed up since I can't find the "resolved merge conflicts" commit and do have a quite long list to rebase/pick from. I will retract my PR since it contained no substantial contribution.

**Comment by NanoAkron** [comment]
@tpltnt There is not such thing as 'no substantial contribution'. Your work will be accepted if you choose to resubmit.

**Pull request closed without merging**
