### PR TITLE
Adjust to the MSYS2/MinGW static ICU library file renaming

### PR DESCRIPTION
**Pull request by rbrunner7**
After [this commit](https://github.com/monero-project/monero/commit/237f0179b70eb795772e815f2e9ff6f056f53c22) of [PR #3313](https://github.com/monero-project/monero/pull/3313), to build Monero for Windows in MSYS2, one needs the static ICU libraries as provided by MSYS2/MinGW package `mingw-w64-x86_64-icu`.

A week ago there was a renaming of those static ICU libs, see the corresponding [MSYS2 commit](https://github.com/Alexpux/MINGW-packages/commit/de7b103ac3b53cf9fe9ca7d3afb09ba0394681e9): Starting with version 58.2-3 of the package he letter "s" in the library names was dropped, so e.g. `libsicudt.a` became `libicudt.a`.

This leads to changes in the toplevel `CMakeLists.txt` that has to list those libraries in case of a Windows build.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Should it not just see which one is available, and use the one that is ?

**Comment by rbrunner7** [comment]
Well, I am quite out of my depth here to decide whether it should dynamically adapt to library file names in such a case; nowhere near experience to judge that on my side.

I was more or less assuming that everybody almost automatically updates anyway, inlcuding the build environment. But maybe that assumption is wrong.

You want me to make an attempt to program that flexibility into the make file?

**Comment by stoffu** [comment]
Does this patch require everyone to upgrade their MSYS2 installation? That doesn't sound very nice:(

Can't we use this? https://cmake.org/cmake/help/v3.7/module/FindICU.html

**Comment by stoffu** [comment]
I noticed that `monero-wallet-cli.exe` builds fine without linking against `sicuio sicuin sicuuc sicudt sicutu`. Can't they be simply removed?

**Comment by rbrunner7** [comment]
Regarding using the FindICU CMake module: I spent several hours trying to get it to work, but somehow I was not successful. As I am no CMake specialist I was not able to get to the bottom of this, and at one point I simply decided to reference the libraries directly. It's not beautiful, agreed, and with the renaming there is already a problem with those libraries; however, I somehow doubt that FindICU is already updated to a rename that the MSYS2 people did for their library files.

Regarding updating: I was under the impression that it's simply best practice to keep MSYS2 as updated as possible at any time. The MSYS2 ReadMe certainly advices to update right after install, as does the Monero ReadMe Windows section itself as well, with "Update packages using pacman: `pacman -Syuu`", so I am a little confused that you feel I force people to do something that is not nice. But anyway, you are problably longer into Open Source than me; I am always eager to learn.

About the ICU libraries not needed: Right now, I simply can't imagine that. After mixing and cherry-picking commits, does your version of `simplewallet.cpp` really still import `boost-locale` and configure the filesystem object, and do you still link ICU statically, i.e. not referencing the DLLs?

`` std::locale::global(boost::locale::generator().generate(""));
  boost::filesystem::path::imbue(std::locale());
``

I mean, I did not add those ICU imports just for fun; I did it after I got linker errors that I found no other way to resolve than adding those libraries.

**Comment by stoffu** [comment]
@rbrunner7 
Sorry that my suggestion made you waste several hours with CMake. And my concern about the need to upgrade MSYS2 was pointless; I was missing that the process is as simple as doing `pacman -Syuu`. 

However, I really see that the GUI builds fine without linking to ICU: https://github.com/monero-project/monero-gui/pull/1177

I've made another PR for this repo to see if that's also true for simplewallet: https://github.com/monero-project/monero/pull/3392

Am I missing something?

**Comment by rbrunner7** [comment]
@stoffu: No problem, I wasted those hours with FindICU and CMake a long time ago, nothing to do with your suggestion :)

The whole situation with those ICU libraries **is** very confusing and tends to "bite you into the leg", as we use to quip in German:

If you do exactly as the Monero ReadMe (i.e. the non-GUI one) instructs you do to, i.e. install the MSYS2 package `mingw-w64-x86_64-boost` and not compile Boost yourself, I am nearly 100% sure that you have to list the ICU libraries yourself in the Make file in order to get them properly linked into `monero-wallet-cli.exe`.

If you compile Boost yourself, as the Monero GUI ReadMe instructs you to do, it seems *sometimes* it links without any mentions of those libraries in the make file. I am really not sure why: Maybe Boost #ifdef's around ICU and only uses `iconv` if you compile it yourself on MSYS2, or it statically links them in somewhere. Mysterious.

I ended up using **two** separate MSYS2 environment on my machine: One with the MSYS2 Boost package installed for Monero, and another one with Boost compiled for the GUI.

But anyway, if you can take out those ICU libray references, and still `monero-wallet-cli.exe` ends up with the **static** ICU libraries inside the .exe, and `monero-wallet-gui.exe` correctly references the 5 ICU DLLs or also has ICU statically inside somewhere, **and** it still correctly processes filenames with non-ASCII characters both in the CLI and the GUI wallet, and all that is reliable and reproducible - well, then maybe we should stop to worry :)

**Comment by stoffu** [comment]
> I ended up using two separate MSYS2 environment on my machine: One with the MSYS2 Boost package installed for Monero, and another one with Boost compiled for the GUI.

Wow, that's what ended up necessary for you? Seems like quite a hurdle for newcomers to get started :)
FWIW, I'm able to build both the CLI and the GUI on the same MSYS2 installation. And yes, I think I've built Boost manually as instructed in the GUI repo.

Anyway, I'm nowhere close to knowledgeable when it comes to building reliable and portable apps, and I'm convinced that your proposal is the right one. Thank you for elaborating :)

**Comment by rbrunner7** [comment]
Well, maybe it was not strictly necessary for me to work with 2 MSYS2 environments, but that way I could easily keep everything under control and stick to both sets of instructions in the Monero and the Monero GUI ReadMe.

But anyway, those are of course not sacrosanct, and as I said, if the problem turns out to be smaller than anticipated under the condition that one builds their own Boost, all the better.

Just remember to be careful: It's quite easy e.g. to produce an EXE file for the CLI wallet that does not have the ICU libraries statically linked in but references the corresponding ICU DLLs which is problably quite unwanted, at least as far as I understand it.

**Comment by shopglobal** [comment]
I will just leave this here https://github.com/julp/FindICU.cmake/blob/master/FindICU.cmake

**Pull request merged**
