### PR TITLE
multisig: fix seed restore (suggestions by @UkoeHB) [release]

### LINKED ISSUE #8537: Restoring multisig wallet fails
Steps to reproduce:

1. Generate 2/3 multisig wallet (the M and N are presumably irrelevant).
2. In the CLI wallet, run `seed` or `encrypted_seed` with no passphrase. Save the seed.
3. Run the CLI wallet with `--restore-multisig-wallet`.
4. Enter the seed from step 2.
5. Observe an error: `Error: failed to generate new wallet: invalid multisig seed`

If we use `encrypted_seed` with some passphrase, the CLI wallet segfaults on step 5 instead of showing an error.

Happens with both v0.17.3.2 and v0.18.1.0.

### PR DESCRIPTION
**Pull request by j-berman**
Solves the `invalid multisig seed` error when restoring a multisig wallet, reported by @tmoravec in #8537. Fixes suggested by @UkoeHB.

### [Fix 1](https://github.com/monero-project/monero/issues/8537#issuecomment-1233717683)

> multisig accounts no longer store a sum of multisig keyshares in the spend_secret_key slot. Instead it is the 'base multisig privkey', which is the private key used to sign key exchange messages post-update (and for the first step of key exchange both pre and post update). This explains why new multisig wallets are throwing an error (can be fixed by just deleting lines 4750-4754; there is no verification step like this for post-update spend secret keys).

### [Fix 2](https://github.com/monero-project/monero/issues/8537#issuecomment-1234611444)

> If restoring from 'multisig keys', presumably the wallet is fully set-up, so it's fine to set the rounds passed [in wallet2::generate()].

### Misc

Tested restoring both a v0.17.2.0 and v0.18.1.0 multisig wallet from plaintext seed using this PR applied to v0.18.1.0. Working smoothly on my end.

I have not yet gone deeper into the segfault reported with an encrypted seed in #8537. [UPDATE: solved in this PR]

### CODE REVIEW

**Review by UkoeHB — APPROVED** [review]
Thanks for spearheading this

**Comment by tmoravec** [comment]
I've just tested this branch. Restoring 2/3 wallets, receiving funds into them, and sending outgoing transactions, all on stagenet. Wallets created with:

* v0.17.2.0
* v0.17.3.2
* v0.18.1.0

* * *

One semi-related suggestion: set enable-multisig-experimental to 1 when restoring a multisig wallet.

**Comment by UkoeHB** [comment]
> One semi-related suggestion: set enable-multisig-experimental to 1 when restoring a multisig wallet.

I think any use of multisig should be gated by the enable-multisig-experimental, in case any user hasn't encountered it before.

**Comment by j-berman** [comment]
I figure an explicit confirmation on restore couldn't hurt (see latest commit). But true that any use of multisig *after* restoring is still gated

**Review by UkoeHB — APPROVED** [review]

**Comment by tmoravec** [comment]
@j-berman I meant the exact opposite. The user has _already_ explicitly said they want a multisig wallet with `--restore-multisig-wallet`. Hence we can set `enable-multisig-experimental` to 1. And any warnings are pointless when restoring a wallet anyway because the wallet already exists. 

So now we ask the user to say it THREE times (first on the CLI, then on restore, then on any use). Which is going beyond superfluous.

**Comment by selsta** [comment]
> So now we ask the user to say it THREE times (first on the CLI, then on restore, then on any use). Which is going beyond superfluous.

Every user should know that multisig is in its current form experimental and unsafe for production (if untrusted participants are involved) until we have security proofs. Someone creating a multisig wallet before we marked it as experimental should also explicitly approve it.

**Comment by j-berman** [comment]
> Someone creating a multisig wallet before we marked it as experimental should also explicitly approve it.

This is why I figured it makes sense to add on restore.

In the latest commit, I kept the explicit confirmation I added for restore, and then the user's confirmation enables multisig into perpetuity for the restored wallet. In sum:

- In order to create a multisig wallet, a user must `set experimental-multisig-enabled 1` once.
- In order to restore a multisig wallet from seed, a user must explicitly acknowledge multisig is experimental once via confirmation, and then the user does not need to `set experimental-multisig-enabled 1` again in order to perform any multisig actions after.

**Review by UkoeHB — APPROVED** [review]

**Comment by j-berman** [comment]
PR onto this branch that solves the segfault when restoring an encrypted seed: https://github.com/j-berman/monero/pull/5

Figure it would be easier to test/review this way, and it won't hold up the release.

**Review by UkoeHB — APPROVED** [review]

**Pull request merged**
