### PR TITLE
blockchain: keep alternative blocks in LMDB

### PR DESCRIPTION
**Pull request by moneromooo-monero**
Alternative blocks are cleared on startup unless --keep-alt-blocks
is passed on the command line

### CODE REVIEW

**Comment by hyc** [comment]
Any reason not to do this by default? Is there a bloat risk? If alt blocks are only stored in RAM for now, isn't there already a bloat risk?

**Comment by moneromooo-monero** [comment]
Blocks are small, and the current code does not keep them, which means any reorg failure due to this will be cleared by a restart. I did wonder about making this the default, but then thought that it's an unbounded set, even if blocks are small. I'm open to changing the default if there's support for it.

**Comment by moneromooo-monero** [comment]
"Blocks" here really means blocks, not blocks plus their transactions. So, small.

**Comment by Mitchellpkt** [comment]
Thanks, this is great! Will update the Noncesense [archival network](https://github.com/noncesense-research-lab/archival_network) to stash alt blocks this way. We really appreciate this feature.

If a transaction (/hash) shows up in an alt block but not a main block, will it be recoverable/retrievable this way? Would be convenient for post-mortem analysis, comparing key images <> ring members.

**Comment by moneromooo-monero** [comment]
It will not.

**Comment by moneromooo-monero** [comment]
Actually... it might. I think the tx will stay in the txpool for a bit, then end up dropped after 7 days. So if you're quick enough, you should find it.

**Pull request merged**
