### PR TITLE
Depends: Bump qt to 5.15.1

### PR DESCRIPTION
**Pull request by TheCharlatan**
Keeping the qt depends recipe updated has been annoying lately. Over the past year it was changed twice, because the archival mirror was not available anymore. Qt 5.15.x is the final LTS version of Qt 5. It is therefore reasonable to assume that Qt 5.15 will remain in the qt source archive indefinitely.

### CODE REVIEW

**Comment by NacJidtyd6op** [comment]
hi,

is any work done for using depends package on monero-gui or there too much to do for that.

i can help if is possible.

Thank you.

**Comment by TheCharlatan** [comment]
@NacJidtyd6op : I have some work on the gui `dependsQt5.15` branch of my fork of the gui: https://github.com/TheCharlatan/monero-gui/tree/dependsQt5.15 . It took quite some time to get this far, but there is still a lot to be done. Any help I can get with it is most welcome.

**Review by moneromooo-monero — APPROVED** [review]

**Comment by NacJidtyd6op** [comment]
hello,

some error on compiling 

checking for gpg-error-config... no
checking for GPG Error - version >= 1.25... no
configure: error: libgpg-error is needed.
                See ftp://ftp.gnupg.org/gcrypt/libgpg-error/ .
make: *** [funcs.mk:262: /monero-gui/depends/work/build/x86_64-pc-linux-gnu/libgcrypt/1.8.6-700cd073bdc/./.stamp_configured] Error 1

 libgpg-error is installed but not found.

**Comment by selsta** [comment]
@NacJidtyd6op Is this GUI related? Please open an issue on the monero-gui repo.

**Comment by NacJidtyd6op** [comment]
TheCharlatan must move this issue to gui

After removing libgcrypt package depends cant find gssapi_krb5 library

**Comment by xmrdsc** [comment]
@NacJidtyd6op fixed in #6824

**Comment by NacJidtyd6op** [comment]
Hello,

How i can help for depends installs.

**Comment by selsta** [comment]
@TheCharlatan Does this change minimum required glibc? Or is Qt only used for translations?

**Comment by TheCharlatan** [comment]
It's only for translations, so no effect on glibc requirments. The recent glibc bump is annoying though and I am still not sure how to solve it without ld preloading. A dynamic object called `__signgam` was updated in glibc 2.23 in connection to its usage of the lgamma function. Since we only started using it recently, I believe it has been like this since the 0.16.x release. I have attempted a bunch of workarounds on this branch: https://github.com/TheCharlatan/monero/commit/be69345bbc22304bf3cca545458a0d964b0a681e, but to no avail.

**Review by selsta — APPROVED** [review]

**Pull request merged**
