### PR TITLE
Fix a -Wformat-extra-args

### PR DESCRIPTION
**Pull request by jroelofs**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I believe this one is actually correct, and hyc confirmed at the time. I don't really have a particular preference whether this gets in or not though.

**Comment by hyc** [comment]
The current code is correct, the compiler is wrong, and we won't take this patch upstream. No opinion on whether it should go in locally or not.

**Comment by jroelofs** [comment]
The compiler *is* wrong, but you’re kind of asking it to perform heroics to
detect that there are two paths, and that the correct number of args are
passed for each path.

Would the equivalent #pragma’s around it to disable the warning around that
specific code be acceptable?

**Comment by moneromooo-monero** [comment]
If you really want to kill the warning, your patch's better than disabling the warning IMHO.

**Comment by hegjon** [comment]
This patch is for an external library, would it be better to ask lmdb to apply it instead?

**Comment by jroelofs** [comment]
Further up in the thread hyc says that this patch would not be acceptable
upstream in that library... hence my abandoning this PR.

**Pull request closed without merging**
