### PR TITLE
Fix console output/compile instructions on OpenBSD

### PR DESCRIPTION
**Pull request by offshoremonero**
OpenBSD unfortunately ships with an old version of readline in its base system.

This causes artifacts on the screen when using the wallet cli and random core dumps.

For now, the best fix is to turn readline off on OpenBSD until I can figure out how to get the newer version of readline working. It can be added to the system using pkg_add, but for some reason it doesn't link cleanly yet.

This fix has been confirmed to work on OpenBSD 6.9, OpenBSD 7.0, OpenBSD 7.1, and OpenBSD 7.2.

Edit: also includes slight changes to the OpenBSD instructions to keep in sync with the changes on OpenBSD that have happened over time.

### CODE REVIEW

**Review by selsta — COMMENTED** [review]
Shouldn't it be enough to just put

```
if(NOT OPENBSD)
  option(USE_READLINE "Build with GNU readline support." ON)
endif()
```

into the if and leave the other code alone? This would make the overall diff smaller but maybe I'm missing something.

**Comment by offshoremonero** [comment]
Yes, you're right. That is much better and simpler.

Do you want me to submit a new pull request or can you just make it happen?

**Comment by offshoremonero** [comment]
Okay, I've committed the fix for the fix. lol

I grew up with CVS so please pardon my mess.

**Comment by offshoremonero** [comment]
I've corrected a couple of very small errors in the OpenBSD compile instructions as well.

Confirmed to work with OpenBSD 7.1 and 7.2 :)

**Comment by selsta** [comment]
Looks good, do you know how to squash commit 1 and 2 together? :) 3 can stay separate since it's a separate commit.

**Comment by offshoremonero** [comment]
No, I don't know how to squash 1+2 together. I'm a tad lost. lol

**Comment by offshoremonero** [comment]
I tried pick/squash and now it looks like a huge mess. haha

**Comment by offshoremonero** [comment]
Okay, I figured out how to revert the giant mess I made.

There are two clean commits now. One for each file.

**Comment by selsta** [comment]
You might have to force push? There are now 8 commits. Otherwise if you don't know how to do it I can open a separate PR and set you as the author.

**Comment by offshoremonero** [comment]
$ git push --force
Everything up-to-date

This didn't appear to change anything. Thanks for being so patient. :)

**Comment by offshoremonero** [comment]
Okay, I think I got force push working.

**Review by selsta — APPROVED** [review]
Looks good :)

**Comment by offshoremonero** [comment]
I had to "git log" find the commit that you guys are on and run "git reset --hard 365fd45b031b0a5c8104195dfabb786e839cb114" & reapply my two patches, commit them individually, and then "git push" and reopen this pull request.

I'm learning stuff. :)

**Pull request merged**
