### PR TITLE
cryptonote_core: slightly optimize block rate calc

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
For the fix, can you add in the commit message which platform it is for, it's not clear what the error is.

**Comment by moneromooo-monero** [comment]
And if that does compile on your arch, I think I'd rather set seconds to be time_t instead, no need to cast then.

**Comment by xiphon** [comment]
> For the fix, can you add in the commit message which platform it is for, it's not clear what the error is.

https://github.com/monero-project/monero/pull/4408#event-1929750503 monero-static-ubuntu-i686 build bot

**Comment by xiphon** [comment]
> I think I'd rather set seconds to be time_t instead, no need to cast then.

Nope. You will still have to cast.

**Comment by xiphon** [comment]
> I think I'd rather set seconds to be time_t instead, no need to cast then.

Nope. You will still have to cast

**Comment by moneromooo-monero** [comment]
OK, fair enough. What is the error, for my edification ?

**Comment by xiphon** [comment]
> OK, fair enough. What is the error, for my edification ?

Ah, just pedantic gcc 5.4.0 doesn't want to let you compare signed and unsigned integers.

**Comment by moneromooo-monero** [comment]
On the off chance you're not taking the piss: one of your patches is rewriting code for no good reason. We do not want that, unless the existing code is egregious. The optimization claim is ridiculous: AFAICT the only such change is taking a pointer to a word size POD type, instead of by value, which I doubt is even speeding things up, might very well slow it down, and is called next to something that calls exp and calculates a factorial.
Are you taking the piss ? If so, stop. If not, remove that patch.

**Comment by xiphon** [comment]
> Are you taking the piss ? If so, stop. If not, remove that patch.

Not. The patch does exactly what it states in the commit message: `avoids gratuitous recalculations in check_block_rate()`.

Current code calculates `now - seconds[n]` 180 times per check_block_rate() call
My patch calculates `now - seconds[n]` 3 times per check_block_rate() call

**Pull request merged**
