### PR TITLE
wallet2: move segregation height to v7

### PR DESCRIPTION
**Pull request by moneromooo-monero**
since people seem to really want to use things the wrong way.

### CODE REVIEW

**Comment by stoffu** [comment]
Can you elaborate a bit more on the context?

**Comment by moneromooo-monero** [comment]
Someone's forking at this point, which is earlier than the point another fork was going to fork. IIRC dEBRUYNE posted a link.

**Comment by stoffu** [comment]
@dEBRUYNE-1 
Could you leave that link here?

**Comment by dEBRUYNE-1** [comment]
@moneromooo-monero & @stoffu - see:

https://twitter.com/xmccurrency

Grep `1546` to see relevant tweets.

**Comment by stoffu** [comment]
@dEBRUYNE-1 Thanks.

**Pull request merged**
