### PR TITLE
Preliminary support for DragonFly BSD

### PR DESCRIPTION
**Pull request by tuxillo**
- It builds but no further testing has been done.

### CODE REVIEW

**Comment by hyc** [comment]
Propagating platform-specific ifdefs like this is going to be unmaintainable and unsustainable. Should be using feature-specific ifdefs and configuring them all in a single place. (E.g., #ifdef HAVE_MALLOC_H instead of all those OS tests before including <malloc.h> )

**Comment by tuxillo** [comment]
Well I just followed what was being done already.

**Comment by fluffypony** [comment]
I agree with @hyc as a long-term solution, and it's something for somebody to refactor and fix later on. In the meantime this should be fine - I do wonder why FreeBSD and DragonFly don't present roughly the same environment? ie. could we do it as a more generic "BSD" check, or are there significant enough differences?

**Comment by tuxillo** [comment]
One would have to check the #ifdefs and see where they can be collapsed. There are certainly differences between the major BSD although I don't know if they'll apply to monero's use cases.

**Comment by fluffypony** [comment]
Also @danrmiller, we'll need a build VM for DragonFly:)

**Comment by fluffypony** [comment]
Tks - will chalk it up as something to investigate later...someday...when someone has time:)

**Pull request merged**
