### PR TITLE
blockchain_ancestry: finds all ancestors of a tx, block, or chain

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by stoffu** [comment]
Looks like almost the identical code is repeated for the cases with and without the `--all` flag; can't it be somehow unified to one? Also, the caching scheme seems to be used only for the cases with `--all`, but I think it (excluding the block caching) can be used also for cases `--txid` or `--height`.

**Comment by moneromooo-monero** [comment]
I almost killed the version for one single tx/height. That was the original code before the requirements changed, but I thought it might still be useful. I'm not sure it can be merged easily since one version's forward and the other backward, but some chunks of the code could be made into functions, and a cache could be added to the original one. I don't think it's worth the bother though. If you don't like the duplication, I'll kill the original code.

**Comment by stoffu** [comment]
> since one version's forward and the other backward
Ah, I didn't realize that at first read.

This analysis task is usually very heavy, I suppose. I tried `--txid` with some randomly picked recent txes, but the execution didn't finish after quite some waiting (an hour or so). I'm currently running with `--all`, and the processed height so far is 31k after about 20min (using 1.4GB RAM). I guess the processing speed and RAM usage can become worse and worse as the size of ancestry keeps increasing. If the expected use case is to run it only once in quite a while when researchers need to extract the latest data, maybe the `--txid` option is not very useful and can be dropped.

Maybe it makes sense to allow incremental mode similar to `monero-blockchain-blackball`? Also, how about putting the analysis result into LMDB for easier handling?

**Comment by moneromooo-monero** [comment]
Yes to all of these. --txid is also useful to double check between forward and backward methods though.

**Pull request merged**
