### PR TITLE
Default 'always confirm transfers' to true for added safety

### PR DESCRIPTION
**Pull request by NanoAkron**
Addresses #1158 and I agree - the harder it is to accidentally screw up, the better.

JSON parsing logic copied from `confirm_missing_payment_id`

Had to add ` m_always_confirm_transfers(true)` to the public part of the `wallet2` class - it was the only option missing from the public part that was in the private part.

Took the opportunity to re-order the public and private lists of the `wallet2` class at the same time so that they now match and are easier to scan, with the uniquely public options at the end.

@moneromooo-monero Just wondering why the logic for `confirm_missing_payment_id` doesn't use `true` as the default value for your `GET_FIELD_FROM_JSON_RETURN_ON_ERROR` function?

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok, would be nice to squash the fixup though.
The default value for the json call should be true, you're right.

**Comment by NanoAkron** [comment]
Will try to squash, no expert with git yet though :)

Can I ask - if I do change the default, will I need to change the logic acting on the returned value or can I just assign 'm_whatever = field_whatever'

**Comment by moneromooo-monero** [comment]
I'm not sure I understand what you're asking here. I can't recall the logic now, I did that a while back. Can you give more details to your question ?

**Comment by NanoAkron** [comment]
Sure.

```
GET_FIELD_FROM_JSON_RETURN_ON_ERROR(json, confirm_missing_payment_id, int, Int, false, false);
    m_confirm_missing_payment_id = !field_confirm_missing_payment_id_found || field_confirm_missing_payment_id;
```

If I changed the final `false` to default to `true`, presumably you could have a simple `if(field_confirm_missing_payment_id_found) {m_confirm_missing_payment_id = field_confirm_missing_payment_id};`

**Comment by moneromooo-monero** [comment]
Can you paste the compile error you get ?

**Comment by NanoAkron** [comment]
It just doesn't compile wallet2.cpp. Times out even if I leave it overnight.

**Comment by moneromooo-monero** [comment]
The compiler times out ? I'm confused now.
For mandatory parameters, using the _found bool is unneeded, I just looked at the code to double check.

**Comment by moneromooo-monero** [comment]
(and for non-mandatory too, unless you want to distinguish between not found and found with the same value as default).

**Comment by NanoAkron** [comment]
Thanks @moneromooo-monero. I'm going to build on this with a few more changes to the handling of the defaults within the scope of the existing code.

**Comment by NanoAkron** [comment]
Superseded by more extensive changes in #1212

**Pull request closed without merging**
