### PR TITLE
wallet2: set user-agent when talking to the dameon

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by fluffypony** [comment]
Do we need this at all, given that ZMQ is in review and will replace the daemon RPC?

**Comment by moneromooo-monero** [comment]
After 0MQ is in, no.

**Comment by moneromooo-monero** [comment]
Well, actually, there'll be a RPC fallback still.

**Comment by fluffypony** [comment]
@moneromooo-monero yes but wallet2 talks to the daemon over 0MQ in #1172 afaics

**Comment by moneromooo-monero** [comment]
OK. I just added this because the daemon shares the --user-agent option, and that doesn't actually work since the wallet doesn't set User-Agent. It's less of a problem than the wallet since no private keys, so if you want to ignore this I'm fine with that.

**Comment by fluffypony** [comment]
Ok - closing to reduce @tewinget's rebase work;)

**Pull request closed without merging**
