### PR TITLE
Sa

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by NanoAkron** [comment]
Can you help me picture a use case for a transaction without a destination?

**Comment by moneromooo-monero** [comment]
All goes in the fee.

**Comment by erikd** [comment]
Why is that not error?

**Comment by moneromooo-monero** [comment]
Why would it be ? It's a perfectly valid tx.

**Comment by erikd** [comment]
Well yes, its valid, but why would anyone be sending all the outputs of their transaction to the miners?

**Comment by moneromooo-monero** [comment]
I don't know, but a low level building block should not make that decision.

**Comment by erikd** [comment]
Is there some higher level logic that checks this?

**Comment by moneromooo-monero** [comment]
In wallet2, you have to give at least one destination. It will auto fill a second dummy one if you don't have change. So it generates at least two outputs.

**Comment by erikd** [comment]
Ok, that's fair.

**Pull request merged**
