### PR TITLE
Ignore fallthrough in base58.cpp when compiling with GCC 7.3.0

### PR DESCRIPTION
**Pull request by NanoAkron**
-Wimplicit-fallthrough=2 or 3 failed to fix this

### CODE REVIEW

**Comment by NanoAkron** [comment]
FFS this is going to be annoying if it's only specific for GCC 7...yet more tinkering with CMakelists.txt required

**Comment by moneromooo-monero** [comment]
Or just remove -Werror ?

**Comment by NanoAkron** [comment]
That would certainly work, but don't we want to notify on some errors?

**Comment by moneromooo-monero** [comment]
The warnings are still there, they just stay warnings.

**Comment by NanoAkron** [comment]
Indeed they are...but now it doesn't halt compilation

I wanted to use -Wimplicit-fallthrough=2 or 3 to detect the /* FALLTHRU */ messages and just go silent, but that flag isn't working for some unknown reason.

Perhaps we should update our build machinery to GCC > 6

**Comment by moneromooo-monero** [comment]
My opinion is that -Werror is an annoying piece of garbage and should be removed. Any other opinion by main contributors ?

**Comment by xiphon** [comment]
Seems the issue is not reproducible on build bot with gcc 7.3.0 https://build.getmonero.org/builders/monero-static-ubuntu-amd64/builds/5923/steps/compile/logs/stdio
Also can't reproduce the warning with gcc 8.2.0.

**Comment by NanoAkron** [comment]
[[fallthrough]] is C++17 (https://en.cppreference.com/w/cpp/language/attributes/fallthrough) and for some reason didn't work for me

Using -Wimplicit-fallthrough=2 or 3 should detect all variants of /* FALLTHROUGH */ in the subsequent comment and ignore, but again it's not working for me for some reason.

```nodey@odroidc2:~/monero$ make release
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- CMake version 3.12.3
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/lib/ccache/gcc
-- Check for working C compiler: /usr/lib/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/g++
-- Check for working CXX compiler: /usr/lib/ccache/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building without build tag
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Checking submodules
-- Submodule 'external/miniupnp' is up-to-date
-- Submodule 'external/unbound' is up-to-date
-- Submodule 'external/rapidjson' is up-to-date
-- Submodule 'external/trezor-common' is up-to-date
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled (using easylogging++)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test _pthread_c
-- Performing Test _pthread_c - Success
-- Performing Test _pthread_cxx
-- Performing Test _pthread_cxx - Success
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.0.2g")  
-- Using OpenSSL include dir at /usr/include
-- Found HIDAPI: /usr/lib/aarch64-linux-gnu/libhidapi-libusb.so  
-- Looking for memset_s in c
-- Looking for memset_s in c - not found
-- Looking for explicit_bzero in c
-- Looking for explicit_bzero in c - not found
-- Looking for strptime
-- Looking for strptime - found
-- Found MiniUPnPc: /usr/include/miniupnpc  
-- Found miniupnpc API version 10
-- Using in-tree miniupnpc
-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 64-bit LMDB from source tree
-- Using HIDAPI include dir at /usr/include/hidapi
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
-- Could not find Protobuf
-- Building on aarch64 for armv8-a
-- Checking to see if CXX compiler accepts flag -march=armv8-a+crypto
-- Checking to see if CXX compiler accepts flag -march=armv8-a+crypto - yes
-- Crypto extensions enabled for ARMv8
-- Performing Test _Wformat_c
-- Performing Test _Wformat_c - Success
-- Performing Test _Wformat_cxx
-- Performing Test _Wformat_cxx - Success
-- Performing Test _Wformat_security_c
-- Performing Test _Wformat_security_c - Success
-- Performing Test _Wformat_security_cxx
-- Performing Test _Wformat_security_cxx - Success
-- Performing Test _fstack_protector_c
-- Performing Test _fstack_protector_c - Success
-- Performing Test _fstack_protector_cxx
-- Performing Test _fstack_protector_cxx - Success
-- Performing Test _fstack_protector_strong_c
-- Performing Test _fstack_protector_strong_c - Success
-- Performing Test _fstack_protector_strong_cxx
-- Performing Test _fstack_protector_strong_cxx - Success
-- Performing Test _fcf_protection=full_c
-- Performing Test _fcf_protection=full_c - Failed
-- Performing Test _fcf_protection=full_cxx
-- Performing Test _fcf_protection=full_cxx - Failed
-- Performing Test _fstack_clash_protection_c
-- Performing Test _fstack_clash_protection_c - Failed
-- Performing Test _fstack_clash_protection_cxx
-- Performing Test _fstack_clash_protection_cxx - Failed
-- Performing Test _mmitigate_rop_c
-- Performing Test _mmitigate_rop_c - Failed
-- Performing Test _mmitigate_rop_cxx
-- Performing Test _mmitigate_rop_cxx - Failed
-- Looking for -pie linker flag
-- Looking for -pie linker flag - found
-- Looking for -Wl,-z,relro linker flag
-- Looking for -Wl,-z,relro linker flag - found
-- Looking for -Wl,-z,now linker flag
-- Looking for -Wl,-z,now linker flag - found
-- Looking for -Wl,-z,noexecstack linker flag
-- Looking for -Wl,-z,noexecstack linker flag - found
-- Looking for -Wl,-z,noexecheap linker flag
-- Looking for -Wl,-z,noexecheap linker flag - not found
-- Using C security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- Setting FPU Flags for ARM Processors
-- Checking to see if CXX compiler accepts flag -mfix-cortex-a53-835769
-- Checking to see if CXX compiler accepts flag -mfix-cortex-a53-835769 - yes
-- Checking to see if CXX compiler accepts flag -mfix-cortex-a53-843419
-- Checking to see if CXX compiler accepts flag -mfix-cortex-a53-843419 - yes
-- Enabling Cortex-A53 workaround 835769
-- Enabling Cortex-A53 workaround 843419
-- Found Boost Version: 106600
-- Found Readline: /usr/include  
-- Looking for rl_copy_text
-- Looking for rl_copy_text - found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - found
-- Found readline library at: /usr
-- Found Git: /usr/bin/git
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen dot 
-- Performing Test HAVE_C11
-- Performing Test HAVE_C11 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nodey/monero/build/release
cd build/release && make
make[1]: Entering directory '/home/nodey/monero/build/release'
make[2]: Entering directory '/home/nodey/monero/build/release'
make[3]: Entering directory '/home/nodey/monero/build/release'

>>>> blah blah

Scanning dependencies of target obj_common
make[3]: Leaving directory '/home/nodey/monero/build/release'
make[3]: Entering directory '/home/nodey/monero/build/release'
[ 34%] Building CXX object src/common/CMakeFiles/obj_common.dir/base58.cpp.o
/home/nodey/monero/src/common/base58.cpp: In function ‘uint64_t tools::base58::{anonymous}::uint_8be_to_64(const uint8_t*, size_t)’:
/home/nodey/monero/src/common/base58.cpp:114:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 1:            res |= *data++; /* FALLTHRU */
                 ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:115:9: note: here
         case 2: res <<= 8; res |= *data++; /* FALLTHRU */
         ^~~~
/home/nodey/monero/src/common/base58.cpp:115:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 2: res <<= 8; res |= *data++; /* FALLTHRU */
                            ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:116:9: note: here
         case 3: res <<= 8; res |= *data++; /* FALLTHRU */
         ^~~~
/home/nodey/monero/src/common/base58.cpp:116:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 3: res <<= 8; res |= *data++; /* FALLTHRU */
                            ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:117:9: note: here
         case 4: res <<= 8; res |= *data++; /* FALLTHRU */
         ^~~~
/home/nodey/monero/src/common/base58.cpp:117:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 4: res <<= 8; res |= *data++; /* FALLTHRU */
                            ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:118:9: note: here
         case 5: res <<= 8; res |= *data++; /* FALLTHRU */
         ^~~~
/home/nodey/monero/src/common/base58.cpp:118:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 5: res <<= 8; res |= *data++; /* FALLTHRU */
                            ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:119:9: note: here
         case 6: res <<= 8; res |= *data++; /* FALLTHRU */
         ^~~~
/home/nodey/monero/src/common/base58.cpp:119:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 6: res <<= 8; res |= *data++; /* FALLTHRU */
                            ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:120:9: note: here
         case 7: res <<= 8; res |= *data++; /* FALLTHRU */
         ^~~~
/home/nodey/monero/src/common/base58.cpp:120:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 7: res <<= 8; res |= *data++; /* FALLTHRU */
                            ~~~~^~~~~~~~~~
/home/nodey/monero/src/common/base58.cpp:121:9: note: here
         case 8: res <<= 8; res |= *data; break;
         ^~~~
cc1plus: all warnings being treated as errors
src/common/CMakeFiles/obj_common.dir/build.make:62: recipe for target 'src/common/CMakeFiles/obj_common.dir/base58.cpp.o' failed
make[3]: *** [src/common/CMakeFiles/obj_common.dir/base58.cpp.o] Error 1
make[3]: Leaving directory '/home/nodey/monero/build/release'
CMakeFiles/Makefile2:736: recipe for target 'src/common/CMakeFiles/obj_common.dir/all' failed
make[2]: *** [src/common/CMakeFiles/obj_common.dir/all] Error 2
make[2]: Leaving directory '/home/nodey/monero/build/release'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/nodey/monero/build/release'
Makefile:87: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by NanoAkron** [comment]
Thanks @xiphon

**Pull request closed without merging**
