### PR TITLE
portable serializer: unsigned/signed tx made portable, ignore archive version check, tests added

### PR DESCRIPTION
**Pull request by kenshi84**
[Issue #1551](https://github.com/monero-project/monero/issues/1511)

I realized that the error was caused when `boost::archive::archive_exception::unsupported_version` was thrown due to the version of the archiver reading the file being smaller than that of the archiver used to write the file. In other words, if my understanding is correct, the error was caused because a wallet built with an older version of Boost tried to de-serialize a file serialized by another wallet built with newer version of Boost.

I'm not sure if I'm doing the right thing, but removing the archiver version check allows me to read the wallet cache file in such cases. Will this change lead to any bad consequences in the future?

(I'm sorry to mess around with this relatively serious matter considering me being not such a skilled programmer. Help and wisdom from more experienced developers are highly appreciated.)

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Why were there two different versions in the first place, if it's using the boost code that you added to the monero tree ? Was it updated after addition ?

**Comment by kenshi84** [comment]
Similar to the official `binary_*archive`, portable ones also write/read the archiver's version in the beginning of the serialized file using a function `BOOST_ARCHIVE_VERSION()`, see [portable_binary_iarchive.hpp#L326](https://github.com/kenshi84/monero/blob/65ab67ba54e3f9984fca58a8551f278de0f457c9/external/boost/archive/portable_binary_iarchive.hpp#L326) and [portable_binary_oarchive.hpp#L281](https://github.com/kenshi84/monero/blob/65ab67ba54e3f9984fca58a8551f278de0f457c9/external/boost/archive/portable_binary_oarchive.hpp#L281)

I can see the function declaration at boost/archive/basic_archive.hpp, but strangely I couldn't find its definition anywhere. In any case, the version number seems to be somewhat correlated to the entire Boost version. As far as I tested with my Mac (Boost 1.60), Windows (Boost 1.62) and Linux (Boost 1.58), their archiver versions are 14, 14 and 12, respectively.

**Comment by moneromooo-monero** [comment]
OK, that makes sense. And in this case, I think disabling that check is OK. I find it a bit odd it'd use the main boost serializer version though, since it's a separate one.

**Comment by kenshi84** [comment]
How about the updated version where I pass `boost::archive::no_header` to the ctor of `portable_binary_*archive`? The code looks nicer in my opinion, but the downside is that the cache file is incompatible with those created by the released GUI. Probably I should stick to the previous code where the version info is simply read and ignored...?

**Comment by NanoAkron** [comment]
Maybe we could look at their version testing code and/or feed this issue back to them?

**Comment by moneromooo-monero** [comment]
Good catch. Always a bad idea to introduce known buggy stuff with a later fix you already have :)

**Comment by kenshi84** [comment]
@NanoAkron 
> Maybe we could look at their version testing code and/or feed this issue back to them?

Do you mean submitting an issue ticket to Boost? I'm not sure if that makes sense, since this behavior (i.e. rejecting files created by newer archive version) seems intentional.

@moneromooo-monero How about PR #1495?

**Comment by moneromooo-monero** [comment]
I can't test this 1495. Do you mean it'd be nice to test the serialization code on ARM ? If so, yes, it'd be nice :)

**Comment by kenshi84** [comment]
@moneromooo-monero I mean, PR #1495 fixes a linker error that only occurs with ARM.

**Comment by kenshi84** [comment]
I made unit tests for wallet cache, outputs, and unsigned/signed transactions. I left the testing of `cryptonote::trasnaction_prefix` as a future task since it's much more complicated than other structs. The tests seem to pass on all platforms on buildbot except with ARMs where the build doesn't succeed like all other PRs (due to undefined reference to abstract_variables_map).

**Comment by moneromooo-monero** [comment]
Unfortunate about the cache. Since the test doesn't actually make any transfers, you could just hack the wallet code to drop all but the genesis block hash before saving, just to save that cache.
Other than that, a pretty thorough test, nice one :)

**Comment by kenshi84** [comment]
@moneromooo-monero 
> you could just hack the wallet code to drop all but the genesis block hash before saving, just to save that cache.

Really smart idea, thanks! Now the wallet cache is only 2 KB :)

**Comment by NanoAkron** [comment]
Hi @kenshi84 do you know whether this warning message (repeated quite frequently during compilation) was introduced by your previous PR?

```
In file included from /home/x/monero/src/cryptonote_core/cryptonote_boost_serialization.h:41:0,
                 from /home/x/monero/src/cryptonote_core/blockchain.cpp:41:
/home/x/monero/external/boost/archive/portable_binary_iarchive.hpp: In member function ‘void boost::archive::portable_binary_iarchive::load_impl(intmax_t&, char)’:
/home/x/monero/external/boost/archive/portable_binary_iarchive.hpp:245:27: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     bool negative = (size < 0);
```

**Comment by kenshi84** [comment]
@NanoAkron Good point! Yes, the warning has existed since PR #1462 but only with ubuntu-arm7 and debian-armv8 builds as far as I can see on the buildbot. This warning is caused by [line 237 of external/boost/archive/portable_binary_iarchive.hpp](https://github.com/monero-project/monero/blob/dd580d7bc751018017e61f4852f68896f6edf620/external/boost/archive/portable_binary_iarchive.hpp#L237) where `char size` is assumed to be signed, which is [incorrect](https://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default#2054941) and compiler-dependent. This code was directly copied from the original Boost unofficial code, and I'm not so sure if this matter has had any real impact so far.

I'll post a PR about this. Thanks!

**Pull request merged**
