### PR TITLE
cmake: fix building when readline is not found

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by ston1th** [comment]
@moneromooo-monero I encountered an issue on OpenBSD where libreadline is available but it seems the version is too old:
```
/usr/bin/../lib/libreadline.so.4.0: undefined reference to `tgetnum'
/usr/bin/../lib/libreadline.so.4.0: undefined reference to `tgoto'
/usr/bin/../lib/libreadline.so.4.0: undefined reference to `tgetflag'
/usr/bin/../lib/libreadline.so.4.0: undefined reference to `tputs'
/usr/bin/../lib/libreadline.so.4.0: undefined reference to `tgetent'
/usr/bin/../lib/libreadline.so.4.0: undefined reference to `tgetstr'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (src/daemon/CMakeFiles/daemon.dir/build.make:279 'bin/monerod')
*** Error 1 in . (CMakeFiles/Makefile2:2395 'src/daemon/CMakeFiles/daemon.dir/all')
*** Error 1 in . (CMakeFiles/Makefile2:2407 'src/daemon/CMakeFiles/daemon.dir/rule')
*** Error 1 in /home/build/monero/build/debug (Makefile:721 'daemon')
```

This fixed it for me: `if(NOT Readline_LIBRARY OR OPENBSD)`

**Comment by moneromooo-monero** [comment]
cmake/FindReadline.cmake should probably test for a compatible version instead. This would also fix for other cases.

**Comment by iDunk5400** [comment]
It is failing to link to libncurses or libtermcap, its dependency. I have the same problem in MSYS2.

**Comment by hyc** [comment]
iDunk is correct. This error doesn't mean readline is incompatible. It only means you need to link some other dependent library in addition.

**Comment by ston1th** [comment]
Thanks for the hint.
I solved it, by adding this to the `FindReadline.cmake`:

```
if(Readline_LIBRARY AND OPENBSD)
  list(APPEND EXTRA_LIBRARIES curses)
endif()
```
Its currently just for OpenBSD, maybe this needs some extension.

**Pull request merged**
