### PR TITLE
Fix IPv6 addr parsing for boost <1.66

### PR DESCRIPTION
**Pull request by jagerman**
Fixes a compilation failure under pre-1.66 boost introduced with PR #4851

### CODE REVIEW

**Comment by xiphon** [comment]
> I don't see a reason to have two versions in use. Just use `from_string` without conditions, and put a todo about updating once the boost version updates.

The reason is that the current approach won't break monero build with the future boost versions that will eventually drop `from_string`.

Wouldn't suggest introducing a TODO just to patch this code once again later.

**Comment by vtnerd** [comment]
Then we update code when necessary and possibly bump the minimum Boost version. Currently this has two different testing paths depending on Boost version, which is less desireable.

Unfortunately the IPv6 PR added 0 unit tests, so no sanity checking against the particular Boost version in use can be done. That might be helpful too.

**Comment by trasherdk** [comment]
Any chance of this one getting merged anytime soon?
#4851 broke compilation on `slackware64 14.2`

**Comment by luigi1111** [comment]
Agree with @vtnerd and @jtgrassie 

Closing in favor of #5827

**Pull request closed without merging**
