### PR TITLE
[RFC] Attempt to improve parallel compilation

### PR DESCRIPTION
**Pull request by NanoAkron**
- Updated CMAKE version in certain CMakeLists.txt files
- Removed add_dependencies from various CMakeLists.txt files
- Centralised all add_dependencies into /src/CMakeLists.txt
- Explicitly listed all dependencies to try to improve parallel compilation

Not expecting this to be merged, just seeking input as discussed in #1209. 

Will delete after discussion.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Why are the dependencies on version moved away from where they were ?

**Comment by NanoAkron** [comment]
To try to collect everything in one place

**Comment by moneromooo-monero** [comment]
Why did you move *only* that, then ? All the make stuff for, eg, simplewallet, was in src/simplewallet/CMakeLists.txt, now there's part in the top level makefile, to keep things together ?

**Comment by NanoAkron** [comment]
To keep the dependency declarations together so I only had to go to one place when changing them to try to get it to compile in parallel. 

Can you compile with make -jX release or do you get compilation failures? Am I the only one who has to compile in a single thread on a quad core system with 2GB of memory?

**Comment by NanoAkron** [comment]
I opened this specifically for discussion of parallel compilation so others could pull in my PR and see what difference it makes to them, not so that it would get merged.

**Comment by iDunk5400** [comment]
I can compile with any -j I tried, usually -j4 to -j6.

**Comment by NanoAkron** [comment]
Well that's a good indication that it's my system that's not coping.

@iDunk5400 would you see if there's any improvement to your build process if we explicitly define the dependencies? If there's little to no change then I'll go ahead and close.

**Comment by iDunk5400** [comment]
Just realized this was about your ARMv8 build, but here are my results if you are still interested.
After several -j6 runs, Master was consistently under 3:50 and the best run was
real    3m40.317s
user    13m39.900s
sys     0m34.228s

PR1217 was consistently around 4:00 with the best run at
real    3m57.638s
user    13m34.640s
sys     0m33.684s

**Comment by moneromooo-monero** [comment]
fwiw, I don't run with -j, and can't test that as I can get up to 1.5 GB on that VM.

**Comment by NanoAkron** [comment]
@iDunk5400 thanks very much for the results, and thanks @moneromooo-monero too.

I'll close this now and sadly have to put it down to my little machine not coping with anything more than single threaded compilation :(

**Comment by radfish** [comment]
@NanoAkron Each thread requires up to ~2GB of RAM. Are you sure you have enough RAM on your build host to support -jN, so around N* 2GB?

I built with -j8 on a Digital Ocean huge droplet. But it took me at least 10mins IIRC (@moneromoo-monero must have pretty magic hardware to get 3min).

I am confused about your patch. CMake first processes all the CMakeLists scripts, builds a dependency graph, then executes recipes for the nodes in that graph. The layout of script files shouldn't matter. There might be some false dependency edges now -- is this what you were after?

**Pull request closed without merging**
