### PR TITLE
return subaddress in get_bulk_payments

### PR DESCRIPTION
**Pull request by onemanstartup**
It's only suggestion.

Why i want this? Because if I save subaddress in my database and I want to check if payment was made on this address and the only way to do this through rpc is query all adresses and find this address by subindex and this is very ineffective.

Sorry, I don't c++, but it's working here.
I don't know what rpc_payment data structure, only tested like this
`
rpc_payment.payment_id   = m_wallet->get_subaddress_as_str(payment.second.m_subaddr_index);
`

### CODE REVIEW

**Comment by onemanstartup** [comment]
@moneromooo-monero yes I want just the address. Working with indices in external application is harder then just using addresses. I can call get_address, but I'll have to map all payments to subaddresses. And size of response could be very big if you have many addresses. It's easier to work with abstractions rather with internals.

I will understand if you don't want to add this. Thanks

**Comment by emesik** [comment]
@onemanstartup could you please add it to `get_payments` as well? Let's keep them in sync.

**Comment by onemanstartup** [comment]
@emesik This is really pseudo-code, not actually production code. I'm sorry, I am new in in monero and I'm not a c++ programmer. This is just a suggestion. 
For now I'm iterate through all addresses and find address through corresponding subaddr_index.

**Comment by stoffu** [comment]
#2916

**Comment by onemanstartup** [comment]
@fluffypony Noooooooo. You are not reviewed this. Right pull request is here - https://github.com/monero-project/monero/pull/2916 by @stoffu 
My request was only suggestion, it's not production code.

**Comment by onemanstartup** [comment]
Ok, maybe I'm wrong. stoffu pull request have the same line as mine. lol. Thanks

**Comment by moneromooo-monero** [comment]
Sorry, I got mixed up and flagged it for merge, it will be reverted.

**Comment by onemanstartup** [comment]
@moneromooo-monero no worries, not that I wouldn't like to be a contributor, but merges without keeping authors anyway :)
Thanks for merging solution for suggestion anyway, that's main thing. ❤️

**Comment by stoffu** [comment]
Sorry for the confusion; I should've advised you to close this PR in favor of #2916.

**Pull request merged**
