### PR TITLE
Improve command naming and documentation

### PR DESCRIPTION
**Pull request by Cifrado**
Improved command naming of some commands:

- `start_save_graph`and `stop_save_graph` are now `save_graph (start|stop)`
- `limit [<Kb/s>]`, `limit_up <Kb/s>` and `limit_down <Kb/s> are now `limit [[up|down] <Kb/s>]`
- ...

Added a documentation section for commands reachable with `help [<command>]`.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
As a first sanity check, you seem to have lots of irrelevant changes that come from other places.
Also, I'm not a fan of arbitrarily changing stuff (in this case, command names). Maybe there's a good reason (apart from the very subjective "I like it better") ?

**Comment by Cifrado** [comment]
Some changes that I didn't made have indeed been included for no apparent reasons. Those changes appear to be the latests merged pull requests (39bc39b86e12f5429a6699fabca71e45f9bbd0a2, 0d4d628805775a96ff7aeae687ee417b7f988895, 5c2dfe157b48a486eb2b92dcf8789b3b1eb20f60, c9a410e394dd5e1de16d853cb2ce59b189f2ae96, 3abd6f1fd054d7f13d6d162dc14d2e6b277c22f6, cd070874bf2f9c9579028f70b936e9709b73dd68, c4587e83f84fa0ecfcfa5c4538697ae96162afe2 and dc6a8014bdbde26468751b89a289d45b73095e51).

The commands that I "merged" together where the ones that do belong to a same group and have no reason to be separated in the `help` command whose output started to become quite long.  There where 3 main reasons:

1. Some commands did just perform a toggle of state and have no reason to be distinct (i.e. `hr_show` and `hr_hide` which can easily become in a more human readable way `hashrate (show|hide)` or `start_save_graph` and `stop_save_graph` which gives `save_graph (start|stop)`). This standard was already used in some way with the already existing `set_log (<level>|<{+,-,}categories>)`. Only commands which performed a toggle of state in a complex way should remain split IMHO (like the easy `stop_mining` but complex `start_mining <addr> [<threads>] [do_background_mining] [ignore_battery]`).

1. Some commands belonged to a single and precise category which was exploded. It is easier to remember a standard command like `limit [[up|down] <Kb/s>]` than the 3 previous separated ones: `limit [<Kb/s>]`, `limit_up <Kb/s>`, `limit_down <Kb/s>`. These commands do perform a complexer action than just a state toggle from the previous reason but do also look like `set_log (<level>|<{+,-,}categories>)` which performs an action within a same category.

1.  Finally, commands that perform different non-vital tasks whose output depends on a single parameter can be grouped to prevent spamming the `help` command. The typical command entering this category is the `print_pool [long|stats]` command which was previously split in three distinct ones (`print_pool_sh`, `print_pool_long` and `print_pool_stats`). For these commands there is a default action and then other optional actions depending on the arguments that acts as flags.

Only this last reason does imply a notion of "I like it better". In a mind set of saving place, a default action should be chosen. To take back the `print_pool [long|stats]` example, the command could have looked like `print_pool [short|stats]`. To make the choices of which option to choose I used the usual bash philosophy of "give the minimum, request for more".

**Comment by moneromooo-monero** [comment]
Those three points seem fairly subjective to me, and not very distinct. print_pool_stats is a totally different command that print_pool{sh,} fwiw. Anyway, I think I'd be fine with that but it would be nice to provide (maybe undocumented, if you hate the help spam) aliases so people's commands don't just stop working.

Also see a previous PR from binaryFate who wanted to change some command syntax to allow options (IIRC it might have been print_tx).

**Comment by Cifrado** [comment]
I do indeed think there is a lack of standardisation in the commands. Don't know where this could be discussed and created.

**Comment by Cifrado** [comment]
Gonna split this PR in two (one for the help section, one for the command naming).

**Pull request closed without merging**
