### PR TITLE
wallet: allow adjusting number of rounds for the key derivation function

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by stoffu** [comment]
@moneromooo-monero 
> Confusing that the value is consistently off by 1 and that you give 0 for 1.

You mean giving 0 to `kdf-rounds` makes it behave the same as before (running `cn_slow_hash` just once)? I made the help message 
```
  --kdf-rounds arg (=0)                 Additional rounds of key derivation function
```
such that it's consistent with the behavior (0 additional rounds = the same as before). If you think it's confusing, I can change it to represent the total number of rounds for the KDF and error out when 0 is given.

**Comment by moneromooo-monero** [comment]
Alright, let's have it be the number of rounds minus 1 then.
Also size_t size is platform dependent. Though admittedly if you ask for 4 billion rounds, it'll take forever so maybe it doesn't matter...

**Comment by stoffu** [comment]
@moneromooo-monero 
OK, I specified `uint64_t` just in case someone might have insane computational power and want to perform more than 2 billion rounds of KDF :)

Also, removed the [WIP] tag as I don't see any further work to be added.

**Comment by stoffu** [comment]
Good point. Please see adjusted message in wallet2.cpp and wallet2_api.h.

**Comment by stoffu** [comment]
Now I got scared by your warning and opted for your way:) Please check.

**Pull request merged**
