### PR TITLE
Added Simplified Chinese electrum wordlist and re-ordered languages

### PR DESCRIPTION
**Pull request by NanoAkron**
Languages were re-ordered alphabetically to make it easier to slot-in future additions

Before merging, can a native Chinese speaker (preferably two) confirm that the words in the list are:

1. Common
2. Correct (i.e. simplified Chinese and not Traditional)

And ideally test out making a wallet with the new wordlist.

Paging @zhizhongzhiwai @p1gd0g

My next plan is to rename all the languages into their own native names, and re-organise the list presented to the user on the CLI once again

### CODE REVIEW

**Comment by zhizhongzhiwai** [comment]
this is 1626 simplified chinese wordlist :  [word list](https://paste.fedoraproject.org/paste/MY~9iri1UoGqpy~anAuMUl5M1UNdIGYhyRLivL9gydE=)

some tips:
1: common
2: corrent
3: unique
4: Remove the Chinese characters that are not easily distinguishable(eg, 日vs曰,  人vs入， 未vs末...)

**Comment by p1gd0g** [comment]
It's OK.

**Comment by moneromooo-monero** [comment]
I'd rather the Chinese list and the language reorderings are in separate commits, though I'll still be fine with this being merged as is.

**Comment by NanoAkron** [comment]
@moneromooo-monero I'll just do the list in this one, and re-order + native languages in selection in a separate PR. Let me change it around.

**Comment by NanoAkron** [comment]
@zhizhongzhiwai Thank you very much for your list! I compared the two and yours is quite different. May I ask - did you make your list? I took mine from the electrum repository, the same person who created the Japanese, Portuguese and Spanish lists that we use.

**Comment by zhizhongzhiwai** [comment]
@NanoAkron 

:->

Yes, i make the word list inspect electrum.
There are some misunderstandings
I think that you need to map wallet seed to chinese words.

Is the words order  important for map seed to chinese words??

If the order is important, i will reserve the first 1626 chinese words from [electrum](https://github.com/spesmilo/electrum/blob/e30a179c974cc2885be37b48d79703935b67eaee/lib/wordlist/chinese_simplified.txt), and remove the other words, 

is't ok?

**Comment by zhizhongzhiwai** [comment]
@NanoAkron 
the words list i maded is subset [electrum simple chinese words](https://github.com/spesmilo/electrum/blob/e30a179c974cc2885be37b48d79703935b67eaee/lib/wordlist/chinese_simplified.txt)

**Comment by dternyak** [comment]
@zhizhongzhiwai I don't think we need a mapping of the words.

We just want to make sure the words are correct, and that they are simplified Chinese and not Traditional.

I hope you did not spend too much time re-arranging the words so that they are mapped by line to the english word.

**Comment by zhizhongzhiwai** [comment]
@dternyak   @NanoAkron 

thanks a lot.  


the words list i maded **is subset** of [electrum simplified chinese word](https://github.com/spesmilo/electrum/blob/e30a179c974cc2885be37b48d79703935b67eaee/lib/wordlist/chinese_simplified.txt).
i have checked the electrum simplified chinese words, the words is correct and not traditional chinese words.

the words list i have maded have some improvement.  the words list Remove the Chinese characters that are not easily distinguishable(eg, 日vs曰, 人vs入， 未vs末...)



this is new word list based on electrum simplified chinese word, reserve the first 1626 words, remove the other.  [new words list](https://paste.fedoraproject.org/paste/Jwfc79LKKxteCtYzdDtvbl5M1UNdIGYhyRLivL9gydE=)

**Pull request closed without merging**
