### PR TITLE
Updated Swedish translation based on changes to source (and fixed typos)

### PR DESCRIPTION
**Pull request by ordtrogen**
Changes to source strings caused by #3093

### CODE REVIEW

**Comment by Maxithi** [comment]
Conflict fixed by #3184 . Only typos should be needed.

**Comment by ordtrogen** [comment]
Thanks, @Maxithi 

Between reporting issues, PRs and merges, I had missed that your fix was already in the pipeline :-) At least the typos from my initial translation can get corrected.

I reported the initial issue and expected to have to PR it myself, but you beat me to it. Great work!

**Comment by fluffypony** [comment]
I spoke too soon - please rebase :)

**Comment by erciccione** [comment]
@ordtrogen please rebase on #3275

**Comment by ordtrogen** [comment]
If it's OK, I'd prefer closing this PR and create a new one with only typos, after this round of merges instead of figuring out how to rebase. Based on experience w/squashing, I'll prolly just mess it up anyway  :-)

(frees up time for higher prio work)

**Pull request closed without merging**
