### PR TITLE
Clsag reviewed rebased

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by selsta** [comment]
Conflicts with src/cryptonote_config.h

**Comment by ph4r05** [comment]
Any plans for CLSAG branch merge to the master?
I would enable the Trezor support then. Thanks

**Comment by selsta** [comment]
> Any plans for CLSAG branch merge to the master?

Yes, while the code is audited we wait for one more code review.

**Review by xiphon — APPROVED** [review]

**Review by xiphon — APPROVED** [review]

**Comment by Snipa22** [comment]
@moneromooo-monero Looks like rebase needed again.  It's the next merge to be pulled in, looks like just the HF version colliding w/ the new requirement for full coinbase value takes.

**Pull request merged**
