### PR TITLE
Turn off readline for GUI

### PR DESCRIPTION
**Pull request by jonathancross**
Improved fix for [#868 as suggested by](https://github.com/monero-project/monero-core/pull/868#issuecomment-339450211) @hyc 

[needs testing]

### CODE REVIEW

**Comment by radfish** [comment]
@hyc's point is clear.

Problem is, without the other patch to monero-core, distros will no
longer be able to build two binary packages from a single source
package, without building everything twice.

I think the real fix is to untanble the dependency of readline from the
API libs. Only the daemon's front-end should depend on readline, not
any of the API libs. How do references to rl_* end up in API libs?

**Comment by hyc** [comment]
@radfish All of the console handling is done in epee. I agree the code organization is ... braindamaged but extricating that from the rest of epee is non-trivial.

**Comment by hyc** [comment]
Looking at the source tree again, I only see console_handler.h being included in daemon and simplewallet. Not sure why rl_* is being referenced anywhere else.

**Comment by moneromooo-monero** [comment]
This is probably moot now, as epee is split in two, with the epee_readline part in a separate lib.

**Comment by hyc** [comment]
Agreed, this PR has been obsoleted by #2736

**Comment by fluffypony** [comment]
Closing in favour of #2736

**Pull request closed without merging**
