### PR TITLE
GCC: Suppress -Wstringop-overflow= warnings in external/boost

### LINKED ISSUE #8320: Compiler warnings: writing 1 byte into a region of size 0
After I upgraded my Ubuntu distro to Ubuntu 22, I got the following warnings when compiling:

```
In file included from /home/jeff/forks/monero/external/boost/archive/portable_binary_oarchive.hpp:32,
                 from /home/jeff/forks/monero/src/p2p/net_peerlist.cpp:37:
In function ‘void boost::archive::reverse_bytes(signed char, char*)’,
    inlined from ‘void boost::archive::portable_binary_oarchive::save_impl(intmax_t, char)’ at /home/jeff/forks/monero/external/boost/archive/portable_binary_oarchive.hpp:267:26:
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;
      |         ~~~~~~~^~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:48:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   48 |         *last = *first;
      |         ~~~~~~^~~~~~~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;
      |         ~~~~~~~^~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:48:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   48 |         *last = *first;
      |         ~~~~~~^~~~~~~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;
      |         ~~~~~~~^~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:48:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   48 |         *last = *first;
      |         ~~~~~~^~~~~~~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;
      |         ~~~~~~~^~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:48:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   48 |         *last = *first;
      |         ~~~~~~^~~~~~~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;
      |         ~~~~~~~^~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:48:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   48 |         *last = *first;
      |         ~~~~~~^~~~~~~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;
      |         ~~~~~~~^~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:48:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   48 |         *last = *first;
      |         ~~~~~~^~~~~~~~
/home/jeff/forks/monero/external/boost/archive/portable_binary_archive.hpp:49:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
   49 |         *first = x;

```

Here's my system info:

```
OS: Ubuntu 22
g++: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
```

### PR DESCRIPTION
**Pull request by jeffro256**
Resolves #8320

### CODE REVIEW

**Review by selsta — COMMENTED** [review]
Seems like we use macros in other places for this, can you check if this works?

```
PUSH_WARNINGS
DISABLE_GCC_WARNING(no-stringop-overflow)
        char x = *last;
        *last = *first;
        *first = x;
POP_WARNINGS
```

**Comment by jeffro256** [comment]
Yeah I thought about doing that, but I didn't want to add the epee dependency. Almost all modern compilers recognize `#pragma GCC ...` and will at worst do nothing.

**Review by selsta — APPROVED** [review]
Oops, didn't even notice that it's in `external/boost/`, yea adding epee here would be bad.

**Review by tobtoht — APPROVED** [review]

**Comment by selsta** [comment]
```
In file included from /Users/selsta/dev/monero/src/blockchain_utilities/blockchain_ancestry.cpp:33:
In file included from /Users/selsta/dev/monero/external/boost/archive/portable_binary_iarchive.hpp:33:
/Users/selsta/dev/monero/external/boost/archive/portable_binary_archive.hpp:48:32: warning: unknown warning group '-Wstringop-overflow=', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wstringop-overflow="
                               ^
1 warning generated.
```

now i get warnings with clang

**Comment by jeffro256** [comment]
Agh that's not supposed to happen! Eye for an eye I guess. I'll make a quick update

**Pull request merged**
