### PR TITLE
Make get_random_gray_peer distribution uniform

### PR DESCRIPTION
**Pull request by IPGlider**
```get_random_gray_peer``` should use an uniform distribution. Explained in #1684

### CODE REVIEW

**Comment by iamsmooth** [comment]
It is not clear to me that this is better. Is it using a non-uniform distribution for some reason? Maybe to prefer peers based on age?

**Comment by IPGlider** [comment]
This is one of the first contributions I did a few weeks ago, based on a white paper, it should really be a uniform distribution.

As I was new here and did not want to break anything, used the same code for the random selection, my bad.

**Comment by NanoAkron** [comment]
Do you want to put the index of the grey peer selected into the log?

**Comment by IPGlider** [comment]
There is no need to log there. Evictions and promotions are logged in https://github.com/monero-project/monero/blob/master/src/p2p/net_node.inl#L1768-L1791.

**Comment by moneromooo-monero** [comment]
If you're making a patch based on recommendations from a paper, please include a link to the paper (or a reference if not online) in the commit message, it will help evaluate the patch (ie, at least we know it's not an arbitrary change).

**Comment by iamsmooth** [comment]
Agree with @moneromooo-monero this needs further justification, white paper, simulations, etc. Things seem to be working okay now, I do not at all understand what problem is being addressed or alleged improvement is being made.

**Comment by IPGlider** [comment]
In PR #1600 I added the feelers connections explained in https://eprint.iacr.org/2015/263.pdf page 12, in that PR I added the ```get_random_gray_peer``` function.

That PR was one of the first ones I did and I did not want to mess anything related to randomness, so I took the code from ```random_index_with_fixed_probability``` and after doing some tests used it in ```get_random_gray_peer```.

When I did the aforementioned tests I saw that the value 0 was returned more often that it should, but didn’t think too much about it.

After doing PR #1684, I was pointed that the code was strange and looked further into it as explained in that PR. Once I understood how that randomness works I thought that it would be better if ```get_random_gray_peer``` used a uniform distribution.

That is the motivation for this PR.

Let me know if you need any further information.

**Comment by moneromooo-monero** [comment]
It does seem OK in theory, assuming it really follows the paper, which I've not checked. However, does it check for an empty gray list first ? I've not checked as there's not enough context that's visible, but it'd introduce a division by zero otherwise. There's also a gratuitous variable rename which adds an unrelated diff, though that's minor.

**Comment by moneromooo-monero** [comment]
Also, you previous patch was factoring two places where this cubic distribution was used. Are you modifying just one of them ? If so, why ?

**Comment by IPGlider** [comment]
The check to prevent the division by zero is in place.

I'm just changing the place I'm sure about. I have not dedicated time yet to comprehend why is done that way in the other place, and therefore it is not a good idea that I modify it.

**Comment by iamsmooth** [comment]
> Once I understood how that randomness works **I thought that it would be better if get_random_gray_peer used a uniform distribution.**

Based on what? Math? Simulations? Paper? Please cite something.

**Comment by NanoAkron** [comment]
@iamsmooth he did link a paper in his reply to you further up. I suggest you read it.

**Comment by moneromooo-monero** [comment]
It is not in the commit message, but should be.

**Comment by IPGlider** [comment]
> Based on what? Math? Simulations? Paper? Please cite something.

Based on the explanation I gave in https://github.com/monero-project/monero/pull/1684#issuecomment-277554159 where is pointed out that the randomness currently used is biased.

The paper does not says anything about using that bias. Why keep the biased one instead of the uniform in this function?

**Comment by moneromooo-monero** [comment]
I assume:
- this patch is to match the 2. Random selection" step of "7. Countermeasures".
- the tried list in that paper is our gray list

If so, this seems like a good change, and please include this particular "2. Random selection" note in the commit message. Things like this are good to know when working with git history.

**Comment by iamsmooth** [comment]
> Why keep the biased one instead of the uniform in this function?

Because the network is working fine right now. A change could cause it to work worse or possible fail altogether (in the sense that nodes are no longer able to reliably find and connect with peers).

I have not read the paper, but from the title it applies to Bitcoin. Bitcoin's p2p network is not the same as Monero, though obviously it shares some concepts in common. 

It certainly is the case that the random function in the current code is biased, but it was also obviously done that way for a reason.

I do not thing the behavior should be changed without some sort of analysis, simulations, etc. to characterize how the change will play out on a large decentralized scale (including an indeterminate mix of both a mix of old and new nodes)

**Comment by NanoAkron** [comment]
@iamsmooth I think you have put too much faith in the belief that the system was designed perfectly in the first place and that any changes must therefore be heavily justified.

In reality the codebase was built as a best guess, and should always be seen as a work in progress.  Any thoughtful improvement based on actual published research is welcome.

May I strongly advise you yet again to read the paper. This is the second time that your misapprehensions would have been cleared up by reading the paper.

Your concerns sound awfully similar to those which emerged at the beginning of the block size debate - 'we don't know what will happen, the sky might fall, we need years of simulations!'

**Comment by moneromooo-monero** [comment]
Those arguments don't seem very persuasive.

The P2P system might or might not have been designed perfectly, but the last few years have shown that it works.

The fact that is it is work in progress does not mean any particular change is better than none.

Paralysis may be better than a change which makes things worse.

On the other hand, arguments which do sound persusaive to me are:

Research was made on a similar system, and shown to make things better

Simulation on the current system showing the patch does indeed make things better

**Comment by fluffypony** [comment]
Just to add to smooth's comment: I'm the first to moan about how the original CN reference code had no comments, had some utterly bizarre choices, and (honestly) looked a little cobbled together. But underneath that was some truly good work, including the decision to separate daemon and clients; or the very extensive test suite (which Bitcoin never had) consisting of both unit tests, functional tests, load tests, and performance tests.

We can (and should) ridicule the badness that infested the original reference code, but we should not assume that all the decisions were taken in isolation, or that all of them were bad.

For this specific decision, consider epee's author, Andrey N. Sebelnikov, a man accused by Microsoft to be [the developer of the code for the Kelihos botnet](https://krebsonsecurity.com/2012/09/malware-dragnet-snags-millions-of-infected-pcs/). Since epee is used nowhere else on the planet (except, probably, in Andrey's botnet software;) it is reasonable to assume that he also contributed to the reference code, and participated in the decision making process. Is it not reasonable to assume that a botnet author, with the knowledge he has on unreliable client devices on the Internet, might have some logical reason for motivating for the distribution?

So should we change the distribution? Maybe. Possibly. But must we? Undoubtedly not, barring some actual evidence. I'm happy to motivate that this goes live on testnet for us to monitor and evaluate, but I see little value in deploying it on to mainnet without some research that indicates that the original decision was bad.

**Comment by IPGlider** [comment]
I want to make a point clear, I'm not sure I explained myself well enough previously.

This PR changes code that was introduced a few weeks ago by me, never touched a release. I tried to explain it in https://github.com/monero-project/monero/pull/1687#issuecomment-277997077.

I'm don't intend to change the original place where the biased distribution is used. https://github.com/monero-project/monero/blob/master/src/p2p/net_node.inl#L822-L823

**Comment by iamsmooth** [comment]
> This PR changes code that was introduced a few weeks ago by me, never touched a release. 

My objections to this PR apply equally to 1600. There is analysis or simulation to show that such a change is helpful and not dangerous within the context of Monero's specific overall implementation of a p2p network.

The fact that you introduced the change in 1600 without understanding the behavior of the code you now propose to change here, nor analyzing the resulting behavior, nor simulating it, is more support for my point.

I believe that #1600 should also be reverted. That is not to say that these aren't good ideas and shouldn't make their way into the code once they are sufficiently analyzed and tested. They may very well be, but both of these are potentially damaging or breaking changes are currently presented without good support. You can't cherry pick one or two individual ideas from a paper or another algorithm and introduce them into a different algorithm (particularly a complicated decentralized algorithm where the _systemwide_ behavior is emergent) and expect that to necessarily work well.

**Comment by moneromooo-monero** [comment]
The fact that the bitcoin and monero network P2P behaviors are different, and thus the same recommendations might have different effects, is a good point. I might have been too readily convinced, and simulations would indeed be a good idea.

**Comment by NanoAkron** [comment]
So let's invite the original authors of the eclipse attack paper to work with us on this.

**Comment by NanoAkron** [comment]
Also, would anyone care to enumerate which of the proposals in the eclipse paper would be accepted without further extensive research, so that @IPGlider doesn't misallocate his time at this stage?

**Comment by moneromooo-monero** [comment]
IPGlider, would you be interested in making a monero network simulator to test whether these changes are actually of benefit to monero ?

**Comment by IPGlider** [comment]
### Setup:

- Two daemons built from master 3473af00, one with PR #1600 and #1687 the other without both of them.
- p2pstate.bin removed to start with empty tables.
- Incoming connections disabled.
- Sampling each 60 seconds approximately.
- Period of data gathering of approximately 6 hours.

### Data:

white

gray

| -  | white list fullness  | gray list fullness |
| - | ------------- | ------------- |
| **master with** | 14.4%  | 29.56%  |
| **master without** | 1.3%  | 19.34%  |


### Short analisys:

As can be observed in the figures, the white list grows arithmetically and the grey list logarithmically.

Both tables get filled faster in the version ‘with’. Having more white peers means having more tried and working (at the moment of the test) connections to other nodes of the network, making easier connections to the network upon restart or when one outgoing connection fails. In spite of the evictions from the gray list, can be observed that the number of gray peers does not decreases drastically.

Phases of non growth in the white list mean failed connections to peers from the gray list and their respective eviction.

The peer lists would continue to grow until they hit the hardcoded limits, 1000 for the white list and 5000 for the gray list, when that happens the eviction mechanism kicks in. The tables would still be full, or near full in the case of the gray list, but with more recently tested peers.

The tradeoff is one outgoing connection open each 60 seconds approximately for the connectivity test and the handshake, the connection is closed afterwards.

There are multiple little things that can improve the system, some from the aforementioned paper and some I have seen reading the code and observing the current behaviour.

Let me know if you need any further information.

**Comment by IPGlider** [comment]
@moneromooo-monero I may be interested, but I don't know if I have enough free time. We can talk about it.

**Comment by moneromooo-monero** [comment]
This is something that can be drawn out over time anyway as there's no urgency, so the lack of time isn't too bad an obstacle, it just slows it down to wherever you want to put a bit of time in it. fluffypony had some ideas about using https://shadow.github.io/ in that regard, though there are probably other projects one could select instead.

**Comment by NanoAkron** [comment]
Got to say, I'm going to start running this on my node. I find the large multi-tiered peer list with an eviction mechanic to be a convincing benefit, and the use of a though-out uniform distribution versus an (as-yet) unexplained cubic distribution.

**Comment by fluffypony** [comment]
@IPGlider thanks for the additional research and work! Not sure if you're on IRC in #monero-dev, but just to update you: we're VERY close to tagging v0.10.2 so that we can release the 2nd beta of the GUI, so I'd like to leave merging this till after the tagged release, that way we don't add anything to the network that almost everyone will update to. It gives us plenty of time till the next point release to have this live on all our nodes (testnet and mainnet) and to see how they behave:) Thanks again for all the effort you've put into this!

**Comment by IPGlider** [comment]
@fluffypony If no network changes are desired for this point release there are two things to comment.

https://github.com/monero-project/monero/blob/master/src/p2p/net_node.inl#L1519-L1524 and https://github.com/monero-project/monero/blob/master/src/p2p/net_node.inl#L1158

I absolutely understand that this should be tested. The last two weeks I have been reading documentation and the two papers published about the Shadow network emulator and tried to build a plugin to integrate monerod into it, but I have found it hard because my lack of knowledge of the cmake build system. I would like to continue the work in this or any other area.

**Comment by NanoAkron** [comment]
Hi @IPGlider would you consider submitting a second PR to change the second location that the cubic distribution is found into a uniform one? I do not believe there is any advantage to such a strongly biased distribution anywhere in the codebase, and I'd like to spin up a node with both these altered.

Thanks!

**Comment by IPGlider** [comment]
@NanoAkron I finally understood why that distribution is used and found some problems in the P2P system.

I'm working on some bigger changes that includes the removal of that distribution. I have already a prototype of design on paper, but will take me some weeks for the implementation and testing.

**Comment by NanoAkron** [comment]
Do the same reasons extend to using the cubic distribution in both places?

**Comment by moneromooo-monero** [comment]
>  I do not believe there is any advantage to such a strongly biased distribution anywhere in the codebase

Maybe the requested change is fine, I'm not sure what you're refering to exactly, but this argument is unpersuasive.

**Pull request merged**
