### PR TITLE
cryptonote_protocol_handler.inl: remove span read just now that failed to pass some basic tests

### PR DESCRIPTION
**Pull request by stoffu**
To fix #3718.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Yes, the code was wrong, so I asked stoffu to fix it. It still worked fine.

**Comment by NanoAkron** [comment]
So why have some been changed from `true` to `1` and others from `1` to `true`? Looks a bit arbitrary.

**Comment by el00ruobuob** [comment]
It's not arbitrary at all. Look at the function type. The Boolean are returning true. The integer are returning 1. It is perfectly done.

**Comment by NanoAkron** [comment]
Ah. Thanks!

So there's a compiler error with interpreting `true` as `1` in integer functions?

**Comment by stoffu** [comment]
No, it’d only cause a warning message.

**Pull request merged**
