### PR TITLE
fix uninitialized variables

### PR DESCRIPTION
**Pull request by MaxXor**

### CODE REVIEW

**Comment by MaxXor** [comment]
@moneromooo-monero The first one (`ignored_blob_size`) is definitely a read operation, it acts as a constant in the same line. I'm not 100% sure about the second one, but should be correct too.

**Comment by moneromooo-monero** [comment]
I've just checked the code, and:

In the first case, the blob size is written by get_object_hash. It's not an input, as seen in "bool get_object_hash(const t_object& o, crypto::hash& res, size_t& blob_size)" in cryptonote_format_utils.h.

In the second case, a version < 6 means it's a read operation from a file written by a previous version of the software.

If you think any of these are wrong, can you explain in more detail please ?

**Comment by moneromooo-monero** [comment]
Have you had a chance to check ?

**Comment by MaxXor** [comment]
@moneromooo-monero Yes, I see now that the first one is actually useless.

**Pull request closed without merging**
