### PR TITLE
simplewallet: tell the user to complain to the recipient

### PR DESCRIPTION
**Pull request by moneromooo-monero**
for long payment ids

### CODE REVIEW

**Comment by SRCoughlin** [comment]
Is there a way to restate this diplomatically?

**Comment by NanoAkron** [comment]
'and kindly inform the recipient'?

**Comment by moneromooo-monero** [comment]
It's already restated in a polite format :D

**Comment by moneromooo-monero** [comment]
Is "warn" OK ? Inform sounds optional, warn sounds more urgent.

**Comment by jtgrassie** [comment]
I agree "warn" is the right word to use here and this message is polite.

Can I suggest changing to:
"...and warn the recipient they are using an deprecated feature that will disappear in the future"

**Pull request merged**
