### PR TITLE
DRY changes

### PR DESCRIPTION
**Pull request by tewinget**
Changes to the core code to make things cleaner and make using the core code for the new zmq rpc nicer.

I was asked to separate these changes into their own PR, so here we are.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Pedantically, it'd be great if commit messages could be of the form "blockchain: refactor whatever it is that's being refactored", makes it easier when searching git log.

**Comment by dternyak** [comment]
@tewinget Do you mind changing the commit messages as @moneromooo-monero suggests? It seems this is close to merging otherwise.

**Comment by tewinget** [comment]
I thought I had already done so...seems I confused these commits with the
others.  Will take care of it tomorrow when I rebaae everything.

**Comment by tewinget** [comment]
Seems I'd forgotten to redo commit messages.  Should be better now.

**Comment by moneromooo-monero** [comment]
No, it isn't done, but that's minor, just please try to do this on future commits, it's helpful when debugging.

**Comment by anonimal** [comment]
I thought DRY was an acronym for a new protocol... Clicked here to see otherwise 😕

**Pull request merged**
