### PR TITLE
New add_aux_pow RPC to support merge mining

### PR DESCRIPTION
**Pull request by moneromooo-monero**
Note about possible conflict of interest: I made this patch for the benefit of another coin. However, I believe making it easier to merge mine is beneficial to monero due to the chance to get additional hash rate from (ideally) many merge mined chains.

### CODE REVIEW

**Comment by sethsimmons** [comment]
Is this being added to Monero to simplify Tari merge-mining specifically?

Curious, as I haven't heard any other coin mention Monero MMing outside of them.

**Comment by moneromooo-monero** [comment]
After the IRC chat, I want to make clear that this patch is not strictly needed for a coin to merge mine with monero: this patch just makes it (much) easier. If it is not merged, every coin wanting to merge mine with monero will still be able to do so, but will have to include some some software that manually alters the extra field in the coinbase tx to include the merkle root of the aux blocks (which is indeed what Tari originally did).

**Comment by moneromooo-monero** [comment]
It has to be a bit more complicated to prevent a hash reuse attack. A nonce needs adding to generate fixed positions for each chain in the aux pow merkle tree. I'll change the patch soon to do this.

**Comment by moneromooo-monero** [comment]
Bug fix, rebase, and get rid of a rider patch that got rejected earlier.

**Comment by selsta** [comment]
CORE_RPC_VERSION_MINOR bump missing :)

**Review by selsta — APPROVED** [review]

**Pull request merged**
