### PR TITLE
Don't lie about scrubbed<T> being a POD type.

### PR DESCRIPTION
**Pull request by jroelofs**
@vtnerd I couldn't find a nice way to specialize the epee / string utils for this, so adding back `inner()` seems reasonable... unless you have an idea for a better trick.

### CODE REVIEW

**Comment by jroelofs** [comment]
https://github.com/monero-project/monero/commit/7193b89fe567327bb78f4c61c887b2e2fad2ed51#r26372001

**Comment by vtnerd** [comment]
I issued a [PR with a less obvious name](https://github.com/monero-project/monero/pull/2969) yesterday. It relaxes the requirements to `std::is_standard_layout`. Although, now that I think about it some more, the better fix is probably a mix of these two patches. The read-only version (pod-to-hex) can be `is_standard_layout`, but the writable version (hex-to-pod) requires `is_pod` because subverting copy/move/destruction behavior is UB. The benefit is that only a few places have hex-to-pod for the secret key.

**Comment by vtnerd** [comment]
Oh and @jroelofs  ... some bikeshedding - how about `data()` ? That's a more common term, although its used differently here than in other contexts.

**Comment by stoffu** [comment]
@vtnerd About bikeshedding: I'm not sure about that, but I might find it a bit weird that the raw byte array is accessed like `skey.data().data()`. `data()` for `std::vector` and others usually imply the raw pointer to the head of the internal storage, which seems to serve quite a different purpose than `inner()` (which is literally to access the inner type object).

**Comment by jroelofs** [comment]
Do you think `operator*()` would be too un-obvious? That seems to work nicely for `boost::optional` where it sort of means "give me what's in this thing" in the same way it does for pointers. 

Another possibility would be to add:

```
template<typename T>
const T &unwrap(const scrubbed<T> &S) {
  return S;
}
```

I don't have a strong preference for any of these; they all seem like undesirable churn.

**Comment by vtnerd** [comment]
I do think `operator*` would be too un-obvious. `unwrap` or `inner` is probably better.

And FYI - I updated [my pr](https://github.com/monero-project/monero/pull/2969). This includes the `unwrap` suggestion, and relaxes the restriction on `pod_to_hex` to `is_standard_layout`. So that gives an idea of what the alternate implementation would look like.

**Comment by jroelofs** [comment]
Abandoning this in favor of PR2969.

**Pull request closed without merging**
