### PR TITLE
device: remove Ledger timeout

### LINKED ISSUE #4734: Sending with Ledger too many inputs timeout
I'm trying to send with the CLI Monero 'Beryllium Bullet' (v0.13.0.4-release) and I think I have too many inputs for the current timeout as on my ledger it displays:
`Monero: 45f7fds!`
forever when sending...

The command line interface has been issued the command (shorted for privacy etc):
`transfer wallet_address amount`

If I'm sending around 1 XMR or less then it works fine every time. But anything over 4-5 then then wallet will get stuck with the last entry and hang and Ledger shows above.

Here is the last part of the wallet file log. I'm not sure what parts of the CLI wallet file log I need to provide? A lot looks to be very sensitive info. However I think below is here in the log it takes over 2 mins to make the transaction:

```
2018-10-27 02:00:59.382             0x1044e95c0        INFO    perf    src/common/perf_timer.cpp:140   PERF    80266      PROVE_step4
2018-10-27 02:04:10.333             0x1044e95c0        INFO    construct_tx    src/cryptonote_core/cryptonote_tx_utils.cpp:599 transaction_created: <66gcsmfj624a
```

It seems to take too long to go from the Prove step to transaction created.

### PR DESCRIPTION
**Pull request by selsta**
Fixes #4734 and improves #4512 (no more timeout after two minutes in the fee menu).

I’ve tested this and it works but maybe there is a reason why there’s a timeout in the first place.

### CODE REVIEW

**Comment by selsta** [comment]
When is infinite wait a problem?

Increasing it to 6 minutes will work until the next person arrives with even more inputs.

**Comment by selsta** [comment]
`<moneromooo> I'd increase, because otherwise if there's a real comms breakdown, monero-wallet-cli hangs forever. But we'll do whatever cslashm prefers.`

ping @cslashm

**Comment by xiphon** [comment]
> When is infinite wait a problem?

Is is not cancellable.

> Increasing it to 6 minutes will work until the next person arrives with even more inputs.

Both ways ain't good (infinite blocking read and too long timeout).
The correct approach would be to implement async Ledger I/O.
But since is is not implemented yet, timeout increase is the only option at the moment.

**Comment by selsta** [comment]
Thanks @xiphon

I’ll close this PR and replace it with a PR that increases the timeout to 6 minutes.

Also I’ll look into async i/o but I think that’s too complicated for me lol.

**Pull request closed without merging**
