### PR TITLE
wallet: remove CLI code for non default ring sizes

### PR DESCRIPTION
**Pull request by jeffro256**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Does this prevent one from spending old pre-rct outputs with fewer than 16 outputs of that amount on the chain ?

**Comment by jeffro256** [comment]
This PR just removes dead code which confirms that users want to use a non default ring size, and stores that setting inside the wallet cache file, which they can't do anyways anymore.

**Review by tobtoht — APPROVED** [review]

**Comment by selsta** [comment]
Needs rebase.

**Comment by jeffro256** [comment]
Done

**Review by selsta — APPROVED** [review]

**Review by tobtoht — APPROVED** [review]

**Comment by luigi1111** [comment]
Needs rebase. 🥇

**Comment by jeffro256** [comment]
rebased again ;)

**Review by tobtoht — APPROVED** [review]

**Review by vtnerd — APPROVED** [review]

**Pull request merged**
