### PR TITLE
workflows: ubuntu 18.04 is deprecated

### PR DESCRIPTION
**Pull request by selsta**
And will soon be removed.

### CODE REVIEW

**Comment by hyc** [comment]
Every reference to bionic in contrib/gitian will need to be updated as well. And possibly some cross-compiler versions will need to be bumped up. This affects pretty much tne entire contents of that directory: *.yml, *.py, *.sh.

**Comment by selsta** [comment]
@hyc sorry, I meant the Ubuntu 18.04 VM image on Github Actions is deprecated and will be removed, so the workflows file is the only thing we have to change at the moment.

**Comment by jeffro256** [comment]
> Workflows using the `ubuntu-18.04` YAML workflow label should be updated to `ubuntu-20.04`, `ubuntu-22.04`, or `ubuntu-latest`

Shouldn't keeping the `ubuntu-latest` actions stay valid?

**Comment by selsta** [comment]
Yes, but ubuntu-latest is currently 20.04 and that would mean we test the same OS twice.

**Comment by plowsof** [comment]
Starting October 3rd - ubuntu-18.04 runners will randomly fail , approved

**Review by plowsof — APPROVED** [review]

**Review by SChernykh — APPROVED** [review]

**Pull request merged**
