### PR TITLE
Small grammatical and spelling fixes suggested by @BitcoinErrorLog

### PR DESCRIPTION
**Pull request by NanoAkron**
To replace #1400 which has been neglected for a week for such a small change

### CODE REVIEW

**Comment by NanoAkron** [comment]
@BitcoinErrorLog Ah, in which case I'm more than happy to close this in favour of yours so that you get the credit.

`rebase -i HEAD~2` 

then change `pick` to `squash` for the second commit

then edit the commit message

then `push --force` back to your repo, and the PR will automatically use the new code

**Comment by fluffypony** [comment]
Oh just saw the comments here - @BitcoinErrorLog do you want me to wait for you to update your PR?

**Comment by NanoAkron** [comment]
@fluffypony Is it possible to merge this one and credit it to @BitcoinErrorLog ?

**Comment by fluffypony** [comment]
@NanoAkron no, git bases it on whoever does the commit(s)

**Comment by expez** [comment]
@NanoAkron 

`git commit --amend --author="Author Name <email@address.com>"`

And then force push the change into this branch.  Not sure how this works if signatures are used.

**Comment by NanoAkron** [comment]
Thanks @expez but I'm afraid I don't think it'll work with signatures

OK should we wait for a day?

**Comment by fluffypony** [comment]
Won't work with signatures - also this isn't critical enough to rush it:)

**Comment by NanoAkron** [comment]
My OCD gets all twitchy leaving tiny PRs open ;)

**Comment by NanoAkron** [comment]
@BitcoinErrorLog Are you going to resubmit?

**Comment by BitcoinErrorLog** [comment]
Yes, I will not be including the "backup" edit though, as I think the rule is dumb and in conflict with common usage.

**Comment by NanoAkron** [comment]
Cool - closing this in favour of yours :)

**Pull request closed without merging**
