### PR TITLE
README.md change | Hyperlinked #monero-dev to IRC website

### PR DESCRIPTION
**Pull request by NajmAjmal**

### CODE REVIEW

**Comment by selsta** [comment]
Thank you, do you know how to squash your commits? This requires a git client and can't be done from the GitHub web interface.

**Comment by NajmAjmal** [comment]
@selsta 

To squash commits using Git in the command-line interface (CLI), follow these steps:

Step 1: Open a terminal or command prompt.

Step 2: Navigate to the Git repository where you want to squash the commits.

Step 3: Make sure you are on the branch that contains the commits you want to squash. You can use the following command to check your current branch and switch to the desired branch if needed:

```bash
git branch
git checkout <branch_name>
```

Step 4: Run the interactive rebase command using the following syntax:

```bash
git rebase -i HEAD~<number_of_commits_to_squash>
```

Replace `<number_of_commits_to_squash>` with the number of commits you want to squash. For example, if you want to squash the last 3 commits, use `git rebase -i HEAD~3`.

Step 5: An interactive text editor will open, showing the commit list in your chosen editor (e.g., Vim, Nano, or other default text editor). Each commit will have the word "pick" next to it.

Step 6: Change the word "pick" to "squash" (or "s" for short) for the commits you want to squash into the previous commit. Keep the word "pick" or remove the line for the commit you want to be the final commit.

Example of an interactive rebase file:

```
pick 2a3e45a Commit message 1
squash 7b86c23 Commit message 2
squash abcd123 Commit message 3
```

Step 7: Save and close the file. In Vim, you can do this by pressing `Esc` followed by `:wq`.

Step 8: Git will perform the rebase and squash the selected commits into the previous one. If there are any conflicts, Git will prompt you to resolve them. Follow the instructions to resolve conflicts, commit the changes, and continue the rebase.

Step 9: After the rebase is complete, check the commit history using `git log` to ensure that the squashing was successful.

Step 10: Finally, force-push the updated branch to the remote repository if you've already pushed the previous commits:

```bash
git push --force origin <branch_name>
```

**Comment by NajmAjmal** [comment]
Hi @selsta

I do not believe this specific PR requires a squash. This is simple text replacement to the README.md, and a normal merge from the GitHub website should suffice.

Thanks, Najm

**Comment by selsta** [comment]
A simple README change should not require two commits, that's why I asked you if you can squash your commits.

commits

**Comment by plowsof** [comment]
@NajmAjmal squash or it will never be approved/merged. Its also a trash PR considering the dev hyperlink is directly above. Close this PR and resubmit a fresh one if yiu cant squash commits.

**Comment by NajmAjmal** [comment]
Squashed: https://github.com/monero-project/monero/pull/8968

**Pull request closed without merging**
