### PR TITLE
blockchain: use high bound block reward on error where appropriate

### PR DESCRIPTION
**Pull request by moneromooo-monero**
If the block reward to use for the fee calculation can't be
calculated (should not happen in practice), use a high bound,
so we use a fee overestimate that will be accepted by the network.

### CODE REVIEW

**Comment by tewinget** [comment]
That amount seems a bit absurd, but beyond that I'd say this should be a
named constant or define somewhere.

I like the pr in concept though.

**Comment by NanoAkron** [comment]
I think we're trying to avoid magic numbers as much as possible

**Comment by moneromooo-monero** [comment]
I don't think it is absurd, current block reward is 9.5 monero AFAICT. Why do you think it is ?
I'll make it as a define though.

**Comment by tewinget** [comment]
I misread and thought you were defaulting to 10xmr per kb...woops

**Pull request merged**
