### PR TITLE
[RELEASE] disable asm w/ x64 instructions set on i386

### PR DESCRIPTION
**Pull request by naughtyfox**
Related to #5206. This fixes compilation on i386 arch.
If the PR is accepted I'll make a PR to master

### CODE REVIEW

**Comment by naughtyfox** [comment]
Oh, there's no jit on master yet. No need to make one more PR :)

**Comment by TheCharlatan** [comment]
I don't know much about these instructions, but shouldn't they be compatible across all x86 architectures?

**Comment by naughtyfox** [comment]
@TheCharlatan the problem is this code uses x64 extended registers which are not available on i386

**Comment by TheCharlatan** [comment]
This still needs to go into master.

**Pull request merged**
