### PR TITLE
wallet: rephrase error message on invalid device address

### PR DESCRIPTION
**Pull request by ph4r05**
A proposal to address issues like #7783, https://github.com/trezor/trezor-firmware/issues/1686
Added @dEBRUYNE-1 's improvement.

### CODE REVIEW

**Review by selsta — APPROVED** [review]

**Review by tobtoht — APPROVED** [review]

**Comment by ph4r05** [comment]
@dEBRUYNE-1 should this be opened also against release branch?

**Comment by selsta** [comment]
@ph4r05 yes please

**Comment by rating89us** [comment]
Possible causes for the "device wallet doesn't match wallet address" error are:
- User entered wrong passphrase.
- User opened a Monero GUI wallet file with non-blank PF but Trezor device has PF protection disabled.
- Trezor device has been initialized/restored with a seed that is different from the one used to create the Monero GUI wallet file.

The error message in this PR is only contemplating the first cause, but it should also contemplate causes #2 and #3.

**Comment by ph4r05** [comment]
#1 is the most common issue, hence we exicitly mention it in the error message as users are usually stil unaware how passphrase works.

#2 is a subset of #1 and I don't think we need to address this explicitly. If user disabled passphrase somehow, he likely knows how to enable it and Trezor Suite enables it by default for all. 

#3 is "you have wrong device". I think the error message indicates this as well.

I don't think we need to mention all possible causes in the error messages. The longer it gets the more confusing it will be. So I believe we are doing some tradeoffs w.r.t. UX.

I am happy with current version of the message in this PR. However, feel free to come up with other version of the message, it's up to debate. Without anything better, this stays :)

**Comment by rating89us** [comment]
Current message is:
`"Device wallet does not match wallet address. If the device uses the passphrase feature, please check whether the passphrase was entered correctly (it may have been misspelled - different passphrases generate different wallets, passphrase is case-sensitive)."`

The "If the device uses the passphrase feature" can be removed, because after https://github.com/monero-project/monero/pull/7793 this message will only appear when passphrase feature is enabled on the device or when the device has a wrong seed (user has two devices and plugged the wrong one/user restored a different seed on the same device).

I would still include cause #2 because you said it will not be solved soon on Monero GUI, and this was the problem that originated this whole discussion about passphrases.

So I suggest the following error message, it's shorter (240 characters vs. 257 of current message), it contemplates all 3 causes, and additionally it gives hints on how to solve causes #1 and #2.:
`"Device wallet does not match wallet address. This can be caused by a wrong passphrase (passphrase is case-sensitive), a device with passphrase encryption disabled (can be enabled on Trezor Suite), or a device with a different recovery seed".`

**Comment by ph4r05** [comment]
> The "If the device uses the passphrase feature" can be removed, because after #7793 this message will only appear when passphrase feature is enabled on the device or when the device has a wrong seed

#7793 will be merged after this one, for sure. I am not even sure #7793 makes it to the release-v0.17. 

Also, this message also displays on PF-disabled Trezors and other hardware wallets (Ledges does not have passphrase AFAIK). 

After is this merged, we may address error message once again. I would prefer to close this PR soon and deal with changes later (#7793 can include this one).

Also, "passphrase encryption" is not correct term. Encryption should not be mentioned at all in this context.

**Comment by rating89us** [comment]
>  I would prefer to close this PR soon and deal with changes later (#7793 can include this one).

Ok. No problem.

> Also, "passphrase encryption" is not correct term. Encryption should not be mentioned at all in this context.

This is the term displayed on Trezor screen when you disable/enabled it on Trezor Suite.

**Comment by ph4r05** [comment]
@rating89us thanks for discussion on Passphrase-related error messages. We may get back to this topic once this one is merged and there are reviews on #7793.

> This is the term displayed on Trezor screen when you disable/enable passphrase feature on Trezor Suite.

This is interesting, I indeed found it in https://github.com/trezor/trezor-suite/blob/4be72d9dfe93910297f94df77c19232d015b0bbc/packages/suite/src/support/messages.ts#L1628 , I am now discussing this wording with Trezor devs.

**Pull request merged**
