### PR TITLE
readline: don't dereference possible NULL pointer

### PR DESCRIPTION
**Pull request by jtgrassie**
Per https://github.com/monero-project/monero/issues/3799#issuecomment-453266091

### CODE REVIEW

**Comment by hyc** [comment]
There shouldn't ever be more than 1 thread trying to read keyboard input. I don't see how there can be any races with set_prompt.

**Comment by jtgrassie** [comment]
@moneromooo-monero I looked at the readline source and there are a few ways rl_prompt can be NULL which is why this check is needed. It's not a race issue as far as I can tell. I did consider putting a sync lock on the install/remove_line_handler functions but this check should suffice.

**Comment by moneromooo-monero** [comment]
Do you mean the sync call here, which is called by libstdc++, cannot happen at the same time as that particular readline code runs ?

**Comment by jtgrassie** [comment]
No I meant a lock on our sync_mutex. Because the install/remove_line_handler functions call through to readline code that can temporarily free rl_prompt. But as I say, shouldn't be needed with our ref check now.

**Comment by moneromooo-monero** [comment]
From my reading of the code, admittedly quick, start/stop can be called by the PAUSE_READLINE function, which is whenever the user inputs something. The sync call is called (at least) when a certain network event happens. It is not clear to me why those do not race.

**Comment by jtgrassie** [comment]
When readline buffer is paused, sync cannot be called though on it's stream.

**Comment by moneromooo-monero** [comment]
Why can it not ?

**Comment by jtgrassie** [comment]
Because cout's buffer is switched back to it's original stream upon stop of readline buffer. Thus there is nothing that can flush the readline buffer causing a sync.

**Comment by moneromooo-monero** [comment]
Ah, I see. This is the rdbuf call, right ? If so, then if does look racy to me since those calls are not atomic with the install/remove of the handler.

**Pull request merged**
