### PR TITLE
Converting README.i18n to Markdown

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by jonathancross** [comment]
Hi @moneromooo-monero,
My idea was to be able to add links, improve structure and make this consistent with other README files that are Markdown.  I'll fixup the commit so that it is only a rename to simplify review.

**Comment by jonathancross** [comment]
Okay, all fixed up.
Diff is trivial now, I can add back pretty formatting and links later.

**Comment by moneromooo-monero** [comment]
I'll wait for other people to chime in. If a few people prefer markup in text files, then I guess I'm fine with it.

**Comment by fluffypony** [comment]
@moneromooo-monero I prefer Markdown because a lot of these files are viewed online on GitHub / GitLab.

**Comment by moneromooo-monero** [comment]
OK, fine by me. It's not like I'll have to debug this file anyway, so clean history doesn't really matter here anyway :)

**Comment by jonathancross** [comment]
I'm happy to follow up with markdown formatting changes after this is merged, otherwise GitHub shows it as a delete and an add (with formatting), which is annoying to try and read.

**Pull request merged**
