### PR TITLE
Fix missing parentheses

### PR DESCRIPTION
**Pull request by IPGlider**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok

**Comment by NanoAkron** [comment]
:(

Thank you!

**Comment by kenshi84** [comment]
How is it possible that the code compiled with this mistake?
Very surprised :o

**Comment by grantae** [comment]
I just saw the project doesn't build without this and at least #1655 (gcc 5.4 / ubuntu 16). Kind of alarming that PRs are merged before running checks.

**Comment by NanoAkron** [comment]
Two reasons really - most people aren't interested in running nightly bleeding edge builds, so these problems usually get sorted out, and secondly there's an element of trusting the work of others so long as it doesn't appear to do anything malicious or obviously stupid.

**Comment by fluffypony** [comment]
@grantae that's on purpose - it can get fixed in a subsequent PR; there's no need to hold up merging a PR if it passes a general review. See: https://rfc.zeromq.org/spec:42/C4/

**Comment by grantae** [comment]
@fluffypony I don't know, from the C4 document it looks like this broke at least 2.3.6 (must compile & pass tests) and 2.5.1 (master branch always builds), and the exception in 2.4.16 doesn't seem to apply. To be clear, I didn't show up here to bash the project or maintainers. In contrast, I have a lot of respect for the project, and many of us understandably hold it to very high standards.

**Comment by fluffypony** [comment]
@grantae I should've added that we don't follow C4 to the letter. The BuildBot stuff is new and often fails for weird reasons like broken deps, so it isn't stable enough to be used as a reference point. There's also a difference in that we require a PR review by a known contributor before merging, which means PRs sometimes hang around a lot longer than they would in a traditional C4 project, and by the time they're merged they can be merged regardless of issues that result from the merge (rather than having it languish for longer). Hope that explains it a bit better :)

**Pull request merged**
