### PR TITLE
abstract_tcp_server2: fix busy calling of idle IO service

### PR DESCRIPTION
**Pull request by moneromooo-monero**
This would make monerod use 100% CPU when running with torsocks
without Tor running

### CODE REVIEW

**Comment by garlicgambit** [comment]
Thanks for looking into this issue.

The issue still persists. Tested on Tails with the local Tor proxy with the following command:
        DNS_PUBLIC=tcp torsocks ./monerod --p2p-bind-ip 127.0.0.1 --no-igd --rpc-bind-ip 127.0.0.1

We have some new/improved info. If you configure iptables to drop monerod traffic to Tor and allow it again monerod will establish new connections with Tor and will have normal cpu use. However if you do a simple restart the of the Tor process monerod won't create new connections to Tor and will keep using 100% of the cpu.

**Comment by anonimal** [comment]
>Tested on Tails with the local Tor proxy with the following command:
DNS_PUBLIC=tcp torsocks ./monerod --p2p-bind-ip 127.0.0.1 --no-igd --rpc-bind-ip 127.0.0.1

There's no need to torsocks behind a local transproxy.

>If you configure iptables to drop monerod traffic to Tor, and allow it again, monerod will establish new connections with Tor (and monero will have normal cpu use). However, if you do a simple restart of the Tor process, monerod won't create new connections to Tor and will continue to use 100% of the cpu.

Don't play with iptables rules unless you know what you're doing. Flushing and then restarting rules on a local transproxy leaves a potential window for application leaks. If you must, use a sandboxed internal network machine with gateway transproxy.

**Comment by moneromooo-monero** [comment]
OK, then run "sudo perf top -p `pidof monerod`" while it's doing this, let it run for 20 seconds, then paste the state.

**Comment by garlicgambit** [comment]
Tested on Debian Stretch x64 with PR #3997.

Action: stop Tor process
Command: sudo perf top -p \`pidof monerod\`
Output:

```
Overhead  Shared Object         Symbol
  11.99%  [kernel]              [k] do_select
   9.67%  [kernel]              [k] memset_erms
   4.42%  [kernel]              [k] tcp_poll
   4.38%  [kernel]              [k] core_sys_select
   4.10%  [kernel]              [k] __fget
   3.74%  [kernel]              [k] _raw_spin_lock_irqsave
   3.68%  [kernel]              [k] entry_SYSCALL_64
   3.41%  [kernel]              [k] fput
   3.17%  [kernel]              [k] entry_SYSCALL_64_after_swapgs
   2.96%  libpthread-2.24.so    [.] __libc_recv
   2.85%  [kernel]              [k] _raw_spin_lock_bh
   2.74%  [kernel]              [k] tcp_recvmsg
   2.44%  libc-2.24.so          [.] __select
   2.23%  [kernel]              [k] __local_bh_enable_ip
   1.97%  [kernel]              [k] _raw_spin_unlock_irqrestore
   1.88%  [kernel]              [k] __check_object_size
   1.62%  [kernel]              [k] __pollwait
   1.60%  [kernel]              [k] SYSC_recvfrom
```

Action: stop Tor process
Command: sudo perf top --sort comm,dso
Output:

```
Overhead  Command          Shared Object
  83.86%  monerod          [kernel]
   5.30%  monerod          libpthread-2.24.so
   4.81%  monerod          libc-2.24.so
   3.82%  monerod          libtorsocks.so.0.0.0
```

Action: drop traffic to Tor with iptables
Command: sudo perf top -p \`pidof monerod\`
Output:

```
Overhead  Shared Object         Symbol
   9.30%  [kernel]              [k] _raw_spin_lock_bh
   8.88%  libc-2.24.so          [.] connect
   7.90%  [kernel]              [k] __fget
   7.66%  [kernel]              [k] __local_bh_enable_ip
   6.51%  [kernel]              [k] entry_SYSCALL_64
   6.08%  [kernel]              [k] SYSC_connect
   5.48%  [kernel]              [k] entry_SYSCALL_64_after_swapgs
   4.45%  [kernel]              [k] __inet_stream_connect
   3.74%  [kernel]              [k] fput
```

Action: drop traffic to Tor with iptables
Command: sudo perf top --sort comm,dso
Output:

```
Overhead  Command          Shared Object
  78.25%  monerod          [kernel]
  18.20%  monerod          libc-2.24.so
   1.26%  monerod          libtorsocks.so.0.0.0
   0.48%  monerod          libpthread-2.24.so
```

Action: run without 'DNS_PUBLIC=tcp', drop traffic to Tor with iptables
Command: sudo perf top -p \`pidof monerod\`
Output:

```
Overhead  Shared Object              Symbol
  11.37%  [kernel]                   [k] __local_bh_enable_ip
  10.53%  libc-2.24.so               [.] connect
  10.53%  [kernel]                   [k] _raw_spin_lock_bh
   8.35%  [kernel]                   [k] entry_SYSCALL_64_after_swapgs
   7.64%  [kernel]                   [k] entry_SYSCALL_64
   7.53%  [kernel]                   [k] __fget
   4.84%  [kernel]                   [k] fput
```

Action: run without 'DNS_PUBLIC=tcp', drop traffic to Tor with iptables
Command: sudo perf top --sort comm,dso
Output:

```
Overhead  Command          Shared Object
  73.56%  monerod          [kernel]
  20.57%  monerod          libc-2.24.so
   1.34%  monerod          libtorsocks.so.0.0.0
   0.23%  monerod          libpthread-2.24.so
```

**Comment by moneromooo-monero** [comment]
What command(s) are you using for "drop traffic to Tor with iptables" ?

**Comment by moneromooo-monero** [comment]
What command(s) are you using for "drop traffic to Tor with iptables" ?

**Comment by moneromooo-monero** [comment]
Well, that patch fixes at least one case so let's add it for now.

**Pull request merged**
