### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hundehausen**
Updated dates and block height of rescheduled hard fork

### CODE REVIEW

**Comment by plowsof** [comment]
Thank you, my generic comment: please squash into 1 commit =) also where did you find the v16 blockheight, im trying to find it myself

**Comment by hundehausen** [comment]
Hey [plowsof](https://github.com/plowsof) I found them in the [dev meeting logs](https://monero.observer/assets/logs/220630-dev.log) from two weeks ago

**Comment by plowsof** [comment]
I only learned how about 2 weeks ago, you have to use `git` locally to do it

Monero repo maintainers would like to see (ideally) 1 commit with a commit message that makes sense e.g. "dates and block height of rescheduled hard fork in README".

The easy option would be to just close this commit / then do your changes in 1 patch directly through github

**Comment by hundehausen** [comment]
I did it locally but it closed this PR. I opened up a new one: https://github.com/monero-project/monero/pull/8431

**Pull request closed without merging**
