### PR TITLE
common: fix windows build

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by hyc** [comment]
Fyi, the Windows equivalent of a combined fork/exec is called spawn. https://msdn.microsoft.com/en-us/library/20y988d2.aspx

**Comment by hyc** [comment]
Also, calling this function "exec()" is misleading, since exec has a well-defined meaning in POSIX and this particular function does both a fork and an exec. I recommend renaming it to spawn, since it performs both actions as a single function, and spawn's meaning is also well-defined.

**Comment by moneromooo-monero** [comment]
execute maybe?

**Comment by xiphon** [comment]
Please don't merge this. I will implement Windows-specific routine.

**Comment by xiphon** [comment]
#4479

**Pull request closed without merging**
