### PR TITLE
Fixed a deadlock issue with easylogger++

### PR DESCRIPTION
**Pull request by NanoAkron**
Thanks to @moneromooo-monero's suggestion in #1595

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Please note in the commit message that it is a Mac + CLANG (IIRC) bug to match the previous recursive mutex fix that was only being used for GCC.

**Comment by NanoAkron** [comment]
So why is it working on my ARMv8/GCC build?

**Comment by NanoAkron** [comment]
Commit message changed

**Comment by moneromooo-monero** [comment]
When I said IIRC, it is because I think this is the setup you were using. You would actually know, and either change it in the actual commit message, or remove the IIRC.

**Comment by NanoAkron** [comment]
Oh. Ok. 

Well, I was on Ubuntu 16.04 with GCC 5.4 on an ARMv8 platform.

**Comment by vtnerd** [comment]
Is this something that needs to be pushed upstream? Or is this due to local changes?

**Comment by NanoAkron** [comment]
I don't know. I believe @moneromooo-Monero is better placed to answer that. Happy to do so though.

**Pull request merged**
