### PR TITLE
Always compile Position Independent Code on 64-bit ARMv8 systems

### PR DESCRIPTION
**Pull request by NanoAkron**
Also removed the duplicated setting of compilation flags and corrected the missing `STATIC_ASSERT_FLAG`

### CODE REVIEW

**Comment by NanoAkron** [comment]
Should I also change the message to "Compile libraries with Position Independent Code" instead of the "Compile libraries as shared" just to make things more explicit?

**Comment by fluffypony** [comment]
@NanoAkron I agree with changing the message to be more explicit

**Comment by NanoAkron** [comment]
Will do @fluffypony 

Can you see any reason why it's still failing buildbot with the message 'compile with -fPIC'? I've bloody set it...

**Comment by moneromooo-monero** [comment]
No commit with "asdf" as commit message please :P

**Comment by NanoAkron** [comment]
D'oh! Saw that via mobile but couldn't do anything to change it. Have fixed it now...

**Comment by NanoAkron** [comment]
Does anyone think I should generalise this to all 64-bit systems, or leave it as is for now?

**Comment by fluffypony** [comment]
@moneromooo-monero maybe asdf stands for "assume static definitions are fixed"? :-P

**Comment by NanoAkron** [comment]
Yes...yes that's definitely what I meant ;)

**Pull request merged**
