### PR TITLE
NetBSD support for Monero

### PR DESCRIPTION
**Pull request by thomasvaughan**
Additions allowing build on NetBSD

* NetBSD's system compiler does not support `-march=native`. Extra lines in top-level _CMakeLists.txt_ allow `-march=native` to be replaced by `-mtune=native` where the former is unsupported.

* NetBSD needs an extra CFLAG ([-D_NETBSD_SOURCE](http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/net/miniupnpc/patches/patch-Makefile)) for miniupnc. Provided in _external/CMakeLists.txt_.

* NetBSD needs an extra CFLAG ([-D_SEM_SEMUN_UNDEFINED](http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/databases/lmdb/Makefile)) for lmdb. Provided in _external/db_drivers/CMakeLists.txt_.

* OpenBSD clauses in _external/easylogging++/easylogging++.h_ seem to be OK for NetBSD too. Replicated accordingly.

* OpenBSD clauses in _src/crypto/oaes_lib.c_ seem to be OK for NetBSD too. Replicated accordingly. Likewise (also in _src/crypto_) for _slow-hash.c_ and _tree-hash.c_. 

TODO; Add instructions to _README.md_ for finding pcsc-lite, boost _et cetera_, since these are typically installed by the NetBSD package manager under /usr/pkg. Add instructions for cppzmq since it doesn't currently have a NetBSD pkgsrc package.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Can you make the first line of the commit message useful please, it's the one we usually see. Also you don't have to file a new PR, you can just push -f to the existing one.

**Comment by jtgrassie** [comment]
@thomasvaughan please remove the "(squashed)" from the title. It doesn't help anyone.

**Comment by moneromooo-monero** [comment]
That's the PR title though, not the commit message, which is the important bit for long term information.

**Comment by thomasvaughan** [comment]
As far as I can tell, the commit message is now "NetBSD support".

**Comment by moneromooo-monero** [comment]
It is, thanks.

**Pull request merged**
