### PR TITLE
typos RFC->RPC, too->to; fixes issue #3310

### PR DESCRIPTION
**Pull request by ordtrogen**

### CODE REVIEW

**Comment by nssy** [comment]
Here is another one in [simplewallet.cpp#L7511](https://github.com/monero-project/monero/blob/a429f06b18c812ccc4a8b17428c73588f87da8a1/src/simplewallet/simplewallet.cpp#L7511). The "an" is unnecessary, should read "Do not reuse your Monero keys on another fork"

**Comment by luigi1111** [comment]
@ordtrogen please rebase.

**Comment by ordtrogen** [comment]
Based (sic!) on experience, I'm afraid I'll mess up if I try ... 
@erciccione can you give me a hand with rebasing?

**Comment by ordtrogen** [comment]
I just fixed a merge conflict that github told me about. Did that fix what I was supposed to do?

**Comment by erciccione** [comment]
Sure no problem @ordtrogen , The conflict is solved, but now you need to get rid of that last merge commit.  To do so with git:
`git reset --hard HEAD~1`
then to rebase
`git pull upstream master --rebase`

**Comment by ordtrogen** [comment]
But first I need to add upstream as a remote repositorym right?

**Comment by ordtrogen** [comment]
Anything I need to do after this? Looks like it failed:

image

**Comment by erciccione** [comment]
It didn't fail. It just stopped because for some reason it found some conflicts in `monero_it.ts`. You need to open that file and fix the conflicts as explained [on this guide](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)

**Comment by erciccione** [comment]
@ordtrogen. I can help you live if you prefer. Just ping me in `#monero-community`

**Comment by ordtrogen** [comment]
I fixed the merge conflict (which I had done once before, in the Github UI) but still something's missing for me to push

image

**Comment by erciccione** [comment]
you didn't need to commit there. After you solved the merge you could have used `git add --all` then `git rebase --continue`. Now it says there are no conflicts since you fixed them with a commit. Try pushing, and see what happen. I think the command here should be `git push -f origin HEAD:master`

**Comment by ordtrogen** [comment]
Your push command suggestion seems to have worked. How does it look now?

**Comment by erciccione** [comment]
looks good, but now the name of the commit is a bit ambiguous, you can change it using `git commit --amend`

**Comment by erciccione** [comment]
@ordtrogen please use `git commit --amend` to change the commit message in something like 'fix typos in language files and rpc_args.cpp' or something like that

**Comment by moneromooo-monero** [comment]
And rebase to current master to make sure it still applies.

**Comment by erciccione** [comment]
@ordtrogen this time you already know the process.

basically:
`git pull upstream master --rebase`
fix conflicts if there are any
`git commit --amend` <- change the message of the commit
`git push -f origin master`

**Comment by ordtrogen** [comment]
I thought so too, and it always seems so easy, doesn't it?

Still, git tells me

"It seems that there is already a rebase-apply directory, and I wonder if you are in the middle of another rebase."

Am I?  I thought we finished the rebasing last week. Or did we abandon it in the middle of?

**Comment by erciccione** [comment]
Don't know why it says that. use `git rebase --abort` and then `git fetch origin master && git reset --hard FETCH_HEAD` so you are sure you have the remote repo synced with the local one. then use the commands above.

**Comment by ordtrogen** [comment]
Now I tried from a fresh clone of my forked repo and it seems to have worked.

**Pull request merged**
