### PR TITLE
wallet, rpc: add a release field to get_version

### PR DESCRIPTION
**Pull request by moneromooo-monero**
It does not leak much since you can make a fair guess by RPC
version already, and some people want to avoid non release
clients when using third parties' nodes (because they'd never
lie about it)

### CODE REVIEW

**Comment by vtnerd** [comment]
Whats the use case? Some users will filter out public nodes if its not a release version?

**Comment by moneromooo-monero** [comment]
Yes, some third party wallet maker wants that to avoid using "less tested" third party nodes. I'm not super confident it's a great idea.

**Comment by m2049r** [comment]
looks good to me - thanks!

the idea @vtnerd is to avoid non-release nodes in automatic node discovery. of course, if the user specifically asks to use such a node, it's fine.

**Comment by moneromooo-monero** [comment]
OTOH, people like hyc run long term stable nodes, and don't necessarliy run a tagged release :)

**Comment by dEBRUYNE-1** [comment]
@m2049r - Could you review the PR as well (and approve)?

**Comment by m2049r** [comment]
@moneromooo-monero this only checks if the commit is tagged. if i tag my fork, it also returns "true" on some random change i have made for testing new crazy functions. is it possible to return true only on official builds by fluffy et al?

**Comment by moneromooo-monero** [comment]
It uses the same system as the release build versioning. I don't really want to make it any different. Anyone who wants to spoof it can do so trivially anyway.

**Comment by m2049r** [comment]
i totally get that. would it maybe make more sense to use the tag instead of true/false? like `release=v0.14.1.0` as this is what it actaully is? and leave it blank if not tagged or `none`...

**Comment by selsta** [comment]
Needs a rebase :)

**Comment by xiphon** [comment]
@m2049r

Does the current implementation suit your needs and will you use this new field in the software?

**Pull request merged**
