### PR TITLE
Hotfix: temporarily disabled SSL certificate storing from PR 7366

### PR DESCRIPTION
**Pull request by mj-xmr**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
"Hotfix" ?

**Comment by moneromooo-monero** [comment]
Is it hard to fix it rather than just paper over it ?

**Comment by mj-xmr** [comment]
> Is it hard to fix it rather than just paper over it ?

We have a failing master, and I think the prio 1 now is to bring it back to life, because it's blocking other PRs. I don't want to mess with other author's sandbox. At least not in such a small time frame.

**Comment by mj-xmr** [comment]
Or to put it in different words, since I'm not the author, my "real fix" could bring even more new risks.

**Comment by moneromooo-monero** [comment]
I wasn't asking you to fix it :) Just that since it's just a test breaking, disabling this outright seems like an overreaction. THen again, I don't really care that much either way.

**Comment by mj-xmr** [comment]
> I wasn't asking you to fix it :) Just that since it's just a test breaking, disabling this outright seems like an overreaction. THen again, I don't really care that much either way.

By breaking the test, you are now unable to test 20 other features, which this test was supposed to test.

**Comment by selsta** [comment]
Should be solved by #7619

**Comment by mj-xmr** [comment]
> Should be solved by #7619

Correct. It solved it.

**Comment by mj-xmr** [comment]
Fixed by https://github.com/monero-project/monero/pull/7619

**Pull request closed without merging**
