### PR TITLE
 bugfix: infinite recursion in get_account_address_from_str_or_url

### PR DESCRIPTION
**Pull request by kenshi84**
Credit goes to @tdprime

https://github.com/monero-project/monero/commit/55a8e982c0b34cd62d1ad1eb83d0683d5291f322#commitcomment-20736734

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok

**Comment by NanoAkron** [comment]
Is this a bug fix for a previously submitted PR (#1626) that's not yet been merged?

**Comment by kenshi84** [comment]
@NanoAkron It's a bugfix for PR #1627 that was merged already. #1626 uses #1627 and is not merged yet.

**Comment by NanoAkron** [comment]
Ok that makes sense - thank you.

**Pull request merged**
