### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by philkode**
Update checkout command from v0.12.2.0 to release-v0.12

### CODE REVIEW

**Comment by philkode** [comment]
Not sure if there's a reason we were pointing to a specific version number rather than just the latest v0.12 release codebase? If so then please let me know and feel free to close this, otherwise I think it's useful to grab the latest release build. 'Specially with the bugfixes in v0.12.3.0.

**Comment by iDunk5400** [comment]
#4215

**Comment by moneromooo-monero** [comment]
And use a sensible commit message next time, please.

**Comment by moneromooo-monero** [comment]
+duplicate

**Pull request closed without merging**
