### PR TITLE
perf_timer: move some debug levels to info for consistency

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by vtnerd** [comment]
Is this change the default log level to "info"? Why increase the times this time is being run?

**Comment by moneromooo-monero** [comment]
This changes the log level of some perf logs to INFO, where they were DEBUG before. It does not change the default log levels. Those are not enabled by default. It should not change anything when run (except they now all get logged at INFO).

**Comment by vtnerd** [comment]
Yes exactly, why increase the default perf timer log level? The info level is used frequently as the default for several categories now IIRC.

**Comment by moneromooo-monero** [comment]
Because it seems like the sensible level for these. If you don't want perf at log level 1, I think it's OK to take them out of that.

**Comment by moneromooo-monero** [comment]
Level 1 currently includes these FWIW. It sets perf*:DEBUG.

**Pull request merged**
