### PR TITLE
epee: delete dead code

### PR DESCRIPTION
**Pull request by 0xFFFC0000**

### CODE REVIEW

**Review by vtnerd — COMMENTED** [review]
Crap. 

The idea was to replace the serialization code in a series of patches. The read patch has unfortunately stalled, so all of this looks like dead code.

**Comment by vtnerd** [comment]
The "next" PR for this code is #8970 .

**Comment by 0xFFFC0000** [comment]
In that case, I am closing this PR. 

Please feel free to reopen this PR if you are not going to push subsequent mentioned PRs.

**Comment by 0xFFFC0000** [comment]
Although I closed this. 

@vtnerd do you remember what was the blocker for that PR of yours?

**Comment by vtnerd** [comment]
The blocker is primarily reviews - I could probably remove a few things so its smaller (but they would have to reviewed later anyway).

**Comment by 0xFFFC0000** [comment]
@vtnerd I will review it next few days. To make sure we will get it in.

**Pull request closed without merging**
