### PR TITLE
rpc: macro to define core RPC version for avoiding future mistake

### PR DESCRIPTION
**Pull request by kenshi84**
[suggested](https://github.com/monero-project/monero/pull/1569#discussion_r96114461) by @moneromooo-monero

### CODE REVIEW

**Comment by kenshi84** [comment]
@NanoAkron It did work, the problem was that sometimes one would write a test like:

    if (version < 0x10005) {...}

and it's easy to do it wrong like:

    if (version < 0x1005) {...}

which I did in PR #1569. This bug can be avoided by

    if (version < MAKE_CORE_RPC_VERSION(1, 5)) {...}

**Comment by moneromooo-monero** [comment]
ok

**Comment by fluffypony** [comment]
Please rebase

**Comment by kenshi84** [comment]
rebased @fluffypony

**Pull request merged**
