### PR TITLE
fix init warning on whatever compiler version

### PR DESCRIPTION
**Pull request by italocoin-project**
fix init warning on whatever compiler version

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
When I said "whatever compiler version" as commit message, I meant for you to replace that with whatever compiler version you're using :D

**Comment by italocoin-project** [comment]
I got the same warning on more than one version

**Comment by fluffypony** [comment]
You were actually pretty close - "whichever" would have worked better :)

**Comment by italocoin-project** [comment]
True :))

**Pull request merged**
