### PR TITLE
simplewallet: remove obsolete transfer_original command

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by vicsn** [comment]
Is there a plan to also remove the other transfer_original related code?

**Comment by moneromooo-monero** [comment]
Is it not ?

**Comment by vicsn** [comment]
I should've been more precise, I mean `wallet2::create_transactions(...)`.

**Comment by moneromooo-monero** [comment]
Well, that particular part is removed.

**Pull request merged**
