### PR TITLE
NetBSD build fixes

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by krytarowski** [comment]
The right fix for alloca on NetBSD is to use `-std=gnu11` / `-std=gnu++11`. This will instruct to the compiler to use GNU extensions with builtin alloca(3).

**Comment by moneromooo-monero** [comment]
I'm not sure all the platforms monero currently builds on use GCC though (or CLANG, which might or might not support those GNU extensions). So we might end up using extensions without realizing.

If you know the details, can you explain in a bit more detail why -std=gnu11 is better ?

**Comment by krytarowski** [comment]
Using -std=c11 -std=c++11 will try to pick a fallback version in libc as compiler extensions (alloca is a compiler extension!) are disabled. libc version will break in real software as it's impossible to implement correctly alloca without compiler support.

**Comment by krytarowski** [comment]
Cross-platform projects like .NET pick `-gnu*` variations as it's supported by virtually everything that is industry standard.

**Comment by moneromooo-monero** [comment]
Here's a version using VLAs for C and std::vector for C++.

**Comment by krytarowski** [comment]
VLA is not supported in MSVC.

**Comment by moneromooo-monero** [comment]
MSVC can not compile monero anyway.

**Comment by krytarowski** [comment]
OK, looks good to me.

**Comment by thomasvaughan** [comment]
Incorporating the no-alloca patches (and the performance_utils.h fix) from this PR into v14.0.0 gives the following test results using the NetBSD system compiler (gcc 5.5.0):

          Start  1: hash-target
     1/18 Test  #1: hash-target ......................   Passed    0.08 sec
          Start  2: core_tests
     2/18 Test  #2: core_tests .......................   Passed  3036.00 sec
          Start  3: cncrypto
     3/18 Test  #3: cncrypto .........................   Passed   11.95 sec
          Start  4: cnv4-jit
     4/18 Test  #4: cnv4-jit .........................***Exception: SegFault  0.15 sec
          Start  5: unit_tests
     5/18 Test  #5: unit_tests .......................***Failed  154.72 sec
          Start  6: difficulty
     6/18 Test  #6: difficulty .......................   Passed    0.03 sec
          Start  7: block_weight
     7/18 Test  #7: block_weight .....................***Not Run   0.00 sec
          Start  8: hash-fast
     8/18 Test  #8: hash-fast ........................   Passed    0.02 sec
          Start  9: hash-slow
     9/18 Test  #9: hash-slow ........................   Passed    0.12 sec
          Start 10: hash-slow-1
    10/18 Test #10: hash-slow-1 ......................   Passed    0.15 sec
          Start 11: hash-slow-2
    11/18 Test #11: hash-slow-2 ......................   Passed    0.39 sec
          Start 12: hash-slow-4
    12/18 Test #12: hash-slow-4 ......................   Passed    1.09 sec
          Start 13: hash-tree
    13/18 Test #13: hash-tree ........................   Passed    0.02 sec
          Start 14: hash-extra-blake
    14/18 Test #14: hash-extra-blake .................   Passed    0.02 sec
          Start 15: hash-extra-groestl
    15/18 Test #15: hash-extra-groestl ...............   Passed    0.02 sec
          Start 16: hash-extra-jh
    16/18 Test #16: hash-extra-jh ....................   Passed    0.02 sec
          Start 17: hash-extra-skein
    17/18 Test #17: hash-extra-skein .................   Passed    0.02 sec
          Start 18: hash-variant2-int-sqrt
    18/18 Test #18: hash-variant2-int-sqrt ...........   Passed  377.71 sec
    
    83% tests passed, 3 tests failed out of 18
    
    Total Test time (real) = 3583.67 sec

(That's with with -Werror removed from the top-level CMakeLists.txt so that -Wvla doesn't halt the build.)

**Comment by krytarowski** [comment]
cnv4-jit this probably violates PaX MPROTECT

You can re-check with: `sysctl -w security.pax.mprotect.enabled=0`

**Comment by thomasvaughan** [comment]
Yes, after `sysctl -w security.pax.mprotect.enabled=0`, Test 4 result is

          Start  4: cnv4-jit
     4/18 Test  #4: cnv4-jit .........................   Passed  147.27 sec

Test 5 is the only *Fail*, and Test 7 is *Not Run*.

**Comment by moneromooo-monero** [comment]
Do you have python intalled ? block_weight tests need it.

About Pax, that's pretty annoying. I'll look it up.

**Comment by thomasvaughan** [comment]
Presumably, the way to run cnv4-jit is `paxctl +M /path/to/cnv4-jit` (as root).

**Comment by krytarowski** [comment]
For PaX MPROTECT the ideal solution is to use the escape API - `PROT_MPROTECT()`.

Examples can be searched on github.

**Comment by moneromooo-monero** [comment]
Oh, perfect, thank you :)

**Comment by thomasvaughan** [comment]
Python is /usr/pkg/bin/python2.7 and /usr/pkg/bin/python3.6 (with /usr/pkg being the default prefix for 3rd party packages), and the build log has `-- Found PythonInterp: /usr/pkg/bin/python2.7 (found version "2.7.14")`.

**Comment by moneromooo-monero** [comment]
Does the last patch from https://github.com/moneromooo-monero/bitmonero/tree/netbsd-jit fix it ?

**Comment by moneromooo-monero** [comment]
Do you have a /usr/bin/python ?

If not, try replacing the first line in tests/block_weight/block_weight.py from:
#!/usr/bin/python
to:
#!/usr/bin/env python

**Comment by krytarowski** [comment]
`python` does not exist in pkgsrc, we always version it (python2.7, etc).

**Comment by moneromooo-monero** [comment]
OK, if there's no symlink with just python, I'll have to twiddle the cmake files a bit.

**Comment by thomasvaughan** [comment]
Should be a fairly minor twiddle since the build is already discovering the existence of the executable named python2.7. For now I've just adjusted the block_weight.py hashbang to #!/usr/pkg/bin/python2.7, and am re-running the tests. I don't know how to bypass core_tests, so it will take an hour.

**Comment by moneromooo-monero** [comment]
pkill core_tests :)

**Comment by moneromooo-monero** [comment]
Indeed, cmake twiddling is seldom trivial, but this time it was. Same branch.

**Comment by thomasvaughan** [comment]
In your netbsd-jit branch (further patched with your trivial patch that adds NetBSD support to performance_utils.h), I'm still seeing ` 4/18 Test  #4: cnv4-jit .........................***Exception: SegFault  0.15 sec`.

If I first use `sysctl` to flip security.pax.mprotect.enabled from 1 to 0, then cnv4-jit-test is successful, as reported yesterday (but I assume your intention in this branch is to obviate the need for that workaround...).

Also, in your netbsd-jit branch, the block_weight test doesn't run. It does runs (and it passes too) if I change the hashbangs in blockweight.py AND compare.py to exact paths; so I guess the ${PYTHON_EXECUTABLE} in block_weight/CMakeLists.txt isn't getting passed to where it's needed whence the compare.py hashbang is being used instead.

**Comment by moneromooo-monero** [comment]
Can you get a stack trace for that crash ?
The latest branch should also fix that python problem.

**Comment by moneromooo-monero** [comment]
I've added PROT_READ as a test in case this is needed on netbsd.

**Comment by thomasvaughan** [comment]
A stack trace is beyond my knowledge. If it helps, there's a cnv4-jit-tests.core file, and /usr/bin/gdb exists.

As for the python problem, the block_weight test still isn't running with your updated netbsd-jit branch. If I get around to writing a pkgsrc Makefile for Monero,  the usual pkgsrc fix for this common annoyance could be incorporated there (many pkgsrc Makefiles have a REPLACE_PYTHON variable listing every python hashbangs in need of replacement), so all is not lost if you grow weary of it.

**Comment by moneromooo-monero** [comment]
That should be enough:
gdb build/debug/tests/crypto/cnv4-jit-tests
run
Then it should crash rather quickly, then:
bt
Please run a debug build for the trace to be meaningful.

About block_weight, can you post the output of:

grep -A6 -B6 block_weight build/release/Testing/Temporary/LastTest.log.tmp
(or s/release/debug, whichever you have)

**Comment by thomasvaughan** [comment]
In build/NetBSD/netbsd-jit/release/Testing/Temporary/LastTest.log, it looks like ${PYTHON_EXECUTABLE} isn't being passed to where it's needed:

    7/18 Testing: block_weight
    7/18 Test: block_weight
    Command: "/home/t/usr/src/bitmonero/tests/block_weight/compare.py" "/home/t/usr/src/bitmonero/tests/block_weight/block_weight.py" "/home/t/usr/src/bitmonero/build/NetBSD/netbsd-jit/release/tests/block_weight/block_weight"
    Directory: /home/t/usr/src/bitmonero/build/NetBSD/netbsd-jit/release/tests/block_weight
    "block_weight" start time: Feb 28 16:32 UTC
    Output:
    ----------------------------------------------------------
    <end of output>
    Test time =   0.00 sec
    ----------------------------------------------------------
    Test Failed.
    "block_weight" end time: Feb 28 16:32 UTC
    "block_weight" time elapsed: 00:00:00
    ----------------------------------------------------------

**Comment by thomasvaughan** [comment]
From `gdb gdb build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests`:

    (gdb) run
    Starting program: /home/t/usr/src/bitmonero/build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests 
    [Inferior 1 (process 24411) exited normally]
    (gdb) bt
    No stack.
    (gdb)

Incidentally, the debug build required gtest (built with -fpIC) from a NetBSD package — the one shipping with Monero didn't work. My slightly out-of-date pkgsrc tree has two patches for googletest, but current pkgsrc (http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/devel/googletest/) doesn't have these patches, so I guess they've been added upstream.

**Comment by moneromooo-monero** [comment]
Can you expand on "didn't work" ?

That log seems to be running not what I put in CMakeLists.txt. Are you sure this was properly regenerated ? The top commit hash should be 361aae63955721cab491b25e7053e4abba2bb515.

cnv4-jit-tests seems to have run normally here. I forgot to tell you to run it with MONERO_USE_CNV4_JIT=1 :)

So:
MONERO_USE_CNV4_JIT=1 gdb build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests
run

**Comment by thomasvaughan** [comment]
Using the gtest that ships with Monero, the debug build stopped at

    [ 80%] Building CXX object tests/unit_tests/CMakeFiles/unit_tests.dir/block_reward.cpp.o
    /home/t/usr/src/bitmonero/tests/unit_tests/block_reward.cpp: In member function ‘virtual void {anonymous}::block_reward_and_current_block_weight_fails_on_huge_median_size_Test::TestBody()’:
    /home/t/usr/src/bitmonero/tests/unit_tests/block_reward.cpp:146:55: error: ‘ASSERT_DEATH’ was not declared in this scope
         ASSERT_DEATH(do_test(huge_size, huge_size + 1), "");
                                                           ^
    /home/t/usr/src/bitmonero/tests/unit_tests/block_reward.cpp: In member function ‘virtual void {anonymous}::block_reward_and_current_block_weight_fails_on_huge_block_weight_Test::TestBody()’:
    /home/t/usr/src/bitmonero/tests/unit_tests/block_reward.cpp:154:55: error: ‘ASSERT_DEATH’ was not declared in this scope
         ASSERT_DEATH(do_test(huge_size - 2, huge_size), "");
                                                           ^
    tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:230: recipe for target 'tests/unit_tests/CMakeFiles/unit_tests.dir/block_reward.cpp.o' failed

... but the debug build was OK after I re-installed googletest (pkgsrc package, built with -fPIC), so I'm assuming the pkgsrc patches (http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/devel/googletest/patches/Attic/?only_with_tag=pkgsrc-2017Q4) do something useful. My pkgsrc googletest is version 1.8.0.

Here's what tests/block_weight/CMakeLists.txt looks like in my local copy of your netbsd-jit branch:

    set(block_weight_sources
      block_weight.cpp)
    
    set(block_weight_headers)
    
    add_executable(block_weight
      ${block_weight_sources}
      ${block_weight_headers})
    target_link_libraries(block_weight
      PRIVATE
        cryptonote_core
        blockchain_db
        ${EXTRA_LIBRARIES})
    
    add_test(
      NAME    block_weight
      COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/compare.py ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/block_weight.py ${CMAKE_CURRENT_BINARY_DIR}/block_weight)

And here's what I see when I run `MONERO_USE_CNV4_JIT=1 gdb ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests`:

    Reading symbols from ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests...done.
    (gdb) run
    Starting program: /home/t/usr/src/bitmonero/build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests 
    [Inferior 1 (process 1188) exited normally]
    (gdb) bt
    No stack.

**Comment by moneromooo-monero** [comment]
For gtest, try:

<pre>
diff --git a/tests/gtest/include/gtest/internal/gtest-port-arch.h b/tests/gtest/include/gtest/internal/gtest-port-arch.h
index 74ab94905..83022c82c 100644
--- a/tests/gtest/include/gtest/internal/gtest-port-arch.h
+++ b/tests/gtest/include/gtest/internal/gtest-port-arch.h
@@ -88,6 +88,8 @@
 # define GTEST_OS_OPENBSD 1
 #elif defined __QNX__
 # define GTEST_OS_QNX 1
+#elif defined(__NetBSD__)
+# define GTEST_OS_NETBSD 1
 #endif  // __CYGWIN__
 
 #endif  // GTEST_INCLUDE_GTEST_INTERNAL_GTEST_PORT_ARCH_H_
diff --git a/tests/gtest/include/gtest/internal/gtest-port.h b/tests/gtest/include/gtest/internal/gtest-port.h
index cb0639b4b..2896dfe64 100644
--- a/tests/gtest/include/gtest/internal/gtest-port.h
+++ b/tests/gtest/include/gtest/internal/gtest-port.h
@@ -790,7 +790,8 @@ using ::std::tuple_size;
      (GTEST_OS_MAC && !GTEST_OS_IOS) || \
      (GTEST_OS_WINDOWS_DESKTOP && _MSC_VER >= 1400) || \
      GTEST_OS_WINDOWS_MINGW || GTEST_OS_AIX || GTEST_OS_HPUX || \
-     GTEST_OS_OPENBSD || GTEST_OS_QNX || GTEST_OS_FREEBSD)
+     GTEST_OS_OPENBSD || GTEST_OS_QNX || GTEST_OS_FREEBSD || \
+     GTEST_OS_NETBSD)
 # define GTEST_HAS_DEATH_TEST 1
 #endif
 

</pre>

For block_weight, CMakeLists.txt looks right, but not the log.

For the core, run:
ulimit -c unlimited
echo core | sudo tee /proc/sys/kernel/core_pattern
run tests
gdb build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests core*
bt

**Comment by thomasvaughan** [comment]
There isn't a subdirectory called sys under /proc, so I'll assume that's a Linuxism. However, playing by ear I tried `gdb build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests.core`, and perhaps it's what you're looking for:

    [New process 1]
    Core was generated by `cnv4-jit-tests'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x00007a984df2d000 in ?? ()
    (gdb) bt
    #0  0x00007a984df2d000 in ?? ()
    #1  0x00007a984d42e7a6 in cn_slow_hash (data=<optimized out>, length=<optimized out>, hash=<optimized out>, variant=<optimized out>, 
        prehashed=<optimized out>, height=<optimized out>) at /home/t/usr/src/bitmonero/src/crypto/slow-hash.c:957
    #2  0x00000000b1e00f2f in test (data=0x7f7fff05a920 'B' <repeats 64 times>, "\340\277\005\377\177\177", len=64, height=1788000)
        at /home/t/usr/src/bitmonero/tests/crypto/cnv4-jit.c:45
    #3  0x00000000b1e01184 in main (argc=<optimized out>, argv=<optimized out>) at /home/t/usr/src/bitmonero/tests/crypto/cnv4-jit.c:109
    (gdb)

It's the same when preceded by `ulimit -c unlimited`.

I'll comment here again when I've tried your above gtest patches.

**Comment by moneromooo-monero** [comment]
Yes, that's what I wanted. Not super helpful unfortunately, but it does show it's probably indeed crashing executing the generated code. I'll lookup more stuff about PROT_MPROTECT to see if I'm missing some setup.

**Comment by moneromooo-monero** [comment]
I pushed another patch that complains on stdout if mprotect fails. Might be that.

**Comment by thomasvaughan** [comment]
Your gtest patches work as intended: they allow the debug build to use the in-tree gtest.

I'm not sure where to look for output from you error-messages patch in https://github.com/moneromooo-monero/bitmonero/commit/a5b93814f44db4a143d3a3b8ec2328eb7f95796c
but `MONERO_USE_CNV4_JIT=1 gdb build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests.core` is resulting in this:

    [New process 1]
    Core was generated by `cnv4-jit-tests'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x000079102372d000 in ?? ()
    (gdb) bt
    #0  0x000079102372d000 in ?? ()
    #1  0x0000791022c2e7e6 in cn_slow_hash (data=<optimized out>, length=<optimized out>, hash=<optimized out>, variant=<optimized out>, 
        prehashed=<optimized out>, height=<optimized out>) at /home/t/usr/src/bitmonero/src/crypto/slow-hash.c:957
    #2  0x000000003f200f2f in test (data=0x7f7fffe91e70 'B' <repeats 64 times>, "à/é\377\177\177", len=64, height=1788000)
        at /home/t/usr/src/bitmonero/tests/crypto/cnv4-jit.c:45
    #3  0x000000003f201184 in main (argc=<optimized out>, argv=<optimized out>) at /home/t/usr/src/bitmonero/tests/crypto/cnv4-jit.c:109
    (gdb)

**Comment by moneromooo-monero** [comment]
The messages, if any, would go on stdout if you run:
MONERO_USE_CNV4_JIT=1 ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests

**Comment by thomasvaughan** [comment]
$ MONERO_USE_CNV4_JIT=1 ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests
    0/1mprotect: 108: Permission denied
    Memory fault (core dumped) 
    $ 
    $ su root -c 'MONERO_USE_CNV4_JIT=1 ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests'
    0/1mprotect: 108: Permission denied
    Memory fault 
    $

**Comment by thomasvaughan** [comment]
Probably not useful, but throwing in a `paxctl +M` results in no messages, which is what you'd expect.

    su root -c 'MONERO_USE_CNV4_JIT=1 paxctl +M ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests'

**Comment by thomasvaughan** [comment]
Correction: that didn't need to be as root. It produces the same lack of messages when run as an ordinary user.

**Comment by thomasvaughan** [comment]
I've misunderstood the use of paxctl. It changes the binary file. So, `paxctl -m ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests && ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests` gives an error message:

    0/1mprotect: 108: Permission denied
    Memory fault (core dumped)

... and `paxctl +m ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests && ./build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests` outputs `0/1`

**Comment by moneromooo-monero** [comment]
I pushed another attempt at fixing this jit crash.

**Comment by moneromooo-monero** [comment]
Commit 705f1226e30ff42a72af0964c37acb61072a57b4

**Comment by krytarowski** [comment]
>  moneromooo-monero

Your code is still not ok.

In PaX MPROTECT you cannot reserve W|X concurrently and grant extra permissions after mmap(2).

To work around this you need: use PROT_MPROTECT() to reserve future allocation permissions. But still you are only allowed to swap between RW and RX in future.

If you need RWX mapping, there is need for double mapping. Something like this is done in libffi

https://github.com/libffi/libffi/blob/05a1796419f68267250c0b8ae7138da36ab60b01/src/closures.c#L41

**Comment by moneromooo-monero** [comment]
Alright, let's try that latest one.

**Comment by thomasvaughan** [comment]
b6a47edb67ccc02aae57959ec23becad4a4a3835

Output from `MONERO_USE_CNV4_JIT=1 gdb build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests.core`:

    Reading symbols from build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests...done.
    [New process 1]
    Core was generated by `cnv4-jit-tests'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x000071ead372d000 in ?? ()
    (gdb) bt
    #0  0x000071ead372d000 in ?? ()
    #1  0x000071ead2c2e7e6 in cn_slow_hash (data=<optimized out>, length=<optimized out>, hash=<optimized out>, variant=<optimized out>, 
        prehashed=<optimized out>, height=<optimized out>) at /home/t/usr/src/bitmonero/src/crypto/slow-hash.c:957
    #2  0x0000000115e00f2f in test (data=0x7f7fff8945f0 'B' <repeats 64 times>, "à_\377\177\177", len=64, height=1788000)
        at /home/t/usr/src/bitmonero/tests/crypto/cnv4-jit.c:45
    #3  0x0000000115e01184 in main (argc=<optimized out>, argv=<optimized out>) at /home/t/usr/src/bitmonero/tests/crypto/cnv4-jit.c:109
    (gdb)

Output from `MONERO_USE_CNV4_JIT=1 build/NetBSD/netbsd-jit/debug/tests/crypto/cnv4-jit-tests`:

    0/1mprotect: 108: Permission denied
    Memory fault (core dumped)

**Comment by moneromooo-monero** [comment]
Another patch with more logs. Maybe mmap itself failed.

**Comment by moneromooo-monero** [comment]
I got access to a NetBSD VM from pigeons, and it's now fixed. The original mmap was failing because it did not like fd 0 for anonymous memory.

**Pull request merged**
