### PR TITLE
rpc: remove mine-to-use RPC on node side

### PR DESCRIPTION
**Pull request by jeffro256**
This is a follow-up PR to #8724. I was able to remove >2000 lines of code and shrink the `monerod` binary by >6%. You can look at the original PR to check up on usage stats for this feature, but last time I checked it was less than 3%.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
> shrink the monerod binary by >6%.

6% fewer bytes vs the ability to implement a fully decentralized microtransaction payment system.

The world never stopped sucking I guess. Time to find a tiny violin somewhere...

**Comment by Gingeropolous** [comment]
> 6% fewer bytes vs the ability to implement a fully decentralized microtransaction payment system.

with no chain bloat and no on-boarding!

it was a beautiful dream.

though I thought the idea was to remove it from the wallet (because aNtIvIrUs) and let it live in the daemon in the hopes that some future 3rd party wallet would do something or other.

**Comment by jeffro256** [comment]
> > 6% fewer bytes vs the ability to implement a fully decentralized microtransaction payment system.
> 
> with no chain bloat and no on-boarding!
> 
> it was a beautiful dream.
> 
> though I thought the idea was to remove it from the wallet (because aNtIvIrUs) and let it live in the daemon in the hopes that some future 3rd party wallet would do something or other.

Yes I'm not pushing incredibly hard for removal on the node side btw, but this PR is available in case that we decide otherwise.

**Comment by jeffro256** [comment]
> > shrink the monerod binary by >6%.
> 
> 6% fewer bytes vs the ability to implement a fully decentralized microtransaction payment system.
> 
> The world never stopped sucking I guess. Time to find a tiny violin somewhere...

Even if the code was removed from the core repo, this could still work as a reverse proxy right?

**Comment by jeffro256** [comment]
Closing for now

**Comment by hinto-janai** [comment]
@jeffro256 Do you have any thoughts on this now?

IMO the points in https://github.com/monero-project/monero/issues/8722 make this worth removing on the node side as well. FWIW if this stays in `monerod`, Cuprate is planning to implement the related fields and routes (`credits`, `rpc_access_info`, etc) on the surface-level but disable it internally.

**Pull request closed without merging**
