### PR TITLE
Gitian build (mac, linux): gzip => bzip2

### LINKED ISSUE #5730: Release monero-linux-x64-v0.14.1.0.tar.bz2 == invalid bzip2 file (rather gzip)
It seems the Linux cli v0.14.1.0 release has been compressed using gzip rather than bzip2:

```
$ curl https://downloads.getmonero.org/cli/monero-linux-x64-v0.14.1.0.tar.bz2 --output monero-linux-x64-v0.14.1.0.tar.bz2

$ openssl dgst -sha256 monero-linux-x64-v0.14.1.0.tar.bz2
SHA256(monero-linux-x64-v0.14.1.0.tar.bz2)= 2b95118f53d98d542a85f8732b84ba13b3cd20517ccb40332b0edd0ddf4f8c62

$ bunzip2 monero-linux-x64-v0.14.1.0.tar.bz2
bunzip2: monero-linux-x64-v0.14.1.0.tar.bz2 is not a bzip2 file.

$ file monero-linux-x64-v0.14.1.0.tar.bz2
monero-linux-x64-v0.14.1.0.tar.bz2: gzip compressed data, max compression, from Unix
```

**Note:** *gzip* rather than *bzip2* as in previous releases.

### PR DESCRIPTION
**Pull request by jonathancross**
This fixes #5730 (now open on gitlab as [monero-site#964](https://repo.getmonero.org/monero-project/monero-site/issues/964) and as https://github.com/monero-project/meta/issues/372)

@dEBRUYNE-1  - Let me know if you have more insight into this fix as I didn't see it in the codebase.

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
>@dEBRUYNE-1 - Let me know if you have more insight into this fix as I didn't see it in the codebase.

Are you referring to my "This should be fixed in the upcoming v0.14.1.1 release." comment?

**Comment by jonathancross** [comment]
> Are you referring to my "This should be fixed in the upcoming v0.14.1.1 release." comment?

Yes.
Did you mean that it was _already fixed_ or that someone _should_ fix it?

**Comment by dEBRUYNE-1** [comment]
I mistakenly thought there was already a pull request merged that fixed it.

**Comment by ndorf** [comment]
bzip2 is obsolete, though. Either xz (for maximum compression) or gzip (for maximum interoperability) should be used.

**Comment by jonathancross** [comment]
@ndorf I was just reverting to the compression we used for years as that was an unintentional side effect of the gitian build process.  I'm open to using another compression method if that is what people want -- `xz` does sound better.  More than anything I just wanted the file extension to match the actual type.

Does anyone else here agree that a switch to `xz` would be better (and will get merged)?

**Note:** `bzip2` isn't fast as the others, but it does make files that are noticeably smaller than the current gzip and files being replaced in this PR.

**Comment by trasherdk** [comment]
Just as a sde note, I'm packing my slackware install package like:
```
mkdir $CWD/monero-$VER
cp $CWD/build-monero-$VER/bin/* $CWD/monero-$VER/
tar --create -f monero-linux-x64-$VER.tar.bz2 monero-$VER
```
Having `xz` available, it could have been `tar --create -f monero-linux-x64-$VER.tar.xz monero-$VER`
Giving me a valid installer.

**Comment by ndorf** [comment]
@jonathancross I see now, sorry for cluttering up your PR with this. Guess I'll open a new issue for that.

**Comment by jonathancross** [comment]
#### Note regarding determinism
I have not yet found a definitive answer as to whether or not `bzip2` compression can be relied upon to always produce the same archive checksum given the same input data.  I've done some tests myself (things known to break gzip determinism) and so far checksums have been reproducible (even when filenames, modification dates, platform and / or filesystem change).

If anyone has more info, please let me know as we need the final archives to be reproducible. I also [asked on Stack Exchange](https://unix.stackexchange.com/questions/531494/can-files-compressed-with-bzip2-be-relied-upon-to-be-deterministic-reproducible).

RE: testing, we might want to have several devs do a build with this PR and compare the final bz2 checksums.

**Comment by fluffypony** [comment]
@jonathancross I would support a switch to xz

**Comment by jonathancross** [comment]
@fluffypony Okay, I'll try to confirm `xz` compression doesn't break reproducibility.
Are you able to update whatever process is creating the incorrect file extensions (currently `.bz2`)?

**Comment by jonathancross** [comment]
### Determinism in xz compressed data

I've found this note in the man page:
```
NOTES
   Compressed output may vary
       The exact compressed output produced from the same uncompressed input file may vary between XZ  Utils  ver-
       sions  even  if  compression options are identical.  This is because the encoder can be improved (faster or
       better compression) without affecting the file format.  The output can vary even between  different  builds
       of the same XZ Utils version, if different build options are used.

       The  above means that once --rsyncable has been implemented, the resulting files won't necessarily be rsyn-
       cable unless both old and new files have been compressed with the same xz version.   This  problem  can  be
       fixed if a part of the encoder implementation is frozen to keep rsyncable output stable across xz versions.
```

#### Experiments

I did some simple testing on MacOS (xz v5.2.1) and Ubuntu (xz v5.2.2) with various inputs and didn't see any obvious variation in reproducibility.  I've noticed that `xz -9` is significantly slower than maximum `bzip2` and `gzip` compression, but dramatically better compression. We can reduce compression level if speed is an issue.

@ndorf Feel free to add more info if you have it about determinism in `xz` compressed output, but right now, this doesn't seem like a great switch as we might be breaking reproducibility somewhere down the road.  From what I've seen, a switch to `xz` would only make sense if archive size or decompression speed are significant issues.  Doesn't seem like it is worth risk IMO.

**Comment by hyc** [comment]
Sounds like xz is too much of a wildcard. If bzip2 can be relied on we should just stick with that.

**Comment by ndorf** [comment]
Why would that be a concern? The gitian build would always use the same version. The output of the compiler and every other tool in the chain can differ between different versions, too.

**Comment by TheCharlatan** [comment]
I don't have much data on the reproducibility effects of either bzip or xz. I'd prefer an encoder with  a stable output, even for different versions. It should be possible to get to the same binary even some time after the actual binary release was made.

**Comment by hyc** [comment]
I don't suppose we could just checksum the uncompressed tar file? It could still be verified pretty easily, and we wouldn't have to worry so much about choice of compressor.

**Comment by jonathancross** [comment]
@ndrorf
> The gitian build would always use the same version. The output of the compiler and every other tool in the chain can differ between different versions, too.

Not exactly.

The version of gzip/bzip2/xz is default included in the docker image (Ubuntu bionic "latest" tag), so it is only isolated from the _host_ OS.  Unfortunately AFAIKT we don't lock / tag the specific docker image we use (yet?), so the version could change between users / builds based on docker / Ubuntu.

I suggest we lock down the docker image hash, then we can then explore compression improvements later.

@hyc 

> I don't suppose we could just checksum the uncompressed tar file?

Using the final compressed file is preferable from a UX perspective because it provides a simple sha256 checksum to verify and compare with [hashes.txt](https://web.getmonero.org/downloads/hashes.txt) + what users are downloading.

@fluffypony
> I would support a switch to xz

Although I agree there are many options we might explore to reduce the compressed files & improve the build process, I think we are bikeshedding a bit here and would appreciate if we could merge this fix for the for the existing issue and address _improvements_ in a separate discussion later.

**Comment by moneromooo-monero** [comment]
Technically, signing the uncompressed version leaves you vulmerable to decompressor based attacks since you have to decompress before verifying. Anyway, if the xz compressor source is fixed, then its output should be deterministic already.

**Comment by moneromooo-monero** [comment]
Any consensus on this ? :)

**Comment by jonathancross** [comment]
@moneromooo-monero : I'd like to see the next release contain archives that match their file extension. :-)
@TheCharlatan doesn't have time to tackle locking the Ubuntu version (and therefore `xz` version) right now.  Personally, I'd like to see this PR merged and `xz` explored once version is locked.

**Pull request merged**
