### PR TITLE
Update year to 2022

### PR DESCRIPTION
**Pull request by AkritW**
Update year from 2021 to 2022

### CODE REVIEW

**Review by tobtoht — APPROVED** [review]
Looks like this slipped past @mj-xmr's recent PR. (Pinging you in case you want to update the script)

**Comment by mj-xmr** [comment]
> Looks like this slipped past @mj-xmr's recent PR. (Pinging you in case you want to update the script)

Thank you. Indeed. The reason is that this file has no extension. Will update.

**Review by mj-xmr — APPROVED** [review]

**Review by mj-xmr — CHANGES_REQUESTED** [review]
Please update the `Makefile` as well, and it's good to go.

**Comment by AkritW** [comment]
Updated the Makefile.

**Review by tobtoht — APPROVED** [review]

**Review by mj-xmr — APPROVED** [review]
You'd typically be asked to squash the commits to just one and then force push, but for such a small change it probably doesn't matter.

**Comment by selsta** [comment]
We will continue in #8302. @AkritW you will get added as co-author.

**Pull request closed without merging**
