### PR TITLE
Add check if submodules need to be updated

### PR DESCRIPTION
**Pull request by TheCharlatan**
This is a replacement pr for #3926 . I am not sure this actually does what I inteded. Please suggest better ways to make the check.

Adds CMake check that checks if the commited hash of the submodule is the same as the currently checked out hash in the submodule directory.

### CODE REVIEW

**Comment by hyc** [comment]
Why bother checking? just run `git submodule update` and it will either do something or be a no-op.

**Comment by TheCharlatan** [comment]
Do you mean why bother with the pr at all, or why bother using git pull?
Using git pull:
- In #3926 the check was made with a submodule update, but it was deemed too intrusive
- It is not possible to dry run a submodule update
Why bother at all:
- People forget to run it constantly, which will lead to issues being opened and institutions running unpatched/incorrectly patched software

**Comment by moneromooo-monero** [comment]
I see the MANUAL_SUBMODULES flag, which can allow this to be bypassed, and that makes me think of this %@!&*%# firefox which pretty much *always* enables privacy invading stuff by default, which means that if you don't know in advance what's coming, you run that stuff at least once and curse seven generations of its children before you have a chance to disable the new trap. And that's if you're lucky and realize they added somehting.

Here it's the same: you'll get to run git submodule update at least once before you realize this is now done automatically. That said, it's something needed, not some shitty thing some marketer wanted, so much less bad, but I really wanted to rant about firefox's underhanded ways today, so there you go.

Anyway, looking at the patch, you still hit the network I think. I just looked up where the submodule hashes are kept:

git ls-tree HEAD external/unbound | awk 'print $3'

You can then compare with the top hash, and can either go ahead or error out without hitting the network.

**Comment by moneromooo-monero** [comment]
But then the wallet does a DNS lookup. Hmm. What to do...

**Comment by TheCharlatan** [comment]
Force pushed a new approach as to @moneromooo-monero 's suggestion. Updated PR description.

**Pull request merged**
