### PR TITLE
Added breaks to db_lmdb.cpp and removed /* FALLTHRU */

### PR DESCRIPTION
**Pull request by NanoAkron**

### CODE REVIEW

**Comment by selsta** [comment]
Wouldn’t that change behaviour?

**Comment by selsta** [comment]
Let’s say we want to upgrade db v1 to v3. migrate() is called once in open(), with your changes it will go only call migrate_1_2() and then break?

The way it was before is call migrate_1_2() and then migrate_2_3(). Maybe I’m missing something.

**Comment by moneromooo-monero** [comment]
Yes, this is broken.

**Comment by moneromooo-monero** [comment]
+invalid

**Pull request closed without merging**
