### PR TITLE
blockchain: fix crash checking pre-validated txids

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by talexpro** [comment]
Wouldn't you like to merge this fix in release-branch and update pre-built binaries?
Or do you expect regular users facing crash bug to spot issues, find this fix and manually build master branch?

And by the way, as far as I understand, it is not very widespread issue. This fact and comment in the code ("//TODO: why is this done?  make sure that keeping invalid blocks makes sense.") makes me wonder if my local blockchain database is ok.
So I think it would be nice to provide some more information related to this bug: why does it happen and should and special action be taken as remedy?

**Comment by mrosseel** [comment]
Just experienced this twice in a row (fresh sync - crash - delete blockchain - fresh sync -crash).
Fairly standard linux installation so +1 for this happening in the wild.

**Comment by KelvinJones** [comment]
HI all,  I'm still experiencing exactly this with the exception being I'm on Ubuntu 14.  I'm upgrading to 16 but doubtful it will help.  I'm trying to setup the daemon and sync the blockchain both to operate a private pool and to support the community.  I downloaded everything fresh over the weekend but no joy.  Suggestions? Start again? Download again.  I get the error reported below on almost exactly the same block.


Segmentation fault for monerod v0.11.0.0 on Ubuntu 16.04
--

**Comment by Tahutipai** [comment]
+1 for experienced this in the wild, which led me to here.  Basically vanilla ubuntu 17.04, fresh install of Monero, fresh sync.  I cancelled the first sync about 90% in, as it appeared stuck. Now monerod seg faults, always.   Currently building monero fresh from github to see if that fixes it.  

If it does, +1 you need to get the public binaries updated...
--
Monero client would seriosuly benefit from an automatic updater - or at the very least, an "out of date - please  upgrade" message appearing clearly on the gui, not buried in the logs.

**Pull request merged**
