### PR TITLE
wallet2: fix secondary partially signed multisig txes

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by rbrunner7** [comment]
I don't fully understand the change, but I can confirm that one of my 2/3 cases that did not work until now (as mentioned on IRC yesterday) now works after applying this change.

**Comment by moneromooo-monero** [comment]
Do the others now work too ?

**Comment by rbrunner7** [comment]
I could not find again one of the three triplets of wallets with the problem, but I could try with the one where I encountered it for the first time, testnet instead of stagenet, and that also works now.

Good catch, that bug!

Is it in any way remarkable that the bug is so reproducible for a certain wallet? So this time it's not a case of shuffeling that works 50% (or is it 33%?) with 2/3 wallets?

**Comment by moneromooo-monero** [comment]
It is deterministic.

**Pull request merged**
