### PR TITLE
refactoring: replace std::stringstream with std::{i|o}stringstream when allowed

### PR DESCRIPTION
**Pull request by stoffu**
Purely for the sake of readability. Perhaps gratuitous?

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
That's... pretty spammy indeed. Why ?

**Comment by stoffu** [comment]
Well, I found a place in #2134 where `std::istringstream` would be more suitable than `std::stringstream`, and then realized that there are this many places where `std::stringstream` could be replaced by `std::{i|o}stringstream`.

IMO it's generally better to not use `std::stringstream` when possible so that any unintended usage can be detected at compile time. But I also agree that these changes may be spammy because the intended usages are almost always obvious.

I thought these changes would be not as meaningless as indentation reformatting etc., but maybe I'm just wrong.

**Comment by moneromooo-monero** [comment]
Well, subjective where to draw the line between pros and cons. I suppose it's similar in some way to adding const qualifiers, which I like to do. So it does bring a code benefit, objectively. If you still want this in, I'll OK it.

**Comment by stoffu** [comment]
OK, I'm curious about how others feel, se let's keep this open for a while.

**Comment by hyc** [comment]
Still looks mostly like a no-op and "if it ain't broke don't fix it". More the kind of thing you can fix incidentally, case-by-case, if you happen to already be working on a specific piece of code.

Unless you can actually identify a misuse somewhere, then it's a legitimate fix.

**Comment by iamsmooth** [comment]
> if you happen to already be working on a specific piece of code

That's my view.

There could also, I suppose, be specific cases where the usage is not trivial and the added specificity makes a significant difference to maintainability. The trivial ones I would leave alone unless touching that code for some other reason.

> Unless you can actually identify a misuse somewhere, then it's a legitimate fix.

Also that of course

**Comment by stoffu** [comment]
Thank you for commenting. I agree, the changes are all trivial and non-ambiguous, and this patch doesn't add much to the maintainability. Closing.

**Pull request closed without merging**
