### PR TITLE
rpc: get_txpool_backlog is now unrestricted

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by MaxXor** [comment]
I think you want to merge this into `release-v0.11.0.0`, not `master`?

**Comment by NanoAkron** [comment]
Now that release has been tagged and people are installing and using it, won't new merges have to be put into 0.11.0.1?

**Comment by MaxXor** [comment]
@NanoAkron We could use the branching structure like `v0.11`, `0.12`, etc...
With this we avoid needing a new branch for each minor release. It's cleaner and easier to manage imho.

**Comment by moneromooo-monero** [comment]
Yes, thanks, I'll push in another PR as I can't seem to be able to change the target branch.

**Pull request closed without merging**
