### PR TITLE
update readme to include blurb on decentralization

### PR DESCRIPTION
**Pull request by Gingeropolous**
it occurred to me that someone discovering monero for the first time, through the code and actually reading the readme, would not have any indication of the design focuses of keeping monero decentralized, both in terms of the mining infrastructure and the low cost of node operation.  I know the topic is sort of a ... wishy washy thing, but I tried to craft some language that gets the point across in general terms.

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
For consistency purposes, please capitalize Monero.

**Comment by Gingeropolous** [comment]
well i think its impossible to squash commits with this git web interface, so i'l either wait till its merged to delete the commit and PR again if thats what ppl want

**Comment by moneromooo-monero** [comment]
Or... use a git tree rather than surrender your agency to what subset of git abilities some centralized tool decided to implement :P

**Comment by moneromooo-monero** [comment]
Shall we merge or not then ?

**Comment by moneromooo-monero** [comment]
Let's merge, then. People can add capitals later if they want them.

**Pull request merged**
