### PR TITLE
protocol: drop peers sending duplicate txes

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Review by vtnerd — APPROVED** [review]

**Comment by jeffro256** [comment]
Would it be better to check to "seen" txids versus blobs since it's trivial to construct a transaction that it semantically equivalent with an equivalent TXID but which has a different blob?

**Comment by moneromooo-monero** [comment]
Explain ?
The reason I used blobs is that it does not require parsing.

**Comment by jeffro256** [comment]
Sorry I was getting the varint serialization formats mixed up, ignore my last comment.

**Comment by jeffro256** [comment]
Could you force-push to run the tests again please?

**Comment by selsta** [comment]
@jeffro256 can you approve?

**Review by selsta — APPROVED** [review]

**Comment by jeffro256** [comment]
It looks okay at first glance, but I haven’t tested it yet and I’m not super familiar with this part of the codebase.

**Pull request merged**
