### PR TITLE
wallet: fix payment ID decryption for construction data with dummy

### PR DESCRIPTION
**Pull request by ph4r05**
As dummy payment ID is a legitimate value now (8xzero byte) the `bool get_short_payment_id()` has to be changed a bit as it returns 8x0B also as an indication of failure / absence of short payment ID. 

Because of this construction data does not get updated in `get_construction_data_with_decrypted_short_payment_id()`. As a consequence, the encrypted dummy ID stays in the construction data `extra` and payment ID is scrambled.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Can you PR to release-v0.13 too please ?

**Comment by rbrunner7** [comment]
This fixes issue #5130 which currently makes multisig transactions impossible to successfully submit to the network with "master". Merging this PR would therefore be quite useful.

**Comment by ph4r05** [comment]
Its approved for 24 days so hopefully it gets merged :)

**Comment by fluffypony** [comment]
I’ll add it to the next batch, but we’ve been merging oldest-first thus far

**Pull request merged**
