### PR TITLE
Fix ZMQ server poll code

### PR DESCRIPTION
**Pull request by vtnerd**
These changes shouldn't be necessary according to the ZeroMQ documentation, but `monerod`s ZeroMQ code is having issue with `EAGAIN` in the RPC server read. I'm marking this as a draft for now so that @sethforprivacy and @Gingeropolous can test first.

### CODE REVIEW

**Comment by SChernykh** [comment]
@sethforprivacy @Gingeropolous did you test it? It's been 6 months. I also got this "ZMQ server destroyed" error yesterday, so I'll be using this PR on my nodes from now on.

**Comment by trasherdk** [comment]
I haven't had any `ZMQ server destroyed` after closing public access to ZMQ ports. `mainnet`, `testnet` and `stagenet` are all happily chucking along.

**Comment by SChernykh** [comment]
I never even had ZMQ ports open on that node, all connections to ZMQ were coming from 127.0.0.1

**Comment by vtnerd** [comment]
@SChernykh let me know if this helps as I've got little feedback on this PR and never had this issue locally.

**Comment by SChernykh** [comment]
@vtnerd it happened only once so far, after almost two years of running this node with ZMQ. I'll report if it happens again.

**Comment by Gingeropolous** [comment]
note to self - test this on a testnet with multiple miners connecting

**Comment by vtnerd** [comment]
Closing in favor of #9052

**Pull request closed without merging**
