### PR TITLE
typo in monero.ts. fixes #3310

### LINKED ISSUE #3310: monero.ts : Various typos
A couple typos. I'll try to create a PR myself for it

"RFC" instead of "RPC":
image

Simplewallet.cpp, line 1680
too -> to
image

### PR DESCRIPTION
**Pull request by ordtrogen**

### CODE REVIEW

**Comment by stoffu** [comment]
Are these last 3 commits made by mistake?

**Comment by ordtrogen** [comment]
Damn, I seem to have messed this PR up when pushing another updated file to my repo ...

**Comment by ordtrogen** [comment]
Yes, @stoffu 
How do I get out of it? 
I guess I should have worked on a branch and created a PR from that

**Comment by stoffu** [comment]
You should create one branch per one pull request. Since this PR was submitted from your master branch, you'd need to create a new branch based on the current Monero master and add commits to it.

In my personal fork https://github.com/stoffu/monero/, I made a remote repository called `upstream` which points to https://github.com/monero-project/monero. To create a new branch that is based on the current master, I do:

```
git remote update
git checkout -b whatever-branch-name
git reset --hard upstream/master
```

After making some commit(s) to the branch, I push it to my remote repository by
```
git push --set-upstream origin whatever-branch-name
```
Then, I can make a new pull request on the GitHub website.

I'm certainly not a git expert, so there can be some other better ways:)

**Comment by ordtrogen** [comment]
thanks. I'll try it out.

**Comment by ordtrogen** [comment]
I'll close this and give it another try (found some more typos to fix)

**Comment by ordtrogen** [comment]
new one is #3373

**Comment by moneromooo-monero** [comment]
+duplicate

**Pull request closed without merging**
