### PR TITLE
Avoid some temporary strings when reading off the database

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by TheCharlatan** [comment]
I found some more candidates `blobdata` -> `blobdata_ref` candidates, is there a selection criteria that I am missing?

**Comment by moneromooo-monero** [comment]
I don't think so. This was an old patch, so maybe those appeared later. Or I just did not know come across them. I did this back when I was trying to speed sync up, so anything not in that path would not be changed I think. Feel free to list any that are speed sensitive.

**Comment by selsta** [comment]
Please rebase.

**Comment by TheCharlatan** [comment]
I only saw the follow up PR's providing more context later, so while there are more potential candidates these do indeed seem to be the performance critical ones.

**Review by TheCharlatan — APPROVED** [review]

**Pull request merged**
