### PR TITLE
Add missing include

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Did you not say on IRC that it did not fix it ?

**Comment by vtnerd** [comment]
Where is `std::string` used in this header? This is likely including transitively, which is not desirable for a commonly used header (`span.h`).

**Comment by moneromooo-monero** [comment]
strspan near the end.

**Comment by stoffu** [comment]
@moneromooo-monero 
> if we're pedantic

It *is* needed regardless of pedantic. The code having been compiling fine on some platforms is just by accident.

**Pull request merged**
