### PR TITLE
wallet rpc provides key images of spent outputs

### PR DESCRIPTION
**Pull request by woodser**

### CODE REVIEW

**Comment by woodser** [comment]
Fixes #7721

**Review by selsta — CHANGES_REQUESTED** [review]
Same here, bump WALLET_RPC_VERSION_MINOR.

Also if you write "Fixes ..." in the original PR comment it will automatically close the issue on merge.

**Comment by woodser** [comment]
> Same here, bump WALLET_RPC_VERSION_MINOR.

Bumped to 22 in both PRs.

**Review by moneromooo-monero — APPROVED** [review]

**Comment by luigi1111** [comment]
@woodser plz rebase

**Comment by woodser** [comment]
> @woodser plz rebase

Branch has been rebased.

**Review by selsta — APPROVED** [review]

**Pull request merged**
