### PR TITLE
Enhance README.md for adding '.bash' and '.txt' to the code block.

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Enhance README.md for adding '.bash' and '.txt' to the code block.

### CODE REVIEW

**Review by jeffro256 — APPROVED** [review]

**Review by sneurlax — APPROVED** [review]
Approving but small nit: @lamtrinhdev, are those actually `bash` or are they the more general `sh`ellscript?  Would either be valid or are these scripts only valid in `bash`?

**Comment by lamtrinhdev** [comment]
Dear @sneurlax ,

I think the 'sh' is more correct. Let me update it.

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @sneurlax ,

As my understand at https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml . It mentions:

```
Shell:
  type: programming
  color: "#89e051"
  aliases:
  - sh
  - shell-script
  - bash
  - zsh
  - envrc
  extensions:
  - ".sh"
  - ".bash"
  - ".bats"
  - ".cgi"
  - ".command"
  - ".fcgi"
  - ".ksh"
  - ".sh.in"
  - ".tmux"
  - ".tool"
  - ".trigger"
  - ".zsh"
  - ".zsh-theme"
  filenames:
  - ".bash_aliases"
  - ".bash_functions"
  - ".bash_history"
  - ".bash_logout"
  - ".bash_profile"
  - ".bashrc"
  - ".cshrc"
  - ".envrc"
  - ".flaskenv"
  - ".kshrc"
  - ".login"
  - ".profile"
  - ".tmux.conf"
  - ".zlogin"
  - ".zlogout"
  - ".zprofile"
  - ".zshenv"
  - ".zshrc"
  - 9fs
  - PKGBUILD
  - bash_aliases
  - bash_logout
  - bash_profile
  - bashrc
  - cshrc
  - gradlew
  - kshrc
  - login
  - man
  - profile
  - tmux.conf
  - zlogin
  - zlogout
  - zprofile
  - zshenv
  - zshrc
  interpreters:
  - ash
  - bash
  - dash
  - ksh
  - mksh
  - pdksh
  - rc
  - sh
  - zsh
  tm_scope: source.shell
  ace_mode: sh
  codemirror_mode: shell
  codemirror_mime_type: text/x-sh
  language_id: 346
```

So I think `bash`, `sh` and `shell` will be the same in block code of Github. I think we do not need to change.

If it answers your concern, could you please help me to merge it? I do not have `write access`permission. 
If it does not answer your concern, please feel free to give feedback.

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @luigi1111 ,

Sorry for tagging you. Could you help me to review this PR?

Thanks,
Lam

**Comment by sneurlax** [comment]
This PR is correct but unnecessary.  It may be merged but I wouldn’t push
on it.

**Comment by lamtrinhdev** [comment]
Dear @sneurlax ,

Thank you for your feedback. I am clear now.

Thanks,
Lam

**Pull request closed without merging**
