### PR TITLE
Fix stall after resizing LMDB

### PR DESCRIPTION
**Pull request by NanoAkron**
No idea why this works, but my stall error (#1595) is fixed by changing all instances of `LOG_PRINT_L3` to `MDEBUG` in `/cryptonote_core/blockchain.cpp`

Also took the opportunity to change `LOG_ERROR` messages to `MERROR`

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
If you change the L3, they should be MTRACE. They'll swamp the debug level otherwise.
You should find what the problem is in the first place anyway, this is just poking the thing until it doesn't fall over. Again, if you get a deadlock, look at the stack trace to see what deadlocks.

**Comment by NanoAkron** [comment]
Will change and try to keep analysing

**Comment by moneromooo-monero** [comment]
In particular, check what LOG_PRINT_Lx get changed to. The changes you made should be noop.
Also you can run with valgrind to see if there's previous memory corruption.

**Comment by NanoAkron** [comment]
How do I use valgrind?

**Comment by moneromooo-monero** [comment]
Instead of running "X", you run "valgrind X". It'll be slow.

**Comment by NanoAkron** [comment]
Debug build or normal build?

**Comment by moneromooo-monero** [comment]
Whichever you are seeing the problems with should be fine.

**Comment by NanoAkron** [comment]
Can you tell me how to check if the changes I made were noop?

**Comment by moneromooo-monero** [comment]
Well... that's not super easy. If you knew how to use makefiles, you could add -E to the GCC commands and avoid linking, then you'd get preprocessed files as objects, which you could diff. Otherwise, well.. it should behave the same :) There's a chance the binaries would be the same, though those things probably contain timestamps etc so that probably doesn't help in practice.

**Comment by NanoAkron** [comment]
I think @moneromooo-monero figured out a solution by changing mutex for recursive_mutex...just testing. Closing this one in favour.

**Pull request closed without merging**
