### PR TITLE
tx_pool: fix crash in stats when a tx was received right now

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by hyc** [comment]
Alternatively, avoid storing age = 0 in the first place:

diff --git a/src/cryptonote_core/tx_pool.cpp b/src/cryptonote_core/tx_pool.cpp
index 33b1d41..73f5190 100644
--- a/src/cryptonote_core/tx_pool.cpp
+++ b/src/cryptonote_core/tx_pool.cpp
@@ -575,7 +575,7 @@ namespace cryptonote
         stats.num_10m++;
       if (meta.last_failed_height)
         stats.num_failing++;
-      uint64_t age = now - meta.receive_time;
+      uint64_t age = now - meta.receive_time + (now == meta.receive_time);
       agebytes[age].txs++;
       agebytes[age].bytes += meta.blob_size;
       return true;


Avoids adding if() in the loop.

**Comment by moneromooo-monero** [comment]
That's about as many tests though, no ?

**Comment by hyc** [comment]
Yes but no branches.

**Comment by moneromooo-monero** [comment]
Alright, since it just replaces the whole patch, feel free to PR it and I'll close this one.

**Pull request closed without merging**
