### PR TITLE
rpc: add new RPCs to get and set limits

### PR DESCRIPTION
**Pull request by MaxXor**
This PR adds the following new RPCs:
- `set_limit <download kB/s> <upload kB/s>` set download and upload limit (restricted)
- ~~`limit_down <kB/s>` set download limit (restricted)~~
- ~~`limit_up <kB/s>` set upload limit (restricted)~~
- `get_limit` get download and upload limit
- ~~`limit_down` get download limit~~
- ~~`limit_up` get upload limit~~

Fixes https://github.com/monero-project/monero-core/issues/805

### CODE REVIEW

**Comment by MaxXor** [comment]
@moneromooo-monero Done!

**Comment by moneromooo-monero** [comment]
It seems a bit unfortunate to have so many RPCs when we could have two (a get and a set), no ?

**Comment by MaxXor** [comment]
For the `get`-RPCs I agree, one is enough there. But setting different up- & download limits isn't possible with only one `set`-RPC I think.

**Comment by moneromooo-monero** [comment]
Sure it is, if you interpret 0 as "do not change".

**Comment by moneromooo-monero** [comment]
Or even with the settings not being there - I added a KV_SERIALIZE_OPT recently.

**Comment by MaxXor** [comment]
Well, yea it's possible to implement but then the current `limit` command has to be changed as well to reflect this change. Currently it only allows one value, we could change it to require two values,
i.e.: `limit <up kB/s> <down kB/s>`

**Comment by NanoAkron** [comment]
But then 'limit 0 100' to leave the upload unchanged but change the download to 100kB/s seems counterintuitive. 

Is it not possible to have the RPC call without any argument just inform you of the current setting, but if passed an argument then it changes it? In which case we just need the limit_up and limit_down calls, and that's it. 

Or is that what you've done, and I'm being an idiot again?

**Comment by MaxXor** [comment]
@NanoAkron limit, limit_up and limit_down without arguments return only the current settings of up- & download limit, upload limit and download limit, respectively. With argument the limit RPC sets the limit for both and the other ones for upload or download.

**Comment by moneromooo-monero** [comment]
Why would the commands have to exactly match the RPC ?
limit_up 10 -> RPC{up=10, down=0}

**Comment by hyc** [comment]
Agreed, I don't see a reason to use multiple RPCs instead of just a single one here.

**Comment by NanoAkron** [comment]
@moneromooo-monero May I ask for an example for leaving the upload the same but changing the download to 10 in your syntax, and then for making upload zero but leaving download the same?

**Comment by hyc** [comment]
Use -1 for no change, then.

**Comment by moneromooo-monero** [comment]
Why would you want to set a 0 upload limit in the first place ? You might as well not run monerod and save the RAM.

**Comment by NanoAkron** [comment]
What if I just want a listening node to archive all transactions and the Blockchain?

**Comment by MaxXor** [comment]
Made some changes as requested, there exist now only two RPC calls, `set_limit` and `get_limit`. The value `-1` means no-change.

I think I noticed a small argument parser bug. Try to execute the RPC with:
`./monerod limit -1` and you'll see: `Failed to parse arguments: unrecognised option '-1'`

Should the commands `limit_up` and `limit_down` get removed altogether?

**Comment by moneromooo-monero** [comment]
-1 means "reset to default".

NanoAkron: if you have a node that never sends anything, how is it going to talk to other nodes ?

**Comment by NanoAkron** [comment]
@moneromooo-monero @hyc I worry we're going to end up with counterintuitive uses of the values `-1 `and `0` here just to reduce the number of RPC calls

I don't think we even need a differentiation between `set` and `get` here 

`limit` - returns current values
`limit 1 100` - sets up at 1kB/s, down at 100kB/s
`limit 0 0` - turns off all traffic up and down
`limit -1 -1` - resets up and down to defaults

It does mean an extra call and response to change just the up or down traffic - you'd have to query first, then use that value in the reply whilst changing the other

`limit`
Limit is 5kB/s up, 10kB/s down
`limit 5 20`
Limit changed to 5kB/s up, 20kB/s down

?

**Comment by moneromooo-monero** [comment]
I don't really care whether to have a single RPC or dual get/set ones. I only slightly prefer the latter.

**Comment by moneromooo-monero** [comment]
Oh, and it'd nice to get the 128/2048 in a single place (defines, maybe) while you're at it. A separate patch and/or PR is fine for this.

**Comment by MaxXor** [comment]
@NanoAkron Yes, that's how you would call the RPC from monerod, in monerod you just use `limit` which internally calls the corresponding RPC for get or set operation. I'm thinking about removing the `limit_up` and `limit_down` commands though...

Some commands are coded to use the RPC and some are not, it might be useful to know which commands work over RPC... i.e. `limit` command currently doesn't use RPC on monero master branch while `status` does. It's pretty confusing imho. This is important for the monero GUI as it uses monerod to execute RPCs and all commands not implemented to use the RPC don't work.

**Comment by MaxXor** [comment]
Updated the `limit` RPC command, moved some validations to the RPC server (don't trust the caller), removed the `limit_up` and `limit_down` commands.
Can the [scaling factor](https://github.com/monero-project/monero/blob/f980b2ca8935816edcddd1bfcbb8bed308e3e8c9/src/p2p/connection_basic.cpp#L177) get removed? Not sure what it's even doing. When u set limit-up to 128, it gets set to 127 because of this.

**Comment by moneromooo-monero** [comment]
Hmm, I thought we were talking about the RPC here, not the text commands...

**Comment by MaxXor** [comment]
@moneromooo-monero It actually started with a bug report in Monero GUI repository. To fix it I needed to add RPCs for the `limit` text commands as that's what the Monero GUI is using.

**Comment by hyc** [comment]
Leave the text commands alone then, if this PR is supposed to be about the RPCs. One issue per PR.

**Comment by moneromooo-monero** [comment]
I'm *fine* with making the commands use the RPC now. I just wasn't expecting the command parser/syntax to change, since there's not much reason for it. New RPCs to get/set limits like you did is great and wanted. Changing the user text commands just doesn't seem good since they're already there and the change seems arbitrary (and it's more annoying for a user to type placeholders than it is in an API).

**Comment by MaxXor** [comment]
Ok, I will revert the text command changes and open a new clean PR.

**Comment by MaxXor** [comment]
Btw. currently the `-1` doesn't set the default values. The default values are declared here: https://github.com/monero-project/monero/blob/335681896a8ea6142a4331aa203ce728d507265c/src/p2p/net_node.inl#L74-L75

**Pull request closed without merging**
