### PR TITLE
[RELEASE] Untangle cyclic dependency chain created by the ledger patch #3303

### PR DESCRIPTION
**Pull request by stoffu**
This patch splits `libringct` into two, introducing a new library `libringct_basic`, so if this gets merged, other library users (cc @moneroexamples) will need to update their CMakeLists.txt accordingly.

### CODE REVIEW

**Comment by stoffu** [comment]
CC: @cslashm

**Comment by stoffu** [comment]
A small fix for `wallet2::check_tx_key()` was added in the last commit, so please check.

**Comment by cslashm** [comment]
Change on prototypes seems OK. Basic idea was to have all device functions to return bool. But I agree with this which is, you are right,  more readable in the code base.

I am not sure to fully understand all effects of  the mods in prehashed function. Even if it seems ok, will have to test once I found the current  (hope last) bug in wallet management.

**Comment by stoffu** [comment]
@cslashm 
> I do not agree with that because tx_key is the transaction key, that it is encrypted by the device, so the ops need to be delegate to device.

I think you're misunderstanding the role of the function `wallet2::check_tx_key()`. This is called from the `check_tx_key` command in `monero-wallet-cli`:
```
check_tx_key <txid> <txkey> <address>
```
This command is supposed to be called by an auditor or a recipient who wants to verify that a sender sent some money to the recipient. All the arguments `<txid>`, `<txkey>` and `<address>` must be provided by the sender, and hence the `<txkey>` must be in plaintext.

This function doesn't require access to the wallet's secret keys, so it could've been in theory implemented as a static function. The only reason it's implemented as a member function of `wallet2` is because it needs to call a daemon RPC `/gettransactions` which then needs access to `m_http_client`.

**Comment by cslashm** [comment]
@stoffu Thank you for the precision. Indeed I though this function was used more than this way. So we can remove the hw device usage for now. In the future it will may  be re-add to be able to check/proof...transactions. But we have to discuss some security point before. So let  that for September release ;).

**Comment by stoffu** [comment]
In the future, the Ledger device could do either

- simply return the unencrypted tx key (for `check_tx_key`), or
- generate and return a tx proof (for `check_tx_proof`) 

The latter is preferable because the tx secret key doesn't need to leave the Ledger device, but it'll require more implementation effort.

In any case, the Ledger device has absolutely no role on the verification side (`check_tx_key` and `checK_tx_proof`).

**Comment by cslashm** [comment]
Understood and agree

**Comment by sammy007** [comment]
Why not merge if it's ok? Build is broken.

https://github.com/monero-project/monero/issues/3361

**Comment by Lafudoci** [comment]
Can confirm this PR fixed the build on my tinkerboard(ARMv7).

**Comment by fluffypony** [comment]
Reviewed

**Pull request merged**
